<section class="cover-essential-comfot-line">
    <div class="kv-warp">
        <ul class="kv-slide">
            <li>
                <div class="img-box">
                    <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_kv_01.jpg" alt="설화수 에센셜 컴포트 라인 01" class="only-pc">
                    <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_kv_01_mo.jpg" alt="설화수 에센셜 컴포트 라인 01" class="only-mo">
                </div>
                <div class="txt-box">
                    <h3>滋盈肌本舒活<br>系列</h3>
                    <div class="txt-kr">
                        <p>
                            韓方基礎護膚系列，<br/>
                            令肌膚瞬間注滿水 <br/>
                            分，    感覺柔軟嫩滑。
                        </p>
                    </div>
                </div>
            </li>
            <li>
                <div class="img-box">
                    <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_kv_02.jpg" alt="설화수 에센셜 컴포트 라인 02" class="only-pc">
                    <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_kv_02_mo.jpg" alt="설화수 에센셜 컴포트 라인 02" class="only-mo">
                </div>
                <div class="txt-box">
                    <h3>滋盈肌本舒活<br>系列</h3>
                    <div class="txt-kr">
                        <p>
                            韓方基礎護膚系列，<br/>
                            令肌膚瞬間注滿水 <br/>
                            分，    感覺柔軟嫩滑。
                        </p>
                    </div>
                </div>
            </li>
            <li>
                <div class="img-box">
                    <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_kv_03.jpg" alt="설화수 에센셜 컴포트 라인 03" class="only-pc">
                    <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_kv_03_mo.jpg" alt="설화수 에센셜 컴포트 라인 03" class="only-mo">
                </div>
                <div class="txt-box">
                    <h3>滋盈肌本舒活<br>系列</h3>
                    <div class="txt-kr">
                        <p>
                            韓方基礎護膚系列，<br/>
                            令肌膚瞬間注滿水 <br/>
                            分，    感覺柔軟嫩滑。
                        </p>
                    </div>
                </div>
            </li>
            <li>
                <div class="img-box">
                    <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_kv_04.jpg" alt="설화수 에센셜 컴포트 라인 04" class="only-pc">
                    <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_kv_04_mo.jpg" alt="설화수 에센셜 컴포트 라인 04" class="only-mo">
                </div>
                <div class="txt-box">
                    <h3>滋盈肌本舒活<br>系列</h3>
                    <div class="txt-kr">
                        <p>
                            韓方基礎護膚系列，<br/>
                            令肌膚瞬間注滿水 <br/>
                            分，    感覺柔軟嫩滑。
                        </p>
                    </div>
                </div>
            </li>
            <li>
                <div class="img-box">
                    <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_kv_05.jpg" alt="설화수 에센셜 컴포트 라인 05" class="only-pc">
                    <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_kv_05_mo.jpg" alt="설화수 에센셜 컴포트 라인 05" class="only-mo">
                </div>
                <div class="txt-box">
                    <h3>滋盈肌本舒活<br>系列</h3>
                    <div class="txt-kr">
                        <p>
                            韓方基礎<br>護膚系列，<br/>
                            令肌膚瞬間注滿水 <br/>
                            分，    感覺柔軟嫩滑。
                        </p>
                    </div>
                </div>
            </li>
        </ul>
        <div class="kv-btn-wrap">
            <button class="btn-prev slick-arrow" style="display: block;"><span class="hidden">이전 페이지로 넘어가기</span></button>
            <button class="btn-next slick-arrow" style="display: block;"><span class="hidden">다음 페이지로 넘어가기</span></button>
        </div>
    </div>
    <div class="container">
        <div class="contents01">
            <div class="con-container">
                <div class="tit-box aos-init" data-aos="fade-up">
                    <span>滋盈肌本舒活</span>
                    <h3>潤顏水</h3>
                </div>
                <div class="img-box right aos-init" data-aos="fade-up">
                    <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_01.jpg" alt="" class="only-pc">
                    <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_01_mo.jpg" alt="" class="only-mo">
                </div>
                <div class="img-box left">
                    <div class="img-texture aos-init" data-aos="fade-up">
                        <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_02.png" alt="" class="only-pc">
                        <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_02_mo.png" alt="" class="only-mo">
                    </div>
                    <div class="img-prd aos-init" data-aos="fade-up" data-aos-delay="100">
                        <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_03.png" alt="" class=" only-pc">
                        <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_03_mo.png" alt="" class="only-mo">
                    </div>
                </div>
                <div class="txt-box aos-init" data-aos="fade-up">
                    <h4 class="prd-name">滋盈肌本舒活潤顏水</h4>
                    <ul class="prd-tag">
                        <li>#SulwhasooNo.1Toner</li>
                        <li>#SuppleSilkyCalm</li>
                    </ul>
                    <p class="prd-desc">
                        具有補濕和舒緩功效，可保 <br class="only-pc">
                        持肌膚水嫩光滑的細膚水
                    </p>
                    <div class="btn-box">
                        <a href="https://www.sulwhasoo.com/hk/zh/products/essential-comfort-balancing-water.html" ap-click-area="Contents" ap-click-name="Click - Product Detail Link" ap-click-data="Cover_Essential Comfort_자음수">View More</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="contents02 aos-init" data-aos="fade-up">
            <div class="con-container">
                <div class="tit-box aos-init" data-aos="fade-up">
                    <span>滋盈肌本舒活</span>
                    <h3>潤顏乳</h3>
                </div>
                <div class="img-box right only-pc aos-init" data-aos="fade-up">
                    <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_05.png" alt="">
                </div>
                <div class="img-box left">
                    <div class="img-texture aos-init" data-aos="fade-up">
                        <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_06.png" alt="" class="only-pc">
                        <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_06_mo.png" alt="" class="only-mo">
                    </div>
                    <div class="img-prd aos-init" data-aos="fade-up" data-aos-delay="100">
                        <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_07.png" alt="" class="only-pc">
                        <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_07_mo.png" alt="" class="only-mo">
                    </div>
                </div>
                <div class="img-box right only-mo aos-init aos-animate" data-aos="fade-up">
                    <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_05_mo.png" alt="">
                </div>
                <div class="txt-box bar aos-init" data-aos="fade-up">
                    <h4 class="prd-name">滋盈肌本舒活潤顏乳</h4>
                    <ul class="prd-tag">
                        <li>#SulwhasooNo.1Lotion</li>
                        <li>#MoisturizingCalming</li>
                    </ul>
                    <p class="prd-desc">
                        具有補濕和舒緩功效，可保持 <br class="only-pc">
                        肌膚水嫩光滑的補濕乳液
                    </p>
                    <div class="btn-box">
                        <a href="https://www.sulwhasoo.com/hk/zh/products/essential-comfort-balancing-emulsion.html" ap-click-area="Contents" ap-click-name="Click - Product Detail Link" ap-click-data="Cover_Essential Comfort_자음유액">View More</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="contents03">
            <div class="con-container">
                <div class="tit-box bar aos-init" data-aos="fade-up">
                    <span>滋盈肌本舒活</span>
                    <h3>緊緻霜</h3>
                </div>
                <div class="img-box right aos-init" data-aos="fade-up">
                    <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_08.png" alt="" class="only-pc">
                    <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_08_mo.png" alt="" class="only-mo">
                </div>
                <div class="img-box left">
                    <div class="img-texture aos-init" data-aos="fade-up">
                        <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_09.png" alt="" class="only-pc">
                        <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_09_mo.png" alt="" class="only-mo">
                    </div>
                    <div class="img-prd aos-init" data-aos="fade-up" data-aos-delay="100">
                        <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_10.png" alt="" class="only-pc">
                        <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_10_mo.png" alt="" class="only-mo">
                    </div>
                </div>
                <div class="txt-box aos-init" data-aos="fade-up">
                    <h4 class="prd-name">滋盈肌本舒活緊緻霜</h4>
                    <ul class="prd-tag">
                        <li>#SmoothFirmLookinSkin</li>
                        <li>#MoistureFirmingCream</li>
                    </ul>
                    <p class="prd-desc">
                        低敏的補濕緊緻面霜，能增強肌膚彈性﹑讓肌膚 <br class="only-pc">
                        變得光滑和緊緻
                    </p>
                    <div class="btn-box">
                        <a href="https://www.sulwhasoo.com/hk/zh/products/essential-comfort-firming-cream.html" ap-click-area="Contents" ap-click-name="Click - Product Detail Link" ap-click-data="Cover_Essential Comfort_탄력크림">View More</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="contents04">
            <div class="con-container">
                <div class="tit-box bar aos-init" data-aos="fade-up">
                    <span>滋盈肌本舒活</span>
                    <h3>面霜</h3>
                </div>
                <div class="img-box left aos-init" data-aos="fade-up">
                    <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_12.png" alt="" class="only-pc">
                    <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_12_mo.png" alt="" class="only-mo">
                </div>
                <div class="img-box right">
                    <div class="img-texture aos-init" data-aos="fade-up">
                        <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_13.png" alt="" class="only-pc">
                        <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_13_mo.png" alt="" class="only-mo">
                    </div>
                    <div class="img-prd aos-init" data-aos="fade-up" data-aos-delay="100">
                        <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_14.jpg" alt="" class="only-pc">
                        <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_14_mo.jpg" alt="" class="only-mo">
                    </div>
                </div>
                <div class="txt-box aos-init" data-aos="fade-up">
                    <h4 class="prd-name">滋盈肌本舒活面霜</h4>
                    <ul class="prd-tag">
                        <li>#RefreshingHydrate</li>
                        <li>#MoisturizingCalmingCream</li>
                    </ul>
                    <p class="prd-desc">
                        深層補濕和舒緩的面霜，清爽的凝膠質地 <br class="only-pc">
                        讓您的肌膚整天保持舒適
                    </p>
                    <div class="btn-box">
                        <a href="https://www.sulwhasoo.com/hk/zh/products/essential-comfort-moisturizing-cream.html" ap-click-area="Contents" ap-click-name="Click - Product Detail Link" ap-click-data="Cover_Essential Comfort_수분크림">View More</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="contents05">
            <div class="bg-box bg-top">
                <div class="con-container">
                    <div class="sub-tit-box aos-init" data-aos="fade-up">
                        <h3 class="sub-tit"><em>使用更少的資源</em></h3>
                    </div>
                    <ul class="img-list">
                        <li data-aos="fade-up" class="aos-init">
                            <div class="img-box">
                                <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_15.png" alt="" class="only-pc">
                                <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_15_mo.png" alt="" class="only-mo">
                            </div>
                            <div class="txt-box">
                                <span>使用更少的資源</span>
                                <p>
                                    與以前的產品相比，我們 <br class="only-pc">
                                    將容器中的玻璃量減少了  <br class="only-pc">
                                    10%，以節約資源。
                                    <em class="txt-color">
                                        <sup>*</sup>僅適用於滋盈肌本舒活潤顏水及滋盈肌本舒活潤顏乳的包裝
                                    </em>
                                </p>
                            </div>
                        </li>
                        <li data-aos="fade-up" class="aos-init">
                            <div class="txt-box only-mo">
                                <span>易於回收</span>
                                <p>
                                    我們致力令回收變得更容易。 <br class="only-pc">
                                    移除容器中的塑料部分以便於回收。
                                </p>
                            </div>
                            <div class="img-box">
                                <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_16.png" alt="" class="only-pc">
                                <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_16_mo.png" alt="" class="only-mo">
                            </div>
                            <div class="txt-box only-pc">
                                <span>易於回收</span>
                                <p>
                                    我們致力令回收變得更容易。 <br class="only-pc">
                                    移除容器中的塑料部分以便於回收。
                                </p>
                            </div>
                        </li>
                        <li data-aos="fade-up" class="aos-init">
                            <div class="img-box">
                                <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_17.png" alt="" class="only-pc">
                                <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_17_mo.png" alt="" class="only-mo">
                            </div>
                            <div class="txt-box">
                                <span>可持續包裝</span>
                                <p>
                                    我們使用可持續生產並 <br class="only-pc">
                                    獲得 FSC認證的紙箱來<br class="only-pc">
                                    保護森林。
                                </p>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="bg-box bg-bottom">
                <div class="con-container">
                    <div class="sub-tit-box aos-init" data-aos="fade-up">
                        <h3 class="sub-tit">
                            低碳排放認證：<br>
                            <em>滋盈肌本舒活潤顏水 <br class="only-pc">滋盈肌本舒活潤顏乳</em>
                        </h3>
                    </div>
                    <div class="img-box aos-init" data-aos="fade-up">
                        <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_kv_19.jpg" alt="" class="only-pc">
                        <img src="/media/html/resource/img/cover/essential-comfort-line/img_20211125_cover_ecl_kv_19_mo.jpg" alt="" class="only-mo">
                    </div>
                    <dl class="txt-list aos-init" data-aos="fade-up">
                        <dt>滋盈肌本舒活潤顏水</dt>
                        <dd>
                            雪花秀擁有英國碳信託的 carbonF 認證。<br class="only-pc">
                            在整體加工、製造和廢料運送過程中，滋盈肌本舒活潤顏 <br class="only-pc">
                            水的成分和包裝的二氧化碳排放減少了 16.8%，即 992 公斤**。<br class="only-pc">
                            這相當於 150 棵 30 年樹齡的松樹吸收的溫室氣體量。
                            <p class="txt-color">
                                *基於之前的 滋陰水（125 毫升） 和新的 滋盈肌本舒活潤顏水 （150 毫升）<br class="only-pc">
                                之間的毫升換算 <br>
                                **基於 2019 年在韓國市場售出的 727,382 支
                            </p>
                        </dd>
                    </dl>
                    <dl class="txt-list aos-init" data-aos="fade-up">
                        <dt>滋盈肌本舒活潤顏乳</dt>
                        <dd>
                            雪花秀擁有英國碳信託的 carbonF 認證。 <br class="only-pc">
                            在整體加工、製造和廢料運送過程中，滋盈肌本舒活潤顏乳的成 <br class="only-pc">
                            的成分和包裝的二氧化碳排放減少了 8.9%，即 34,906公斤**。 <br class="only-pc">
                            這相當於 5,289 棵 30 年樹齡的松樹吸收的溫室氣體量。
                            <p class="txt-color">
                                *基於之前的 滋陰乳 (125ml) 和新的滋盈肌本舒活潤顏乳(125ml) 之間的毫升換算<br>
                                ** 基於 2019 年在韓國市場的總銷量 523,878支
                            </p>
                        </dd>
                    </dl>
                </div>
            </div>
        </div>
    </div>
</section>
<script type="text/javascript">
    require([
        'jquery',
        'js/plugins/aos/aos',
        'js/plugins/slick/slick'
    ], function ($,AOS) {
        function CoverCommFunc() {
            var _$this = this,
                scrollInit = window.pageYOffset,
                kvOffset,
                isMobile = false,
                filter = "win16|win32|win64|mac";
            //swiper = {};

            // library event
            _$this.library = {
                init: function() {
                    _$this.library.aos();
                },
                // aos
                aos: function() {
                    AOS.init({
                        duration: 2000
                    });
                }
            };
            return {
                init: function() {
                    // 모바일 접속 구분 (notosans font mobile line-height 적용 위해 필요)
                    if (navigator.platform) isMobile = filter.indexOf(navigator.platform.toLowerCase()) < 0;
                    if (isMobile) $('body').addClass('mobile');
                    _$this.library.init();
                },
            };
        };

        var coverCommFunc = new CoverCommFunc();

        $(document).ready(function () {
            coverCommFunc.init();
            $(".kv-slide").slick({
                slidesToShow: 1,
                slidesToScroll: 1,
                infinite: true,
                autoplay : false,
                autoplaySpeed: 2500,
                prevArrow: $(".btn-prev"),
                nextArrow: $(".btn-next"),
                responsive: [
                    {
                        breakpoint: 750,
                        settings: {
                            prevArrow: false,
                            nextArrow: false,
                        }
                    },
                ]
            });
        });
    });

</script>
