<!--<title>First Care Activating Serum - Print - 2020.04 | 雪花秀</title>-->
<!--<meta name="description" content="雪花秀資訊 - First Care Activating Serum - Print - 2020.04.01 | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="og:title" content="First Care Activating Serum - Print - 2020.04 | 雪花秀">-->
<!--<meta property="og:description" content="雪花秀資訊 - First Care Activating Serum - Print - 2020.04.01 | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="twitter:title" content="First Care Activating Serum - Print - 2020.04 | 雪花秀">-->
<!--<meta property="twitter:description" content="雪花秀資訊 - First Care Activating Serum - Print - 2020.04.01 | Sulwhasoo Hong Kong 中國香港">-->

<section class="content renewal-archive-detail">
		
	<!-- S : ICS + 부분 HTML 영역으로 사용하는 경우 (Beauty Ritual, News, Print, film) -->
    
	<div class="archive-section">
        <div class="archive-header">
            <div class="header-inner">
                <h1 class="h">First Care Activating Serum</h1>
				<span class="type">Print</span>
				<span class="date">2020.04.01</span>
			</div>
		</div>
		<!-- S : 이미지인 경우 Beauty Ritual, News, Print-->
        
			<!-- Beauty Ritual은 video 존재 유무에 따라 타입이 나눠짐-->
			
			
			<div class="archive-content">
				
				<figure class="archive-image">
					<img src="/media/html/experience/archive/__icsFiles/afieldfile/2020/04/02/03_int_940.jpg" alt="First Care Activating Serum">
				</figure>
				
				
				<div class="archive-static-body">
					<!-- HTML or text 삽입 -->
					<div class="print-copy">
						<div class="archive-print-body">
							<div class="content static parbase ">
								<style>
								.archive-print-body {padding:4.25531915% 0;}
								.archive-print-section span{display:block}
								.text_center {text-align:center}
								@media only all and (max-width: 767px){
								.text_center {text-align:left}
								.archive-print-section span{display:inline}
								}
								</style>
								<div class="archive-print-section text_center">
									<p><span> Healthy Radiance<br> with new JAUM Activator&trade; </span></p>
								</div>
							</div>

						</div>
					</div>
					<!-- //HTML or text 삽입 -->
				</div>
			</div>
			
		<!-- E : 이미지인 경우 -->
		
		<!-- S : 영상인 경우 -->
        
		<!-- E : 영상인 경우 -->
		<!-- S : HTML 영역으로 사용하는 경우-->
        
		<!-- E : HTML 영역으로 사용하는 경우 -->
	</div>
	<!-- E : ICS + 부분 HTML 영역으로 사용하는 경우 (Beauty Ritual, News, Print, film) -->
	

	<!-- E : 전체 HTML 영역으로 사용하는 경우 (event, cover, etc) -->
	<!-- S : 아카이브 컨텐츠 목록 -->
	<div class="others-archive-list-wrap">
		<div class="others-archive-list">
			<button class="sul-slide-btn-prev"><span class="blind">이전</span></button>
			<div class="sul-slide-list others-list">
				<div class="sul-slide-item others-item">
					<a href="/hk/zh/experience/archive/1314925_3836.html" class="thumb" ap-click-area="Contents" ap-click-name="Click - Contents" ap-click-data="Sulwhasoo Post Others_Perfecting Cushion" tabindex="0">
						<div class="thumb-frame">
							<div class="cover"><span class="category">PRINT</span></div>
							<img src="/media/html/experience/archive/__icsFiles/afieldfile/2021/06/02/20210602_final_cushion_archive_list_02_pc.jpg" alt="Perfecting Cushion">
						</div>
					</a>
				</div>
				<div class="sul-slide-item others-item">
					<a href="/hk/zh/experience/archive/1314926_3836.html" class="thumb" ap-click-area="Contents" ap-click-name="Click - Contents" ap-click-data="Sulwhasoo Post Others_Perfecting Cushion &amp; Foundation" tabindex="0">
						<div class="thumb-frame">
							<div class="cover"><span class="category">PRINT</span></div>
							<img src="/media/html/experience/archive/__icsFiles/afieldfile/2021/06/02/20210602_final_cushion_archive_list_01_pc.jpg" alt="Perfecting Cushion &amp; Foundation">
						</div>
					</a>
				</div>
				<div class="sul-slide-item others-item">
					<a href="/hk/zh/experience/archive/1314927_3836.html" class="thumb" ap-click-area="Contents" ap-click-name="Click - Contents" ap-click-data="Sulwhasoo Post Others_First Care Activating Serum" tabindex="0">
						<div class="thumb-frame">
							<div class="cover"><span class="category">PRINT</span></div>
							<img src="/media/html/experience/archive/__icsFiles/afieldfile/2021/04/05/20210405_final_archive_thumb_355_pc_02_2.jpg" alt="First Care Activating Serum">
						</div>
					</a>
				</div>
			</div>
			<button class="sul-slide-btn-next"><span class="blind">다음</span></button>
		</div>
	</div>
	<!-- E : 아카이브 컨텐츠 목록 -->
</section>

<script>
	require([
	'jquery',
	'js/plugins/slick/slick'
	], function ($) {
	    $('.others-list').slick({
	        slidesToShow: 3,
	        slidesToScroll: 1,
	        arrows: true,
	        fade: false,
	        dots: false,
	        infinite : false,
	        draggable : true,
	        prevArrow: $('.others-archive-list').find('.sul-slide-btn-prev'),
	        nextArrow: $('.others-archive-list').find('.sul-slide-btn-next'),
	        responsive: [{
	            breakpoint: 768,
	            settings: {
	                slidesToShow: 1.5,
	                slidesToScroll: 1
	            }
	        }]
	    });
	});

</script>