<!--<title>First Care Activating Serum - Film - 2021.04 | 雪花秀</title>-->
<!--<meta name="雪花秀資訊 - First Care Activating Serum - Film - 2021.04.02 | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="og:title" content="First Care Activating Serum - Film - 2021.04 | 雪花秀">-->
<!--<meta property="og:description" content="雪花秀資訊 - First Care Activating Serum - Film - 2021.04.02 | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="twitter:title" content="First Care Activating Serum - Film - 2021.04 | 雪花秀">-->
<!--<meta property="twitter:description" content="雪花秀資訊 - First Care Activating Serum - Film - 2021.04.02 | Sulwhasoo Hong Kong 中國香港">-->
	<section class="content renewal-archive-detail">
		<div class="archive-section">
            <div class="archive-header">
                <div class="header-inner">
                    <h1 class="h">First Care Activating Serum</h1>
					<span class="type">Film</span>
					<span class="date">2021.04.02</span>
				</div>
			</div>
			<div class="archive-content">
				<a href=" https://www.youtube.com/watch?v=xBtwK3lJ1Z0" class="archive-player yt-player media" data-track-name="movie">
					<img src="/media/html/experience/archive/__icsFiles/afieldfile/2021/07/15/20210402_final_archive_thumb_940_pc_01.jpg" alt="First Care Activating Serum">
					<i class="icon-play icon-expend"></i>
				</a>

				<div class="film-desc">
					<div class="desc" tabindex="0">
						[Narration/Subtitle]<br>
						How can you get skin that's more radiant than ever?<br>
						Sulwhasoo analyzed 60,000 skin factors and discovered skin moisture barrier master key<br><br>

						[Subtitle]<br>
						World's first discovery of skin moisture barrier master factor<br><br>

						[Narration/Subtitle]<br>
						When the master key is activated,<br>
						Youth Master Technology™ boosts skin moisture barrier network.<br>
						Strenthens the skin's texture,<br>
						awakens the skin's natural radiance, <br>
						and skin looks visibly firming.<br><br>

						[Subtitle]<br>
						Strengthened skin moisture barrier immediately after use +56%*<br>
						*Quick skin moisure barrier reinforcement effect confirmed<br>
						Human skin testing/Subject: ages 35-39, 32persons/Test period: 19.08.26-11.29/<br>
						Research institution: P&K SKin Reserach Center<br><br>

						[Narration/Subtitle]<br>
						Your skin, more radiant than ever<br>
						with first anti-aging care <br><br>

						[Subtitle]<br>
						After use of 1 bottle*<br>
						Skin moisture barrier +16.98%<br>
						Firmness +11.07%<br>
						Radiance +7.64%<br>
						*Quick skin moisure barrier reinforcement effect confirmed<br>
						Human skin testing/Subject: ages 35-39, 32persons/Test period: 19.08.26-11.29/<br>
						Research institution: P&K SKin Reserach Center<br><br>

						[Narration/Subtitle]<br>
						Sulwhasoo First Care Activation Serum
				</div>
				</div>
			</div>
		</div>
		<div class="others-archive-list-wrap">
			<div class="others-archive-list">
				<button class="sul-slide-btn-prev"><span class="blind">이전</span></button>
				<div class="sul-slide-item sul-slide-list others-list">
					<div class="others-item">
						<a href="/hk/zh/experience/archive/1314965_3836.html" class="thumb media" ap-click-area="Contents" ap-click-name="Click - Contents" ap-click-data="Sulwhasoo Post Others_First Care Activating Serum" tabindex="0">
							<div class="thumb-frame">
								<div class="cover"><span class="category">FILM</span></div>
								<img src="/media/html/experience/archive/__icsFiles/afieldfile/2021/07/15/20210402_final_archive_thumb_355_pc_01.jpg" alt="First Care Activating Serum">
								<i class="icon-play"><span class="blind">영상보기</span></i>
							</div>
						</a>
					</div>
					<div class="sul-slide-item  others-item">
						<a href="/hk/zh/experience/archive/1314929_3836.html" class="thumb media" ap-click-area="Contents" ap-click-name="Click - Contents" ap-click-data="Sulwhasoo Post Others_Concentrated Ginseng Renewing Serum&amp;Rescue Ampoule_GINSENOMICS™" tabindex="0">
							<div class="thumb-frame">
								<div class="cover"><span class="category">FILM</span></div>
								<img src="/media/html/experience/archive/__icsFiles/afieldfile/2021/01/15/20210115_final_concentrated-ginseng-rescue-ampoule-texture_archive-list_pc_1.jpg" alt="Concentrated Ginseng Renewing Serum&amp;Rescue Ampoule_GINSENOMICS™">
								<i class="icon-play"><span class="blind">영상보기</span></i>
							</div>
						</a>
					</div>
					<div class="sul-slide-item others-item">
						<a href="/hk/zh/experience/archive/1314932_3836.html" class="thumb media" ap-click-area="Contents" ap-click-name="Click - Contents" ap-click-data="Sulwhasoo Post Others_HOW TO : F/W MAKEUP LOOK" tabindex="0">
							<div class="thumb-frame">
								<div class="cover"><span class="category">FILM</span></div>
							<img src="/media/html/experience/archive/__icsFiles/afieldfile/2020/09/21/20200921_final_perfecting-foundation_archive-main_350_1.jpg" alt="HOW TO : F/W MAKEUP LOOK">
							<i class="icon-play"><span class="blind">영상보기</span></i>
						</div>
					</a>
				</div>
			</div>
			<button class="sul-slide-btn-next"><span class="blind">다음</span></button>
		</div>
	</div>
</section>
<script>
	require([
    'jquery',
    'js/plugins/slick/slick'
	], function ($) {
        $('.others-list').slick({
            slidesToShow: 3,
            slidesToScroll: 1,
            arrows: true,
            fade: false,
            dots: false,
            infinite : false,
            draggable : true,
            prevArrow: $('.others-archive-list').find('.sul-slide-btn-prev'),
            nextArrow: $('.others-archive-list').find('.sul-slide-btn-next'),
            responsive: [{
                breakpoint: 768,
                settings: {
                    slidesToShow: 1.5,
                    slidesToScroll: 1
                }
            }]
        });
    });

</script>
