<!--<title>雪花秀全新推出UV Wise Brightening Multi Protector<br>溫和親膚零負擔 亮肌防曬抗污染 打造健康自信美肌 | 雪花秀</title>-->
<!--<meta name="description" content="雪花秀資訊 - 雪花秀全新推出UV Wise Brightening Multi Protector<br>溫和親膚零負擔 亮肌防曬抗污染 打造健康自信美肌 | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="og:title" content="雪花秀全新推出UV Wise Brightening Multi Protector<br>溫和親膚零負擔 亮肌防曬抗污染 打造健康自信美肌 | 雪花秀">-->
<!--<meta property="og:description" content="雪花秀資訊 - 雪花秀全新推出UV Wise Brightening Multi Protector<br>溫和親膚零負擔 亮肌防曬抗污染 打造健康自信美肌 | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="twitter:title" content="雪花秀全新推出UV Wise Brightening Multi Protector<br>溫和親膚零負擔 亮肌防曬抗污染 打造健康自信美肌 | 雪花秀">-->
<!--<meta property="twitter:description" content="雪花秀資訊 - 雪花秀全新推出UV Wise Brightening Multi Protector<br>溫和親膚零負擔 亮肌防曬抗污染 打造健康自信美肌 | Sulwhasoo Hong Kong 中國香港">-->

<section class="content renewal-archive-detail">
	<!-- S : ICS + 부분 HTML 영역으로 사용하는 경우 (Beauty Ritual, News, Print, film) -->
	<div class="archive-section">
        <div class="archive-header">
            <div class="header-inner">
                <h1 class="h">雪花秀全新推出UV Wise Brightening Multi Protector<br>溫和親膚零負擔 亮肌防曬抗污染 打造健康自信美肌</h1>
				<span class="type">News</span>
				<span class="date">2020.03.02</span>
			</div>
		</div>
		<!-- S : 이미지인 경우 Beauty Ritual, News, Print-->
        
		<!-- Beauty Ritual은 video 존재 유무에 따라 타입이 나눠짐-->
		
		<div class="archive-content">
			
			<figure class="archive-image">
				<img src="/media/html/experience/archive/__icsFiles/afieldfile/2021/08/23/uv_wise_brightening_multi_protector_detail_article_1.jpg" alt="Sulwhasoo releases upgraded anti-pollution, sun-care cream, UV Wise Brightening Multi Protector">
			</figure>
			
			
			<div class="archive-static-body">
				<!-- HTML or text 삽입 -->
				<div class="print-copy">
					<div class="content static parbase about-view-content">

						<style>
						.mt10 {margin-top:10px;} 
						.l-about .tit-list,
						.l-about ul li dl dt, 
						.l-about h3, 
						.product-line h4,
						.prod-text .prod-sub-tit,
						.prod-text .prod-sub-desc,
						.color-txt {color:#555;}
						.product-line h4 {margin-bottom:10px;font-weight:bold;}
						.product-line:after {display:block;content:"";clear:both;}
						.product-line .prod-text .prod-price {display:block;margin-top:10px;font-weight:bold;}
						.news-view-content .product-line .prod-desc {width:100%;}
						.news-view-content .product-line .prod-text {padding-top:0;}
						.news-view-content .l-about h3 {margin-top:20px;margin-bottom:10px;}
						.prod-text .prod-sub-tit {display:block;font-weight:bold;}
						.prod-text .prod-sub-desc {display:block;margin-top:10px;}
						.news-view-content .product-line .prod-text .prod-sub-txt-list li {padding-top:10px;}
						.rel-date {color:#555;font-weight:bold;text-align:right;}
						.l-about .tit-list {font-size:1.17em;text-align:center;}
						.l-about .tit-list li, 
						.l-about .inner-list dt {font-weight:bold;margin-bottom:10px;}
						.l-about .sub-list li {margin-bottom:10px;}
						.l-about .sub-list li:last-child {margin-bottom:0;}
						.l-about ul li dl {margin-bottom:10px;}
						.l-about .inner-list dd {margin-bottom:10px;}
						.l-about .inner-list dd, .l-about .inner-list li {padding-left:11px;text-indent:-11px;}
						@media only all and (max-width: 767px) {
						.news-view-content .product-line .prod-img {float:none;}
						}
						</style>
						<div class="l-about">
							<ul class="tit-list">
							    <li>多重防線守護健康透亮肌膚：高效防曬ｘ抗污染ｘ抗熱老化ｘ美白修容</li>
							    <li>專利成分桑白丹™以天然韓方草藥糅合白參多醣　保護及紓緩肌膚</li>
							    <li>兩款不同質感 Creamy Glow 輕柔水漾質感極致補濕 Milky Tone Up 提亮均勻膚色同時阻隔藍光</li>
							</ul>    
							<br>
							<p>韓國尊貴護膚品牌雪花秀致力探索韓方傳統藥理，匯聚超過半世紀對人參及韓方草藥深入研究，精心鑽研護膚精髓。當中 Snowise Brightening滋晶雪瀅煥白系列，以專利白參皂苷、白參多醣配以韓方草藥，天然美白成分深受女士們愛戴。凝聚多年探索與革新，今年雪花秀推出 <em class="color-txt">UV Wise Brightening Multi Protector 智感煥白修護防曬霜</em>，高效 Plantia Protecting Complex™抗曬修護療方為肌膚締造強效防護膜，保護肌膚免受紫外線及環境污染侵害，即使在艷陽夏日仍無間斷美白。</p>

							<h3>對抗外在環境侵害 築起保護屏障 保護肌膚免受污染刺激</h3>
							<ul class="sub-list">
							    <li>微細懸浮粒子會破壞肌膚保護屏障，令肌膚彈性下降，刺激肌膚誘發過敏反應，並導致肌膚色素沉著。</li>
							    <li>配方為肌膚築起保護屏障，有效阻隔 <b>PM10、PM2.5 等微細懸浮粒子</b>，預防並改善因環境污染導致的肌膚衰老。</li>
							    <li>防曬成分有效阻隔紫外線，保護肌膚避免曬傷。</li>
							</ul>

							<h3>專利桑白丹<sup>™</sup>(Plantia Protecting Complex<sup>™</sup>)防曬同時修護受損肌膚　打造紓緩防護膜</h3>
							<ul class="sub-list">
							    <li>
							        以韓方藥理為本的獨有抗曬修護療方，以桑白皮、桑葚、煙燻烏梅及黃芩，糅合雪花秀獨有白參多醣，全方位防曬、修護、美白，更有效為肌膚降溫，對抗熱老化。
							        <ul class="inner-list mt10">
							            <li>- 桑白皮︰有助促進肌膚修復</li>
							            <li>- 桑葚︰桑樹的果實，具有紓緩肌膚功效。</li>
							            <li>- 白參多醣︰雪花秀以專利技術萃取的白參精髓，強化肌膚保護屏障並提供滋潤補濕。</li>
							            <li>- 煙燻烏梅︰有助對抗肌膚老化，紓緩曬傷、火熱引致的過敏不適。</li>
							            <li>- 黃芩︰具清熱解毒消腫功效，紓緩因曬傷或敏感導致的紅腫情況。</li>
							        </ul>
							    </li>
							    <li>配以現代科學為基礎的紫外線防護技術，保護肌膚免受污染，帶來抗光害修護效用，防曬同時打造健康美肌。</li>
							</ul>

							<h3>2款色調質感選擇 配合顧客不同需要</h3>
							<ul class="sub-list">
							    <li>
							        <dl class="inner-list">
							            <dt>No.1 Creamy Glow 光透膚色 :</dt>
							            <dt>HKD $570/50ml</dt>
							            <dd>- 水潤柔滑乳霜質感，適合喜歡較滋潤或膚質屬乾性及中性肌膚。</dd>
							        </dl>
							    </li>
							    <li>
							        <dl class="inner-list">
							            <dt>No.2 Milky Tone Up 光透玫瑰色</dt>
							            <dt>HKD $570/50ml</dt>
							            <dd>- 清新乳液質感，同時備有抗藍光和代替妝前底霜的效果。</dd>
							            <dd>- 適合注重妝容或膚質屬中性/混合性/油性肌膚</dd>
							        </dl>
							    </li>
							    <li>2款色調均通過低敏測試、眼睛刺激測試、皮膚科測試，性質溫和，不同肌膚亦可安心使用。</li>
							</ul>
						</div>

						<div class="product-line">    
							<h4>配合滋晶雪瀅煥白系列其他產品一同使用，深層淨白肌膚同時改善色班問題，煥發透亮耀眼光彩。</h4>
							<div class="prod-desc">
							    <div>
							        <img class="prod-img" src="/media/html/resource/img/news/snowise_brightening_serum_news_hk.jpg" alt="">
							    </div>
							    <div class="prod-text">
							        <strong class="prod-sub-tit">深層呵護 淨白透亮第一步</strong>
							        <em class="prod-sub-desc">滋晶雪瀅煥白精華 Snowise Brightening Serum</em>
							        <span class="prod-price">HKD $1,350 / 50ml</span>
							        <ul class="prod-sub-txt-list">
							            <li>滋晶雪瀅煥白系列最皇牌產品，革命性美白肌膚的新方案。</li>
							            <li>蘊含專利白參皂苷及白參多醣成分，珍貴白參精髓比之前濃縮2.5倍，讓肌膚更顯亮白，抑制黑色素過度生成，從內煥發炫亮光采。</li>
							            <li>深層修護肌膚，締造潤滑緊致輪廓。</li>
							            <li>啫喱狀的豐盈質感帶來極致補水滋養效果，且輕易被肌膚吸收。</li>
							        </ul>
							    </div>
							</div>

							<div class="prod-desc">
							    <div>
							        <img class="prod-img" src="/media/html/resource/img/news/brightening_Cleansing_Foam_news_hk.jpg" alt="">
							    </div>
							    <div class="prod-text">
							        <strong class="prod-sub-tit">乳霜質感潔面泡沫 淨化清潔肌膚</strong>
							        <em class="prod-sub-desc">滋晶雪瀅煥白潔面乳Snowise Brightening Cleansing Foam</em>
							        <span class="prod-price">HKD $310 / 150ml</span>
							        <ul class="prod-sub-txt-list">
							            <li>白土成分有助去除肌膚上的污垢雜質及多餘皮脂，深層淨化清潔，提亮膚色。</li>
							            <li>清新潔淨的潔面觸感，有效分解肌膚上的環境污染物質，還原淨白肌膚。</li>
							            <li>乳霜的質地瞬間形成豐盈泡沫，徹底清潔肌膚。</li>
							        </ul>
							    </div>
							</div>

							<div class="prod-desc">
							    <div>
							        <img class="prod-img" src="/media/html/resource/img/news/snowise_brightening_water_news_hk.jpg" alt="">
							    </div>
							    <div class="prod-text">
							        <strong class="prod-sub-tit">深層灌注水份 為肌膚滋養補濕</strong>
							        <em class="prod-sub-desc">滋晶雪瀅煥白水 Snowise Brightening Water</em>
							        <span class="prod-price">HKD $440 / 125ml</span>
							        <ul class="prod-sub-txt-list">
							            <li>雪花秀獨有Snowise Brightening Triplex™配方，提升美白透亮效果。</li>
							            <li>蘊含桑根精華有效抵禦肌膚免受環境侵害，提高肌膚的透明度並撫平粗糙肌膚紋理，於其他美白產品前使用能幫助肌膚更有效吸收後續成分。</li>
							            <li>啫喱質感易於被肌膚吸收，快速滲透深層灌注水分，為肌膚滋養補濕。</li>
							        </ul>
							    </div>
							</div>

							<div class="prod-desc">
							    <div>
							        <img class="prod-img" src="/media/html/resource/img/news/snowise_brightening_emulsion_news_hk.jpg" alt="">
							    </div>
							    <div class="prod-text">
							        <strong class="prod-sub-tit">輕薄水潤乳液 締造柔嫩淨透肌膚</strong>
							        <em class="prod-sub-desc">滋晶雪瀅煥白乳液 Snowise Brightening Emulsion</em>
							        <span class="prod-price">HKD $470 / 125ml</span>
							        <ul class="prod-sub-txt-list">
							            <li>蘊含白花蛇舌草成分，有效抵禦肌膚免受環境侵害。</li>
							            <li>豐富的綠茶萃取物，能調整肌膚狀態，加強肌膚的亮白光采，煥發年輕活力。</li>
							            <li>乳液質感輕薄水潤，能快速滲透，締造柔嫩淨透肌膚。</li>
							        </ul>
							    </div>
							</div>

							<div class="prod-desc">
							    <div>
							        <img class="prod-img" src="/media/html/resource/img/news/snowise_brightening_spot_treatment_news_hk.jpg" alt="">
							    </div>
							    <div class="prod-text">
							        <strong class="prod-sub-tit">從根源淡褪斑瑕 散發亮白光彩</strong>
							        <em class="prod-sub-desc">滋晶雪瀅煥白淡斑精華 Snowise Brightening Spot Treatment</em>
							        <span class="prod-price">HKD $880 / 35ml</span>
							        <ul class="prod-sub-txt-list">
							            <li>蘊含珍貴白參成分，深入暗沉根源，抑制黑色素細胞，集中淡化肌底黑色素沉著、斑點與瑕疵。</li>
							            <li>清爽而不油膩，以指腹輕推按摩於臉部斑點處，有效減淡已形成的色斑，明亮及均勻膚色。</li>
							        </ul>
							    </div>
							</div>

							<div class="prod-desc">
							    <div>
							        <img class="prod-img" src="/media/html/resource/img/news/snowise_brightening_cream_news_hk.jpg" alt="">
							    </div>
							    <div class="prod-text">
							        <strong class="prod-sub-tit">深度亮白保濕 肌膚水盈飽滿</strong>
							        <em class="prod-sub-desc">滋晶雪瀅煥白面霜 Snowise Brightening Cream</em>
							        <span class="prod-price">HKD $870 / 50ml</span>
							        <ul class="prod-sub-txt-list">
							            <li>以白參皂苷搭配白花蛇舌草，從根源淡化黑色素，提升肌膚緊緻與均勻度，深度亮白補濕且築起鎖水障屏，維持豐盈水潤養分。</li>
							            <li>配以仙人果萃取物，使膚質柔滑細緻。</li>
							            <li>細緻的薄透質地軟滑如霜，可迅速被肌膚吸收，締造水盈飽滿感。</li>
							        </ul>
							    </div>
							</div>

							<div class="prod-desc">
							    <div>
							        <img class="prod-img" src="/media/html/resource/img/news/snowise_brightening_mask_news_hk.jpg" alt="">
							    </div>
							    <div class="prod-text">
							        <strong class="prod-sub-tit">豐饒白參滲透 淨白補水潤顏</strong>
							        <em class="prod-sub-desc">滋晶雪瀅煥白面膜 Snowise Brightening Mask</em>
							        <span class="prod-price">HKD $880 / 10片</span>
							        <ul class="prod-sub-txt-list">
							            <li>蘊含豐富白參成分，每片面膜皆浸泡珍貴的Snowise Brightening Serum經人手發酵2星期，大大提高面膜精華液承載量，短時間內紓緩膚色不均與暗沉，加速骨膠原合成消除沉著色素，提昇肌膚整體剔透度。</li>
							            <li>獨特呈透明凝膠質地的面膜比一般面膜材質緻密度高達500倍，猶如第二層肌膚般的貼合度令活性成分可被迅速吸收，肌膚深層淨白，提升飽滿亮澤感。</li>
							        </ul>
							    </div>
							</div>

							<div class="prod-desc">
							    <div>
							        <img class="prod-img" src="/media/html/resource/img/news/snowise_brightening_exfoliating_mask_news_hk.jpg" alt="">
							    </div>
							    <div class="prod-text">
							        <strong class="prod-sub-tit">還原淨白的塗抹式面膜</strong>
							        <em class="prod-sub-desc">滋晶雪瀅煥白磨砂面膜 Snowise Brightening Exfoliating Mask</em>
							        <span class="prod-price">HKD $480 / 80ml</span>
							        <ul class="prod-sub-txt-list">
							            <li>白參粉末配以蜂蜜及韓方草藥補濕複合物，溫和更新煥膚，帶走肌膚老化角質及污垢雜質，並提供補濕呵護。</li>
							            <li>啫喱狀的白參粒子從毛孔中帶走老化角質及污垢，淨化肌膚，讓肌膚還原淨白散發健康光澤。</li>
							            <li>煥膚產品同時也是面膜，可於沐浴期間使用，配以輕柔地按摩，滋潤肌膚。</li>
							        </ul>
							    </div>
							</div>
							</div>
					</div>
				</div>
				<!-- //HTML or text 삽입 -->
			</div>
		</div>
			
		<!-- E : 이미지인 경우 -->
		
		<!-- S : 영상인 경우 -->
        
		<!-- E : 영상인 경우 -->
		<!-- S : HTML 영역으로 사용하는 경우-->
        
		<!-- E : HTML 영역으로 사용하는 경우 -->
	</div>
	<!-- E : ICS + 부분 HTML 영역으로 사용하는 경우 (Beauty Ritual, News, Print, film) -->
	

	<!-- E : 전체 HTML 영역으로 사용하는 경우 (event, cover, etc) -->
	<!-- S : 아카이브 컨텐츠 목록 -->
	<div class="others-archive-list-wrap">
		<div class="others-archive-list">
			<button class="sul-slide-btn-prev"><span class="blind">이전</span></button>
			<div class="sul-slide-list others-list">
				<div class="sul-slide-item others-item">
					<a href="/hk/zh/experience/archive/1314968_3836.html" class="thumb" ap-click-area="Contents" ap-click-name="Click - Contents" ap-click-data="Sulwhasoo Post Others_雪花秀全新推出UV Wise Brightening Multi Protector<br>溫和親膚零負擔 亮肌防曬抗污染 打造健康自信美肌" tabindex="0">
						<div class="thumb-frame">
							<div class="cover"><span class="category">NEWS</span></div>
							<img src="/media/html/experience/archive/__icsFiles/afieldfile/2021/07/14/thumbnail_article_1.jpg" alt="Sulwhasoo releases upgraded anti-pollution, sun-care cream, UV Wise Brightening Multi Protector">
						</div>
					</a>
				</div>
				<div class="sul-slide-item others-item">
					<a href="/hk/zh/experience/archive/1314969_3836.html" class="thumb" ap-click-area="Contents" ap-click-name="Click - Contents" ap-click-data="Sulwhasoo Post Others_雪花秀2020限量版彩妝系列<br>Spring Into Happiness<br>韓式粉嫩春妝氣色 綻放春日迷人氣息" tabindex="0">
						<div class="thumb-frame">
							<div class="cover"><span class="category">NEWS</span></div>
							<img src="/media/html/experience/archive/__icsFiles/afieldfile/2021/08/23/KakaoTalk_20210823_163311146.jpg" alt="Sulwhasoo launches its new “2020 Spring Limited Collection”">
						</div>
					</a>
				</div>
				<div class="sul-slide-item others-item">
					<a href="/hk/zh/experience/archive/1314966_3836.html" class="thumb" ap-click-area="Contents" ap-click-name="Click - Contents" ap-click-data="Sulwhasoo Post Others_雪花秀至臻巨獻 – Timetreasure Honorstige<br> 珍雪芊萃琉金霜及精華 <br>內外強化修護肌膚 臻極尊貴韓方 譜寫恆久美顏傳奇" tabindex="0">
						<div class="thumb-frame">
							<div class="cover"><span class="category">NEWS</span></div>
							<img src="/media/html/experience/archive/__icsFiles/afieldfile/2021/07/14/timetreasure_1.jpg" alt="Sulwhasoo launches the new Timetreasure Honorstige">
						</div>
					</a>
				</div>
			</div>
			<button class="sul-slide-btn-next"><span class="blind">다음</span></button>
		</div>
	</div>
	<!-- E : 아카이브 컨텐츠 목록 -->
</section>

<script>
	require([
	'jquery',
	'js/plugins/slick/slick'
	], function ($) {
	    $('.others-list').slick({
	        slidesToShow: 3,
	        slidesToScroll: 1,
	        arrows: true,
	        fade: false,
	        dots: false,
	        infinite : false,
	        draggable : true,
	        prevArrow: $('.others-archive-list').find('.sul-slide-btn-prev'),
	        nextArrow: $('.others-archive-list').find('.sul-slide-btn-next'),
	        responsive: [{
	            breakpoint: 768,
	            settings: {
	                slidesToShow: 1.5,
	                slidesToScroll: 1
	            }
	        }]
	    });
	});

</script>