<!--<title>Better Skin Every Day<br>with First Care Activating Serum<br>#6 Instant 8 Hours of Sleep Care | 雪花秀</title>-->
<!--<meta name="description" content="雪花秀資訊 - Better Skin Every Day<br>with First Care Activating Serum<br>#6 Instant 8 Hours of Sleep Care | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="og:title" content="Better Skin Every Day<br>with First Care Activating Serum<br>#6 Instant 8 Hours of Sleep Care | 雪花秀">-->
<!--<meta property="og:description" content="雪花秀資訊 - Better Skin Every Day<br>with First Care Activating Serum<br>#6 Instant 8 Hours of Sleep Care | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="twitter:title" content="Better Skin Every Day<br>with First Care Activating Serum<br>#6 Instant 8 Hours of Sleep Care | 雪花秀">-->
<!--<meta property="twitter:description" content="雪花秀資訊 - Better Skin Every Day<br>with First Care Activating Serum<br>#6 Instant 8 Hours of Sleep Care | Sulwhasoo Hong Kong 中國香港">-->
<section class="content renewal-archive-detail">
		
		<!-- S : ICS + 부분 HTML 영역으로 사용하는 경우 (Beauty Ritual, News, Print, film) -->
        
		<div class="archive-section">
            <div class="archive-header">
                <div class="header-inner">
                    <h1 class="h">Better Skin Every Day<br>with First Care Activating Serum<br>#6 Instant 8 Hours of Sleep Care</h1>
					<span class="type">Film</span>
					<span class="date">2020.04.09</span>
				</div>
			</div>
			<!-- S : 이미지인 경우 Beauty Ritual, News, Print-->
            
			<!-- S : 영상인 경우 -->
            
			<div class="archive-content">
				<a href="https://youtu.be/17H_dtwTIQQ" class="archive-player yt-player media" data-track-name="movie">
					<img src="/media/html/experience/archive/__icsFiles/afieldfile/2020/04/03/09_940.png" alt="Better Skin Every Day with First Care Activating Serum #6 Instant 8 Hours of Sleep Care">
					<i class="icon-play icon-expend"></i>
				</a>
				
				<div class="film-desc">
					<!-- HTML or text 삽입 -->
					<!-- <div class="desc" tabindex="0"> -->
					<div class="desc" tabindex="0"> 
						(Subtitles)<br>
						Better Skin Every Day with First Care Activating Serum<br>
						#Day6 Instant 8 Hours of Sleep Care<br><br>

						With First Care Activating Serum, <br>
						you can make your skin look well-rested, <br>
						even when you haven't, and look better in makeup<br><br>

						After washing your face, <br>
						moisten cotton pads with First Care Activating Serum<br>
						and lay them on your cheeks, <br>
						forehead, <br>
						and eyelids, <br>
						for 5 minutes. <br><br>

						And one more tip! <br><br>

						Before doing your makeup, <br>
						put some First Care Activating Serum<br>
						on your makeup sponge and apply concealer to your dark circles<br>
						and see them disappear like magic. <br><br>

						Instant 8 Hours of Sleep Care<br>
						#First Care Activating Serum
					</div>
												
					<!-- </div> -->
					<!-- //HTML or text 삽입 -->
				</div>
			</div>
            
			<!-- E : 영상인 경우 -->
			<!-- S : HTML 영역으로 사용하는 경우-->
            
			<!-- E : HTML 영역으로 사용하는 경우 -->
		</div>
		<!-- E : ICS + 부분 HTML 영역으로 사용하는 경우 (Beauty Ritual, News, Print, film) -->
		

		<!-- E : 전체 HTML 영역으로 사용하는 경우 (event, cover, etc) -->
		<!-- S : 아카이브 컨텐츠 목록 -->
		<div class="others-archive-list-wrap">
			<div class="others-archive-list">
				<button class="sul-slide-btn-prev"><span class="blind">이전</span></button>
				<div class="sul-slide-list others-list">
					<div class="sul-slide-item others-item">
						<a href="/hk/zh/experience/archive/1314965_3836.html" class="thumb media" ap-click-area="Contents" ap-click-name="Click - Contents" ap-click-data="Sulwhasoo Post Others_First Care Activating Serum" tabindex="0">
							<div class="thumb-frame">
								<div class="cover"><span class="category">FILM</span></div>
								<img src="/media/html/experience/archive/__icsFiles/afieldfile/2021/07/15/20210402_final_archive_thumb_355_pc_01.jpg" alt="First Care Activating Serum">
								<i class="icon-play"><span class="blind">영상보기</span></i>
							</div>
						</a>
					</div>
					<div class="sul-slide-item others-item">
						<a href="/hk/zh/experience/archive/1314929_3836.html" class="thumb media" ap-click-area="Contents" ap-click-name="Click - Contents" ap-click-data="Sulwhasoo Post Others_Concentrated Ginseng Renewing Serum&amp;Rescue Ampoule_GINSENOMICS™" tabindex="0">
							<div class="thumb-frame">
								<div class="cover"><span class="category">FILM</span></div>
								<img src="/media/html/experience/archive/__icsFiles/afieldfile/2021/01/15/20210115_final_concentrated-ginseng-rescue-ampoule-texture_archive-list_pc_1.jpg" alt="Concentrated Ginseng Renewing Serum&amp;Rescue Ampoule_GINSENOMICS™">
								<i class="icon-play"><span class="blind">영상보기</span></i>
							</div>
						</a>
					</div>
					<div class="sul-slide-item others-item">
						<a href="/hk/zh/experience/archive/1314932_3836.html" class="thumb media" ap-click-area="Contents" ap-click-name="Click - Contents" ap-click-data="Sulwhasoo Post Others_HOW TO : F/W MAKEUP LOOK" tabindex="0">
							<div class="thumb-frame">
								<div class="cover"><span class="category">FILM</span></div>
								<img src="/media/html/experience/archive/__icsFiles/afieldfile/2020/09/21/20200921_final_perfecting-foundation_archive-main_350_1.jpg" alt="HOW TO : F/W MAKEUP LOOK">
								<i class="icon-play"><span class="blind">영상보기</span></i>
							</div>
						</a>
					</div>
				</div>
				<button class="sul-slide-btn-next"><span class="blind">다음</span></button>
			</div>
		</div>
		<!-- E : 아카이브 컨텐츠 목록 -->
	</section>
<script>
	require([
	'jquery',
	'js/plugins/slick/slick'
	], function ($) {
	    $('.others-list').slick({
	        slidesToShow: 3,
	        slidesToScroll: 1,
	        arrows: true,
	        fade: false,
	        dots: false,
	        infinite : false,
	        draggable : true,
	        prevArrow: $('.others-archive-list').find('.sul-slide-btn-prev'),
	        nextArrow: $('.others-archive-list').find('.sul-slide-btn-next'),
	        responsive: [{
	            breakpoint: 768,
	            settings: {
	                slidesToShow: 1.5,
	                slidesToScroll: 1
	            }
	        }]
	    });
	});

</script>