<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */
?>
<div class="content_logout">
    <p><?= $block->escapeHtml(__('You have successfully logged out.')) ?></p>
    <a href="<?= $this->getUrl('/') ?>" class="action secondary"><?= $block->escapeHtml(__('Go to main page')) ?></a>
</div>


