<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login\Info $block */
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
    <a href="<?= $block->escapeUrl($block->getCreateAccountUrl()) ?>"
       class="action create"
       ap-click-area="<?= $block->escapeHtmlAttr('login') ?>"
       ap-click-name="<?= $block->escapeHtmlAttr('login menu click') ?>"
       ap-click-data="<?= $block->escapeHtmlAttr('New to Laneige? Create new account') ?>"
        <span><?= $block->escapeHtml(__('New to Laneige? Create new account')) ?></span>
    </a>
<?php endif; ?>
