<?php
/**
 * @author Eguana Team
 * @copyriht Copyright (c) 2020 Eguana {http://eguanacommerce.com}
 * Created by PhpStorm
 * User: raheel
 * Date: 11/3/21
 * Time: 8:50 PM
 */

/** @var \Eguana\Redemption\Block\RedemptionDetails $block */
/** @var \Eguana\Redemption\ViewModel\RedemptionDetail $viewModel */
$viewModel = $block->getData('redemption_view_model');
$redemption = $viewModel->getRedemption();
$thankYouImage = $viewModel->getThumbnailImageURL($redemption->getThankYouImage());
$participantId = $block->getRequest()->getParam('participant_id');
if ($participantId): ?>
<script type="text/javascript">
    window.AP_REDEMPTION_ID = '<?= $participantId ?>'
</script>
<?php endif;?>
<?php if ($thankYouImage): ?>
    <div class="message success">
        <span><?= $block->escapeHtml(__('You have successfully applied for redemption, please check your email and newsletter.')); ?></span>
    </div>
    <div class="redemption-success-image-box">
        <img
            class="redemption-success-image"
            src="<?= $block->escapeHtmlAttr($thankYouImage); ?>"
            alt="thank-you-image"/>
    </div>
<?php endif; ?>
