<?php
/**
 * @author Eguana Team
 * @copyright Copyright (c) 2020 Eguana {http://eguanacommerce.com}
 * Created by PhpStorm
 * User: umer
 * Date: 23/7/20
 * Time: 6:21 PM
 */
/** @var $viewModel \Eguana\Pip\ViewModel\LeaveAccount */
$viewModel = $block->getData('view_model_leave_account');
$isEnabled = $viewModel->getHelper()->isEnabledInFrontend();
?>
<?php if ($isEnabled): ?>
<div class="pip-box-actions box-actions">
    <a href="javascript:void(0);" class="action" id="account-leave">
        <span class="leave_account_action"><?= $block->escapeHtml(__('Click here to leave account')) ?></span>
    </a>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
   {
       "*": {
             "accountLeaveModal": {}
       }
   }
</script>
