<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Amore\CustomerRegistration\Block\Widget\CheckBox $block */
$isSelected = $block->getFormValue();
?>
<div class="checkbox-wrapper choice field <?= $block->getAttributeCode() ?><?= $block->isRequired() ? ' required' : ''?>">
    <select style="display: none"  id="<?= $block->escapeHtmlAttr($block->getFieldId($block->getAttributeCode())) ?>" name="<?= $block->escapeHtmlAttr($block->getFieldName($block->getAttributeCode())) ?>" title="<?= $block->escapeHtmlAttr($block->getStoreLabel($block->getAttributeCode())) ?>"<?php if ($block->isRequired()) : ?> class="validate-select" data-validate="{required:true}"<?php endif; ?>>
        <?php $options = $block->getOptions(); ?>
        <?php $value = $block->getData($block->getAttributeCode())?$block->getData($block->getAttributeCode()):0; ?>
        <?php foreach ($options as $option) : ?>
            <option value="<?= $block->escapeHtmlAttr($option->getValue()) ?>"<?= ($option->getValue() == $isSelected) ? ' selected="selected"' : '' ?>><?= $block->escapeHtml(__($option->getLabel())) ?></option>
        <?php endforeach;?>
    </select>
    <input type="checkbox" name="<?= $block->getAttributeCode() ?>_checkbox" id="sel_<?= $block->escapeHtmlAttr($block->getFieldId($block->getAttributeCode())) ?>" class="<?= $block->getAttributeCode() ?>_checkbox select_unselect_terms" <?= $isSelected == 1?'checked':''; ?> <?= $block->getAttributeCode() == 'terms_and_services_policy'?'data-validate="{required:true}"':''; ?> />
    <?php if($block->getAttributeCode() != 'mobile_number') : ?>
        <label class="<?= $block->getAttributeCode().'-label' ?> label" for="<?= $block->escapeHtmlAttr($block->getFieldId($block->getAttributeCode())) ?>">
            <span>
                <?php if ($block->getData('change_text') && $block->getAttributeCode() == 'terms_and_services_policy'): ?>
                    <?= __('I hereby agree to the terms in the Data protection and Privacy Policy Notice.') ?>
                <?php elseif($block->getData('change_text') && $block->getAttributeCode() == 'term_personal_data'): ?>
                    <?= __('I hereby consent to the processing of my Personal Data for the above purposes and to receive email from LANEIGE.') ?>
                <?php else: ?>
                    <?= $block->escapeHtml($block->getStoreLabel($block->getAttributeCode())) ?>
                <?php endif;?>
            </span>
        </label>
    <?php else: ?>
        <label class="<?= $block->getAttributeCode().'-label' ?> label" for="<?= $block->escapeHtmlAttr($block->getFieldId($block->getAttributeCode())) ?>"><span><?= $block->escapeHtml(__('Change mobile number')) ?></span></label>
    <?php endif; ?>
    <?php if(in_array($block->getAttributeCode(), ['terms_and_services_policy', 'term_personal_data'])): ?>
        <span>
        <a href="#" id="<?= $block->getAttributeCode().'-read-policy' ?>" target="_blank"><?= $block->escapeHtml(__('Read more')) ?></a>
    </span>
    <?php endif; ?>
</div>
<?php if(in_array($block->getAttributeCode(), ['terms_and_services_policy', 'term_personal_data'])): ?>
    <div class="<?= $block->getAttributeCode().'-policy-popup' ?>" style="display: none;">
        <?=  $block->getReadMoreContent($block->getAttributeCode()); ?>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "*": {
            "checkboxfield":{
                "attributeCode": "<?= $block->getAttributeCode() ?>"
            }
        }
    }
</script>
