<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login\Info $block */
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
    <a href="<?= $block->escapeUrl($block->getCreateAccountUrl()) ?>" class="action create"><span><?= $block->escapeHtml(__('Create an Account')) ?></span></a>
<?php endif; ?>
