<?php
/**
 * Top menu for store
 *
 * @see \Sapt\Megamenu\Block\Topmenu
 */
?>
<?php
    $_helper = $this->helper('Sapt\Megamenu\Helper\Data');
    $_config = $_helper->getConfig('sapt_megamenu');
    $columnsLimit = 0;
    if($_config['general']['enable']) {
?>
<?php $_menu = $block->getMegamenuHtml(); ?>

<nav class="navigation sapt-megamenu side-megamenu" role="navigation">
    <ul>
        <?php echo $_menu; ?>
    </ul>
</nav>

<script type="text/javascript">
    require([
        'jquery',
        'Sapt_Megamenu/js/sapt_megamenu'
    ], function ($) {
        $(".sapt-megamenu").saptMegamenu();
    });
</script>
<?php
    }
?>
