<?php
/**
TODO: event best seller page template
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */

// phpcs:disable Generic.Files.LineLength.TooLong
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

$galleryId = $block->getData('id');
?>

<?php if ($block->getProductCollection()): ?>
    <?php
    /** @var \Satp\CustomWidget\Helper\GalleryImage $_helperGallery */
    $_helperGallery = $this->helper(\Satp\CustomWidget\Helper\GalleryImage::class);
    $_helper = $this->helper(Magento\Catalog\Helper\Output::class);
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = false;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
    ?>
    <div class="block widget widget_new_page block-products-list <?= /* @noEscape */ $mode ?> <?php if ($block->getModeStyle()): ?><?= $block->escapeHtml(__($block->getModeStyle())) ?><?php endif ?>">
        <?php if ($block->getTitle()): ?>
            <div class="block-title">
                <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
            </div>
        <?php endif ?>
        <div class="block-content">
            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
            <div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
                <ol class="product-items products list items <?= /* @noEscape */ $type ?>">
                    <?php $iterator = 1; ?>
                    <?php
                    foreach ($items as $_item) :
                        $productSku = $_item->getSku();
                        ?>
                        <?= /* @noEscape */ ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                        <div class="product-item-wrapper">
                            <div class="product-item-info">
                                <?php /*
                                <?php if ($_item->getProductLabels()): ?>
                                    <div class="product_labels">
                                        <?php echo $_helper->productAttribute($_item, $_item->getProductLabels(), 'product_labels') ?>
                                    </div>
                                <?php endif;?>
                                */ ?>
                                <div class="product-item-details">
                                    <?php /*
                                        <div class="product_tags">
                                            <?php if ($_item->getProductTags()): ?>
                                                <?php echo $_helper->productAttribute($_item, $_item->getProductTags(), 'product_tags') ?>
                                            <?php endif;?>
                                        </div>
                                    */ ?>
                                    <?php if($_item->getData('new')):?>
                                        <span class="product-item-flag"><?= $block->escapeHtml($_item->getResource()->getAttribute('new')->getStoreLabel());?></span>
                                    <?php endif;?>
                                    <?php if($_item->getData('best')):?>
                                        <span class="product-item-flag"><?= $block->escapeHtml($_item->getResource()->getAttribute('best')->getStoreLabel()); ?></span>
                                    <?php endif;?>
                                    <strong class="product-item-name">
                                        <a title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                           href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                           class="product-item-link"
                                           ap-click-area="product"
                                           ap-click-name="prd click"
                                           ap-click-data="<?= $block->escapeHtmlAttr($block->getProductDefaultName($productSku) . '/' . $productSku); ?>">
                                            <?= $block->escapeHtml($_item->getName()) ?>
                                        </a>
                                    </strong>
                                    <div class="product-item-short-description">
                                        <?= $this->helper(Magento\Catalog\Helper\Output::class)->productAttribute($_item, $_item->getShortDescription(), 'short_description') ?>
                                    </div>

                                    <?= $block->getProductPriceHtml($_item, $type) ?>

                                    <?php if ($templateType): ?>
                                        <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                    <?php endif; ?>

                                    <div class="product-item-inner">
                                        <div class="product-item-actions">
                                            <div class="actions-primary">
                                                <?php if ($showCart): ?>
                                                    <?php if ($_item->isSaleable()): ?>
                                                        <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                        <form data-role="tocart-form"
                                                              data-product-sku="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                                                              action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
                                                            <input type="hidden" name="product" value="<?= $block->escapeUrl($postParams['data']['product']) ?>">
                                                            <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                            <?= $block->getBlockHtml('formkey') ?>
                                                            <button type="submit"
                                                                    title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                                    class="action tocart primary">
                                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                            </button>
                                                        </form>
                                                    <?php endif; ?>
                                                <?php endif?>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="new-gallery">
                                <div id="<?= $galleryId ?>" class="gallery-item-wrapper">
                                    <?php
                                    $_helperGallery->addGallery($_item);
                                    $images = $_helperGallery->getGalleryImages($_item);
                                    if ($images instanceof \Magento\Framework\Data\Collection) {
                                        foreach ($images as $image) {
                                            ?>
                                            <div><img src="<?php echo $image->getData('medium_image_url')  ?>" alt="<?= $block->escapeHtml($_item->getName()) ?>"/></div>
                                            <?php
                                        }
                                    }
                                    ?>
                                </div>

                                <?php if(!$_item->getData('offline')):?>
                                    <?php if ($showWishlist || $showCompare || $showCart): ?>
                                        <?php if ($showWishlist || $showCompare): ?>
                                            <div class="actions-secondary add_to_item" data-role="add-to-links">
                                                <?php if ($this->helper(Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist): ?>
                                                    <?php $viewModel = $block->getData('wishlistStatusViewModel'); ?>
                                                    <?php if ($viewModel && $viewModel->moduleStatus()): ?>
                                                        <!-- ko scope: 'ajaxwishlist' -->
                                                        <a
                                                            class="action towishlist"
                                                            data-bind="css:{wishlisticon : wishlistitem().all_wishlist_items ?
                                                                            typeof wishlistitem().all_wishlist_items[<?=/* @noEscape */$_item->getId()?>] !='undefined':false}"
                                                            data-product-id='<?= /* @noEscape */$_item->getId() ?>'
                                                            data-action="wishlist-actions"><span><?= $block->escapeHtml(__('Add to Wish List')) ?></span></a>
                                                        <!-- /ko -->
                                                    <?php else: ?>
                                                        <a href="#"
                                                           data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                            <span><?= $block->escapeHtml(__('Add to Wishlist')) ?></span>
                                                        </a>
                                                    <?php endif; ?>

                                                <?php endif; ?>
                                                <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                    <?php $compareHelper = $this->helper(Magento\Catalog\Helper\Product\Compare::class);?>
                                                    <!-- ko scope: 'compareAction' -->
                                                    <a href="#" class="action tocompare"
                                                       data-bind="css:{ compared: isAddedToCompare('<?= $_item->getId() ?>') }"
                                                       data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>'
                                                       title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                        <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                    </a>
                                                    <!-- /ko  -->
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
        </div>
    </div>
    <?php if($block->getBlockHtml('formkey')): ?>
        <script type="text/x-magento-init">
    {
        ".block.widget [data-role=tocart-form]": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
    </script>
    <?php endif;?>
<?php endif;?>

<script type="text/javascript">
    require(['jquery', 'slick'], function($, slick) {
        $(document).ready(function() {
            $("#<?= $galleryId ?>").on('init', function(event, slick){
                $('<div class="wrap-progress kv-progress">\n' +
                    '      <div class="inner-progress">\n' +
                    '        <div class="progress"><span class="progress_ing"></span></div>\n' +
                    '      </div>\n' +
                    '    </div>').appendTo('#<?= $galleryId ?> .slick-button');
                $KvProgressBarWrap = $('#<?= $galleryId ?> .wrap-progress.kv-progress');
                $KvProgressBar = $('#<?= $galleryId ?> .kv-progress .progress .progress_ing');

                var slideNum = slick.$slides.length;

                if (slideNum > 1) $KvProgressBarWrap.css('opacity', 1);

                var calc = (100 / (slick.slideCount / 1));

                $KvProgressBar.css({
                    'width': calc + '%',
                });

                if (slick.$slides[0].classList.contains('txt_black')) $KvProgressBarWrap.addClass('txt_black');
                else $KvProgressBarWrap.removeClass('txt_black');
            });
            $("#<?= $galleryId ?>").on("beforeChange", function (event, slick, currentSlide, nextSlide){
                $KvProgressBarWrap = $('#<?= $galleryId ?> .wrap-progress.kv-progress');
                $KvProgressBar = $('#<?= $galleryId ?> .kv-progress .progress .progress_ing');
                if (slick.$slides[nextSlide].classList.contains('txt_black')) $KvProgressBarWrap.addClass('txt_black');
                else $KvProgressBarWrap.removeClass('txt_black');

                var calc = (100 / (slick.slideCount / 1)) * (nextSlide + 1);

                $KvProgressBar.css({
                    'width': calc + '%',
                });
            });

            $('#<?= $galleryId ?>').slick({
                dots: true,
                infinite: true,
                speed: 300,
                autoplay: true,
                slidesToShow: 1,
                adaptiveHeight: true
            });
        })
    });
</script>
