<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Sales\Block\Order\Info */ ?>
<?php $_order = $block->getOrder() ?>
<?php if (!$_order->getIsVirtual()) : ?>
    <?php
    $shippingAddress = $_order->getShippingAddress();
    $allowedAddressHtmlTags = ['b', 'br', 'em', 'i', 'li', 'ol', 'p', 'strong', 'sub', 'sup', 'ul'];
    ?>
    <div class="block block-order-shipping">
        <div class="block-title">
            <strong><?= $block->escapeHtml(__('Shipping Address')) ?></strong>
        </div>
        <div class="block-content">
            <div class="info-item">
                <span class="label"><?= __('Email') ?></span>
                <span><?= $_order->getCustomerEmail() ?></span>
            </div>
            <div class="info-item">
                <span class="label"><?= __('Name') ?></span>
                <span><?= $shippingAddress->getName() ?></span>
            </div>
            <div class="info-item">
                <span class="label"><?= __('Phone number') ?></span>
                <span><?= $shippingAddress->getTelephone() ?></span>
            </div>
            <div class="info-item">
                <span class="label"><?= __('Shipping method') ?></span>
                <span>
                    <?php if ($_order->getShippingDescription()) : ?>
                        <?= $block->escapeHtml($_order->getShippingDescription()) ?>
                    <?php else : ?>
                        <?= $block->escapeHtml(__('No shipping information available')) ?>
                    <?php endif; ?>
                </span>
            </div>
            <div class="info-item">
                <span class="label"><?= __('Address') ?></span>
                <span><?= $block->escapeHtml($block->getFormattedAddress($shippingAddress), $allowedAddressHtmlTags) ?></span>
            </div>
        </div>
    </div>
<?php endif; ?>

<div class="block block-order-payment">
    <div class="block-title">
        <strong><?= $block->escapeHtml(__('Payment Detail')) ?></strong>
    </div>
    <div class="block-content">
        <div class="payment-method">
            <span class="label"><?= __('Payment method') ?></span>
            <?= $block->getPaymentInfoHtml() ?>
        </div>

        <table class="table totals">
            <?= $block->getChildHtml('order_totals') ?>
        </table>
    </div>
</div>
<?php if ($block->getRequest()->getActionName() != 'print'): ?>
    <div class="actions-toolbar">
        <div class="secondary">
            <a class="action back" href="<?= $block->getUrl('sales/order/history') ?>">
                <span><?= __('Back to the list') ?></span>
            </a>
        </div>
    </div>
<?php endif; ?>
