<?php
/** @var \Eguana\CustomerRefund\ViewModel\Refund $refundOnlineViewModel */
/** @var \Magento\Framework\View\Element\Template $block */
$refundOnlineViewModel = $block->getRefundOnlineViewModel();
/** @var \Magento\Sales\Model\Order $_order */
$_order = $block->getOrder();
?>
<div class="order-info">
    <div class="order-date">
        <span class="label"><?= $block->escapeHtml(__('Order Date')) ?></span>
        <span class="value"><?= $block->escapeHtml($block->formatDate($block->getOrder()->getCreatedAt(), \IntlDateFormatter::LONG)) ?></span>
    </div>
    <div class="order-number">
        <span class="label"><?= $block->escapeHtml(__('Order Number')) ?></span>
        <span class="value"><?= $block->escapeHtml($block->getOrder()->getIncrementId()) ?></span>
    </div>
    <div class="order-status">
        <span class="label"><?= $block->escapeHtml(__('Order Status')) ?></span>
        <span class="value"><?= $block->escapeHtml(__($block->getOrder()->getStatusLabel())) ?></span>
    </div>
    <div class="order-cancel">
        <?php if ($refundOnlineViewModel->canShowRefundOnlineButton($_order)): ?>
            <span class="label">
                <a href="#" class="action refund-online" data-role="refund-online-button"
                                   data-mage-init='{"Eguana_CustomerRefund/js/view/refund-confirmation": {"orderId": "<?= (int)$_order->getId() ?>"}}'>
                    <span><?= $block->escapeHtml(__('Cancel Order')) ?></span>
                </a>
            </span>
        <?php endif; ?>
        <?php if ($this->helper(Magento\Rma\Helper\Data::class)->canCreateRma($block->getOrder()) && $refundOnlineViewModel->availableFreeReturn()) : ?>
            <span class="label">
                <a href="<?= $block->escapeUrl($this->helper(Magento\Rma\Helper\Data::class)->getReturnCreateUrl($block->getOrder())) ?>" class="action return"><span><?= $block->escapeHtml(__('Return request')) ?></span></a>
            </span>
        <?php endif;?>
    </div>
</div>
