<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="order-info">
    <div class="order-date">
        <?= $block->escapeHtml(
            __(
                '<span class="label">Order Date</span> %1',
                '<span>' . $block->formatDate($block->getOrder()->getCreatedAt(), \IntlDateFormatter::LONG) . '</span>'
            ),
            ['span']
        )?>
    </div>
    <div class="order-number">
        <?= $block->escapeHtml(
            __(
                '<span class="label">Order Number</span> %1',
                '<span>' . $block->getOrder()->getIncrementId() . '</span>'
            ),
            ['span']
        )?>
    </div>
    <div class="order-status">
        <?= $block->escapeHtml(
            __(
                '<span>' . $block->escapeHtml(__($block->getOrder()->getStatusLabel())) . '</span>'
            ),
            ['span']
        )?>
    </div>
</div>
