<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Sales\Block\Order\Info */ ?>
<div class="order-info">
    <span class="order-id"><?= __('Order #').$block->escapeHtml($block->getOrder()->getRealOrderId()) ?></span>
    <span class="order-status"><?= $block->escapeHtml($block->getOrder()->getStatusLabel()) ?></span>
    <?php if ($block->getOrder()->getStatus() === 'shipment_failure'): ?>
        <div class="order-status-message"><?= $block->escapeHtml(__('Due to the abnormal delivery of the CVS, please contact the customer service and place the order again.')) ?></div>
    <?php endif; ?>
    <?= $block->getChildHtml();?>
</div>
