<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div data-role="loader" class="loading-mask" data-mage-init='{"preLoader": {}}'>
    <div class="loader">
        <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif')); ?>"
             alt="<?= $block->escapeHtmlAttr(__('Loading...')); ?>"
             style="position: absolute;">
    </div>
</div>
