<?php
/**
 * Created by Eguana Team.
 * User: sonia
 * Date: 7/5/20
 * Time: 8:08 AM
 */

/** @var \Eguana\CustomerRefund\ViewModel\Refund $refundOfflineViewModel */
/** @var \Magento\Framework\View\Element\Template $block */
$refundOfflineViewModel = $block->getRefundOfflineViewModel();
/** @var \Magento\Sales\Model\Order $_order */
$_order = $block->getOrder();
?>
<?php if ($refundOfflineViewModel->canShowRefundOfflineButton($_order)): ?>
<a href="#" class="action refund-offline bankinfo-popup-wrapper" data-role="refund-offline-button">
    <span><?= __('Request to Refund') ?></span>
</a>
<div data-bind="scope: 'bankinfo_popup'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "bankinfo_popup": {
                    "component": "Eguana_CustomerRefund/js/view/bankinfo-modal",
                    "orderId": "<?= (int)$_order->getId() ?>",
                    "button": "[data-role=refund-offline-button]",
                    "options": {
                        "title": "<?= $block->escapeJs($block->escapeHtml(__('Please enter a bank information for your refund.')))?>",
                        "modalClass": "bankinfo-popup"
                    },
                    "children": {
                        "form": {
                            "component": "Eguana_CustomerRefund/js/view/bankinfo-form",
                            "template": "Eguana_CustomerRefund/bankinfo-form"
                        }
                    }
                }
            }
        }
    }
}
</script>
<?php endif;?>




