<?php
/**
 * Created by Eguana.
 * User: Brian
 * Date: 2020-09-29
 * Time: 오후 7:16
 */
/** @var $block \Eguana\CustomRma\Block\Order\Button */
$order = $block->getOrder();
?>
<?php if ($this->helper(Magento\Rma\Helper\Data::class)->canCreateRma($block->getOrder()) && $block->availableFreeReturn()) : ?>
    <a href="<?= $block->escapeUrl($this->helper(Magento\Rma\Helper\Data::class)->getReturnCreateUrl($block->getOrder())) ?>" class="action return"><span><?= $block->escapeHtml(__('Return request')) ?></span></a>
<?php endif;?>
