<?php
/**
 * @author Eguana Team
 * @copyriht Copyright (c) 2020 Eguana {http://eguanacommerce.com}
 * Created by PhpStorm
 * User: raheel
 * Date: 20/5/21
 * Time: 6:00 PM
 */

/**
 * Shopping cart totals update
 * @var $block \Magento\Checkout\Block\Cart\Totals
 * @var $viewModel \Eguana\CustomCheckout\ViewModel\CheckCart
 */
$viewModel = $block->getData('check_cart_view_model');
?>
<?php if (!$viewModel->isCartEmpty()): ?>
<script type="text/x-magento-init">
    {
         "*": {
            "updateCartTotals": {}
        }
    }
</script>
<?php endif; ?>
