<?php
/**
 * Created by Eguana.
 * User: Brian
 * Date: 2021-01-27
 * Time: 오전 10:46
 */
?>
<?= /* @noEscape */ $block->getButtonHtml(); ?>

<span class="collect-indicator" id="inventory_compensation_collect_span">
    <span id="inventory_compensation_collect_message_span"></span>
</span>
<script type="text/x-magento-init">
   {
       "*": {
           "inventory_compensation_cron": {"manualRunUrl":"<?= $block->escapeUrl($block->getAjaxUrl()) ?>"}
       }
   }
</script>
