<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div style="text-align: center">
<h1>Service Temporarily Unavailable Notice</h1>
<p>

    We are currently working on a service check and upgrade for better service.<br>
    Please understand that the service may be unstable during the period below, and please use the site after maintenance.</p>
<p>
    We apologize for any inconvenience caused by this service maintenance.<br>
    We will do our best to provide stable service.</p>

<p>thank you.</p>
</div>
