<!--<title>李智善 - 雪花秀風格 Sulwhasoo Style | 雪花秀</title>-->
<!--<meta name="description" content="雪花秀風格 Sulwhasoo Style 專訪 設計師 李智善 面試詳情 | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="og:title" content="李智善 - 雪花秀風格 Sulwhasoo Style | 雪花秀">-->
<!--<meta property="og:description" content="雪花秀風格 Sulwhasoo Style 專訪 設計師 李智善 面試詳情 | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="twitter:title" content="李智善 - 雪花秀風格 Sulwhasoo Style | 雪花秀">-->
<!--<meta property="twitter:description" content="雪花秀風格 Sulwhasoo Style 專訪 設計師 李智善 面試詳情 | Sulwhasoo Hong Kong 中國香港">-->

<section class="content">
    <div class="blind">Sulwhasoo Style</div>
    
    <article class="sws-style">
		<div class="l-wrap l-full">
			<div class="basic style_basic"><div class="sws-style-visual">
				<h1 class="h1"><span class="title">設計師</span> <b class="name">李智善</b></h1>
				<img src="/media/html/resource/img/experience/sulwhasoo_style/1528437138195.jpg" class="only-desktop" alt="">
				<img src="/media/html/resource/img/experience/sulwhasoo_style/1528437138195m.jpg" class="only-mobile" alt="">
				</div>

			</div>

		</div>

		<div class="l-wrap">
			<div class="sws-style-body">
				<div class="content static parbase"><div class="sws-style-section">
					<blockquote class="blockquote">
					<p class="quote break-word">創作的理想國度</p>
					</blockquote>
					<div class="sws-style-sticky">
						<img src="/media/html/resource/img/experience/sulwhasoo_style/15284372978371.jpg" alt="Designer Lee Ji Sun">
					</div>
					<div class="sws-style-desc">
						<p class="q">設計師李智善，於2007年奪得韓國小姐冠軍，因而為人所熟悉。</p>
						<p class="p">
						  李智善在國外留學期間的一個偶然的機會下，參加了選美比賽。她憑著精緻的外表、優雅的姿態和明亮的眼睛，瞬間受到大眾的關注。然而她並沒有因為成為公眾人物而感到一絲煩惱，因她從來只從自己的角度出發看待自己，毫不在意別人的目光。她是自由的，她只選擇做自己想做的事，而不是做別人告訴她去做的事。「 我受到高度關注並經歷了許多，這同時亦是一個審視自己的機會，讓我能夠深刻思考我是誰。我一直希望能成為一名設計師。這條路是艱辛而漫長的，但我真的希望能完成自己的理想，所以我決意排除萬難，堅持走下去。現在我對自己這個決定感到滿意，如果我讓我再重頭選一次，我仍然會選擇成為一名設計師，因為沒有什麼比創作令我更覺開心。」<br>
						時裝對女性，甚至可以說對所有人類都很重要。一件衣服可以影響著你的感受，如何裝扮也影響著你的行為。每當李智善感受到因展示出完美的時裝的那份愉悅，或別人因穿著她的衣服而感到高興時，她就確切感受到自己在做重要的事。 「『讓人感受到美好』是我對孩子唯一的要求，我認為這是人生中最寶貴的特質。」我在家中的大廳放了一件Frank Stella的作品，一件非常獨特而富有動感的作品。它是我每天早晚的力量來源。這不僅給我力量，這份能量也能流通到每個我遇到的人身上。」

						</p>
					</div>
					</div>
					<div class="sws-style-section">
						<div class="sws-style-sticky">
						<img src="/media/html/resource/img/experience/sulwhasoo_style/15284372978372.jpg" alt="Designer Lee Ji Sun">
						</div>
						<div class="sws-style-desc">
						<!--<p class="q"></p>

						<p class="p"></p>-->

						<blockquote class="blockquote">
						  <p class="quote break-word">接收美好以創造美好</p>
						</blockquote>

						<p class="q">李智善不僅從Frank Stella的畫中獲得正能量， 她還有其他力量泉源。 她相信透過她的工作，在展示新作品的過程中，都在不斷接收美好的事物。</p>
						<p class="p">
						 「我近來常到寧靜的鄉村旅遊。 前陣子我到過慶州和寶城綠茶園。 這是我第一次到寶城，我在入口處站了好一陣子。 極高大的樹木鋪設出道路，沿途整齊排列的綠茶田非常美麗。我吸著清新的空氣，於寧靜的綠茶田中遊走。我從大自然、街道、藝術及其他的一切當中獲得靈感。 而最重要的是，我能與他人分享我內心那高質素的情感。」
						 <br>
						有一個簡單的原因令她能吸收所有正能量：在一邊滿足著大眾需求的同時，一邊流露著品牌的意念。如果只把時裝看成一盤生意而非藝術，很容易就會失去平衡。李智善不斷努力在保持平衡。這就是為什麼。Apostrophe系列，如像高大又健康的樹木般，於有利的環境中茁莊成長。在努力平衡後取得了成果，李智善向全世界展示出童裝「Little Stella」系列。這是另一個在滿足客戶需求的同時，又能表達出她自己意念的成果。「隨著我女兒泰熙的成長，我有著一些與客戶一樣的需求。我一直覺得為她購買衣服是人件困難的事，高素質的兒童服裝實在太昂貴，而那些為人熟悉、擁有廣泛尺寸的SPA品牌，質量往往又不是太好。我在想如果能為成長中的孩子們提供價格實惠、漂亮而又高質量的服裝那就好了。我和那些有機會成為我顧客的媽媽們交談，他們都有著相同的想法。我立即採取了行動，並以我女兒的名字推出了一個名為 『Little Stella』的兒童品牌，這品牌蘊含著『明亮星宿』的意思。我很高興這個系列能獲得認同。」
						<br>
						「Little Stella」 在推出一年後迅速發展。它在無論線上和線下平台都廣受好評，並且不斷擴展。她的女兒泰熙就是「Little Stella」的第一個也是最好的顧客，她亦是李智善最好的支持者。儘管泰熙不能常常和媽媽在一起，但她很明白事理。看到女兒能健康快樂地成長，完全沒有責怪她這個繁忙的媽媽，這令李智善感到很欣慰。她女兒積極的個性也為她帶來能量。「我希望保持家庭和工作之間的平衡。我希望我的犧牲和愛，能為我身邊的人帶來更多的啟迪和愛。我想成為一名能把生活反映在服裝上的設計師，將美好的生活化作禮物，送給穿著我作品的人。」
						<br>
						你剛開啟了一扇叫李智善的門，在那裡透射出耀眼的光芒。我們可以自由、毫無阻礙地進入她的世界，她內在的世界，一個由對美善事物具洞察力的人所創造的世界。她不斷傾注積極的能量，創造出新的作品。當你走出那扇門時，你自己也不其然成了一扇門，流通著正能量。我們可能要更頻繁地打開李智善這扇門，讓生活變得更好。

						</p>
						</div>
					</div>

				</div>

			</div>
		</div>
	</article>
    
    
	<div class="l-wrap">
        <div class="experience-list">
            <div class="blind">Sulwhasoo style list</div>
            <ul>
                
                <li class="experience-item">
                    <a href="/hk/zh/experience/sulwhasoo_style/cho-sang-kyung.html" class="thumb">
                        <img src="/media/html/experience/sulwhasoo_style/__icsFiles/afieldfile/2019/02/07/15421034050921.jpg" alt="服裝指導  Cho Sang Kyung">
                        <div class="cover">
                            <span class="title">服裝指導</span>
                            <b class="name">Cho Sang Kyung</b>
                        </div>
                    </a>
                </li>
                
                <li class="experience-item">
                    <a href="/hk/zh/experience/sulwhasoo_style/goh-sang-ji.html" class="thumb">
                        <img src="/media/html/experience/sulwhasoo_style/__icsFiles/afieldfile/2019/02/07/15385496872242.jpg" alt="音樂家  Goh Sang Ji">
                        <div class="cover">
                            <span class="title">音樂家</span>
                            <b class="name">Goh Sang Ji</b>
                        </div>
                    </a>
                </li>
                
                <li class="experience-item">
                    <a href="/hk/zh/experience/sulwhasoo_style/kim-yoona.html" class="thumb">
                        <img src="/media/html/experience/sulwhasoo_style/__icsFiles/afieldfile/2019/02/07/1534905539124.jpg" alt="歌手  金潤雅">
                        <div class="cover">
                            <span class="title">歌手</span>
                            <b class="name">金潤雅</b>
                        </div>
                    </a>
                </li>
                
                <li class="experience-item">
                    <a href="/hk/zh/experience/sulwhasoo_style/lee-ji-sun.html" class="thumb">
                        <img src="/media/html/experience/sulwhasoo_style/__icsFiles/afieldfile/2019/02/07/1528437138195.jpg" alt="設計師  李智善">
                        <div class="cover">
                            <span class="title">設計師</span>
                            <b class="name">李智善</b>
                        </div>
                    </a>
                </li>
                
            </ul>
        </div>
    </div>
</section>

<script>
	require([
	'jquery',
	], function ($) {
	    $(".sws-style-sticky").each(function (u, v) {
	    	console.log("sdkh");
	        var t = $(v),
	            s = t.parent();
	        $(window).on("scroll", function () {
	        	console.log(t.css("position"));
                if (t.css("position") !== "absolute") {
                    return;
                }
                console.log("ajs");
                t.css("top", n(t, s));
            }).scroll();
	        $(window).on("resize", function () {
	            var w = n(t, s);
	            if (t.css("position") !== "absolute") {
	                return;
	            }
	            t.css("top", w);
	        });
	        $('body').on("mousewheel", function () {
	            var x = event.wheelDelta / 8;
	            var w = window.pageYOffset;
	            window.scrollTo(0, w - x);
	        });
	    });
	    function n(w, v) {
	        var x = 0,
	            t = w.outerHeight(),
	            s = v.offset().top,
	            u = v.outerHeight();
	        if ($(window).scrollTop() > s) {
	            x = $(window).scrollTop() - s;
	            if (u - t + s < $(window).scrollTop()) {
	                x = u - t;
	            }
	        } else {
	            x = 0;
	        }
	        return x;
	    }
	});
</script>