<?php
/**
 * Created by Eguana Team.
 * User: sonia
 * Date: 7/15/20
 * Time: 9:34 AM
 */

/** @var \Eguana\CustomerRefund\Block\Adminhtml\Sales\Order\View\Tab\BankInfo $block */
?>
<section class="admin__page-section edit-order-bankinfo">
    <div class="edit-order-bankinfo-block-title">
        <?= $block->escapeHtml(__('Customer Bank Information for this Orders')) ?>
    </div>
    <ul class="bankinfo-list">
        <?php /** @var \Eguana\CustomerRefund\Api\Data\BankInfoDataInterface $_item */
        foreach ($block->getBankInformations() as $_item) : ?>
            <li class="bankinfo-list-item">
                <span class="bankinfo-list-created-at"><?= /* @noEscape */ $block->escapeHtml($_item->getCreatedAt()) ?></span>
                <span class="bankinfo-list-created-at"> | </span>
                <span class="bankinfo-list-bankname"><?= /* @noEscape */ $block->escapeHtml($_item->getBankName()) ?></span>
                <span class="bankinfo-list-account-owner-name"><?= /* @noEscape */ $block->escapeHtml($_item->getBankAccountNumber()) ?></span>
                <span class="bankinfo-list-account-name"><?= /* @noEscape */ $block->escapeHtml($_item->getBankAccountNumber()) ?></span>
            </li>
        <?php endforeach; ?>
    </ul>
</section>

