<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Sales\Block\Order\Info */ ?>
<div class="order-id">
    <strong><?= $block->escapeHtml(__('Order #')) ?></strong>
    <?= $block->escapeHtml($block->getOrder()->getRealOrderId()) ?>
    <div class="order-status"><?= $block->escapeHtml($block->getOrder()->getStatusLabel()) ?></div>
</div>
