<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var \Magento\Sales\Block\Order\History $block */
?>
<div class="block block-orders-history">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Order Details')) ?></strong></div>
    <div class="order-info">
        <?= $block->getChildHtml('order.status') ?>
        <?= $block->getChildHtml('order.date') ?>
        <?= $block->getChildHtml('order.actions.container') ?>
    </div>
</div>
