<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php
$_product = $block->getProduct();
?>
<?php if ($block->hasOptions()) : ?>
    <div id="bundleSummary"
         class="block-bundle-summary"
         data-mage-init='{"sticky":{"container": ".product-add-form"}}'>
        <div class="content">
            <div class="visual-aids-container">
                <div class="visual-aids">
                    <div class="visual-aids-header-container">
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M21 16V8C20.9996 7.64928 20.9071 7.30481 20.7315 7.00116C20.556 6.69752 20.3037 6.44536 20 6.27L13 2.27C12.696 2.09446 12.3511 2.00205 12 2.00205C11.6489 2.00205 11.304 2.09446 11 2.27L4 6.27C3.69626 6.44536 3.44398 6.69752 3.26846 7.00116C3.09294 7.30481 3.00036 7.64928 3 8V16C3.00036 16.3507 3.09294 16.6952 3.26846 16.9988C3.44398 17.3025 3.69626 17.5546 4 17.73L11 21.73C11.304 21.9055 11.6489 21.998 12 21.998C12.3511 21.998 12.696 21.9055 13 21.73L20 17.73C20.3037 17.5546 20.556 17.3025 20.7315 16.9988C20.9071 16.6952 20.9996 16.3507 21 16Z" stroke="#888888" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                            <path d="M3.26999 6.96L12 12.01L20.73 6.96" stroke="#888888" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                            <path d="M12 22.08V12" stroke="#888888" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                        </svg>
                        <div class="visual-aids-header" data-role="trigger">
                            <span><?= $block->escapeHtml(__('Related Bundle Set Option')) ?></span>
                        </div>
                    </div>
                    <div class="visual-aids-content">
                        <?= $block->getChildHtml('bundle.product.options.wrapper', true) ?>
                        <div class="bundle-summary">
                            <div id="bundle-summary" data-container="product-summary">
                                <ul data-mage-init='{"productSummary": []}' class="bundle items"></ul>
                                <script data-template="bundle-summary" type="text/x-magento-template">
                                    <li>
                                        <div data-container="options"></div>
                                    </li>
                                </script>
                                <script data-template="bundle-option" type="text/x-magento-template">
                                    <div><?= /* @noEscape */ __('%2 x %1', '<%- data._quantity_ %>', '<%- data._label_ %>') ?></div>
                                </script>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <?= $block->getChildHtml('visualaids', true) ?>
            <?php
            $block->unsetChild('visualaids');
            $block->unsetChild('bundle.product.options.wrapper');
            ?>
            <div class="bundle-info">
                <div class="product-details">
                    <?= $block->getChildHtml('', true) ?>
                </div>
            </div>
        </div>
    </div>
    <script type="text/x-magento-init">
    {
        ".product-add-form": {
            "slide": {
                "slideSpeed": 1500,
                "slideSelector": "#bundle-slide",
                "slideBackSelector": ".action.customization.back",
                "bundleProductSelector": "#bundleProduct",
                "bundleOptionsContainer": ".product-add-form"
                <?php if ($block->isStartCustomization()) : ?>
                ,"autostart": true
                <?php endif;?>
            }
        }
    }
</script>
<?php endif; ?>
