<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
/** @var $helper \Eguana\Share\Helper\Data */
$helper = $this->helper('Eguana\EcommerceStatus\Helper\Data');
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<div class="box-tocart">
    <?php if ($_product->isSaleable()) :?>
    <div class="fieldset">
        <div class="product attributes">
            <?= $block->getChildHtml('product.info.prdvl', true) ?>
            <?= $block->getChildHtml('product.info.vlunt', true) ?>
            <?= $block->getChildHtml('product.info.product.count', true) ?>
        </div>
        <?php if ($block->shouldRenderQuantity() && !$_product->getData('offline')) :?>
        <div class="field qty">
            <div class="control">
                <button onclick="var qty_el = document.getElementById('qty'); var qty = qty_el.value; if( !isNaN( qty ) &amp;&amp; qty > 1 ) qty_el.value--; return false;" class="qty-decrease qty-selector" >
                    <span class="icon"><?= /* @escapeNotVerified */ __('collapse') ?></span>
                </button>
                <input type="number"
                       name="qty"
                       id="qty"
                       min="0"
                       value="<?= $block->getProductDefaultQty() * 1 ?>"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty"
                       readonly
                       data-validate="<?= $block->escapeHtmlAttr(json_encode($block->getQuantityValidators())) ?>"
                       />
                <button onclick="var qty_el = document.getElementById('qty'); var qty = qty_el.value; if( !isNaN( qty )) qty_el.value++;return false;" class="qty-increase qty-selector">
                    <span class="icon"><?= /* @escapeNotVerified */ __('expand') ?></span>
                </button>
            </div>
        </div>
        <?php endif; ?>
        <?= $block->getChildHtml('product.info.price', true) ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action tocart"
                    id="product-addtocart-button">
                <span><?php /* @escapeNotVerified */ echo __('Add to Cart'); ?></span>
            </button>
            <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary tocheckout"
                    id="product-addtocheckout-button" onclick="return setCheckoutURL()">
                <span><?php /* @escapeNotVerified */ echo __('Go to shopping cart'); ?></span>
            </button>
        </div>
    </div>
    <?php else :?>
        <div class="product attributes">
            <?= $block->getChildHtml('product.info.prdvl', true) ?>
            <?= $block->getChildHtml('product.info.vlunt', true) ?>
            <?= $block->getChildHtml('product.info.product.count', true) ?>
        </div>
        <?= $block->getChildHtml('product.info.price', true) ?>
        <?php if($helper->getECommerceStatus()) :?>
            <div class="actions">
                <?php if($_product->getData('offline')):?>
                    <a href="<?= $block->escapeUrl($block->getUrl()) ?>"
                       title="<?= $block->escapeHtml(__('Find a store')) ?>"
                       class="action action-offline">
                        <span><?= $block->escapeHtml(__('Find a store')) ?></span>
                    </a>
                <?php else :?>
                    <button type="submit"
                            title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                            class="action tocart disabled"
                            id="product-addtocart-button" disabled>
                        <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                    </button>
                <?php endif; ?>
            </div>
        <?php endif; ?>
    <?php endif; ?>
</div>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
        }
    }
</script>
<?php endif; ?>
<script type="text/javascript">
    function setCheckoutURL()
    {
        document.product_addtocart_form.return_url.value = '<?php echo $this->getUrl('checkout/cart');?>';
        return true;
    }
</script>
