<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
    $_helper = $this->helper(Magento\Catalog\Helper\Output::class);
    $_product = $block->getProduct();
?>
<?php if ($_additional = $block->getAdditionalData()) :?>
    <div class="additional-attributes-wrapper">
        <div class="additional-attribute">
            <?php foreach ($_additional as $_data) :?>
                <div class="attribute-title" data-mage-init='{"toggleAdvanced": {"toggleContainers": "#attribute-content-<?= /* @noEscape */ $_data['code']?>", "selectorsToggleClass": "active"}}'><span><?= $block->escapeHtml($_data['label']) ?></span></div>
                <div id="attribute-content-<?= /* @noEscape */ $_data['code']?>" class="attribute-content"><?= /* @noEscape */ $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif;?>
