stage:
    global:
        SCD_MATRIX:
            "AmorePacific/backend":
                language:
                    - en_US
                    - zh_Hant_TW
                    - vi_VN
            "Magento/backend": []
            "Magento/blank": []
            "Magento/luma": []
            "AmorePacific/laneige":
                language:
                    - zh_Hant_TW
                    - vi_VN
                    - en_US
            "AmorePacific/sulwhasoo":
                language:
                    - zh_Hant_TW
                    - en_US
                    - vi_VN
            "Laneige/vn":
                language:
                    - vi_VN
            "Laneige/my":
                language:
                    - en_US
    deploy:
        REDIS_BACKEND: '\Magento\Framework\Cache\Backend\RemoteSynchronizedCache'
        CONSUMERS_WAIT_FOR_MAX_MESSAGES: true
        CRON_CONSUMERS_RUNNER:
            cron_run: true
            max_messages: 1000
            consumers:
                - async.operations.all
                - sales.rule.update.coupon.usage


