# Default value: false                                                                                                #
# Stages: deploy                                                                                                      #
# Example:                                                                                                            #
#          stage:                                                                                                     #
#            deploy:                                                                                                  #
#              CONSUMERS_WAIT_FOR_MAX_MESSAGES: true

# Example:                                                                                                            #
#          stage:                                                                                                     #
#            deploy:                                                                                                  #
#              CRON_CONSUMERS_RUNNER:                                                                                 #
#                cron_run: true                                                                                       #
#                max_messages: 1000                                                                                   #
#                consumers:                                                                                           #
#                  - consumer1                                                                                        #
#                  - consumer2                                                                                        #



stage:
    global:
        SCD_MATRIX:
            "Magento/backend":
                language:
                    - en_US
                    - zh_Hant_TW
            "Magento/blank": []
            "Magento/luma": []
            "AmorePacific/laneige":
                language:
                    - zh_Hant_TW
            "AmorePacific/sulwhasoo":
                language:
                    - zh_Hant_TW

    deploy:
        CONSUMERS_WAIT_FOR_MAX_MESSAGES: true
        CRON_CONSUMERS_RUNNER:
            cron_run: true
            max_messages: 1000
            consumers:
                - async.operations.all

