stage:
    global:
        SCD_MATRIX:
            "AmorePacific/backend":
                language:
                    - en_US
                    - zh_Hant_TW
                    - vi_VN
            "Magento/backend": []
            "Magento/blank": []
            "Magento/luma": []
            "AmorePacific/laneige":
                language:
                    - zh_Hant_TW
                    - vi_VN
            "AmorePacific/sulwhasoo":
                language:
                    - zh_Hant_TW
                    - en_US
                    - vi_VN
            "Laneige/vn":
                language:
                    - vi_VN

    deploy:
        CONSUMERS_WAIT_FOR_MAX_MESSAGES: true
        CRON_CONSUMERS_RUNNER:
            cron_run: true
            max_messages: 1000
            consumers:
                - async.operations.all



