stage:
    global:
      SCD_MATRIX:
        "AmorePacific/backend": [ ]
        "Magento/backend": [ ]
        "Magento/blank": [ ]
        "Magento/luma": [ ]
        "AmorePacific/laneige": [ ]
        "AmorePacific/sulwhasoo": [ ]
        "Laneige/vn": [ ]
        "Laneige/my": [ ]
      SKIP_HTML_MINIFICATION: true
    build:
        SCD_MAX_EXECUTION_TIME: 7200
        SKIP_SCD: false
        SCD_STRATEGY: "compact"
        QUALITY_PATCHES:
            - ACSD-47920
            - MDVA-12304
    deploy:
        REDIS_BACKEND: '\Magento\Framework\Cache\Backend\RemoteSynchronizedCache'
        CONSUMERS_WAIT_FOR_MAX_MESSAGES: true
        CRON_CONSUMERS_RUNNER:
            cron_run: true
            max_messages: 10000
            consumers:
                - async.operations.all
                - sales.rule.update.coupon.usage
                - product_action_attribute.update
                - product_action_attribute.website.update
            multiple_processes:
              'async.operations.all': 4


