<?php
/**
 * Created by Eguana Team.
 * User: sonia
 * Date: 9/4/20
 * Time: 3:53 PM
 */

/** @var \Amore\GaTagging\Block\GaTagging $block */
$canceledOrderData = $block->getCanceledOrderData();
?>
<?php if ($canceledOrderData) : ?>
<script>
    //주문취소
    var AP_REFUND_PRICE = "<?= $block->escapeHtml($canceledOrderData['AP_REFUND_PRICE'])?>";
    var AP_REFUND_ORDERNUM = "<?= $block->escapeHtml($canceledOrderData['AP_REFUND_ORDERNUM'])?>";
    var AP_REFUND_CONTENT = "<?= $block->escapeHtml($canceledOrderData['AP_REFUND_CONTENT'])?>";
    var AP_REFUND_PRDS = [
        <?php foreach($canceledOrderData['AP_REFUND_PRDS'] as $prod) : ?>
        <?= $prod ?>,
        <?php endforeach; ?>
    ];
</script>

<script type="text/x-magento-init">
    {
        "*": {
            "Amore_GaTagging/js/action/notify":{
                "eventName": "<?= /* @noEscape */$block->getEventName() ?>"
            }
        }
    }
</script>
<?php endif; ?>
