<?php
/** @var \Sapt\Customer\Block\Widget\BeautyProfile $block */
$values = $block->getFormValue();
?>
<fieldset class="fieldset beauty-profile">
    <div class="fields">
        <label class="label"><?= $block->getStoreLabel($block->getAttributeCode()) ?></label>
        <span><?= __('Please select an beauty profile based on your skin concern.') ?></span>
        <div class="control">
            <?php $options = $block->getOptions(); ?>
            <?php foreach ($options as $option) : ?>
                <?php if (!empty($option->getValue())): ?>
                    <div class="field field-beauty-profile">
                        <div class="control">
                            <input type="checkbox"
                                   id="<?= $block->escapeHtmlAttr($block->getFieldName($block->getAttributeCode())) . '_' . $option->getValue() ?>"
                                   name="<?= $block->escapeHtmlAttr($block->getFieldName($block->getAttributeCode())) ?>[]"
                                   value="<?= $block->escapeHtmlAttr($option->getValue()) ?>"
                                <?= (in_array($option->getValue(), $values)) ? ' checked="checked"' : '' ?>/>
                        </div>
                        <label class="label" for="<?= $block->escapeHtmlAttr($block->getFieldName($block->getAttributeCode())) . '_' . $option->getValue() ?>">
                            <?= $block->escapeHtml(__($option->getLabel())) ?>
                        </label>
                    </div>
                <?php endif; ?>
            <?php endforeach;?>
        </div>
    </div>
</fieldset>
