<?php
/**
 * Created by Eguana Team.
 * User: sonia
 * Date: 7/5/20
 * Time: 8:08 AM
 */

/** @var \Eguana\CustomerRefund\ViewModel\Refund $refundOnlineViewModel */
/** @var \Magento\Framework\View\Element\Template $block */
$refundOnlineViewModel = $block->getRefundOnlineViewModel();
/** @var \Magento\Sales\Model\Order $_order */
$_order = $block->getOrder();
?>
<?php if ($refundOnlineViewModel->canShowRefundOnlineButton($_order)): ?>
    <a href="#" class="action refund-online" data-role="refund-online-button"
       data-mage-init='{"Eguana_CustomerRefund/js/view/refund-confirmation": {"orderId": "<?= (int)$_order->getId() ?>"}}'>
        <!-- Changed by Mobeen on 29/07/2020 as per ticket APT-134  -->
        <span><?= $block->escapeHtml(__('Order cancel and refund')) ?></span>
    </a>
<?php endif;?>
