<!--<title>Sulwhasoo Brand Belief - Beauty From Culture | Sulwhasoo Hong Kong</title>-->
<!--<meta name="description" content="Sulwhasoo - BRAND BELIEF - BEAUTY FROM CULTURE - 2020 BEAUTY FROM CULTURE Reboot Me限量版 | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="og:title" content="Sulwhasoo Brand Belief - Beauty From Culture | Sulwhasoo Hong Kong">-->
<!--<meta property="og:description" content="Sulwhasoo - BRAND BELIEF - BEAUTY FROM CULTURE - 2020 BEAUTY FROM CULTURE Reboot Me限量版 | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="twitter:title" content="Sulwhasoo Brand Belief - Beauty From Culture | Sulwhasoo Hong Kong">-->
<!--<meta property="twitter:description" content="Sulwhasoo - BRAND BELIEF - BEAUTY FROM CULTURE - 2020 BEAUTY FROM CULTURE Reboot Me限量版 | Sulwhasoo Hong Kong 中國香港">-->

<div class="sulwhainside wrap-beauty-from-culture">
    <h1 class="txt-hidden">BEAUTY FROM CULTURE 2020</h1>
    <div class="wrap-bfc-container">
        <div class="wrap-bfc-kv aos-init" data-aos="fade-up" data-aos-delay="200">
            <img src="/media/html/resource/img/about/beauty_from_culture/20210623_Sulwhasoo_Beauty_From_Culture_pc_kv.jpg" alt="CSR 컬렉션 제품" class="display-pc">
            <img src="/media/html/resource/img/about/beauty_from_culture/20210623_Sulwhasoo_Beauty_From_Culture_mo_kv.jpg" alt="CSR 컬렉션 제품" class="display-mo">
        </div>
        <div class="inner-bfc-container">
            <section class="wrap-bfc-contents align-center">
                <h2 class="bfc-title-h2 aos-init" data-aos="fade-up" data-aos-delay="250">BEAUTY FROM CULTURE</h2>
                <p class="bfc-txt-box display-pc aos-init" data-aos="fade-up" data-aos-delay="300">
                    <span>為履行社會責任，雪花秀十多年來一直堅持資助藝術文化活動。 </span>
                    <span>2017年起，更將活動拓展至全世界。雪花秀相信，傳統與現代文化 </span>
                    <span>共存，能創造更大價值，這就是雪花秀Beauty From Culture的起源。</span>
                </p>
                <p class="bfc-txt-box display-mo aos-init" data-aos="fade-up" data-aos-delay="200">
                    <span>為履行社會責任，</span>
                    <span>雪花秀十多年來一直堅持資助藝術文化活動。  </span>
                    <span>2017年起，更將活動拓展至全世界。 </span>
                    <span>雪花秀相信，傳統與現代文化 </span>
                    <span>共存，能創造更大價值， </span>
                    <span>這就是雪花秀Beauty From Culture的起源。</span>
                </p>
            </section>
            <section class="wrap-bfc-contents align-center">
                <p class="bfc-txt-box display-pc aos-init" data-aos="fade-up" data-aos-delay="600">
                    <span>雪花秀將會把BEAUTY FROM CULTURE限量版銷售收益的一部分， </span>
                    <span>捐獻用於保存、傳承世界文化遺產。</span>
                </p>
                <p class="bfc-txt-box display-mo aos-init" data-aos="fade-up" data-aos-delay="600">
                    <span>雪花秀將會把BEAUTY FROM CULTURE </span>
                    <span>限量版銷售收益的一部分，</span>
                    <span>捐獻用於保存、傳承世界文化遺產。</span>
                </p>
            </section>
            <section class="wrap-bfc-vdo">
                <div class="inner-bfc-vdo">
                    <div class="vdo-bfc aos-init" data-aos="fade-up" data-aos-delay="400">
                        <a href="https://youtu.be/lT7ZHWI5CyM" role="button" ap-click-area="Brand" ap-click-name="Click - Video" ap-click-data="Beauty from Culture 2020" data-role-video="youtube">
                            <h3 class="hidden">BEAUTY FROM CULTURE 유튜브 영상 재생</h3>
                        </a>
                        <div class="vdo" style="display: none;">
                            <iframe id="beauty-from-culture" src="https://www.youtube.com/embed/lT7ZHWI5CyM?showinfo=0&amp;color=white&amp;theme=dark&amp;enablejsapi=1&amp;rel=0&amp;playsinline=1" allow="autoplay; encrypted-media" allowfullscreen="" title="BEAUTY FROM CULTURE 유튜브 영상" class="video-iframe"></iframe>
                        </div>
                    </div>
                </div>
            </section>
            <section class="wrap-bfc-contents align-center">
                <h2 class="bfc-title-h2 aos-init" data-aos="fade-up"><span style="font-family: 'Theinhardt';">2020</span> BEAUTY FROM CULTURE<br>Reboot Me<span style="font-weight: 600;">限量版</span></h2>
            </section>
            <section class="wrap-bfc-contents align-left">
                <figure data-aos="fade-up" class="aos-init">
                    <img src="/media/html/resource/img/about/beauty_from_culture/20210507_img_01_pc.jpg" alt="" class="display-pc">
                    <img src="/media/html/resource/img/about/beauty_from_culture/20210507_img_01_mo.jpg" alt="" class="display-mo">
                </figure>
                <h3 class="bfc-title-h3 aos-init" data-aos="fade-up">參與作家： <br class="display-mo">拼貼藝術家Saki(權恩真)</h3>
                <p class="bfc-txt-box display-pc aos-init" data-aos="fade-up" data-aos-delay="200">
                    <span>雪花秀與年度藝術家Saki攜手打造出潤燥再生精華BEAUTY FROM CULTURE限量版！</span>
                    <span>並將繼續發掘新銳藝術家，讓他們以創新多樣的視角，詮釋韓國文化。</span>
                </p>
                <p class="bfc-txt-box display-mo aos-init" data-aos="fade-up" data-aos-delay="200">
                    <span>雪花秀與年度藝術家Saki攜手打造出潤燥再生精華BEAUTY FROM CULTURE限量版！</span>
                    <span>並將繼續發掘新銳藝術家，讓他們以創新多樣的視角，詮釋韓國文化。</span>
                </p>
            </section>
            <section class="wrap-bfc-contents align-left">
                <figure data-aos="fade-up" data-aos-delay="200" class="aos-init">
                    <img src="/media/html/resource/img/about/beauty_from_culture/20210507_img_03_pc.jpg" alt="" class="display-pc">
                    <img src="/media/html/resource/img/about/beauty_from_culture/20210507_img_03_mo.jpg" alt="" class="display-mo">
                </figure>
            </section>
            <div class="inner-bfc-contents">
                <section class="wrap-bfc-contents align-left">
                    <div class="img-set display-pc">
                        <figure data-aos="fade-up" class="aos-init"><img src="/media/html/resource/img/about/beauty_from_culture/20210507_img_04_pc.jpg" alt=""></figure>
                        <figure data-aos="fade-up" data-aos-delay="200" class="aos-init"><img src="/media/html/resource/img/about/beauty_from_culture/20210507_img_05_pc.jpg" alt=""></figure>
                        <figure data-aos="fade-up" class="aos-init"><img src="/media/html/resource/img/about/beauty_from_culture/20210507_img_06.gif" alt=""></figure>
                    </div>
                    <div class="img-set display-mo">
                        <figure data-aos="fade-up" class="aos-init"><img src="/media/html/resource/img/about/beauty_from_culture/20210507_img_04_mo.jpg" alt=""></figure>
                        <figure data-aos="fade-up" data-aos-delay="200" class="aos-init"><img src="/media/html/resource/img/about/beauty_from_culture/20210507_img_05_mo.jpg" alt=""></figure>
                        <figure data-aos="fade-up" class="aos-init"><img src="/media/html/resource/img/about/beauty_from_culture/20210507_img_06.gif" alt=""></figure>
                    </div>
                    <h3 class="bfc-title-h3 aos-init" data-aos="fade-up">REBOOT ME</h3>
                    <p class="bfc-txt-box display-pc aos-init" data-aos="fade-up" data-aos-delay="200">
                            <span>Saki繪製的貼紙，風格色彩自由奔放又極富感性，呈現韓國的傳統裝飾藝術丹青與雪花秀的象徵，讓客人利用這些貼紙打造自己專屬的潤燥再生精華，為自己注入青春活力。
                            </span>
                    </p>
                    <p class="bfc-txt-box display-mo aos-init" data-aos="fade-up" data-aos-delay="200">
                            <span>Saki繪製的貼紙，風格色彩自由奔放又極富感性，呈現韓國的傳統裝飾藝術丹青與雪花秀的象徵，讓客人利用這些貼紙打造自己專屬的潤燥再生精華，為自己注入青春活力。
                            </span>
                    </p>
                </section>
                <section class="wrap-bfc-contents global-map align-left">
                    <h3 class="bfc-title-h3 aos-init" data-aos="fade-up">全球文化推廣 </h3>
                    <p class="bfc-txt-box display-pc aos-init" data-aos="fade-up" data-aos-delay="200">
                        <span>雪花秀希望把美麗的傳統文化代代傳承，讓人與文化、傳統與現代和諧共存，打造出更有價值的文化。除了韓國總公司投入此活動外，中國、新加坡、馬來西亞、泰國、印尼等子公司皆共襄盛舉。</span>
                        <span>韓國總公司會將部分銷售收益用於修復即將失傳或難以傳承的非等物質文化遺產。</span>
                    </p>
                    <p class="bfc-txt-box display-mo aos-init" data-aos="fade-up" data-aos-delay="200">
                            <span>雪花秀希望把美麗的傳統文化代代傳承，讓人與文化、傳統與現代和諧共存，打造出更有價值的文化。除了韓國總公司投入此活動外，中國、新加坡、馬來西亞、泰國、印尼等子公司皆共襄盛舉。韓國總公司會將部分銷售收益用於修復即將失傳或難以傳承的非等物質文化遺產。
                            </span>
                    </p>
                </section>
                <section class="wrap-bfc-contents bfc-history">
                    <h2 class="bfc-title-h2 aos-init" data-aos="fade-up">Collection History</h2>
                    <div class="inner-bfc-history">
                        <div class="cicle active" style="top: 333px;"></div>
                        <ul>
                            <li data-aos="fade-up" class="active aos-init" style="z-index: 4;">
                                <div class="wrap-history-list">
                                    <figure>
                                        <img src="/media/html/resource/img/about/beauty_from_culture/20210507_history_img_2020.jpg" alt="BEAUTY FROM CULTURE 리미티드_Reboot Me 에디션">
                                    </figure>
                                    <div class="history-txt-box">
                                        <strong>2020</strong>
                                        <p>BEAUTY FROM CULTURE<br> Limited_Reboot Me Edition</p>
                                    </div>
                                </div>
                            </li>
                            <li data-aos="fade-up" data-aos-delay="600" class="aos-init" style="z-index: 3;">
                                <div class="wrap-history-list">
                                    <figure>
                                        <img src="/media/html/resource/img/about/beauty_from_culture/20210507_history_img_2019.jpg" alt="BEAUTY FROM YOUR CULTURE 리미티드_실란컬렉션">
                                    </figure>
                                    <div class="history-txt-box">
                                        <strong>2019</strong>
                                        <p>BEAUTY FROM YOUR CULTURE<br> Limited_Shine Classic Collection</p>
                                    </div>
                                </div>
                            </li>
                            <li data-aos="fade-up" data-aos-delay="600" class="aos-init" style="z-index: 2;">
                                <div class="wrap-history-list">
                                    <figure>
                                        <img src="/media/html/resource/img/about/beauty_from_culture/20210507_history_img_2018.jpg" alt="BEAUTY FROM YOUR CULTURE 리미티드_금박에디션">
                                    </figure>
                                    <div class="history-txt-box">
                                        <strong>2018</strong>
                                        <p>BEAUTY FROM YOUR CULTURE<br> Limited_Gold Leaf Edition</p>
                                    </div>
                                </div>
                            </li>
                            <li data-aos="fade-up" data-aos-delay="800" class="aos-init" style="z-index: 1;">
                                <div class="wrap-history-list">
                                    <figure>
                                        <img src="/media/html/resource/img/about/beauty_from_culture/20210507_history_img_2017.jpg" alt="BEAUTY FROM YOUR CULTURE 리미티드_설화, 나무꾼과 선녀 에디션">
                                    </figure>
                                    <div class="history-txt-box">
                                        <strong>2017</strong>
                                        <p>BEAUTY FROM YOUR CULTURE<br> Limited_Once Upon a Time: <br>A Fairy and A Woodcutter <br class="display-mo"> Edition</p>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </section>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    require([
        'jquery',
        'js/plugins/aos/aos'
    ], function ($,AOS) {

        /**
         * Youtube iFrame API
         * @type {HTMLScriptElement}
         */
        var tag = document.createElement("script");
        tag.src = "https://www.youtube.com/iframe_api";
        var firstScriptTag = document.getElementsByTagName('script')[0];
        firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
        var player;
        window.onYouTubeIframeAPIReady = function() {
            var i = 0;
            var youtubeId = $(".vdo iframe").attr('id');
            player = new YT.Player(youtubeId, {
                events: {
                    'onReady': onPlayerReady,
                    'onStateChange': onPlayerStateChange
                }
            });
        };
        function onPlayerReady(event){};
        function onPlayerStateChange(event){};

        $(function(){
            var youtubeBtn = $('[data-role-video="youtube"]');
            var youtubeDiv = $('.vdo');
            youtubeBtn.on('click', function(e) {
                e.preventDefault();
                player.playVideo();
                youtubeBtn.css('display', 'none');
                youtubeDiv.css('display', 'block');
            });
        });

        function BeautyFromCultureCommFunc() {
            var _$this = this,
                isMobile = false,
                filter = "win16|win32|win64|mac",
                history = document.querySelectorAll('.inner-bfc-history ul li'),
                historyList = $('.wrap-history-list'),
                historyWrapTop,
                historyImg = $('.wrap-history-list figure'),
                historyYear = $('.history-txt-box strong'),
                historyDot = $('.cicle'),
                historyDotTop = {},
                historyYearOffset = {},
                windowHeight,
                activeYear;

            // library event
            _$this.library = {
                init: function() {
                    _$this.library.aos();
                },
                // aos
                aos: function() {
                    AOS.init({
                        duration: 1000,
                        // mirror: true,
                    });
                }
            };
            _$this.history = {
                init: function() {
                    var index = history.length + 1;
                    $('.inner-bfc-history ul li').each(function(idx, element) {
                        index = index - 1;
                        this.style.zIndex = index;
                        if ($(this).hasClass('active')) activeYear = idx;
                    });
                },
                resposive: function() {
                    historyWrapTop = $('.inner-bfc-history ul').offset().top;
                    // history year text offsetTop
                    historyYear.each(function(idx) {
                        historyYearOffset[idx] = $(this).offset().top;
                    });
                    // history dot offsetTop
                    historyList.each(function(idx) {
                        if (!$(this).closest('.aos-init').hasClass('aos-animate')) {
                            historyDotTop[idx] = $(this).offset().top - 100 - historyWrapTop + $('.wrap-history-list figure').innerHeight() + ($('.history-txt-box strong').innerHeight() / 2) - ($('.cicle').innerHeight() / 2);
                        } else {
                            historyDotTop[idx] = $(this).offset().top - historyWrapTop + $('.wrap-history-list figure').innerHeight() + ($('.history-txt-box strong').innerHeight() / 2) - ($('.cicle').innerHeight() / 2);
                        }
                    });

                    // window height size
                    windowHeight = $(window).innerHeight();
                },
                yearActive: function(i) {
                    historyDot.addClass('active');
                    historyDot.css({top : historyDotTop[i] + 'px'})
                },
                scrollAction: function() {
                    $('.inner-bfc-history ul li').each(function(idx, element) {
                        if (idx === activeYear && $(this).hasClass('aos-animate')) {
                            _$this.history.yearActive(activeYear);
                        } else if (!$(this).hasClass('aos-animate')) {
                            historyDot.removeClass('active');
                            historyDot.css({top : 0 + 'px'});
                        };
                    });
                },
            };

            return {
                init: function() {

                    if (navigator.platform) isMobile = filter.indexOf(navigator.platform.toLowerCase()) < 0;
                    if (isMobile) $('body').addClass('mobile');
                    _$this.library.init();
                    _$this.history.init();
                    _$this.history.resposive();
                },
                resposive: function() {
                    _$this.history.resposive();
                },
                scrollAction: function() {
                    _$this.history.scrollAction();
                }
            };
        };

        var beautyFromCultureCommFunc = new BeautyFromCultureCommFunc();

        $(document).ready(function () {
            beautyFromCultureCommFunc.init();
        });

        $(window).on('load',function () {
            beautyFromCultureCommFunc.resposive();
        });
        $(document).scroll(function () {
            beautyFromCultureCommFunc.scrollAction();
        });

        $(window).resize(function () {
            beautyFromCultureCommFunc.resposive();
            beautyFromCultureCommFunc.scrollAction();
        });

    });

</script>
