<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use CJ\Catalog\Setup\Patch\Data\AddProductDateLaunchAttribute;

/** @var $block \Magento\Catalog\Block\Product\View*/
$product = $block->getProduct();
?>
<?php if (!($product->getData('offline')) && !$product->getData(AddProductDateLaunchAttribute::PROMOTION_TEXT)) : ?>
    <div class="product-addto-links" data-role="add-to-links">
        <?= $block->getChildHtml() ?>
    </div>
<?php endif; ?>
