<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @var \Magento\CompanyPayment\Block\Company\Profile\PaymentMethod $block
 * @codingStandardsIgnoreFile
 */
?>

<div class="block block-company-profile-payment-methods">
    <div class="block-title">
        <strong><?= $block->escapeHtml(__('Payment Information')) ?></strong>
    </div>
    <div class="block-content">
        <?php
        if ($block->hasPaymentMethods()): ?>
            <div class="box company-profile-payment-methods">
                <strong class="box-title payment-methods-label">
                    <span><?= $block->escapeHtml(__('Available Payment Methods')) ?></span>
                </strong>
                <div class="box-content"><p>
    <?php
    foreach ($block->getPaymentMethods() as $paymentMethod):
        ?><?= $block->escapeHtml($paymentMethod) ?><br /><?php
    endforeach; ?>
             </p></div>
            </div>
        <?php
        else: ?>
            <div class="message message-notice notice">
                <div data-ui-id="messages-message-notice">
                <?= $block->escapeHtml(__('This company has no payment methods. Please contact store administrator.')) ?>
                </div>
            </div>
        <?php
        endif; ?>
    </div>
</div>
