<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Image $block */

/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>
<a class="product-item-photo" tabindex="-1" href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>" title="<?= $block->escapeHtmlAttr($product->getName()) ?>">
    <span class="flags">
        <?php if($product->getData('new')):?>
            <span class="flag new"><?= $product->getResource()->getAttribute('new')->getStoreLabel();?></span>
        <?php endif;?>
        <?php if($product->getData('best')):?>
            <span class="flag best"><?= $product->getResource()->getAttribute('best')->getStoreLabel(); ?></span>
        <?php endif;?>
    </span>
    <?= $block->getImage($block->getProductForThumbnail($item), 'wishlist_thumbnail')->toHtml() ?>
</a>
