<?php
/** @var \Sapt\Sales\Block\Order\SearchHistory $block */
$from = $block->getRequest()->getParam('from', false);
$to = $block->getRequest()->getParam('to', false);
?>

<div class="order-toolbar">
    <ul class="monthly-list">
        <li><button class="monthly" data-number="-1"><?= __('%1 month', 1) ?></button></li>
        <li><button class="monthly" data-number="-3"><?= __('%1 month', 3) ?></button></li>
        <li><button class="monthly" data-number="-6"><?= __('%1 month', 6) ?></button></li>
        <li class="hd-mobile"><button class="monthly" data-number="-9"><?= __('%1 month', 9) ?></button></li>
        <li><button class="monthly" data-number="-12"><?= __('%1 month', 12) ?></button></li>
    </ul>
    <form action="<?= $block->getUrl('rma/returns/history') ?>" method="GET">
        <div id="date-range">
            <input class="input-text required-entry"
                   type="text"
                   id="date-from"
                   name="from" />
            <span>~</span>
            <input class="input-text required-entry"
                   type="text"
                   id="date-to"
                   name="to" />
        </div>
        <button type="submit" class="btn primary"><?= __('Search') ?></button>
    </form>
</div>
<script>
    require([
        'jquery',
        'mage/translate',
        'mage/calendar'
    ], function ($, $t) {
        $('#date-range').dateRange({
            changeYear: true,
            from: {
                id: 'date-from'
            },
            to: {
                id: 'date-to'
            }
        });
        function dateWithMonthsDelay (months) {
            const date = new Date();
            date.setMonth(date.getMonth() + months);
            return date;
        }
        function setDateInput(months) {
            $('#date-from').datepicker('setDate', dateWithMonthsDelay(months));
            $('#date-to').datepicker('setDate', new Date());
        }
        $('button.monthly').on('click', function() {
            var number = parseInt($(this).attr('data-number'));
            $('button.monthly').removeClass('selected');
            $(this).addClass('selected');
            setDateInput(number);
        });
        <?php if ($from || $to): ?>
            <?php if ($from): ?>
            $('#date-from').datepicker('setDate', new Date('<?= $from ?>'));
            <?php endif; ?>
            <?php if ($to): ?>
            $('#date-to').datepicker('setDate', new Date('<?= $to ?>'));
            <?php endif; ?>
        <?php else: ?>
        $('button[data-number="-1"]').click();
        <?php endif; ?>

    })
</script>
