<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Widget\Gender $block */
?>
<div class="field gender<?= $block->isRequired() ? ' required' : ''?>">
    <label class="label" for="<?= $block->escapeHtmlAttr($block->getFieldId('gender')) ?>"><span><?= $block->escapeHtml($block->getStoreLabel('gender')) ?></span></label>
    <?php $options = $block->getGenderOptions(); ?>
    <?php $value = $block->getGender(); ?>
    <?php foreach ($options as $option) : ?>
        <?php if (!empty($option->getValue()) && $option->getLabel() != 'Not Specified') : ?>
            <input type="radio"
                   id="<?= $block->escapeHtmlAttr($block->getFieldId('gender').'_'.$option->getLabel()) ?>"
                   value="<?= $block->escapeHtmlAttr($option->getValue()) ?>"
                   title="<?= $block->escapeHtmlAttr($option->getLabel()) ?>"
                   name="<?= $block->escapeHtmlAttr($block->getFieldName('gender')) ?>"
                   class="radio<?php if ($block->isRequired()) : ?> validate-radio<?php endif; ?>"
                   <?php if ($block->isRequired()) : ?>data-validate="{required:true}"<?php endif; ?>
                   <?= ($option->getValue() == $value || ($option->getLabel() == 'Male' && empty($value))) ? ' checked="checked"' : '' ?>>
            <label class="label" for="<?= $block->escapeHtmlAttr($option->getValue()) ?>"><span><?= $block->escapeHtml(__($option->getLabel())) ?></span></label>
        <?php endif; ?>
    <?php endforeach;?>
</div>
