<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php if ($bottomContent = $block->getCurrentCategory()->getBlockBottomContent()):?>
    <div class="category-bottom">
        <?php $bottomContentHtml = $this->helper(Magento\Catalog\Helper\Output::class)->categoryAttribute(
            $block->getCurrentCategory(),
            $bottomContent,
            'block_bottom_content'
        );?>
        <?php if (stripos($bottomContent, 'data-appearance') === false):?>
            <div data-content-type="row" data-appearance="contained" data-element="main">
                <div data-enable-parallax="0" data-parallax-speed="0.5" data-background-images="{}" data-element="inner"
                     style="justify-content: flex-start; display: flex; flex-direction: column;
                     background-position: left top; background-size: cover; background-repeat: no-repeat;
                     background-attachment: scroll; border-style: none; border-width: 1px; border-radius: 0px;
                     margin: 0px 0px 10px; padding: 10px;">
                    <div data-content-type="html" data-appearance="default" data-element="main"
                         style="border-style: none; border-width: 1px; border-radius: 0px; margin: 0px; padding: 0px;">
                        <?= /* @noEscape */$bottomContentHtml; ?>
                    </div>
                </div>
            </div>
        <?php else: ?>
            <?= /* @noEscape */$bottomContentHtml; ?>
        <?php endif; ?>
    </div>
    <script type="text/x-magento-init">
    {
        "*": {
            "CJ_CatalogProduct/js/category/bottom":{
            }
        }
    }
    </script>
<?php endif; ?>
