<meta property="og:type" content="website" />
<meta property="og:title"
      content="<?= /* @noEscape */ $block->stripTags($block->getMetaTitle()) ?>" />
<meta property="og:image"
      content="<?= /* @noEscape  */ $block->escapeUrl($block->getImageViewUrl($block->getImage())) ?>" />
<meta property="og:description"
      content="<?= /* @noEscape */ $block->stripTags($block->getDescription()) ?>" />
<meta property="og:url" content="<?= $block->escapeUrl($block->getCurrentUrl()) ?>" />
