<meta name="twitter:card" content="summary_large_image" />
<meta property="twitter:title"
      content="<?= /* @noEscape */ $block->stripTags($block->getMetaTitle()) ?>" />
<meta property="twitter:image"
      content="<?= /* @noEscape  */ $block->escapeUrl($block->getImageViewUrl($block->getImage())) ?>" />
<meta property="twitter:description"
      content="<?= /* @noEscape */ $block->stripTags($block->getDescription()) ?>" />
<meta property="twitter:url" content="<?= $block->escapeUrl($block->getCurrentUrl()) ?>" />
