<!--<title>Cho Sang Kyung - 雪花秀風格 Sulwhasoo Style | 雪花秀</title>-->
<!--<meta name="description" content="雪花秀風格 Sulwhasoo Style 專訪 服裝指導 Cho Sang Kyung 面試詳情 | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="og:title" content="Cho Sang Kyung - 雪花秀風格 Sulwhasoo Style | 雪花秀">-->
<!--<meta property="og:description" content="雪花秀風格 Sulwhasoo Style 專訪 服裝指導 Cho Sang Kyung 面試詳情 | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="twitter:title" content="Cho Sang Kyung - 雪花秀風格 Sulwhasoo Style | 雪花秀">-->
<!--<meta property="twitter:description" content="雪花秀風格 Sulwhasoo Style 專訪 服裝指導 Cho Sang Kyung 面試詳情 | Sulwhasoo Hong Kong 中國香港">-->

<section class="content">
    <div class="blind">Sulwhasoo Style</div>

	<article class="sws-style">
		<div class="l-wrap l-full">
			<div class="basic style_basic">
				<div class="sws-style-visual">
					<h1 class="h1"><span class="title">服裝指導</span> <b class="name">Cho Sang Kyung</b></h1>
					<img src="/media/html/resource/img/experience/sulwhasoo_style/1542103405092.jpg" class="only-desktop" alt="">
					<img src="/media/html/resource/img/experience/sulwhasoo_style/1542103405092m.jpg" class="only-mobile" alt="">
				</div>
			</div>

		</div>

		<div class="l-wrap">
			<div class="sws-style-body">
				<div class="content static parbase">
					<style>
					.sws-style .q.style_1 {margin:2em 0 1.8em;}
					</style>
					<div class="sws-style-section">
						<blockquote class="blockquote">
						    <p class="quote break-word">見證韓國電影崛起</p>
						</blockquote>
						<div class="sws-style-sticky">
						    <img src="/media/html/resource/img/experience/sulwhasoo_style/15421036426901.jpg" alt="Costume director Cho Sang Kyung">
						</div>
						<div class="sws-style-desc">
						    <p class="q">2002年，她為導演柳承完執導的電影擔任服裝指導，正式投身電影圈。
						</p>
						    <p class="p">
						        她此後一直努力工作，曾為80齣電影擔任服裝指導，包括多齣即將上映的矚目新作。她的作品亦可見於多套韓劇，包括不久前收視報捷的《Mr.Sunshine》，亦因戲服精美而引起話題。《Mr.Sunshine》是電視台的重頭戲，但劇集的拍攝模式令她不能預先製作服裝，所以她當時幾乎將整副心思放到這套劇集的服裝上。話雖如此，她手頭上平均有八部作品在拍攝中。<br>
						服裝指導超常景原先專攻舞台服裝，由《無血無淚》起加入電影界。工作性質沒太大分別，但服裝設計在當時的電影圈算不上是一門專業。她在大學讀過服裝相關課程，但她表示不敢說自己修讀過電影服裝設計。<br>「我很幸運，初次涉足電影服裝設計時，剛好是加入電影圈的好時機。2000年代初，韓國電影業充滿活力，不斷有新嘗試，行業仍未擴展，可以嘗試各種各樣的東西。我以前不太了解韓國電影界，只是從外國電影取經，再製作自己想做的服裝。我在過去16年來不間斷地工作，才建立起今時今日的履歷。」
						<br><br>

						    </p>
						</div>
					</div>

					<div class="sws-style-section">
						<div class="sws-style-sticky">
						    <img src="/media/html/resource/img/experience/sulwhasoo_style/15421036426902.jpg" alt="Costume director Cho Sang Kyung">
						</div>
						<div class="sws-style-desc">
						    <!--<p class="q"></p>

						    <p class="p"></p>-->

						    <blockquote class="blockquote">
						        <p class="quote break-word">個人與團隊</p>
						    </blockquote>

						    <p class="q">雖然她形容自己是「幸運兒」，遇上的都是好人，「只是盡自己本分」，其實她對工作十分嚴謹。</p>
						    <p class="p">
						        為歷史劇製作服裝時，她為了盡可能符合文獻而花時間親自進行資料搜集。<br>
						「即使在日本帝國統治下，不同時代都有不同的服裝風格。《Modern Boy》背景設於1920至1930年代，《Mr. Sunshine》的故事則在日本殖民統治前的朝鮮展開。歷史情感和氣氛每隔一、兩年便改變，需以截然不同的手法處理。有需要時，我甚至會看論文及翻查編年史。」
						<br>
						因此超常景設計的服裝極費工夫。她甚至為了重現大韓帝國的服裝，而研究現代用不上的圖案。
						<br>
						「服裝設計極花時間和心力。Gom Gom Studio約有30位員工，有些在我麾下工作已逾十年，有些則是新人。」<br>
						她期望將Gom Gom Studio塑造成一個工會，部分為Gom Gom效力的員工亦同時經營自己的業務。他們共同處理超常景受託的設計項目，或者與Gom Gom Studio合作進行個人項目。<br>
						超常景主理的Gom Gom Studio透過找出現有問題，更新工作指引，尋求共存的方法。她本人亦積極改善工作模式和環境。<br>
						「拍攝用的服裝只是畫面上好看的『假衣服』，關鍵是你騙過觀眾雙眼的手法有多高明。服裝絕對稱不上實用，所以我們盡可能將騙到人的部分做得像真點。譬如說，我的工作室用紙張製作所有盔甲，然後上色令它們看起來像皮革。用中國產塑膠比較簡單，但紙張更易循環再用。用其他物料亦做到相同效果，但較堅固的物料較容易循環再用。我們盡量用天然物料，即使你要將服裝燒毀，燃燒天然物料跟燃燒尼龍亦不同。雖然成本更高，但我認為這才是對的。」<br>
						當旁人問到她有何計劃，她回道︰「沒有計劃。」她認為每個人應該跟隨自己的生活方式，早已明白人生沒什麼事情能夠一如預期。她的人生專注於活在「當下」。超常景的「當下」創造出以昨天與明天、現實與虛構交織的服裝。正因為人人都活在「當下」，令她的作品更特別，帶出更宏大的願景。

						    </p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</article>

	<div class="l-wrap">
        <div class="experience-list">
            <div class="blind">Sulwhasoo style list</div>
            <ul>

                <li class="experience-item">
                    <a href="/hk/zh/experience/sulwhasoo_style/cho-sang-kyung.html" class="thumb">
                        <img src="/media/html/experience/sulwhasoo_style/__icsFiles/afieldfile/2019/02/07/15421034050921.jpg" alt="服裝指導  Cho Sang Kyung">
                        <div class="cover">
                            <span class="title">服裝指導</span>
                            <b class="name">Cho Sang Kyung</b>
                        </div>
                    </a>
                </li>

                <li class="experience-item">
                    <a href="/hk/zh/experience/sulwhasoo_style/goh-sang-ji.html" class="thumb">
                        <img src="/media/html/experience/sulwhasoo_style/__icsFiles/afieldfile/2019/02/07/15385496872242.jpg" alt="音樂家  Goh Sang Ji">
                        <div class="cover">
                            <span class="title">音樂家</span>
                            <b class="name">Goh Sang Ji</b>
                        </div>
                    </a>
                </li>

                <li class="experience-item">
                    <a href="/hk/zh/experience/sulwhasoo_style/kim-yoona.html" class="thumb">
                        <img src="/media/html/experience/sulwhasoo_style/__icsFiles/afieldfile/2019/02/07/1534905539124.jpg" alt="歌手  金潤雅">
                        <div class="cover">
                            <span class="title">歌手</span>
                            <b class="name">金潤雅</b>
                        </div>
                    </a>
                </li>

                <li class="experience-item">
                    <a href="/hk/zh/experience/sulwhasoo_style/lee-ji-sun.html" class="thumb">
                        <img src="/media/html/experience/sulwhasoo_style/__icsFiles/afieldfile/2019/02/07/1528437138195.jpg" alt="設計師  李智善">
                        <div class="cover">
                            <span class="title">設計師</span>
                            <b class="name">李智善</b>
                        </div>
                    </a>
                </li>

            </ul>
        </div>
    </div>
</section>

<script>
	require([
	'jquery',
	], function ($) {
	    $(".sws-style-sticky").each(function (u, v) {
	    	console.log("sdkh");
	        var t = $(v),
	            s = t.parent();
	        $(window).on("scroll", function () {
	        	console.log(t.css("position"));
                if (t.css("position") !== "absolute") {
                    return;
                }
                console.log("ajs");
                t.css("top", n(t, s));
            }).scroll();
	        $(window).on("resize", function () {
	            var w = n(t, s);
	            if (t.css("position") !== "absolute") {
	                return;
	            }
	            t.css("top", w);
	        });
	        $('body').on("mousewheel", function () {
	            var x = event.wheelDelta / 8;
	            var w = window.pageYOffset;
	            window.scrollTo(0, w - x);
	        });
	    });
	    function n(w, v) {
	        var x = 0,
	            t = w.outerHeight(),
	            s = v.offset().top,
	            u = v.outerHeight();
	        if ($(window).scrollTop() > s) {
	            x = $(window).scrollTop() - s;
	            if (u - t + s < $(window).scrollTop()) {
	                x = u - t;
	            }
	        } else {
	            x = 0;
	        }
	        return x;
	    }
	});
</script>
