<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\NegotiableQuote\Block\Quote\Totals
 */
?>
<div class="quote-block-content catalog-price">
    <div class="quote-block-title">
        <?= $block->escapeHtml(__('Catalog Price')) ?>
    </div>
    <table class="items data table quote-table-totals">
        <tfoot>
        <?php foreach ($block->getTotals() as $code => $total): ?>
            <?php if ($total->getBlockName()): ?>
                <?= $block->getChildHtml($total->getBlockName(), false) ?>
            <?php endif; ?>
        <?php endforeach?>
        </tfoot>
    </table>
</div>
