<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Amore\CustomerRegistration\ViewModel\POS $viewModel */
$viewModel = $block->getData('view_model');
?>
<form class="form create account form-create-account-pos" method="post" id="form-pos" enctype="multipart/form-data" autocomplete="off">
    <fieldset class="fieldset pos">
        <legend class="legend"><span><?= $block->escapeHtml(__('POS Information')) ?></span></legend><br>
        <div class="terms">
            <?=
               $block->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId($viewModel->getTermsCmsBlockId())
                ->toHtml();
            ?>
        </div>
        <div class="field name required">
            <label for="name" class="label"><span><?= /* @noEscape */ $block->escapeHtml(__('Name')) ?></span></label>
            <div class="control">
                <?php //phpcs:disable ?>
                <input type="text" name="name" value="" title="<?= /* @noEscape */ $block->escapeHtml(__('Name')) ?>" class="input-text" id="name">
                <?php //phpcs:enable ?>
            </div>
        </div>
        <div class="field mobile required">
            <label for="mobile_number" class="label"><span><?= /* @noEscape */ 'telephone' ?></span></label>
            <div class="control">
                <?php //phpcs:disable ?>
                <input type="text" name="mobile_number" value="" title="<?= /* @noEscape */ $block->escapeHtml(__('Telephone')) ?>" class="input-text mobile_number" id="mobile_number">
                <a class="action primary sms-link">
                    <span><?= $block->escapeHtml(__('Get Code')) ?></span>
                </a>
                <?php //phpcs:enable ?>
            </div>
        </div>
        <div class="field verification-code required">
            <label for="code" class="label"><span><?= /* @noEscape */ 'code' ?></span></label>
            <div class="control">
                <?php //phpcs:disable ?>
                <input type="text" name="code" value="" title="<?= /* @noEscape */ $block->escapeHtml(__('Input 4 digit verification code')) ?>" class="input-text code" id="code">
                <a class="action primary verify-link">
                    <span><?= $block->escapeHtml(__('Verify')) ?></span>
                </a>
                <?php //phpcs:enable ?>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" title="<?= $block->escapeHtmlAttr(__('Registration Verification')) ?>"><span><?= $block->escapeHtml(__('Registration Verification')) ?></span></button>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "*": {
            "posform":{
                "AjaxUrl": "<?php echo 'url'; ?>"
            }
        }
    }
</script>