<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Form\Register $block */

/** @var \Amore\CustomerRegistration\ViewModel\Register $viewModel */
$viewModel = $block->getData('view_model');
?>
<!-- This div is added by Abbas so in first step to hide all the content of registration and secnodly in case of disable module from admin panel to not effect the css -->
<div class="customer-registration-form-create-account">
    <?= $block->getChildHtml('form_fields_before') ?>
    <?php /* Extensions placeholder */ ?>
    <?= $block->getChildHtml('customer.form.register.extra') ?>
    <form class="form create account form-create-account" action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off">
        <?= /* @noEscape */ $block->getBlockHtml('formkey'); ?>
        <div class="pos-alert" style="display: none;">
            <?=
            $block->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId($viewModel->getPosAlertCmsBlockId())
                ->toHtml();
            ?>
        </div>
        <fieldset class="fieldset create info">
            <input type="hidden" name="success_url" value="<?= $block->escapeUrl($block->getSuccessUrl()) ?>">
            <input type="hidden" name="error_url" value="<?= $block->escapeUrl($block->getErrorUrl()) ?>">
            <?= $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Name::class)->setObject($block->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>

            <?php $_taxvat = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Taxvat::class) ?>
            <?php if ($_taxvat->isEnabled()) : ?>
                <?= $_taxvat->setTaxvat($block->getFormData()->getTaxvat())->toHtml() ?>
            <?php endif ?>
        </fieldset>
        <?php if ($block->getShowAddressFields()) : ?>
            <fieldset class="fieldset address">
                <legend class="legend"><span><?= $block->escapeHtml(__('Address Information')) ?></span></legend><br>
                <input type="hidden" name="create_address" value="1" />

                <?php $_company = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Company::class) ?>
                <?php if ($_company->isEnabled()) : ?>
                    <?= $_company->setCompany($block->getFormData()->getCompany())->toHtml() ?>
                <?php endif ?>

                <?php $_telephone = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Telephone::class) ?>
                <?php if ($_telephone->isEnabled()) : ?>
                    <?= $_telephone->setTelephone($block->getFormData()->getTelephone())->toHtml() ?>
                <?php endif ?>

                <?php $_fax = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Fax::class) ?>
                <?php if ($_fax->isEnabled()) : ?>
                    <?= $_fax->setFax($block->getFormData()->getFax())->toHtml() ?>
                <?php endif ?>
                <?php //phpcs:disable ?>
                <?php $_streetValidationClass = $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('street'); ?>
                <?php //phpcs:enable ?>
                <div class="field street required">
                    <label for="street_1" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?></span></label>
                    <div class="control">
                        <input type="text" name="street[]" value="<?= $block->escapeHtmlAttr($block->getFormData()->getStreet(0)) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?>" id="street_1" class="input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>">
                        <div class="nested">
                            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                            <?php //phpcs:disable ?>
                            <?php for ($_i = 2, $_n = $this->helper(\Magento\Customer\Helper\Address::class)->getStreetLines(); $_i <= $_n; $_i++) : ?>
                            <?php //phpcs:enable ?>
                                <div class="field additional">
                                    <label class="label" for="street_<?= /* @noEscape */ $_i ?>">
                                        <span><?= $block->escapeHtml(__('Address')) ?></span>
                                    </label>
                                    <div class="control">
                                        <input type="text" name="street[]" value="<?= $block->escapeHtmlAttr($block->getFormData()->getStreetLine($_i - 1)) ?>" title="<?= $block->escapeHtmlAttr(__('Street Address %1', $_i)) ?>" id="street_<?= /* @noEscape */ $_i ?>" class="input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>">
                                    </div>
                                </div>
                            <?php endfor; ?>
                        </div>
                    </div>
                </div>

                <div class="field required">
                    <label for="city" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?></span></label>
                    <div class="control">
                        <?php //phpcs:disable ?>
                        <input type="text" name="city" value="<?= $block->escapeHtmlAttr($block->getFormData()->getCity()) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?>" class="input-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('city')) ?>" id="city">
                        <?php //phpcs:enable ?>
                    </div>
                </div>

                <div class="field region required">
                    <label for="region_id" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?></span></label>
                    <div class="control">
                        <select id="region_id" name="region_id" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>" class="validate-select region_id" style="display:none;">
                            <option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
                        </select>
                        <?php //phpcs:disable ?>
                        <input type="text" id="region" name="region" value="<?= $block->escapeHtmlAttr($block->getRegion()) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>" class="input-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('region')) ?>" style="display:none;">
                        <?php //phpcs:enable ?>
                    </div>
                </div>

                <div class="field zip required">
                    <label for="zip" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?></span></label>
                    <div class="control">
                        <?php //phpcs:disable ?>
                        <input type="text" name="postcode" value="<?= $block->escapeHtmlAttr($block->getFormData()->getPostcode()) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>" id="zip" class="input-text validate-zip-international <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('postcode')) ?>">
                        <?php //phpcs:enable ?>
                    </div>
                </div>

                <div class="field country required">
                    <label for="country" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('country_id') ?></span></label>
                    <div class="control">
                        <?= $block->getCountryHtmlSelect() ?>
                    </div>
                </div>
                <?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes');?>
                <?php if ($addressAttributes) : ?>
                    <?php $addressAttributes->setEntityType('customer_address'); ?>
                    <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]');?>
                    <?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address');?>
                    <?= $addressAttributes->setShowContainer(false)->toHtml() ?>
                <?php endif;?>
                <input type="hidden" name="default_billing" value="1">
                <input type="hidden" name="default_shipping" value="1">
            </fieldset>

        <?php endif; ?>
        <fieldset class="fieldset create account" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
            <div class="field required">
                <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                <div class="control">
                    <input placeholder="<?= $block->escapeHtml(__('Email')) ?>" type="email" name="email" autocomplete="email" id="email_address" value="<?= $block->escapeHtmlAttr($viewModel->getSocialMediaEmail()?$viewModel->getSocialMediaEmail():$block->getFormData()->getEmail()) ?>" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" class="input-text" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
                </div>
            </div>
            <div class="field password required">
                <label for="password" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                <div class="control">
                    <input type="password" name="password" id="password"
                           placeholder="<?= $block->escapeHtmlAttr(__('Password')) ?>"
                           title="<?= $block->escapeHtmlAttr(__('Password')) ?>"
                           class="input-text"
                           data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                           data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                           data-validate="{required:true, 'validate-customer-password':true}"
                           autocomplete="off">
                    <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                        <div id="password-strength-meter" class="password-strength-meter">
                            <?= $block->escapeHtml(__('Password Strength')) ?>:
                            <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                                <?= $block->escapeHtml(__('No Password')) ?>
                            </span>
                        </div>
                        <div class="password-strength-meter-status">
                            <span class="password-weak"></span>
                            <span class="password-medium"></span>
                            <span class="password-strong"></span>
                            <span class="password-very-strong"></span>
                        </div>
                    </div>
                </div>

            </div>
            <div class="field confirmation required">
                <label for="password-confirmation" class="label"><span><?= $block->escapeHtml(__('Confirm Password')) ?></span></label>
                <div class="control">
                    <input placeholder="<?= $block->escapeHtml(__('Confirm Password')) ?>" type="password" name="password_confirmation" title="<?= $block->escapeHtmlAttr(__('Confirm Password')) ?>" id="password-confirmation" class="input-text" data-validate="{required:true, equalTo:'#password'}" autocomplete="off">
                </div>
            </div>
            <?= $block->getChildHtml('form_additional_info') ?>
        </fieldset>
        <fieldset class="fieldset extra-info">

            <?php $_mobile = $block->getLayout()->createBlock(\Amore\CustomerRegistration\Block\Widget\TextField::class, 'mobile_number', ['data'=>['attribute_code'=>'mobile_number', 'read_only' => 1, 'form_value'=> $block->escapeHtmlAttr($block->getFormData()->getMobileNumber())]]) ?>
            <?php if ($_mobile->isEnabled()) : ?>
                <?= $_mobile->setDate($block->getFormData()->getMobileNumber())->toHtml() ?>
            <?php endif ?>

            <?php $_dob = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Dob::class) ?>
            <?php if ($_dob->isEnabled()) : ?>
                <?= $_dob->setDate($block->getFormData()->getDob())->toHtml() ?>
            <?php endif ?>

            <?php $_gender = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Gender::class) ?>
            <?php if ($_gender->isEnabled()) : ?>
                <?= $_gender->setGender($block->getFormData()->getGender())->toHtml() ?>
            <?php endif ?>

            <?php $_smsSubscriptionStatus = $block->getLayout()->createBlock(\Amore\CustomerRegistration\Block\Widget\CheckBox::class, 'sms_subscription_status', ['data'=>['attribute_code'=>'sms_subscription_status', 'form_value'=> $block->escapeHtmlAttr($block->getFormData()->getSmsSubscriptionStatus())]]) ?>
            <?php $_dmSubscriptionStatus = $block->getLayout()->createBlock(\Amore\CustomerRegistration\Block\Widget\CheckBox::class, 'dm_subscription_status', ['data'=>['attribute_code'=>'dm_subscription_status', 'form_value'=> $block->escapeHtmlAttr($block->getFormData()->getDmSubscriptionStatus())]]) ?>
            <?php $_termsAndServicesPolicy = $block->getLayout()->createBlock(\Amore\CustomerRegistration\Block\Widget\CheckBox::class, 'terms_and_services_policy', ['data'=>['attribute_code'=>'terms_and_services_policy', 'form_value'=> $block->escapeHtmlAttr($block->getFormData()->getTermsAndServicesPolicy())]]) ?>
            <?php $callSubscriptionStatus = $block->getLayout()->createBlock(\Amore\CustomerRegistration\Block\Widget\CheckBox::class, 'call_subscription_status', ['data'=>['attribute_code'=>'call_subscription_status', 'form_value'=> $block->escapeHtmlAttr($block->getFormData()->getCallSubscriptionStatus())]]) ?>

            <?php if ($_smsSubscriptionStatus->isEnabled() || $_dmSubscriptionStatus->isEnabled()) : ?>
                <p class="marketing-title"><?= $block->escapeHtml(__('Marketing Consent')) ?></p>
            <?php endif ?>

            <?php if ($_termsAndServicesPolicy->isEnabled()) : ?>
                <?= $_termsAndServicesPolicy->setDate($block->getFormData()->getTermsAndServicesPolicy())->toHtml() ?>
            <?php endif ?>

            <?php if ($callSubscriptionStatus->isEnabled()) : ?>
                <?= $callSubscriptionStatus->setDate($block->getFormData()->getCallSubscriptionStatus())->toHtml() ?>
            <?php endif ?>

            <?php if ($_smsSubscriptionStatus->isEnabled()) : ?>
                <?= $_smsSubscriptionStatus->setDate($block->getFormData()->getSmsSubscriptionStatus())->toHtml() ?>
            <?php endif ?>

            <?php if ($block->isNewsletterEnabled()) : ?>
                <div class="field choice newsletter">
                    <input type="checkbox" name="is_subscribed" title="<?= $block->escapeHtmlAttr(__('Sign Up for Newsletter')) ?>" value="1" id="is_subscribed"<?php if ($block->getFormData()->getIsSubscribed()) : ?> checked="checked"<?php endif; ?> class="checkbox">
                    <label for="is_subscribed" class="label news-letter-policy-label"><span><?= $block->escapeHtml(__('Sign Up for Newsletter')) ?></span></label>
                    <span>
                        <a href="#" id="is_subscribed-read-policy" target="_blank"><?= $block->escapeHtml(__('Read more')) ?></a>
                    </span>
                </div>
                <div class="news-letter-policy-popup" style="display: none;">
                    <?= /* @noEscape */
                    $block->getLayout()
                        ->createBlock('Magento\Cms\Block\Block')
                        ->setBlockId($viewModel->getNewsLetterPolicyCMSBlockId())
                        ->toHtml(); ?>
                </div>
                <?php /* Extensions placeholder */ ?>
                <?= $block->getChildHtml('customer.form.register.newsletter') ?>
            <?php endif ?>

            <?php if ($_dmSubscriptionStatus->isEnabled()) : ?>
                <?= $_dmSubscriptionStatus->setDate($block->getFormData()->getDmSubscriptionStatus())->toHtml() ?>
            <?php endif ?>

            <div class="field required" style="display: none;">
                <input type="hidden" name="integration_number" class="input-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('integration_number')) ?>" id="integration_number">
            </div>

            <div class="fieldset dm-address" style="<?= $block->escapeHtmlAttr($block->getFormData()->getDmSubscriptionStatus()) == 1?'':'display: none'; ?>">
                <div class="field country required">
                    <label for="country" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('country_id') ?></span></label>
                    <div class="control">
                        <?= $block->getCountryHtmlSelect() ?>
                    </div>
                </div>

                <div class="field required">
                    <label for="dm_state" class="label"><span><?= $block->escapeHtml(__('State')) ?></span></label>
                    <div class="control">
                        <?php //phpcs:disable ?>
                        <select id="region_id" name="region_id" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>" class="validate-select region_id">
                            <option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
                        </select>
                        <!--<input type="text" id="dm_state" name="dm_state" placeholder="<?/*= $block->escapeHtml(__('State')) */?>"  value="<?/*= $block->escapeHtmlAttr($block->getFormData()->getDmState()) */?>" title="<?/*= $block->escapeHtml(__('State')) */?>" class="input-text <?/*= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('dm_state')) */?>" >-->
                        <input type="text" id="dm_state" name="dm_state" value="<?= $block->escapeHtmlAttr($block->getRegion()) ?>"  title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>" class="input-text <?= /* @noEscape */ $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('region') ?>"<?= (!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>/>
                        <?php //phpcs:enable ?>
                    </div>
                </div>

                <div class="field required">
                    <label for="dm_city" class="label"><span><?= $block->escapeHtml(__('City')) ?></span></label>
                    <div class="control">
                        <?php //phpcs:disable ?>
                        <select id="city_id" name="city_id" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?>" class="validate-select region_id" <?= (!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>>
                            <option value=""><?= $block->escapeHtml(__('Please select a city, city or district.')) ?></option>
                        </select>
                        <input type="text" placeholder="<?= $block->escapeHtml(__('City')) ?>" name="dm_city" value="<?= $block->escapeHtmlAttr($block->getFormData()->getDmCity()) ?>" title="<?= $block->escapeHtml(__('City')) ?>" class="input-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('dm_city')) ?>" id="dm_city">
                        <?php //phpcs:enable ?>
                    </div>
                </div>

                <div class="field required">
                    <label for="dm_detailed_address" class="label"><span><?= $block->escapeHtml(__('Detailed Address')) ?></span></label>
                    <div class="control">
                        <?php //phpcs:disable ?>
                        <input type="text" placeholder="<?= $block->escapeHtml(__('Detailed Address')) ?>" name="dm_detailed_address" value="<?= $block->escapeHtmlAttr($block->getFormData()->getDmDetailedAddress()) ?>" title="<?= $block->escapeHtml(__('Detailed Address')) ?>" class="input-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('dm_detailed_address')) ?>" id="dm_detailed_address">
                        <?php //phpcs:enable ?>
                    </div>
                </div>

                <div class="field required">
                    <label for="dm_zipcode" class="label"><span><?= $block->escapeHtml(__('Zip Code')) ?></span></label>
                    <div class="control">
                        <?php //phpcs:disable ?>
                        <input type="text" readonly placeholder="<?= $block->escapeHtml(__('Zip Code')) ?>" name="dm_zipcode" value="<?= $block->escapeHtmlAttr($block->getFormData()->getDmZipcode()) ?>" title="<?= $block->escapeHtml(__('Zip Code')) ?>" class="input-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('dm_zipcode')) ?>" id="dm_zipcode">
                        <?php //phpcs:enable ?>
                    </div>
                </div>
            </div>
        </fieldset>
        <div class="store-info" style="display: none">
            <input type="hidden"
                   name="partner_id"
                   id="partner_id"
                   value="<?= $block->escapeHtml($viewModel->getFavoriteStore()) ?>">

            <input type="hidden"
                   name="referrer_code"
                   id="referrer_code"
                   value="<?= $block->escapeHtml($viewModel->getReferrerCode()) ?>">

            <input type="hidden"
                   name="imported_from_pos"
                   id="imported_from_pos"
                   value="0">
        </div>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" id="customerSubmit" class="action submit primary" title="<?= $block->escapeHtmlAttr(__('Create an Account')) ?>"><span><?= $block->escapeHtml(__('Create an Account')) ?></span></button>
            </div>
            <div class="secondary">
                <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>"><span><?= $block->escapeHtml(__('Back')) ?></span></a>
            </div>
        </div>
    </form>
</div>
<script>
require([
    'jquery',
    'mage/mage'
], function($){

    var dataForm = $('#form-validate');
    var ignore = <?= /* @noEscape */ $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null' ?>;

    dataForm.mage('validation', {
    <?php if ($_dob->isEnabled()) : ?>
        errorPlacement: function(error, element) {
            if (element.prop('id').search('full') !== -1) {
                var dobElement = $(element).parents('.customer-dob'),
                    errorClass = error.prop('class');
                error.insertAfter(element.parent());
                dobElement.find('.validate-custom').addClass(errorClass)
                    .after('<div class="' + errorClass + '"></div>');
            }
            else {
                error.insertAfter(element);
            }
        },
        ignore: ':hidden:not(' + ignore + ')'
    <?php else : ?>
        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
    <?php endif ?>
    }).find('input:text').attr('autocomplete', 'off');

});
</script>

<script type="text/x-magento-init">
    {
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ $block->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#dm_state",
                "postcodeId": "#dm_zipcode",
                "form": "#form-validate",
                <?php //phpcs:disable ?>
                "regionJson": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                <?php //phpcs:enable ?>
                "defaultRegion": "<?= (int) $block->getFormData()->getRegionId() ?>",
                <?php //phpcs:disable ?>
                "countriesWithOptionalZip": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
                <?php //phpcs:enable ?>
            }
        },
        "#region_id": {
            "cityUpdater": {
                "optionalCityAllowed": <?= /* @noEscape need to do config*/ ($block->getConfig('general/region/display_all') ? 'true' : 'false') ?>,
                "cityListId": "#city_id",
                "cityInputId": "#dm_city",
                "postcodeId": "#dm_zipcode",
                "form": "#form-validate",
                "cityJson": <?= /* @noEscape */ $this->helper(\Eguana\Directory\Helper\Data::class)->getCityJson() ?>,
                "defaultRegion": "<?= /* @noEscape */ $block->getRegionId() ?>",
                "defaultCity": <?= /* @noEscape */ $this->helper(\Eguana\Directory\Helper\Data::class)->getCityCodeByRegionName((int)$block->getRegionId(), $block->getFormData()->getDmCity()) ?>
            }
        }

    }
</script>


<script type="text/x-magento-init">
    {
        ".field.password": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-create-account"
            }
        },
        "*": {
            "privacypolicypopup":{},
            "createaccount":{}
        }
    }
</script>
