<?php
/**
 * @author Eguana Team
 * @copyriht Copyright (c) 2020 Eguana {http://eguanacommerce.com}
 * Created by PhpStorm
 * User: arslan
 * Date: 16/6/20
 * Time: 05:18 PM
 */

/** @var \Eguana\VideoBoard\Block\View $block */
$videoBlock = $block->getVideoBoard();
$videoBlockList = $block->getCollection();

$url = $block->getUrl();

?>
<div class="block block-video-board-details">
    <div class="block-content">
        <div class="video-board-item">
            <div class="video-board-item-content">
                <p class="video-created-date">
                    <?= $block->escapeHtml($block->formatDate($videoBlock->getCreatedAt()));?>
                </p>
                <div class="video-board-detail">
                    <div class="video-iframe">
                        <iframe
                                allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                                allowfullscreen
                                frameborder="0"
                                src="<?=$block->escapeUrl($videoBlock->getUrl());?>" width="100%">
                        </iframe>
                    </div>
                    <?= /* @noEscape */  $block->contentFiltering($videoBlock->getDescription()); ?>
                </div>
            </div>
        </div>
    </div>
    <div class="back-button">
        <a class="action button primary" href="<?= $block->escapeUrl($block->getBaseUrl().'videoboard')?>">
            <span><?= $block->escapeHtml(__('Back'));?></span>
        </a><br/>
        <span><?= $block->escapeHtml(__('Back'));?></span>
    </div>
</div>

