<?php
/**
 * @author Eguana Team
 * @copyriht Copyright (c) 2020 Eguana {http://eguanacommerce.com}
 * Created by PhpStorm
 * User: arslan
 * Date: 16/6/20
 * Time: 01:20 PM
 */

/** @var \Eguana\VideoBoard\ViewModel\VideoList $viewModel */
$viewModel = $block->getData('list_view_model');
$videoBlockList = $viewModel->getVideoCollection();
$videoBlockSize = $videoBlockList->getTotalCount();
?>
<div class="video-board-list-wrapper">
    <?php if ($videoBlockList->getTotalCount() == 0): ?>
        <div class="video-board-empty">
            <?= $block->escapeHtml(__('No video found!.')); ?>
        </div>
    <?php else: ?>
        <ul class="video-board-list">
        <?php foreach ($videoBlockList as $videoBlockItem):?>
            <li class="video-board-item">
                <a
                    class="video-link"
                    href="<?= $block->escapeUrl($viewModel->getVideoBoardUrl($videoBlockItem->getEntityId()))?>">
                    <img
                        src="<?= $block->escapeHtml($viewModel->
                        getThumbnailImageURL($videoBlockItem->getThumbnailImage()));?>"
                        alt="<?= $block->escapeHtml(__('Thumbnail Image'));?>"/>
                </a>
                <div class="video-heading">
                    <a class="action view video-title"
                       href="<?= $block->escapeUrl($viewModel->getVideoBoardUrl($videoBlockItem->getEntityId())) ?>">
                        <?= $block->escapeHtml($videoBlockItem->getTitle());?>
                    </a>
                    <p class="video-created-date">
                        <?= $block->escapeHtml($block->formatDate($videoBlockItem->getCreatedAt())); ?>
                    </p>
                </div>
            </li>
        <?php endforeach; ?>
        </ul>
    <?php endif; ?>
</div>
<?php if ($videoBlockSize > 6): ?>
<div class="more-item-button">
    <button class="action primary" id="more-button">
        <span><?=$block->escapeHtml(__('More'));?></span>
    </button>
    <br/>
    <span id="video-count">6</span>/<?= $block->escapeHtml($videoBlockSize); ?>
</div>
<?php endif ; ?>
<script type="text/x-magento-init">
    {
        "*": {
            "pagination":{
                "totalVideo":"<?= $block->escapeHtml($videoBlockSize)?>"
            }
        }
    }
</script>
