<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Info $block */

/** @var \Magento\Wishlist\Model\Item $item */

/** @var $getDefault \Eguana\CustomCatalog\ViewModel\GetDefaultCategory */

$item = $block->getItem();
$product = $item->getProduct();
$productSku = $product->getSku();
$getDefault = $block->getData('view_model');
?>
<strong class="product-item-name">
    <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>"
       title="<?= $block->escapeHtmlAttr($product->getName()) ?>"
       class="product-item-link"
       ap-click-area="product"
       ap-click-name="prd click"
       ap-click-data="<?= $getDefault->getProductByDefault($productSku)->getName() . '/' . $productSku ?>">
        <?= $block->escapeHtml($product->getName()) ?>
    </a>
</strong>
