<?php
?>

<span class="description">
    <?= __('The password change process has been sent to your email. Please reset your password and log in with the changed password.') ?>
</span>
<div class="box_link">
    <a class="action secondary" href="<?= $this->getUrl('/') ?>"><?= __('Go to main page') ?></a>
    <a class="action primary" href="<?= $this->getUrl('customer/account/login') ?>"><?= __('Login') ?></a>
</div>
