<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Newsletter\Block\Subscribe $block */
?>
<div class="block newsletter">
    <div class="block_title"><strong><?= $block->escapeHtml(__('訂閱雪花秀香港資訊')) ?></strong></div>
    <div class="content">
        <form class="form subscribe"
              novalidate
              action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
              method="post"
              data-mage-init='{"validation": {"errorClass": "mage-error"}}'
              id="newsletter-validate-detail">
            <div class="field_newsletter">
                <div class="field newsletter">
                    <div class="control">
                        <label for="newsletter">
                        <span class="label">
                            <?= $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?>
                        </span>
                            <input name="email" type="email" id="newsletter"
                                   placeholder="<?= $block->escapeHtml(__('Email address')) ?>"
                                   data-mage-init='{"mage/trim-input":{}}'
                                   data-validate="{required:true, 'validate-email':true}"
                            />
                        </label>
                    </div>
                </div>
                <div class="actions">
                    <button class="action subscribe primary"
                            title="<?= $block->escapeHtmlAttr(__('SUBMIT')) ?>"
                            type="submit"
                            aria-label="Subscribe">
                        <span><?= $block->escapeHtml(__('SUBMIT')) ?></span>
                    </button>
                </div>
            </div>
            <div class="field_check">
                <input type="checkbox" required="true" name="check_subscribe" value="" id="is_subscribed" class="checkbox">
                <label for="is_subscribed"><?= $block->escapeHtml(__('By clicking Submit, I want to receive promotional emails from Laneige and other Amorepacific brands.')) ?></label>
            </div>
        </form>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "newsletter-validate-detail"
            }
        }
    }
</script>
