<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper(\Magento\Search\Helper\Data::class);
?>
<div class="top-search-overlay"></div>
<div class="block block-search" >
    <div class="block block-content" id="top-search">
        <form class="form minisearch" id="search_mini_form" action="<?= $block->escapeUrl($helper->getResultUrl()) ?>" method="get">
            <div class="field search">
                <label class="label" for="search" data-role="minisearch-label">
                    <span><?= $block->escapeHtml(__('Search')) ?></span>
                </label>
                <div class="control">
                    <input id="search"
                           data-mage-init='{"quickSearch":{
                                "formSelector":"#search_mini_form",
                                "url":"<?= $block->escapeUrl($helper->getSuggestUrl()) ?>",
                                "destinationSelector":"#search_autocomplete",
                                "destinationHistory":"#search_wrapper",
                                "searcTermUrl":"<?= $block->getBaseUrl() ?>/searchterms/index/search"
                                }
                           }'
                           type="text"
                           name="<?= $block->escapeHtmlAttr($helper->getQueryParamName()) ?>"
                           value="<?= /* @noEscape */ $helper->getEscapedQueryText() ?>"
                           placeholder="<?= $block->escapeHtmlAttr(__('Enter a search term')) ?>"
                           class="input-text"
                           maxlength="<?= $block->escapeHtmlAttr($helper->getMaxQueryLength()) ?>"
                           role="combobox"
                           aria-haspopup="false"
                           aria-autocomplete="both"
                           autocomplete="off"
                           aria-expanded="false"/>
                    <span class="remove_character" style="display:none;"></span>
                    <div id="search_wrapper">
                        <div id="search_history">
                            <div class="search_history_top">
                                <div class="box_title"><?= $block->escapeHtmlAttr(__('Recent Searches')) ?></div>
                                <a href="#" class="delete_all_search"><?= $block->escapeHtmlAttr(__('Delete All')) ?></a>
                            </div>
                            <ul id="search_history_list"></ul>
                        </div>
                        <div id="search_autocomplete" class="search-autocomplete"></div>
                    </div>
                    <?= $block->getChildHtml() ?>
                </div>
                <div class="actions">
                    <button type="submit"
                            title="<?= $block->escapeHtmlAttr(__('Search')) ?>"
                            class="action search"
                            aria-label="Search"
                    >
                        <span><?= $block->escapeHtml(__('Search')) ?></span>
                    </button>
                </div>
            </div>
            <div class="actions-bottom">
                <button type="button" class="action close" data-role="minisearch-close">
                    <span><?= $block->escapeHtml(__('Close')) ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
<script>
    require([
        'jquery'
    ], function ($) {
        $(document).ready(function(){
            var RecentSearch = (function(){
                function init(){
                    $("#search").change(function() {
                        var val = $(this).val();
                        searchHistory(val);
                    });
                    $(".icon-search-popup").off('click').on('click',function(e){
                        if(!$("html").hasClass("is-open-search")) {
                            $("html").addClass("is-open-search");
                        }
                        else {
                            $("html").removeClass("is-open-search");
                        }
                    });
                    $(".top-search-overlay").off('click').on('click',function(e){
                        $("html").removeClass("is-open-search");
                    });
                    updateSearchHistoryUi();
                    removeSearchHistory();
                    deleteallSearchHistory();
                }

                function searchHistory(searchParam) {
                    const maxHistoryLength = 5;
                    const history = JSON.parse(localStorage.getItem('searchHistory') || '[]');
                    const isHistoryMaxed = history.length === maxHistoryLength;
                    const workingHistory = isHistoryMaxed ? history.slice(1) : history;
                    const updatedHistory = workingHistory.concat(searchParam);
                    localStorage.setItem('searchHistory', JSON.stringify(updatedHistory));
                }

                function updateSearchHistoryUi(){
                    const history = JSON.parse(localStorage.getItem('searchHistory') || '[]');
                    var arr = history instanceof Array ? history : [];
                    if(arr.length > 0) {
                        $('.search_history_top').show();

                        var lihtml = '';
                        var delemiter = '';
                        $.each(history, function(index, _history){
                            if (_history.trim() !== '') {
                                delemiter = (Number(_history.length) >= 13 )? '...': '';
                                lihtml +=  '<li><span class="search_history_item jsRecentTerm" title="'+ _history +'" data-history="' + _history + '">' + _history.substring( 0, 13 ) + delemiter + '</span></li>'
                            }
                        });

                        $('#search_history_list').empty().append(lihtml);
                    } else {
                        $('.search_history_top').hide();
                    }
                }

                function removeSearchHistory(){
                    $('.search_history_item').on('click',function(){
                        $(this).parent().remove();
                        var target = $(this).data('history');
                        const searchs = JSON.parse(localStorage.getItem("searchHistory"));
                        const filtered = searchs.filter(item => item !== target);
                        localStorage.setItem("searchHistory", JSON.stringify(filtered));
                    });
                }

                function deleteallSearchHistory(){
                    $('.delete_all_search').on('click',function(){
                        $('.search_history_item').remove();
                        $('#search_history').hide();
                        localStorage.removeItem('searchHistory');
                    });
                }

                return {
                    init: init
                }
            })();
            RecentSearch.init();
        });

        $('#top-search #search_mini_form .field.search input').keyup(function()
        {
            if( $(this).val() ) {
                $('.remove_character').show()
            }else {
                $('.remove_character').hide()
            }
        });

        $(".remove_character").click(function(){
            $("#top-search #search_mini_form .field.search input").val('');
            $(this).hide()
        });
    });
</script>
