<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\NegotiableQuote\Block\Quote\Totals
 */
?>
<div class="quote-block-content negotiated-price">
    <div class="quote-block-title">
        <?= $block->escapeHtml(__('Negotiated Price')) ?>
    </div>
    <table id="shopping-cart-table-totals" class="items data table quote-table-totals">
        <tfoot>
        <?php foreach ($block->getTotals() as $code => $total): ?>
            <?php if (!$total->getBlockName()): ?>
                <?php $style = ($total->getStyle() ? ' ' . $total->getStyle() : '' ); ?>
                <tr class="<?= $block->escapeHtml($code . $style) ?>">
                    <th <?= $block->escapeHtml($block->getLabelProperties()) ?> scope="row" class="mark">
                        <?php if ($total->getStrong()): ?>
                            <strong><?= $block->escapeHtml($total->getLabel()) ?></strong>
                        <?php else: ?>
                            <?= $block->escapeHtml($total->getLabel()) ?>
                        <?php endif ?>
                    </th>
                    <td <?= $block->escapeHtml($block->getValueProperties()) ?>
                        data-th="<?= $block->escapeHtml($total->getLabel()) ?>"
                        class="amount">
                        <?php $currencyCode = $total->getCurrency()
                            ? $total->getCurrency()
                            : $block->getQuote()->getQuoteCurrencyCode(); ?>
                        <?php if ($total->getStrong()): ?>
                            <strong>
                                <?= /* @noEscape */
                                $block->formatPrice(
                                    $total->getValue(),
                                    $currencyCode
                                ) ?>
                            </strong>
                        <?php else: ?>
                            <?= /* @noEscape */
                            $block->formatPrice(
                                $total->getValue(),
                                $currencyCode
                            ) ?>
                        <?php endif ?>
                    </td>
                </tr>
            <?php endif ?>
        <?php endforeach ?>
        <?= $block->getChildHtml() ?>
        </tfoot>
    </table>
</div>
