<?php
/**
 * @author Eguana Team
 * @copyriht Copyright (c) 2020 Eguana {http://eguanacommerce.com}
 * Created by PhpStorm
 * User: raheel
 * Date: 03/11/20
 * Time: 6:50 PM
 */

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Eguana\EventReservation\ViewModel\Event\Reservation $viewModel */
$viewModel = $block->getData('reservation_view_model');
$counterDates = $viewModel->getCounterDates();
?>

<option value="">-- <?= $block->escapeHtml(__('Select Date')) ?> --</option>
<?php foreach ($counterDates as $date): ?>
    <option value="<?= $block->escapeHtml($date['date']); ?>" <?= $date['disabled'] ? 'disabled="true"' : ''; ?>>
        <?= $block->escapeHtml($date['date']); ?>
    </option>
<?php endforeach; ?>
