<div class="cart-summary">
    <div id="cart-totals" class="cart-totals">
        <div class="table-wrapper">
            <table class="data table totals">
                <caption class="table-caption"><?= __('Total') ?></caption>
                <tbody>
                <tr class="totals sub">
                    <th class="mark" scope="row"><?= __('Subtotal') ?></th>
                    <td class="amount">
                        <span class="price" data-th="Subtotal">0</span>
                    </td>
                </tr>
                <tr class="totals discount">
                    <th class="mark" scope="row"><?= __('Discount') ?></th>
                    <td class="amount">
                        <span class="price" data-th="Subtotal">0</span>
                    </td>
                </tr>
                <tr class="grand totals">
                    <th class="mark" scope="row">
                        <strong><?= __('Total') ?></strong>
                    </th>
                    <td class="amount" data-th="Order Total">
                        <strong><span class="price">0</span></strong>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <ul class="checkout methods items checkout-methods-items">
        <li class="item">
            <button type="button" disabled data-role="proceed-to-checkout" title="Proceed to Checkout" class="action primary checkout">
                <span><?= __('Order') ?></span>
            </button>
        </li>
    </ul>
    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('cart_banner_sidebar')->toHtml(); ?>
</div>
