<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Review\Block\Form $block */
$imageHelper = $this->helper(Magento\Cms\Helper\Wysiwyg\Images::class);
$orderItemId = $block->getOrderItemId();
/** @var \Amasty\AdvancedReview\Helper\Config $advancedReviewHelper */
$advancedReviewHelper = $this->helper(Amasty\AdvancedReview\Helper\Config::class);
?>
<div class="block review-add amreview-submit-form review-product-<?= $block->getOrderItemId() ?> " style="display:none">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Write Your Own Review')) ?></strong></div>
    <div class="block-content">
        <?php if ($block->getAllowWriteReviewFlag()): ?>
            <form action="<?= $block->escapeUrl($block->getAction()) ?>" class="review-form form-default" method="post" id="review-form" data-role="product-review-form" <?= $advancedReviewHelper->isAllowImages() ? ' enctype="multipart/form-data" ' : ''?> data-bind="scope: 'review-form'"
                  data-product-name="<?= $block->escapeHtml($block->getProductInfo()->getName()) ?>">
                <?= $block->getBlockHtml('formkey') ?>
                <?= $block->getChildHtml('form_fields_before') ?>
                <fieldset class="fieldset review-fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                    <div class="review-product">
                        <div class="review-product-image">
                            <?php if($block->getProductInfo()->getImage()): ?>
                                <img src="<?= $imageHelper->getBaseUrl() . 'catalog/product' . $block->getProductInfo()->getImage() ?>"/>
                            <?php endif;?>
                        </div>
                        <div class="review-product-name">
                            <p><?= $block->escapeHtml($block->getProductInfo()->getName()) ?></p>
                        </div>
                    </div>
                    <?php if ($block->getRatings() && $block->getRatings()->getSize()): ?>
                        <span id="input-message-box"></span>
                        <fieldset class="field required review-field-ratings">
                            <legend class="label"><span><?= $block->escapeHtml(__('Your Rating')) ?></span></legend><br/>
                            <div class="control">
                                <div class="nested product-review-table">
                                    <?php foreach ($block->getRatings() as $_rating): ?>
                                        <div class="field choice review-field-rating">
                                            <label class="label" id="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_rating_label"><span><?= $block->escapeHtml($_rating->getRatingCode()) ?></span></label>
                                            <div class="control review-control-vote">
                                                <?php $options = $_rating->getOptions();?>
                                                <?php $iterator = 1; foreach ($options as $_option): ?>
                                                    <input
                                                        type="radio"
                                                        name="ratings[<?= $block->escapeHtmlAttr($_rating->getId()) ?>]"
                                                        id="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $block->escapeHtmlAttr($_option->getValue()) ?>_<?= $block->escapeHtmlAttr($block->getOrderItemId()) ?>"
                                                        value="<?= $block->escapeHtmlAttr($_option->getId()) ?>"
                                                        class="radio"
                                                        data-star-value="<?= $block->escapeHtmlAttr($iterator) ?>"
                                                        data-validate="{'rating-required':true}"
                                                        aria-labelledby="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_rating_label <?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $block->escapeHtmlAttr($_option->getValue()) ?>_label" />
                                                    <label
                                                        class="rating-<?= $block->escapeHtmlAttr($iterator) ?>"
                                                        for="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $block->escapeHtmlAttr($_option->getValue()) ?>_<?= $block->escapeHtmlAttr($block->getOrderItemId()) ?>"
                                                        title="<?= $block->escapeHtmlAttr(__('%1 %2', $iterator, $iterator > 1 ? __('stars') : __('star'))) ?>"
                                                        id="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $block->escapeHtmlAttr($_option->getValue()) ?>_label">
                                                        <span><?= $block->escapeHtml(__('%1 %2', $iterator, $iterator > 1 ? __('stars') : __('star'))) ?></span>
                                                    </label>
                                                    <?php $iterator++; ?>
                                                <?php endforeach; ?>
                                            </div>
                                        </div>
                                    <?php endforeach; ?>
                                </div>
                                <input type="hidden" name="validate_rating" class="validate-rating" value="" />
                            </div>
                        </fieldset>
                    <?php endif ?>
                    <div class="field review-field-nickname required" style="display:none">
                        <label for="nickname_field" class="label"><span><?= $block->escapeHtml(__('Nickname')) ?></span></label>
                        <div class="control">
                            <input type="text" placeholder="<?= __('Nickname') ?>" name="nickname" id="nickname_field" class="input-text" data-validate="{required:true}" data-bind="value: nickname()" />
                        </div>
                    </div>
                    <div class="field review-field-summary required">
                        <label for="summary_field" class="label"><span><?= $block->escapeHtml(__('Summary')) ?></span></label>
                        <div class="control">
                            <input type="text" placeholder="<?= __('Please enter a summary') ?>" name="title" id="summary_field" class="input-text" data-validate="{required:true}" data-bind="value: review().title" />
                        </div>
                    </div>
                    <div class="field review-field-text required">
                        <label for="review_field" class="label"><span><?= $block->escapeHtml(__('Review')) ?></span></label>
                        <div class="control">
                            <textarea name="detail" placeholder="<?= __('Please enter a message') ?>" id="review_field" cols="5" rows="3" data-validate="{required:true}" data-bind="value: review().detail"></textarea>
                        </div>
                    </div>
                    <?php if ($advancedReviewHelper->isAllowImages()): ?>
                        <div class="field review-field-image ">
                            <label class="label"><?= __('Add your photo') ?></label><div class="control">
                                <label id="am_upload_image_button_<?= $orderItemId ?>" class="cj_am_upload_image_button"><?= __("Select upload file") ?></label>
                                <label id="am_upload_image_label_<?= $orderItemId ?>" class="label" style="margin-left: 20px"><?= __("No file uploaded") ?></label>
                                <input id="am_upload_image_<?= $orderItemId ?>" class="amrev-input" name="review_images[]" accept="image/*" multiple="" type="file" title="<?= __('Add your photo') ?>" hidden="hidden" placeholder="<?= __('Add your photo') ?>">
                            </div>
                        </div>
                    <?php endif; ?>
                </fieldset>
                <div class="field required amreview-gdpr-wrap">
                    <input type="checkbox" name="gdpr" class="amreview-checkbox" id="amreview-gdpr-field" title="<?= __('GDPR') ?>" data-validate="{required:true}">
                    <label class="label-gdpr amreview-checkboxlabel">
                        <?= __('I have read & accept the <a target="_blank" href="/privacy-policy">Privacy Policy</a>'); ?><span class="asterix">*</span>
                    </label>
                </div>
                <div class="actions-toolbar review-form-actions">
                    <div class="primary actions-primary">
                        <button type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Submit Review')) ?></span></button>
                    </div>
                </div>
            </form>
            <script type="text/x-magento-init">
                {
                    "[data-role=product-review-form]": {
                        "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
                },
                "#review-form": {
                    "Magento_Review/js/error-placement-mypage": {},
                    "Magento_Review/js/validate-review": {},
                    "Magento_Review/js/submit-review-mypage": {}
                }
            }
            </script>
        <?php else: ?>
            <div class="message info notlogged" id="review-form" style="display:none">
                <div>
                    <?= $block->escapeHtml(__('Only registered users can write reviews. Please <a href="%1">Sign in</a> or <a href="%2">create an account</a>', $block->getLoginLink(), $block->getRegisterUrl()), ['a']) ?>
                </div>
            </div>
        <?php endif ?>
    </div>
</div>

<script>
    require(["jquery"], function($){
        var imageElement = $("#am_upload_image_<?= $orderItemId; ?>-<?= $block->getProductInfo()->getId()?>");
        document.getElementById("am_upload_image_button_<?= $orderItemId; ?>-<?= $block->getProductInfo()->getId()?>").onclick = function() {showImageUpload()};
        document.getElementById("am_upload_image_<?= $orderItemId; ?>-<?= $block->getProductInfo()->getId()?>").onchange = function() {changeImageText()};

        function showImageUpload (){
            imageElement.trigger("click");
        }
        function changeImageText(){
            var fileName;
            if (imageElement[0].files.length > 1){
                fileName = imageElement[0].files.length + " files";
            } else {
                fileName = imageElement[0].files[0].name;
                if (fileName.length > 30) {
                    fileName = fileName.substring(0, 10) + "...";
                }
            }
            $("#am_upload_image_label_<?= $orderItemId; ?>-<?= $block->getProductInfo()->getId()?>").text(fileName)
        }
    });
</script>
