<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Review\Block\Product\Review $block */
?>
<div class="product attribute review"  id="review-form">
    <strong class="type click_show review">Review</strong>
    <div class="value content_detail content_review" style="display: none">
        <div id="product-review-container" data-role="product-review"></div>
        <?= $block->getChildHtml() ?>

        <script type="text/x-magento-init">
            {
                "*": {
                    "Magento_Review/js/process-reviews": {
                        "productReviewUrl": "<?= $block->escapeJs($block->getProductReviewUrl()) ?>",
                        "reviewsTabSelector": "#tab-label-reviews"
                    }
                }
            }
        </script>
    </div>
</div>

<script>
	require([
		'jquery'
	],function ($) {
		$("#tab-label-reviews").click(function() {
			$(".click_show.review").addClass("active");
			$(".content_review").show();
		});

		$(".click_show.review").click(function(){
			$(this).toggleClass("active");
			$(".content_review").slideToggle();
		});
	});
</script>
