<?php
/** @var $block \Satp\Customer\Block\Membership */
$customer = $block->getCustomer();
$groupName = $block->getGroupName($customer->getGroupId());
$couponCount = number_format($block->getCountCoupon());
$pointSearchResult = $block->getPointsSearchResult();
?>

<div class="membership_section">
    <div class="container">
        <div class="box_member">
            <div class="member_info">
                <h3><?= $customer->getName() ?></h3>
                <p>
                    <?= $block->escapeHtml(__('Membership')) ?>
                    <?php if (isset($pointSearchResult['memberExpreDate']) && !empty($pointSearchResult['memberExpreDate'])): ?>
                        <?= $block->escapeHtml(__('(Expiry Date: %1)', $block->dateFormat($pointSearchResult['memberExpreDate']))) ?>
                    <?php endif; ?>
                </p>
                <div class="rank">
                    <h2><?= $groupName ?></h2>
                    <a class="view_all" href="<?= $block->getUrl('membership/member.html') ?>"><?= $block->escapeHtml(__('View all benefits')) ?></a>
                </div>
            </div>
            <div class="member_point">
                <p class="label point">
                    <?= $block->escapeHtml(__('Point')) ?>
                    <?php if (isset($pointSearchResult['expireDate']) && !empty($pointSearchResult['expireDate'])): ?>
                        <?= $block->escapeHtml(__('(Expiry Date: %1)', $block->dateFormat($pointSearchResult['expireDate']))) ?>
                    <?php endif; ?>
                </p>
                <p class="count"><?=number_format($block->getPoint());?><span><?= __('p') ?></span></p>
            </div>
            <div class="member_review">
                <p class="label point"><?= $block->escapeHtml(__('Review')) ?></p>
                <p class="count"><?=number_format($block->getCountOrderReviewed())?> / <?=number_format($block->getCountOrderReviewAvailable())?></p>
            </div>
        </div>
    </div>
</div>
