<?php
/**
 * Created by Eguana Team.
 * User: sonia
 * Date: 7/19/20
 * Time: 1:19 PM
 */
?>
<?php
/** @var \Magento\Framework\View\Element\Template $block */
    $containerId = $this->helper(\Amore\GaTagging\Helper\Data::class)->getAdditionalContainerId();
?>
<?php if ($containerId): ?>
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':

            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],

        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=

        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);

    })(window,document,'script','dataLayer','<?= /* @noEscape */ $containerId ?>');</script>
<!-- End Google Tag Manager -->
<?php endif; ?>