<?php
/**
 * Created by Eguana Team.
 * User: sonia
 * Date: 7/2/20
 * Time: 6:25 AM
 */
?>
<?php
/** @var \Amore\GaTagging\Block\GaTagging $block */
?>
<!-- AP GA Tagging Data -->
<script>
    //공동변수
    var AP_DATA_GCID = "";
    var AP_DATA_CID = "";
    var AP_DATA_ISMEMBER = "";
    var AP_DATA_ISLOGIN = "N";
    var AP_DATA_LOGINTYPE = "";
    var AP_DATA_CA = "";
    var AP_DATA_CD = "";
    var AP_DATA_CG = "";
    var AP_DATA_CT = "";
    var AP_DATA_SITENAME = "<?= $block->escapeJs($block->escapeHtml($this->helper(\Amore\GaTagging\Helper\Data::class)->getSiteName())) ?>";
    var AP_DATA_CHANNEL = "PC";
    var AP_DATA_PAGENAME = "<?= $block->getTitle() ?>";
    var AP_DATA_PAGETYPE = "";
    var AP_CART_ADDPRDS = [];
</script>


