<?php
/**
 * Created by Eguana Team.
 * User: sonia
 * Date: 7/19/20
 * Time: 12:59 PM
 */
?>
<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<?php if ($block->getEventName()) : ?>
<script type="text/x-magento-init">
    {
        "*": {
            "Amore_GaTagging/js/action/notify":{
                "eventName": "<?= /* @noEscape */$block->getEventName() ?>"
            }
        }
    }
</script>
<?php endif; ?>
