<!--<title>Sulwhasoo Beauty Service - Beautylounge | 雪花秀</title>-->
<!--<meta name="description" content="雪花秀SPA用亞洲智慧體驗整體美。雪花秀Beauty Lounge由 | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="og:title" content="Sulwhasoo Beauty Service - Beautylounge | 雪花秀">-->
<!--<meta property="og:description" content="雪花秀SPA用亞洲智慧體驗整體美。雪花秀Beauty Lounge由 | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="twitter:title" content="Sulwhasoo Beauty Service - Beautylounge | 雪花秀">-->
<!--<meta property="twitter:description" content="雪花秀SPA用亞洲智慧體驗整體美。雪花秀Beauty Lounge由 | Sulwhasoo Hong Kong 中國香港">-->

<section class="content">
        <div class="blind">BEAUTY LOUNGE</div>

        <div class="content static parbase"><div class="l-wrap l-full">
            <div class="spa-intro">
                <div class="h1"><img src="/media/html/resource/img/spa/beautylounge/image_2.png" alt=""></div>
                <img src="/media/html/resource/img/spa/beautylounge/image_1.jpg" alt="">
            </div>
        </div>
            <div class="l-wrap">
                <section class="spa-section">
                    <div class="spa-section-guide" style="border-bottom: 0;">
                        <h1 class="h">韓國傳統美療智慧盡在全新美療護理</h1>
                        <p class="p">雪花秀Beauty Lounge由韓國旗艦店引入全新美療護理，以獨有之韓式激活按摩手法，透過淨化、激活、滋養三步曲，配以珍貴韓方草本精萃，全面提昇肌膚元氣及能量，喚醒肌膚細胞，發揮更極緻美療效果，締造和諧調和之美。</p>
                    </div>
                </section>

                <div class="spa-programs">
                    <h2 class="h2"><span>Beauty Lounge Programs</span></h2>
                    <section class="spa-section">
                        <div class="spa-section-item">
                            <span class="flag">面部護理</span>
                            <h3 class="h">韓方穴位淨肌護理</h3>
                            <p class="p">韓國全新激活按摩暢通血氣運行，配合雪花秀基礎護理系列，為肌膚灌注水份，密封式親膚補濕膜能促進補益成分滲透至肌膚深處，同時帶走肌膚中的不良雜質，回復均衡潤澤肌膚。</p>
                            <span class="price"><i>80 分鐘</i> HKD880</span>
                        </div>
                    </section>
                    <section class="spa-section">
                        <div class="spa-section-item">
                            <span class="flag">面部護理</span>
                            <h3 class="h">白樺深層水潤舒緩護理</h3>
                            <p class="p">護理透過全新韓方手法，改善外在環境等因素影響的缺水問題；當中人參籽、白樺樹精華及闊葉麥冬成分，有效紓緩及滋養肌膚，改善細胞更新力，提供長效補濕效果，回復健康水潤狀態。</p>
                            <span class="price"><i>90 分鐘</i> HKD980</span>
                        </div>
                    </section>
                    <section class="spa-section">
                        <div class="spa-section-item">
                            <span class="flag">面部護理</span>
                            <h3 class="h">梅花煥活緊緻護理</h3>
                            <p class="p">以梅花强效抗氧精萃為肌膚細胞作防護，質地清新易吸收，瞬間滲透肌膚鎖緊水分以保持肌膚水漾潤澤，富有彈性，更顯強韌細緻</p>
                            <span class="price"><i>90 分鐘</i> HKD1,100</span>
                        </div>
                    </section>
                    <section class="spa-section">
                        <div class="spa-section-item">
                            <span class="flag">面部護理</span>
                            <h3 class="h">人參煥顏活肌護理</h3>
                            <p class="p">珍貴的人參蘊含高效抗氧功效，護理以人參面霜及人參籽油改善暗啞粗糙缺水膚質，促進血氣運行，全面提升肌膚吸收力；深層滋補緊緻肌膚 ，令肌膚回復細緻柔嫩，煥活青春光采。</p>
                            <span class="price"><i>90 分鐘</i> HKD1,200</span>
                        </div>
                    </section>
                    <section class="spa-section">
                        <div class="spa-section-item">
                            <span class="flag">面部護理</span>
                            <h3 class="h">白參滋晶透亮淨白護理</h3>
                            <p class="p">專門針對黑色素、泛紅、暗晦肌膚，透過韓式全新激活按摩，配合Snowise系列中白參皂苷等專利美白成分，從肌底阻截黑色素形成，重點淡斑及促進膠原再生，從肌膚煥發亮白剔透光芒。</p>
                            <span class="price"><i>90 分鐘</i> HKD1,350</span>
                        </div>
                    </section>
                    <section class="spa-section">
                        <div class="spa-section-item">
                            <span class="flag">面部護理</span>
                            <h3 class="h">赤松珍雪臻金煥生修復護理</h3>
                            <p class="p">選用極致尊貴的全新珍雪臻金煥生系列產品，讓肌膚深層盡享珍罕赤松的長青生機，高效修復受損細胞，阻截老化連鎖效應，預防色斑、改善毛孔，讓肌膚瞬間回春再生。</p>
                            <span class="price"><i>90 分鐘</i> HKD1,750</span>
                        </div>
                    </section>
                    <section class="spa-section">
                        <div class="spa-section-item">
                            <span class="flag">面部護理</span>
                            <h3 class="h">人參極緻煥顏活肌全效護理</h3>
                            <p class="p">以珍貴人參全系列產品配合全效韓式全新激活按摩，暢通氣血運行，先排毒後進補，深層灌注人參豐饒能量，瞬間緊緻潤澤肌膚，煥活青春元氣，重現彈性光澤，達到極致美顏功效。</p>
                            <span class="price"><i>100 分鐘</i> HKD1,950</span>
                        </div>
                    </section>
                    <section class="spa-section">
                        <div class="spa-section-item">
                            <span class="flag">重點護理</span>
                            <h3 class="h">人參明眸護理</h3>
                            <p class="p">專為塑造緊緻眼眸輪廓而設，為眼周肌膚深層灌注人參滋養，激活眼部血氣運行，瞬間重現青春明眸神采。</p>
                            <span class="price"><i>30 分鐘</i> HKD600</span>
                        </div>
                    </section>
                    <section class="spa-section">
                        <div class="spa-section-item">
                            <span class="flag">重點護理</span>
                            <h3 class="h">珍雪無痕明眸護理</h3>
                            <p class="p">以珍罕赤松喚醒眼部肌膚青春元氣，全效對抗眼周歲月痕跡，撫平眼周皺紋，顯著修復肌膚彈性，締造柔嫩緊緻的無痕明眸。</p>
                            <span class="price"><i>25 分鐘</i> HKD600</span>
                        </div>
                    </section>
                    <section class="spa-section">
                        <div class="spa-section-item">
                            <span class="flag">重點護理</span>
                            <h3 class="h">頸部滋養緊然護理</h3>
                            <p class="p">溫和清除頸部肌膚老化角質後，再以韓式按摩暢通經絡循環，深層滋養並緊緻肌膚紋理，撫平頸部細紋，膚色回復均勻澄淨。</p>
                            <span class="price"><i>30 分鐘</i> HKD500</span>
                        </div>
                    </section>
                    <section class="spa-section">
                        <div class="spa-section-item">
                            <span class="flag">重點護理</span>
                            <h3 class="h">腹腔養生熱敷護理</h3>
                            <p class="p">以素有「醫草」美譽之艾草於腹部作熱敷護理，發揮溫炙療效，有助暢通腰腹部位的血氣循環，調和五臟六腑。</p>
                            <span class="price"><i>15 分鐘</i> HKD400</span>
                            <br>
                            <p class="p">* 重點護理須同時享用60分鐘或以上的護理服務。</p>
                        </div>
                    </section>
                    <section class="spa-section">
                        <div class="spa-section-item">
                            <span class="flag">重點護理</span>
                            <h3 class="h">腹腔養生熱療按摩</h3>
                            <p class="p">以素有「醫草」美譽之艾草於腹部作熱療按摩，發揮溫炙療效，有助暢通血氣循環，調和五臟六腑，提升體內排毒功能，舒緩週期性不適。</p>
                            <span class="price"><i>20 分鐘</i> HKD500</span>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </section>