<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Rma\Block\Returns\History */
?>
<?php $_returns = $block->getReturns(); ?>
<?= $block->getChildHtml('info') ?>
<div class="block block-returns-history">
    <div class="block-title">
        <strong role="heading" aria-level="2"><?= $block->escapeHtml(__('Return History')) ?></strong>
    </div>
    <div class="table-wrapper returns">
        <table class="data table table-returns" id="my-returns-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('My Returns')) ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col id"><?= $block->escapeHtml(__('Return order number')) ?></th>
                <th scope="col" class="col date"><?= $block->escapeHtml(__('Date')) ?></th>
                <th scope="col" class="col shipping"><?= $block->escapeHtml(__('Ship From')) ?></th>
                <th scope="col" class="col status"><?= $block->escapeHtml(__('Return Status')) ?></th>
                <th scope="col" class="col actions">&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            <?php if ($_returns->getSize()): ?>
                <?php $_odd = ''; ?>
                <?php foreach ($_returns as $_return): ?>
                    <tr>
                        <td data-th="<?= $block->escapeHtmlAttr(__('Return #')) ?>" class="col id"><?= $block->escapeHtml($_return->getIncrementId()) ?></td>
                        <td data-th="<?= $block->escapeHtmlAttr(__('Date')) ?>" class="col date"><?= $block->escapeHtml($this->helper(Magento\Rma\Helper\Data::class)->getFormatedDate($_return->getDateRequested())) ?></td>
                        <td data-th="<?= $block->escapeHtmlAttr(__('Ship From')) ?>" class="col shipping"><?= $block->escapeHtml($_return->getCustomerName()) ?></td>
                        <td data-th="<?= $block->escapeHtmlAttr(__('Return Status')) ?>" class="col status">
                            <?php if($_return->getStatus() == 'pending'):?>
                                <?= $block->escapeHtml(__('Waiting for a refund')); ?>
                            <?php else :?>
                                <?= $block->escapeHtml($_return->getStatusLabel()) ?>
                            <?php endif ?>
                        </td>
                        <td data-th="<?= $block->escapeHtmlAttr(__('Actions')) ?>" class="col actions">
                            <a href="<?= $block->escapeUrl($block->getViewUrl($_return)) ?>" class="action view"><span><?= $block->escapeHtml(__('View Return')) ?></span></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="5" class="empty">
                        <?= $block->escapeHtml(__('You have placed no returns.')) ?>
                    </td>
                </tr>
            <?php endif ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom">
            <?= $block->getPagerHtml() ?>
        </div>
    <?php endif ?>
</div>
