<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Rma\Block\Returns\View */
?>
<?php
    $_rma = $block->getRma();
?>
<div class="return-info">
    <span class="return-id"><?= $block->escapeHtml(__('Return #')); ?><?=$block->escapeHtml($_rma->getOrderIncrementId()) ?></span>
    <span class="return-status">
        <?php if($_rma->getStatus() == 'pending'):?>
            <?= $block->escapeHtml(__('Waiting for a refund')); ?>
        <?php else :?>
            <?= $block->escapeHtml($_rma->getStatusLabel()) ?>
        <?php endif ?>
    </span>
</div>