<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Button $block */
try {
    $ecommerceStatus = $this->helper('Eguana\EcommerceStatus\Helper\Data')->getECommerceStatus();
}catch (\Exception $e){
    $ecommerceStatus = 1;
}
?>

<?php if ($block->getWishlist()->getItemsCount() && $block->getWishlist()->isSalable() && $ecommerceStatus): ?>
    <button type="button" data-role="all-tocart" title="<?= $block->escapeHtmlAttr(__('Add All to Cart')) ?>" class="action tocart">
        <span><?= $block->escapeHtml(__('Add All to Cart')) ?></span>
    </button>
<?php endif;?>
