<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Amore\CustomerRegistration\Block\Widget\CheckBox $block */
?>
<div class="checkbox-wrapper field <?= $block->getAttributeCode() ?><?= $block->isRequired() ? ' required' : ''?>">
    <label class="label" for="<?= $block->escapeHtmlAttr($block->getFieldId($block->getAttributeCode())) ?>"><span><?= $block->escapeHtml($block->getStoreLabel($block->getAttributeCode())) ?></span></label>
    <div class="control">
        <select id="<?= $block->escapeHtmlAttr($block->getFieldId($block->getAttributeCode())) ?>" name="<?= $block->escapeHtmlAttr($block->getFieldName($block->getAttributeCode())) ?>" title="<?= $block->escapeHtmlAttr($block->getStoreLabel($block->getAttributeCode())) ?>"<?php if ($block->isRequired()) : ?> class="validate-select" data-validate="{required:true}"<?php endif; ?>>
            <?php $options = $block->getOptions(); ?>
            <?php $value = $block->getData($block->getAttributeCode())?$block->getData($block->getAttributeCode()):0; ?>
            <?php foreach ($options as $option) : ?>
                <option value="<?= $block->escapeHtmlAttr($option->getValue()) ?>"<?= ($option->getValue() == $value) ? ' selected="selected"' : '' ?>><?= $block->escapeHtml(__($option->getLabel())) ?></option>
            <?php endforeach;?>
        </select>
        <input type="checkbox" class="<?= $block->getAttributeCode() ?>_checkbox" />
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "checkboxfield":{
                "attributeCode": "<?= $block->getAttributeCode() ?>"
            }
        }
    }
</script>