<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Amore\CustomerRegistration\Block\Widget\CheckBox $block */
$isSelected = $block->getFormValue();
?>
<div class="checkbox-wrapper choice field <?= $block->getAttributeCode() ?><?= $block->isRequired() ? ' required' : ''?>">
    <select style="display: none"  id="<?= $block->escapeHtmlAttr($block->getFieldId($block->getAttributeCode())) ?>" name="<?= $block->escapeHtmlAttr($block->getFieldName($block->getAttributeCode())) ?>" title="<?= $block->escapeHtmlAttr($block->getStoreLabel($block->getAttributeCode())) ?>"<?php if ($block->isRequired()) : ?> class="validate-select" data-validate="{required:true}"<?php endif; ?>>
        <?php $options = $block->getOptions(); ?>
        <?php $value = $block->getData($block->getAttributeCode())?$block->getData($block->getAttributeCode()):0; ?>
        <?php foreach ($options as $option) : ?>
            <option value="<?= $block->escapeHtmlAttr($option->getValue()) ?>"<?= ($option->getValue() == $isSelected) ? ' selected="selected"' : '' ?>><?= $block->escapeHtml(__($option->getLabel())) ?></option>
        <?php endforeach;?>
    </select>
    <input type="checkbox" name="<?= $block->getAttributeCode() ?>_checkbox" class="<?= $block->getAttributeCode() ?>_checkbox" <?= $isSelected == 1?'checked':''; ?> <?= $block->getAttributeCode() == 'terms_and_services_policy'?'data-validate="{required:true}"':''; ?> />
    <?php if($block->getAttributeCode() != 'mobile_number') : ?>
        <label class="<?= $block->getAttributeCode().'-label' ?> label" for="<?= $block->escapeHtmlAttr($block->getFieldId($block->getAttributeCode())) ?>"><span><?= $block->escapeHtml($block->getStoreLabel($block->getAttributeCode())) ?></span></label>
    <?php else: ?>
        <label class="<?= $block->getAttributeCode().'-label' ?> label" for="<?= $block->escapeHtmlAttr($block->getFieldId($block->getAttributeCode())) ?>"><span><?= $block->escapeHtml(__('Change mobile number')) ?></span></label>
    <?php endif; ?>:
    <?php if($block->getAttributeCode() == 'terms_and_services_policy'): ?>
    <span>
        <a href="#" id="<?= $block->getAttributeCode().'-read-policy' ?>" target="_blank"><?= $block->escapeHtml(__('Read more')) ?></a>
    </span>
    <?php endif; ?>
</div>
<?php if($block->getAttributeCode() == 'terms_and_services_policy'): ?>
<div class="<?= $block->getAttributeCode().'-policy-popup' ?>" style="display: none;">
    <?=  $block->getReadMoreContent(); ?>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "*": {
            "checkboxfield":{
                "attributeCode": "<?= $block->getAttributeCode() ?>"
            }
        }
    }
</script>