<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Amore\CustomerRegistration\Block\Widget\MobileNumber $block */
?>

<div class="field fax <?= $block->isRequired() ? 'required' : '' ?>">
    <label for="fax" class="label">
        <span>
            <?= $block->escapeHtml(__('Mobile Number')) ?>
        </span>
    </label>
    <div class="control">
            <?php
            $_validationClass = $block->escapeHtmlAttr(
                $this->helper(\Magento\Customer\Helper\Address::class)
                     ->getAttributeValidationClass('mobile_number')
            );
            ?>
        <input type="text"
               name="fax"
               id="fax"
               value="<?= $block->escapeHtmlAttr($block->getFax()) ?>"
               title="<?= $block->escapeHtmlAttr(__('Mobile Number')) ?>"
               class="input-text <?= $_validationClass ?: '' ?>"
        >
    </div>
</div>
