<?php
/** @var \Satp\Customer\Block\Widget\BeautyProfile $block */
$values = $block->getFormValue();
?>
    <fieldset class="fieldset subscription <?php if ($values): ?>no-display <?php endif; ?>">
        <div class="fields">
            <label class="label"><?= __('Product information and promotion information') ?></label>
            <div class="checkbox-wrapper choice field <?= $block->getAttributeCode() ?><?= $block->isRequired() ? ' required' : ''?>">
                <select style="display: none"  id="<?= $block->escapeHtmlAttr($block->getFieldId($block->getAttributeCode())) ?>" name="<?= $block->escapeHtmlAttr($block->getFieldName($block->getAttributeCode())) ?>" title="<?= $block->escapeHtmlAttr($block->getStoreLabel($block->getAttributeCode())) ?>"<?php if ($block->isRequired()) : ?> class="validate-select" data-validate="{required:true}"<?php endif; ?>>
                    <?php $options = $block->getOptions(); ?>
                    <?php $value = $block->getData($block->getAttributeCode())?$block->getData($block->getAttributeCode()):0; ?>
                    <?php foreach ($options as $option) : ?>
                        <option value="<?= $block->escapeHtmlAttr($option->getValue()) ?>"<?= ($option->getValue() == $value) ? ' selected="selected"' : '' ?>><?= $block->escapeHtml(__($option->getLabel())) ?></option>
                    <?php endforeach;?>
                </select>
                <input type="checkbox" name="<?= $block->getAttributeCode() ?>_checkbox" id="sel_<?= $block->escapeHtmlAttr($block->getFieldId($block->getAttributeCode())) ?>" class="<?= $block->getAttributeCode() ?>_checkbox select_unselect_terms" <?= $value == 1?'checked':''; ?> <?= $block->getAttributeCode() == 'terms_and_services_policy'?'data-validate="{required:true}"':''; ?> />
                <label class="<?= $block->getAttributeCode().'-label' ?> label" for="<?= $block->escapeHtmlAttr($block->getFieldId($block->getAttributeCode())) ?>"><span><?= $block->escapeHtml($block->getStoreLabel($block->getAttributeCode())) ?></span></label>
            </div>
        </div>
    </fieldset>
    <script type="text/x-magento-init">
        {
            "*": {
                "checkboxfield":{
                    "attributeCode": "<?= $block->getAttributeCode() ?>"
                }
            }
        }
    </script>

