<!--<title>雪花文化展 - Sulwhasoo EXPERIENCE | 雪花秀</title>-->
<!--<meta name="description" content="以文化為基礎的活動，通過現代視角重新詮釋韓國傳統文化，在全球範圍內提升韓國的真美，提升其藝術價值 | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="og:title" content="雪花文化展 - Sulwhasoo EXPERIENCE | 雪花秀">-->
<!--<meta property="og:description" content="以文化為基礎的活動，通過現代視角重新詮釋韓國傳統文化，在全球範圍內提升韓國的真美，提升其藝術價值 | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="twitter:title" content="雪花文化展 - Sulwhasoo EXPERIENCE | 雪花秀">-->
<!--<meta property="twitter:description" content="以文化為基礎的活動，通過現代視角重新詮釋韓國傳統文化，在全球範圍內提升韓國的真美，提升其藝術價值 | Sulwhasoo Hong Kong 中國香港">-->

<section class="content">
    <div class="blind">Culture</div>
    <div class="l-wrap l-full">
        <header class="experience-header">
            <div class="experience-header-cell">
                <h1 class="h">支持文化藝術——雪花文化展</h1>
                <p>雪花文化展是Sulwhasoo特有的文化活動，以全新角度重現傳統工藝的優美與價值，透過與當代藝術的互動交流，體現傳統與現代和諧共融。雪花文化展亦致力傳承及推廣韓國獨有的精湛工藝，向世界宣揚韓國文化之美。雪花文化展並非純粹展出作品，而是發掘韓國傳統文化之美，並以現代視野將傳統重新演繹，達至文化交流，促進傳統與現代文化和諧發展。自2009年至2014年，每年舉辦一屆的雪花文化展不斷深入探索不同主題，展示傳統和現代文化的和諧之美。</p>
                <img src="/media/html/resource/img/experience/bg_culture.jpg" class="experience-header-thumb" alt="雪花文化展">
            </div>
        </header>
    </div>
    <div class="l-wrap">
        <div class="content parsys">
            <div class="parbase culture_section section"><section class="culture-section">
                    <a href="/hk/zh/experience/culture/micro-sense-house-pattern.html" class="culture">
                        <div class="culture-thumb">
                            <img src="/media/html/experience/culture/__icsFiles/afieldfile/2020/03/17/20191004_final_thumnails_pc_1.jpg" alt="微視感覺 － 紋樣之家">
                        </div>
                        <div class="culture-desc">
                            <span class="history">2019</span>
                            <h2 class="h">微視感覺 － 紋樣之家</h2>
                            <span class="date">OCT.18 ~ DEC.29</span>
                            <p class="p break-word"><span style="white-space: nowrap;">「房子」是我們觀察日常生活必不可少的地方。一打開門，你便可以融入雪花秀「微視感覺</span> <span style="white-space: nowrap;">－</span> <span style="white-space: nowrap;">紋樣之家」的房子，感受傳統圖案的啟發。</span></p>
                            <div class="func">
                                <div class="btn">了解更多</div>
                            </div>
                        </div>
                    </a>
                </section>
            </div>
            <div class="parbase culture_section section"><section class="culture-section">
                    <a href="/hk/zh/experience/culture/fortune-land.html" class="culture">
                        <div class="culture-thumb">
                            <img src="/media/html/experience/culture/__icsFiles/afieldfile/2019/02/08/2018.jpg" alt="豐饒之地 ── 金箔工藝">
                        </div>
                        <div class="culture-desc">
                            <span class="history">2018</span>
                            <h2 class="h">豐饒之地 ── 金箔工藝</h2>
                            <span class="date">OCT.16 - DEC.14</span>
                            <p class="p break-word"><span style="white-space: nowrap;">滿有福氣力量的東方故事</span></p>
                            <div class="func">
                                <div class="btn">了解更多</div>
                            </div>
                        </div>
                    </a>
                </section>
            </div>
            <div class="parbase culture_section section"><section class="culture-section">
                    <a href="/hk/zh/experience/culture/once-upon-a-time.html" class="culture">
                        <div class="culture-thumb">
                            <img src="/media/html/experience/culture/__icsFiles/afieldfile/2019/02/08/2017.jpg" alt="傳說 ── 仙女與樵夫">
                        </div>
                        <div class="culture-desc">
                            <span class="history">2017</span>
                            <h2 class="h">傳說 ── 仙女與樵夫</h2>
                            <span class="date">9月15日至10月29日</span>
                            <p class="p break-word"><span style="white-space: nowrap;">以現代化觀點重新詮釋流行的韓國民間傳說</span></p>
                            <div class="func">
                                <div class="btn">了解更多</div>
                            </div>
                        </div>
                    </a>
                </section>
            </div>
            <div class="parbase culture_section section"><section class="culture-section">
                    <a href="/hk/zh/experience/culture/once-upon-a-time-love-star.html" class="culture">
                        <div class="culture-thumb">
                            <img src="/media/html/experience/culture/__icsFiles/afieldfile/2019/02/08/2016.jpg" alt="傳說 ── 牛郎與織女">
                        </div>
                        <div class="culture-desc">
                            <span class="history">2016</span>
                            <h2 class="h">傳說 ── 牛郎與織女</h2>
                            <span class="date">10月13至11月13日</span>
                            <p class="p break-word"><span style="white-space: nowrap;">薈萃傳統與現代概念，傳揚韓國美麗之道</span></p>
                            <div class="func">
                                <div class="btn">了解更多</div>
                            </div>
                        </div>
                    </a>
                </section>
            </div>
            <div class="parbase culture_section section"><section class="culture-section">
                    <a href="/hk/zh/experience/culture/once-upon-a-time-crape-myrtle.html" class="culture">
                        <div class="culture-thumb">
                            <img src="/media/html/experience/culture/__icsFiles/afieldfile/2019/02/08/2015.jpg" alt="傳說 ── 紫薇花逸事">
                        </div>
                        <div class="culture-desc">
                            <span class="history">2015</span>
                            <h2 class="h">傳說 ── 紫薇花逸事</h2>
                            <span class="date">Nov. 24 – Dec. 19</span>
                            <p class="p break-word"><span style="white-space: nowrap;">訴說紫薇花逸事</span></p>
                            <div class="func">
                                <div class="btn">了解更多</div>
                            </div>
                        </div>
                    </a>
                </section>
            </div>
            <div class="parbase culture_section section"><section class="culture-section">
                    <a href="/hk/zh/experience/culture/skin-niks.html" class="culture">
                        <div class="culture-thumb">
                            <img src="/media/html/experience/culture/__icsFiles/afieldfile/2019/02/08/2014.jpg" alt="傳說 ── 紫薇花逸事">
                        </div>
                        <div class="culture-desc">
                            <span class="history">2014</span>
                            <h2 class="h">傳說 ── 紫薇花逸事</h2>
                            <span class="date">Nov.25 - Dec.31</span>
                            <p class="p break-word"><span style="white-space: nowrap;">全新角度詮釋傳統與現代的邂逅</span></p>
                            <div class="func">
                                <div class="btn">了解更多</div>
                            </div>
                        </div>
                    </a>
                </section>
            </div>
            <div class="parbase culture_section section"><section class="culture-section">
                    <a href="/hk/zh/experience/culture/the-power-of-arrows.html" class="culture">
                        <div class="culture-thumb">
                            <img src="/media/html/experience/culture/__icsFiles/afieldfile/2019/02/08/2013.jpg" alt="穿越年代的弓箭之力">
                        </div>
                        <div class="culture-desc">
                            <span class="history">2013</span>
                            <h2 class="h">穿越年代的弓箭之力</h2>
                            <span class="date">Oct.25 - Nov.9</span>
                            <p class="p break-word"><span style="white-space: nowrap;">穿越年代的弓箭之力</span></p>
                            <div class="func">
                                <div class="btn">了解更多</div>
                            </div>
                        </div>
                    </a>
                </section>
            </div>
            <div class="parbase culture_section section"><section class="culture-section">
                    <a href="/hk/zh/experience/culture/onggi-respiring-earth.html" class="culture">
                        <div class="culture-thumb">
                            <img src="/media/html/experience/culture/__icsFiles/afieldfile/2019/02/08/2012.jpg" alt="呼吸的泥土——瓷器">
                        </div>
                        <div class="culture-desc">
                            <span class="history">2012</span>
                            <h2 class="h">呼吸的泥土——瓷器</h2>
                            <span class="date">Oct.18 - Nov.3</span>
                            <p class="p break-word"><span style="white-space: nowrap;">從大自然建構的韓國美學核心</span></p>
                            <div class="func">
                                <div class="btn">了解更多</div>
                            </div>
                        </div>
                    </a>
                </section>
            </div>
            <div class="parbase culture_section section"><section class="culture-section">
                    <a href="/hk/zh/experience/culture/hypothetical-garden.html" class="culture">
                        <div class="culture-thumb">
                            <img src="/media/html/experience/culture/__icsFiles/afieldfile/2019/02/08/2011.jpg" alt="假設庭園">
                        </div>
                        <div class="culture-desc">
                            <span class="history">2011</span>
                            <h2 class="h">假設庭園</h2>
                            <span class="date">Oct.28 - Nov.10</span>
                            <p class="p break-word"><span style="white-space: nowrap;">開啟未知之門</span></p>
                            <div class="func">
                                <div class="btn">了解更多</div>
                            </div>
                        </div>
                    </a>
                </section>
            </div>
            <div class="parbase culture_section section"><section class="culture-section">
                    <a href="/hk/zh/experience/culture/sujak-an-earnest-meeting.html" class="culture">
                        <div class="culture-thumb">
                            <img src="/media/html/experience/culture/__icsFiles/afieldfile/2019/02/08/1450344681354.jpg" alt="手作 —— 一次真誠相會">
                        </div>
                        <div class="culture-desc">
                            <span class="history">2010</span>
                            <h2 class="h">手作 —— 一次真誠相會</h2>
                            <span class="date">Oct.30 - Nov.8</span>
                            <p class="p break-word"><span style="white-space: nowrap;">探索美之本源</span></p>
                            <div class="func">
                                <div class="btn">了解更多</div>
                            </div>
                        </div>
                    </a>
                </section>
            </div>
        </div>
    </div>
</section>
