<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;
use Sapt\AjaxWishlist\Helper\Data as AjaxHelper;

// @codingStandardsIgnoreFile

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */

?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
    <?php
    $_helper = $this->helper(Magento\Catalog\Helper\Output::class);
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'category_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = false;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    $description = false;
    ?>
    <div class="block widget block-products-list <?= /* @noEscape */ $mode ?>">
        <?php if ($block->getTitle()): ?>
            <div class="block-title">
                <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
            </div>
        <?php endif ?>
        <div class="block-content">
            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
            <div class="swiper-container products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
                <ol class="swiper-wrapper products list items product-items <?= /* @noEscape */ $type ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item) : ?>
                        <?php /* @noEscape */ $productSku = $_item->getSku(); ?>
                        <?= /* @noEscape */ ($iterator++ == 1) ? '<li class="swiper-slide product-item">' : '</li><li class="swiper-slide product-item">' ?>
                        <div class="product-item-wrapper">
                            <div class="product-item-info">
                                <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                   class="product-item-photo"
                                   ap-click-area="product"
                                   ap-click-name="prd click"
                                   ap-click-data="<?= /* @noEscape */ $block->getProductDefaultName($productSku) . '/' . $productSku; ?>">
                                    <?= $block->getImage($_item, $image)->toHtml() ?>
                                </a>
                                <?php if ($_item->getProductLabels()): ?>
                                    <div class="product_labels">
                                        <?php echo $_helper->productAttribute($_item, $_item->getProductLabels(), 'product_labels') ?>
                                    </div>
                                <?php endif;?>
                                <div class="product-item-details">
                                    <div class="product_tags">
                                        <?php if ($_item->getProductTags()): ?>
                                            <?php echo $_helper->productAttribute($_item, $_item->getProductTags(), 'product_tags') ?>
                                        <?php endif;?>
                                    </div>
                                    <?php if($_item->getData('new')):?>
                                        <span class="product-item-flag"><?= $block->escapeHtml($_item->getResource()->getAttribute('new')->getStoreLabel());?></span>
                                    <?php endif;?>
                                    <?php if($_item->getData('best')):?>
                                        <span class="product-item-flag"><?= $block->escapeHtml($_item->getResource()->getAttribute('best')->getStoreLabel()); ?></span>
                                    <?php endif;?>
                                    <strong class="product-item-name">
                                        <a title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                           href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                           class="product-item-link"
                                           ap-click-area="product"
                                           ap-click-name="prd click"
                                           ap-click-data="<?= /* @noEscape */ $block->getProductDefaultName($productSku) . '/' . $productSku; ?>">
                                            <?= $block->escapeHtml($_item->getName()) ?>
                                        </a>
                                    </strong>
                                    <div class="product-item-short-description">
                                        <?= $this->helper(Magento\Catalog\Helper\Output::class)->productAttribute($_item, $_item->getShortDescription(), 'short_description') ?>
                                    </div>

                                    <?= $block->getProductPriceHtml($_item, $type) ?>
                                    <?php if($block->getReviewsSummaryHtml($_item, $templateType)): ?>
                                        <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                    <?php else: ?>
                                        <div class="product-reviews-summary empty">
                                            <div class="reviews-actions">
                                                <a class="action add" href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>#review-form">
                                                    <?= __('Be the First to Review'); ?>
                                                </a>
                                            </div>
                                        </div>
                                    <?php endif ?>

                                    <div class="actions-primary">
                                        <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                           class="action todetail primary"
                                           type="button"
                                           ap-click-area="product"
                                           ap-click-name="prd click"
                                           ap-click-data="<?= /* @noEscape */ $block->getProductDefaultName($productSku) . '/' . $productSku; ?>">
                                            <span><?= $block->escapeHtml(__('Details')) ?></span>
                                        </a>
                                    </div>

                                    <div class="product-item-inner">
                                        <div class="product-item-actions">
                                            <?php if ($showWishlist || $showCompare || $showCart): ?>
                                                <?php if ($showCart): ?>
                                                    <div class="actions-primary">
                                                        <?php if ($_item->isSaleable()): ?>
                                                            <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                            <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtmlAttr($_item->getSku()) ?>" action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
                                                                <input type="hidden" name="product" value="<?= $block->escapeUrl($postParams['data']['product']) ?>">
                                                                <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                                <?= $block->getBlockHtml('formkey') ?>
                                                                <button type="submit"
                                                                        clicktext="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                        formtext="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                        title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                                        class="action tocart primary">
                                                                    <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                                </button>
                                                            </form>
                                                        <?php else: ?>
                                                            <button class="action tocart primary disabled"
                                                                    clicktext="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                    formtext="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                    type="button" disabled
                                                                    title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                                <span><?= $block->escapeHtml(__('Sold out')) ?></span>
                                                            </button>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>
                                                <?php if(!$_item->getData('offline')):?>
                                                    <?php if ($showWishlist || $showCompare): ?>
                                                        <div class="actions-secondary" data-role="add-to-links">
                                                            <?php if ($this->helper(Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist): ?>
                                                                <?php if ($this->helper(AjaxHelper::class)->isModuleEnabled()): ?>
                                                                    <!-- ko scope: 'ajaxwishlist' -->
                                                                    <a
                                                                        class="action towishlist"
                                                                        data-bind="css:{wishlisticon : wishlistitem().all_wishlist_items
         ?typeof wishlistitem().all_wishlist_items[<?=
                                                                        /* @noEscape */
                                                                        $_item->getId() ?>]!='undefined':false}"
                                                                        title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
                                                                        aria-label="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
                                                                        data-action="wishlist-actions"
                                                                        data-product-id='<?= /* @noEscape */
                                                                        $_item->getId() ?>'
                                                                        role="button">
                                                                        <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>

                                                                    </a>
                                                                    <!-- /ko -->
                                                                <?php else:?>
                                                                    <a href="#"
                                                                       clicktext="<?= $block->escapeHtml(__('Add to Wishlist')) ?>"
                                                                       formtext="<?= $block->escapeHtml(__('Add to Wishlist')) ?>"
                                                                       data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                                        <span><?= $block->escapeHtml(__('Add to Wishlist')) ?></span>
                                                                    </a>
                                                                <?php endif; ?>
                                                            <?php endif; ?>
                                                            <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                                <?php $compareHelper = $this->helper(Magento\Catalog\Helper\Product\Compare::class);?>
                                                                <!-- ko scope: 'compareAction' -->
                                                                <a href="#" class="action tocompare"
                                                                   data-bind="css:{ compared: isAddedToCompare('<?= $_item->getId() ?>') }"
                                                                   data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>'
                                                                   title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                                    <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                                </a>
                                                                <!-- /ko  -->
                                                            <?php endif; ?>
                                                        </div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <div class="swiper-button-prev swiper-button-prev"></div>
            <div class="swiper-button-next swiper-button-next"></div>
            <div class="swiper-pagination"></div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif;?>
