<?php
/**
 * Created by Eguana Team.
 * User: sonia
 * Date: 10/9/20
 * Time: 9:53 PM
 */
declare(strict_types=1);

namespace Eguana\GWLogistics\Test\Integration;


use Eguana\GWLogistics\Controller\Test\Index;

class firstTest extends \PHPUnit\Framework\TestCase
{
    private $test;

    protected function setUp():void
    {
//        $objectManager = new \Magento\Framework\TestFramework\Unit\Helper\ObjectManager($this);
//        $this->test = $objectManager->getObject(Index::class);
//        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testExecute()
    {
        $this->expectOutputString('ttt');
//        $this->test->execute();
        print_r('ttt');

    }

}