<?php
/**
 * Created by Eguana Team.
 * User: sonia
 * Date: 7/21/20
 * Time: 10:41 AM
 */

/** @var \Amore\GaTagging\Block\GaTagging $block */
?>
<script>
    //회원가입
    var AP_JOIN_NAME = "<?= $block->escapeHtml($block->getJoinName()) ?>";
</script>

<?php if ($block->getEventName()) : ?>
    <script type="text/x-magento-init">
    {
        "#form-validate": {
            "Amore_GaTagging/js/customer/ap-register":{
                "eventName": "<?= /* @noEscape */$block->getEventName() ?>"
            }
        }
    }
</script>
<?php endif; ?>

