<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Weee\Block\Item\Price\Renderer
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

/** @var \Magento\Weee\Helper\Data $weeeHelper */
$weeeHelper = $block->getData('weeeHelper');

$item = $block->getItem();

$price = round($item->getPrice());
$originalPrice = $item->getProduct() ? (int)$item->getProduct()->getPrice() : $item->getOriginalPrice();
$discountPrice = $originalPrice - $price;
$helper = $this->helper(\Eguana\CustomCatalog\Helper\Data::class);
$isBundleDynamic = ($item->getProductType() == \Magento\Catalog\Model\Product\Type::TYPE_BUNDLE && $item->getProduct()->getPriceType() == \Magento\Bundle\Model\Product\Price::PRICE_TYPE_DYNAMIC);
if ($isBundleDynamic) {
    $originalPrice = $helper->getTotalOriginalPriceForBundleDynamic($item);
    $discountPrice = $originalPrice - $price;
}
?>
<?php if (($block->displayPriceInclTax() || $block->displayBothPrices()) && !$item->getNoSubtotal()): ?>
    <span class="price-including-tax" data-label="<?= $block->escapeHtmlAttr(__('Incl. Tax')) ?>">
        <?php if ($block->displayPriceWithWeeeDetails()): ?>
            <span class="cart-tax-total"
                data-mage-init='{"taxToggle": {"itemTaxId" : "#subtotal-item-tax-details<?= (int) $item->getId() ?>"}}'>
        <?php else: ?>
            <span class="cart-price">
        <?php endif; ?>
            <?= /* @noEscape */ $block->formatPrice($block->getRowDisplayPriceInclTax()) ?>
            </span>

        <?php if ($weeeHelper->getApplied($item)): ?>
            <div class="cart-tax-info no-display" id="subtotal-item-tax-details<?= (int) $item->getId() ?>">
                <?php foreach ($weeeHelper->getApplied($item) as $tax): ?>
                    <span class="weee" data-label="<?= $block->escapeHtmlAttr($tax['title']) ?>">
                        <?= /* @noEscape */ $block->formatPrice($tax['row_amount_incl_tax'], true, true) ?>
                    </span>
                <?php endforeach; ?>
            </div>

            <?php if ($block->displayFinalPrice()): ?>
                <span class="cart-tax-total"
                    data-mage-init='{"taxToggle": {"itemTaxId" : "#subtotal-item-tax-details<?= (int) $item->getId()
                    ?>"}}'>
                    <span class="weee" data-label="<?= $block->escapeHtmlAttr(__('Total Incl. Tax')) ?>">
                        <?= /* @noEscape */ $block->formatPrice($block->getFinalRowDisplayPriceInclTax()) ?>
                    </span>
                </span>
            <?php endif; ?>
        <?php endif; ?>
    </span>
<?php endif; ?>

<?php if ($block->displayPriceExclTax() || $block->displayBothPrices()): ?>
       <span class="price-excluding-tax <?php if ($discountPrice > 0) : ?>cart-custom-price<?php endif; ?>"
             data-label="<?= $block->escapeHtmlAttr(__('Excl. Tax')) ?>">
        <?php
        $originalPriceFormat = $block->formatPrice($block->getRowDisplayPriceExclTax());
        if ($discountPrice > 0) :
            ?>
            <?php
            $discountPercent = round($discountPrice / $originalPrice * 100);
            $originalPriceFormat = $block->formatPrice($originalPrice * $item->getQty());
            ?>
            <span class="cart-item-discount">
                        <?= __('%1%', $discountPercent) ?>
                    </span>
            <span class="cart-final-price">
                        <?= $block->escapeHtml(
                            $this->helper(Magento\Checkout\Helper\Data::class)->formatPrice($price),
                            ['span']
                        ) ?>
                    </span>
        <?php endif; ?>
        <?php if ($block->displayPriceWithWeeeDetails()): ?>
            <span class="cart-tax-total"
                data-mage-init='{"taxToggle": {"itemTaxId" : "#esubtotal-item-tax-details<?= (int) $item->getId()?>"}}'>
        <?php else: ?>
            <span class="cart-price">
        <?php endif; ?>
                <?=$originalPriceFormat;?>
            </span>

        <?php if ($weeeHelper->getApplied($item)): ?>
            <span class="cart-tax-info no-display" id="esubtotal-item-tax-details<?= (int) $item->getId() ?>">
                <?php foreach ($weeeHelper->getApplied($item) as $tax): ?>
                    <span class="weee" data-label="<?= $block->escapeHtmlAttr($tax['title']) ?>">
                        <?= /* @noEscape */ $block->formatPrice($tax['row_amount'], true, true) ?>
                    </span>
                <?php endforeach; ?>
            </span>

            <?php if ($block->displayFinalPrice()): ?>
                <span class="cart-tax-total"
                      data-mage-init='{"taxToggle": {"itemTaxId" : "#esubtotal-item-tax-details<?= (int)$item->getId()
                        ?>"}}'>
                    <span class="weee" data-label="<?= $block->escapeHtmlAttr(__('Total')) ?>">
                        <?= /* @noEscape */ $block->formatPrice($block->getFinalRowDisplayPriceExclTax()) ?>
                    </span>
                </span>
            <?php endif; ?>
        <?php endif; ?>

    </span>
<?php endif; ?>
