<?php

/**
 * @author Eguana Team
 * @copyriht Copyright (c) 2020 Eguana {http://eguanacommerce.com}
 * Created by PhpStorm
 * User: shahroz
 * Date: 28/1/20
 * Time: 2:42 PM
 * @var  \Eguana\StoreLocator\Block\Adminhtml\JsLoader $block
 */
$apiKey = $block->getApiKey();
?>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=
<?= $block->escapeHtml($apiKey)?>">
</script>
<script type="text/x-magento-init">
    {
        "*": {
            "location-selector":{}
        }
    }
</script>