<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Magento2.Files.LineLength.MaxExceeded

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
$messageError = false;
?>
<tbody class="cart item">
<?php if ($messages = $block->getMessages()) :?>
    <?php foreach ($messages as $message) :?>
        <?php if ($message['type'] == 'error') {$messageError = true;} ?>
    <?php endforeach; ?>
<?php endif; ?>
<tr class="item-info <?php if ($giftItems = $_item->getGiftItems()): ?>item-info-gift<?php endif; ?> <?php if ($messageError) { ?> cart_message_error <?php } ?>">
    <td data-th="<?= $block->escapeHtmlAttr(__('Item')) ?>" class="col item">
        <?php if ($block->hasProductUrl()) :?>
        <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"
           title="<?= $block->escapeHtmlAttr($block->getProductName()) ?>"
           tabindex="-1"
           class="product-item-photo">
            <?php else :?>
            <span class="product-item-photo">
            <?php endif;?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            <?php if ($block->hasProductUrl()) :?>
        </a>
    <?php else :?>
        </span>
    <?php endif; ?>
        <div class="product-item-details <?php if ($messageError) { ?> cart_message_error <?php } ?>">
            <div class="product-item-details-top">
            <?php if ($messages = $block->getMessages()) :?>
                <?php foreach ($messages as $message) :?>
                    <?php if ($message['type'] == 'error') {$messageError = true;} ?>
                    <div class= "cart item message <?= $block->escapeHtmlAttr($message['type']) ?>">
                        <div <?= $_item->getData('is_gift')?'gift':''; ?>><?= $block->escapeHtml($message['text']) ?></div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
            <strong class="product-item-name">
                <?php if ($block->hasProductUrl()) :?>
                    <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                <?php else :?>
                    <?= $block->escapeHtml($block->getProductName()) ?>
                <?php endif; ?>
            </strong>
            <?php if($product->getTypeId() != 'bundle'){ ?>
                <?php if ($_options = $block->getOptionList()) :?>
                    <dl class="item-options">
                        <?php foreach ($_options as $_option) :?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <dd>
                                <span class="label"><?= $block->escapeHtml($_option['label']) ?>:</span>
                                <?php if (isset($_formatedOptionValue['full_view'])) :?>
                                    <?= $block->escapeHtml($_formatedOptionValue['full_view']) ?>
                                <?php else :?>
                                    <?= $block->escapeHtml($_formatedOptionValue['value'], ['span', 'a']) ?>
                                <?php endif; ?>
                            </dd>
                        <?php endforeach; ?>
                    </dl>
                <?php endif;?>
            <?php } ?>

            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock) :?>
                <?= $addInfoBlock->setItem($_item)->toHtml() ?>
            <?php endif;?>
            <div class="item-actions item-actions-desktop">
                <?php if (!$_item->getData('is_gift')):?>
                    <?= /* @noEscape */ $block->getActions($_item) ?>
                <?php endif; ?>
            </div>
            <?php if($product->getTypeId() == 'bundle'){ ?>
                <?php if ($_options = $block->getOptionList()) :?>
                    <div class="bundle-detail-cart">
                        <button class="bundle-button-toggle" type="button">
                            <span><?= $block->escapeHtml(__('SET GOODS')) ?>(<span class="count"><?= count($_options); ?></span>)</span>
                        </button>
                        <dl class="item-options">
                            <?php foreach ($_options as $_option) :?>
                                <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                                <dd>
                                    <span class="label"><?= $block->escapeHtml($_option['label']) ?>:</span>
                                    <?php if (isset($_formatedOptionValue['full_view'])) :?>
                                        <?= $block->escapeHtml($_formatedOptionValue['full_view']) ?>
                                    <?php else :?>
                                        <?= $block->escapeHtml($_formatedOptionValue['value'], ['span', 'a']) ?>
                                    <?php endif; ?>
                                </dd>
                            <?php endforeach; ?>
                        </dl>
                    </div>
                <?php endif;?>
            <?php } ?>
            </div>
            <div class="product-item-details-qty col qty" data-th="<?= $block->escapeHtmlAttr(__('Qty')) ?>">
                <div class="field qty">
                    <div class="control qty qty_control">
                        <button type="button"   id="<?= /* @escapeNotVerified */ $_item->getId() ?>-dec"  class="decreaseQty"></button>
                        <input id="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty"
                               name="cart[<?= $block->escapeHtmlAttr($_item->getId()) ?>][qty]"
                               data-cart-item-id="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                               value="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                               type="number"
                               size="4"
                               step="any"
                               title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                               class="input-text qty"
                               data-validate="{required:true,'validate-greater-than-zero':true}"
                               data-role="cart-item-qty"
                            <?php if ($_item->getData('is_gift')):?>
                                readonly
                            <?php endif; ?>
                        />
                        <button type="button"  id="<?= /* @escapeNotVerified */ $_item->getId() ?>-upt" class="increaseQty"></button>
                    </div>
                </div>
                <div class="item-actions item-actions-mobile">
                    <?php if (!$_item->getData('is_gift')):?>
                        <?= /* @noEscape */ $block->getActions($_item) ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </td>
    <td class="col subtotal" data-th="<?= $block->escapeHtmlAttr(__('Subtotal')) ?>">
        <?php if ($canApplyMsrp) :?>
            <span class="cart msrp subtotal">--</span>
        <?php else :?>
            <?= $block->getRowTotalHtml($_item) ?>
        <?php endif; ?>
    </td>
</tr>
<?php if ($giftItems = $_item->getGiftItems()): ?>
<tr class="cart-gift--warpper">
    <td colspan="4">
        <div class="cart-gift-content">
            <?php /** @var $giftItem \Magento\Quote\Model\Quote\Item */ ?>
            <?php foreach ($giftItems as $giftItem): ?>
                <div class="cart_gift_item">
                    <?php $giftProduct = $giftItem->getProduct(); ?>
                    <span class="product-item-photo">
                        <?= $block->getImage($giftProduct, 'cart_page_product_thumbnail')->toHtml() ?>
                    </span>
                    <div class="product-item-details">
                        <span class="giveaway"><?= __('Give Away') ?></span>
                        <strong class="product-item-name">
                            <?= $block->escapeHtml($giftItem->getProduct()->getName()) ?>
                        </strong>
                    </div>
                    <?= $block->getRowTotalHtml($giftItem) ?>
                </div>
            <?php endforeach; ?>
        </div>
    </td>
</tr>
<?php endif; ?>
</tbody>
