<?php
/**
 * Created by Eguana Team.
 * User: sonia
 * Date: 7/19/20
 * Time: 1:01 PM
 */
?>
<?php
/** @var \Amore\GaTagging\Block\GaTagging $block */

$orderData = $block->getOrderData();
?>
<?php if ($orderData && is_array($orderData)) : ?>
<script>
    //카트  todo additional AP
    var AP_ORDER_PRICE = <?= $block->escapeHtml($orderData['AP_ORDER_PRICE'])?>;
    var AP_ORDER_PRDPRICE = <?= $block->escapeHtml($orderData['AP_ORDER_PRDPRICE'])?>;
    var AP_ORDER_DISCOUNT = <?= $block->escapeHtml($orderData['AP_ORDER_DISCOUNT'])?>;
    var AP_ORDER_PRDS = [
        <?php foreach($orderData['AP_ORDER_PRDS'] as $prod) : ?>
        <?= $prod ?>,
        <?php endforeach; ?>
    ];
</script>
<?php endif; ?>

