<?php
/**
 * Created by Eguana Team.
 * User: sonia
 * Date: 7/19/20
 * Time: 1:01 PM
 */
?>
<?php
/** @var \Amore\GaTagging\Block\GaTagging $block */

$orderData = $block->getCartData();
?>
<?php if ($orderData) : ?>
<script>
    //카트  todo additional AP
    var AP_ORDER_PRICE = '<?= $block->escapeHtml($orderData['apCartPrice'])?>';
    var AP_ORDER_PRDPRICE = '<?= $block->escapeHtml($orderData['apCartProdPrice'])?>';
    var AP_ORDER_DISCOUNT = '<?= $block->escapeHtml($orderData['apCartDiscount'])?>';
    var AP_ORDER_PRDS = [
        <?php foreach($orderData['apCartProds'] as $prod) : ?>
        <?= $prod ?>,
        <?php endforeach; ?>
    ];
</script>
<?php endif; ?>

