<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php
/** @var \Magento\DataServices\Block\Context $block */
?>

<script>
    require(['magentoStorefrontEvents'], function (magentoStorefrontEvents) {
        window.magentoStorefrontEvents = magentoStorefrontEvents;
        magentoStorefrontEvents.context.setStorefrontInstance(
            <?= /* @noEscape */ $block->getStorefrontInstanceContext(); ?>
        );
        magentoStorefrontEvents.context.setMagentoExtension({
            magentoExtensionVersion: "<?= /* @noEscape */ $block->getExtensionVersion(); ?>",
        });
        magentoStorefrontEvents.context.setPage({
            pageType: "<?= /* @noEscape */ $block->getData('page_type'); ?>"
        });
        magentoStorefrontEvents.context.setContext("pageExtended", {
            action: "<?= /* @noEscape */ $block->getData('step_name'); ?>"
        });
    });
</script>

<script type="text/x-magento-init">
    {
        "*": {
            "dataServicesBase": {
                "isCookieRestrictionModeEnabled": <?= 0 ?>,
                "isEnabled": <?= (int) $block->isEnabled() ?>
            },
            "magentoStorefrontEventCollector": {}
        }
    }
</script>
