<?php
/** @var \CJ\DataLayer\Block\DataLayer $block */
$orderData = $block->getCJPurchaseData();
?>
<?php if($orderData) : ?>
    <script>
        //주문완료
        var CJ_PURCHASE_PRICE = <?= $block->escapeHtml($orderData['CJ_PURCHASE_PRICE'])?>;
        var CJ_PURCHASE_SHIPPING = <?= $block->escapeHtml($orderData['CJ_PURCHASE_SHIPPING'])?>;
        var CJ_PURCHASE_ORDER_ID = <?= $block->escapeHtml($orderData['CJ_PURCHASE_ORDER_ID'])?>
        var CJ_PURCHASE_PRDS = [
            <?php foreach($orderData['CJ_PURCHASE_PRDS'] as $prod) : ?>
            <?= $prod ?>,
            <?php endforeach; ?>
        ];
    </script>
<?php endif; ?>

