<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php
$isSalable = $block->getProduct()->getIsSalable();
if ($isSalable) {
    $availability = 'https://schema.org/InStock';
} else {
    $availability = 'https://schema.org/OutOfStock';
}
if ($block->getProduct()->getTypeId() == 'bundle') {
    $price = $block->getProduct()->getPriceInfo()->getPrice('final_price')->getMinimalPrice()->getValue();
} else {
    $price = $block->getProduct()->getFinalPrice();
}
?>
<?php
$shortDescription = $this->helper(Magento\Catalog\Helper\Output::class)->productAttribute(
    $block->getProduct(),
    $block->getProduct()->getShortDescription(),
    'short_description'
);
$shortDescription = trim(preg_replace('/\s\s+/',' ', $shortDescription));
?>
<script type="application/ld+json">
    {
        "@context": "https://schema.org/",
        "@type": "Product",
        "name": "<?= /* @noEscape */ $block->escapeHtml($block->getProduct()->getName()) ?>",
        "productID": "<?= /* @noEscape */ $block->escapeHtml($block->getProduct()->getSku()) ?>",
        "image": "<?= $block->escapeUrl($block->getImage($block->getProduct(), 'product_base_image')->getImageUrl()) ?>",
        "description": "<?= /* @noEscape */ $shortDescription ? $block->stripTags($shortDescription) : $block->escapeHtml($block->getProduct()->getName()) ?>",
        "brand": "Sulwhasoo",
        "offers": {
            "@type": "Offer",
            "price": "<?= /* @noEscape */ $block->escapeHtml(round($price)) ?>",
            "priceCurrency": "TWD",
            "availability": "<?= $availability ?>"
        }
    }
</script>
