<?php
/** @var \Eguana\EventReservation\Block\Event\TextBanner $block */
?>
<?php if ($message = $block->getMessage()): ?>
    <?php $backgroundColor = $block->getBgColor(); ?>
    <?php $hyperlink = $block->getHyperlink(); ?>

    <div class="fixed-text-banner"

        <?php if ($backgroundColor !== '') echo 'style="background-color:' . $backgroundColor . '"'; ?>>
        <!-- print the open '<a>' tag -->
        <?php if ($hyperlink !== ''): ?>

        <a href="<?= $hyperlink; ?>" target="_blank" rel="noopener">

            <?php endif; ?>

            <span class="message"><?= $message ?></span>
            <!-- print the close '</a>' tag-->
            <?php if ($hyperlink != ''): ?>

        </a>

    <?php endif; ?>
    </div>
<?php endif; ?>
