<?php


/** @var \Eguana\Magazine\ViewModel\Magazine $viewModel */
$viewModel = $block->getData('view_model');
$bottomBlockId = $viewModel->getListingBottomBlockValue();
?>
<div class="magazine-bottom-content">
    <?php if (isset($bottomBlockId)): ?>
        <?= $block->getLayout()
            ->createBlock(Magento\Cms\Block\Block::class)
            ->setBlockId($bottomBlockId)
            ->toHtml();
        ?>
    <?php endif;?>
</div>
