<?php
/**
 * @author Eguana Team
 * @copyriht Copyright (c) 2020 Eguana {http://eguanacommerce.com}
 * Created by PhpStorm
 * User: yasir
 * Date: 6/18/20
 * Time: 6:45 AM
 */
$magazine = $block->getMagazine();
$magazineList = $block->getCollection($block->getMazineType());

$url = $block->getUrl();
?>
<div class="block-content">
    <div class="magazine-detail">
        <?= /* @noEscape */$block->contentFiltering($magazine->getContent()); ?>
    </div>
</div>

