<?php
/** @var $viewModel \Eguana\Magazine\ViewModel\Index\MagazineList */
$viewModel = $block->getData('view_model_list');
$bannerCollection = $viewModel->getBannerThumbnail();
$imageMagazineCollection = $viewModel->getImageMagazineCollection();
$videoThumbnail = $viewModel->getVideoThumbnail();
$magazineCollection = $viewModel->getMagazineTotalCollection();
?>
<div class="block magazine-image">
    <div>
        <?php if (!empty($bannerCollection->getData())):?>
            <?php foreach ($bannerCollection as $magazineItem): ?>
                <div class="magazine-photo-banner">
                    <a class="action view"
                       href="<?= $block->escapeHtml($block->getUrl($viewModel->getItemDetailsUrl($magazineItem['entity_id'])));?>">
                        <img src="<?= $block->escapeHtml($viewModel->getThumbnailSrc($magazineItem['thumbnail_image']));?>"
                             alt="<?= $block->escapeHtml($magazineItem['thumbnail_alt']);?>" />
                        <div class="banner-text">
                            <strong><?= $block->escapeHtml($magazineItem['title']) ?></strong>
                            <span><?= $block->escapeHtml($magazineItem['content_short']) ?></span>
                        </div>
                    </a>
                </div>
            <?php endforeach; ?>
        <?php endif;?>
        <?php if (!empty($imageMagazineCollection->getData())):?>
            <ul class="list-image-box"">
            <?php foreach ($imageMagazineCollection as $magazineItem): ?>
                <li class="magazine-item-box">
                    <div class="magazine-item">
                        <a
                                href="<?= $block->escapeHtml($block->
                                getUrl($viewModel->getItemDetailsUrl($magazineItem['entity_id'])));?>">
                            <img src="<?= $block->escapeHtml($viewModel->
                            getThumbnailSrc($magazineItem['thumbnail_image']));?>"
                                 alt="<?= $block->escapeHtml($magazineItem['thumbnail_alt']);?>" />
                            <div class="block-title">
                                <strong><?= $block->escapeHtml($magazineItem['title']) ?></strong>
                            </div>
                            <div class="short-discription">
                                <span><?= $block->escapeHtml($magazineItem['content_short']) ?></span>
                            </div>
                        </a>
                    </div>
                </li>
            <?php endforeach; ?>
            </ul>
        <?php endif;?>
        <div class="block magazine-video">
            <?php if (!empty($videoThumbnail->getData())):?>
                <?php foreach ($videoThumbnail as $magazineItem): ?>
                    <div class="magazine-video-banner">
                        <a class="action view"
                           href="<?= $block->escapeHtml($block->getUrl($viewModel->getItemDetailsUrl($magazineItem['entity_id'])));?>">
                            <img src="<?= $block->escapeHtml($viewModel->getThumbnailSrc($magazineItem['thumbnail_image']));?>"
                                 alt="<?= $block->escapeHtml($magazineItem['thumbnail_alt']);?>" />
                        </a>
                    </div>
                <?php endforeach; ?>
            <?php endif;?>
        </div>
    </div>
    <?php if (!empty($magazineCollection->getData())):?>
        <div class="other-magazine">
            <span><?= $block->escapeHtml(__('Other Magazines')) ?></span>
        </div>
        <div class="magazine-slider" id="slick">
            <?php $date = '' ?>
            <?php foreach ($magazineCollection as $magazineItem): ?>
                <?php if ($date == '' || $magazineItem['show_date'] < $date):?>
                    <?php $magazine = $viewModel->getSliderThumnai($magazineItem['show_date'])->getData(); ?>
                    <div class="magazine-slider-item">
                        <div class="magazine-item">
                            <a
                                    href="<?= $block->escapeHtml($block->
                                    getUrl($viewModel->getMonthlyMagazineUrl($magazine[0]['show_date'])));?>">
                                <img src="<?= $block->escapeHtml($viewModel->
                                getThumbnailSrc($magazine[0]['thumbnail_image']));?>"
                                     alt="<?= $block->escapeHtml($magazine[0]['thumbnail_alt']);?>" />
                                <div class="block-title">
                                    <strong><?= $block->escapeHtml($magazineItem['title']) ?></strong>
                                </div>
                            </a>
                        </div>
                    </div>
                    <?php $date = $viewModel->getMonthFromDate($magazineItem['show_date']) ?>
                <?php endif;?>
            <?php endforeach; ?>
        </div>
    <?php endif;?>
</div>
<script>
    require([
        'jquery',
        'slick'
    ], function ($) {

        $('#slick').slick({
            infinite: false,
            speed: 300,
            slidesToShow: 4,
            slidesToScroll: 1,
            responsive: [
                {
                    breakpoint: 1024,
                    settings: {
                        slidesToShow: 3
                    }
                },
                {
                    breakpoint: 767,
                    settings: {
                        slidesToShow: 1
                    }
                }
            ]
        });
    });
</script>
