<?php

/** @var \Eguana\Magazine\ViewModel\Magazine $viewModel */
$viewModel = $block->getData('view_model');
$banner = $viewModel->getBanner();
?>
<div>
    <?php if ($banner): ?>
        <a
           href="<?= $block->escapeUrl($block->getMagazineUrl($banner->getId())); ?>">
            <span>
                <img src="<?=$block->escapeUrl($banner->getThumbnailImageURL());?>"
                     alt="<?=
                        $block->escapeHtml($banner->getThumbnailAlt());?>" />
            </span>
        </a>
    <?php endif; ?>
</div>
