<?php


/** @var \Eguana\Magazine\ViewModel\Magazine $viewModel */
$viewModel = $block->getData('view_model');
$topBlockId = $viewModel->getListingTopBlockValue();
?>
<div class="magazine-top-content"
<?php if (isset($topBlockId)): ?>
         <?= $block->getLayout()
            ->createBlock(Magento\Cms\Block\Block::class)
            ->setBlockId($topBlockId)
            ->toHtml();
            ?>
    <?php endif;?>
</div>
