<?php
/** @var $block \Amore\PointsIntegration\Block\Points\Index */
$pointSearchResult = $block->getPointsSearchResult();
$customer = $block->getCustomer();
$groupName = $block->getGroupName($customer->getGroupId());
?>
<div class="block-title block-membership">
    <strong><?= $block->escapeHtml(__('Membership Point')); ?></strong>
</div>
<div class="membership-wrapper">
    <?php if (count($pointSearchResult) > 0) : ?>
        <div class="items">
            <div class="item">
                <span class="label"><?= $block->escapeHtml(__('Membership level')) ?></span>
                <p class="count"><?= $pointSearchResult['cstmGradeNM']; ?></p>
            </div>
            <div class="item">
                <span class="label"><?= $block->escapeHtml(__('Number Of Point')) ?></span>
                <span class="count"><?= __('%1 Point %2', $pointSearchResult['availablePoint'], '<span>can be used</span>') ?></span>
            </div>
            <div class="item">
                <span class="label"><?= $block->escapeHtml(__('Membership Level Expiration Date')) ?></span>
                <span class="count"><?= $block->dateFormat($pointSearchResult['expireDate']); ?></span>
            </div>
        </div>
    <?php endif; ?>
</div>
