<?php
/**
 * @author Eguana Team
 * @copyright Copyright (c) 2020 Eguana {http://eguanacommerce.com}
 * Created by PhpStorm
 * User: umer
 * Date: 10/8/20
 * Time: 5:25 PM
 */
/** @var \Eguana\SocialLogin\ViewModel\AddFriends $viewModel */
$viewModel = $block->getData('add_friend_view_model');
?>
<?php if ($viewModel->getEnabledInFrontend()):?>
    <?php if ($viewModel->getEnabledLine()):?>
        <div class="line-add-friend">
            <a href="<?= $block->escapeUrl($viewModel->lineAddFriendLink()) ?>" target="_blank">
                <img src="<?= $block->escapeUrl("https://scdn.line-apps.com/n/line_add_friends/btn/zh-Hant.png") ?>" alt="<?= $block->escapeHtml(__('Add as friend')) ?>" height="36" border="0">
            </a>
        </div>
    <?php endif; ?>
<?php endif; ?>
