<?php
/** @var \Eguana\SocialLogin\ViewModel\AddFriends $viewModel */
$viewModel = $block->getData('add_friend_view_model');
?>
<?php if ($viewModel->getLineBannerEnabled()): ?>
    <a href="<?= $block->escapeUrl($viewModel->lineAddFriendLink()) ?>" target="_blank">
        <div class="line-banner">
            <div class="marketing-message">
                <div class="content"><?=$block->escapeHtml($viewModel->getLineMarketingMessage())?></div>
                <img class="line-logo" alt="line logo" src="<?=$block->escapeUrl($viewModel->getLineLogoUrl())?>"/>
                <img class="line-qr-code" alt="line qr code" src="<?=$block->escapeUrl($viewModel->getLineQRCodeUrl())?>"/>
            </div>
        </div>
    </a>
<?php endif; ?>
