<?php
/** @var \Eguana\SocialLogin\ViewModel\AddFriends $viewModel */
$viewModel = $block->getData('add_friend_view_model');
$helper = $this->helper('Eguana\SocialLogin\Helper\Data');
?>
<?php if ($viewModel->getLineBannerEnabled()): ?>
    <?php
    $lineBannerBlockId = $helper->getLineBannerCMSBlockId();
    $lineBannerBlock = $this->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId($lineBannerBlockId)
        ->toHtml();
    ?>
    <?= $lineBannerBlock ?>
<?php endif; ?>
