<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block Magento\Catalog\Block\Product\ProductList\Item\AddTo\Compare */
$product = $block->getProduct();
?>
<!-- ko scope: 'compareAction' -->
<a href="#"
   class="action tocompare"
   data-bind="css:{ compared: isAddedToCompare('<?= $product->getId() ?>') }"
   title="<?= $block->escapeHtml(__('Add to Compare')) ?>"
   aria-label="<?= $block->escapeHtml(__('Add to Compare')) ?>"
   data-post='<?= /* @noEscape */ $block->getCompareHelper()->getPostDataParams($block->getProduct()) ?>'
   role="button">
    <span><?= $block->escapeHtml(__('Compare')) ?></span>
</a>
<!-- /ko  -->
