<?php
/**
 * @author Eguana Team
 * @copyriht Copyright (c) 2020 Eguana {http://eguanacommerce.com}
 * Created by PhpStorm
 * User: Mobeen
 * Date: 23/7/20
 * Time: 3:18 PM
 */

namespace Eguana\StoreSms\Model\Config\Source;

use Magento\Framework\Option\ArrayInterface;

/**
 * Class CountryCode
 */
class CountryCode implements ArrayInterface
{
    /**
     * to option array
     *
     * @return array
     */
    public function toOptionArray()
    {
        $options = [
            ['label'=>'ANDORRA','value'=>'376'],
            ['label'=>'UNITED ARAB EMIRATES','value'=>'971'],
            ['label'=>'AFGHANISTAN','value'=>'93'],
            ['label'=>'ANTIGUA AND BARBUDA','value'=>'1268'],
            ['label'=>'ANGUILLA','value'=>'1264'],
            ['label'=>'ALBANIA','value'=>'355'],
            ['label'=>'ARMENIA','value'=>'374'],
            ['label'=>'NETHERLANDS ANTILLES','value'=>'599'],
            ['label'=>'ANGOLA','value'=>'244'],
            ['label'=>'ANTARCTICA','value'=>'672'],
            ['label'=>'ARGENTINA','value'=>'54'],
            ['label'=>'AMERICAN SAMOA','value'=>'1684'],
            ['label'=>'AUSTRIA','value'=>'43'],
            ['label'=>'AUSTRALIA','value'=>'61'],
            ['label'=>'ARUBA','value'=>'297'],
            ['label'=>'AZERBAIJAN','value'=>'994'],
            ['label'=>'BOSNIA AND HERZEGOVINA','value'=>'387'],
            ['label'=>'BARBADOS','value'=>'1246'],
            ['label'=>'BANGLADESH','value'=>'880'],
            ['label'=>'BELGIUM','value'=>'32'],
            ['label'=>'BURKINA FASO','value'=>'226'],
            ['label'=>'BULGARIA','value'=>'359'],
            ['label'=>'BAHRAIN','value'=>'973'],
            ['label'=>'BURUNDI','value'=>'257'],
            ['label'=>'BENIN','value'=>'229'],
            ['label'=>'SAINT BARTHELEMY','value'=>'590'],
            ['label'=>'BERMUDA','value'=>'1441'],
            ['label'=>'BRUNEI DARUSSALAM','value'=>'673'],
            ['label'=>'BOLIVIA','value'=>'591'],
            ['label'=>'BRAZIL','value'=>'55'],
            ['label'=>'BAHAMAS','value'=>'1242'],
            ['label'=>'BHUTAN','value'=>'975'],
            ['label'=>'BOTSWANA','value'=>'267'],
            ['label'=>'BELARUS','value'=>'375'],
            ['label'=>'BELIZE','value'=>'501'],
            ['label'=>'CANADA','value'=>'1'],
            ['label'=>'COCOS (KEELING] ISLANDS','value'=>'61'],
            ['label'=>'CONGO, THE DEMOCRATIC REPUBLIC OF THE','value'=>'243'],
            ['label'=>'CENTRAL AFRICAN REPUBLIC','value'=>'236'],
            ['label'=>'CONGO','value'=>'242'],
            ['label'=>'SWITZERLAND','value'=>'41'],
            ['label'=>'COTE D IVOIRE','value'=>'225'],
            ['label'=>'COOK ISLANDS','value'=>'682'],
            ['label'=>'CHILE','value'=>'56'],
            ['label'=>'CAMEROON','value'=>'237'],
            ['label'=>'CHINA','value'=>'86'],
            ['label'=>'COLOMBIA','value'=>'57'],
            ['label'=>'COSTA RICA','value'=>'506'],
            ['label'=>'CUBA','value'=>'53'],
            ['label'=>'CAPE VERDE','value'=>'238'],
            ['label'=>'CHRISTMAS ISLAND','value'=>'61'],
            ['label'=>'CYPRUS','value'=>'357'],
            ['label'=>'CZECH REPUBLIC','value'=>'420'],
            ['label'=>'GERMANY','value'=>'49'],
            ['label'=>'DJIBOUTI','value'=>'253'],
            ['label'=>'DENMARK','value'=>'45'],
            ['label'=>'DOMINICA','value'=>'1767'],
            ['label'=>'DOMINICAN REPUBLIC','value'=>'1809'],
            ['label'=>'ALGERIA','value'=>'213'],
            ['label'=>'ECUADOR','value'=>'593'],
            ['label'=>'ESTONIA','value'=>'372'],
            ['label'=>'EGYPT','value'=>'20'],
            ['label'=>'ERITREA','value'=>'291'],
            ['label'=>'SPAIN','value'=>'34'],
            ['label'=>'ETHIOPIA','value'=>'251'],
            ['label'=>'FINLAND','value'=>'358'],
            ['label'=>'FIJI','value'=>'679'],
            ['label'=>'FALKLAND ISLANDS (MALVINAS]','value'=>'500'],
            ['label'=>'MICRONESIA, FEDERATED STATES OF','value'=>'691'],
            ['label'=>'FAROE ISLANDS','value'=>'298'],
            ['label'=>'FRANCE','value'=>'33'],
            ['label'=>'GABON','value'=>'241'],
            ['label'=>'UNITED KINGDOM','value'=>'44'],
            ['label'=>'GRENADA','value'=>'1473'],
            ['label'=>'GEORGIA','value'=>'995'],
            ['label'=>'GHANA','value'=>'233'],
            ['label'=>'GIBRALTAR','value'=>'350'],
            ['label'=>'GREENLAND','value'=>'299'],
            ['label'=>'GAMBIA','value'=>'220'],
            ['label'=>'GUINEA','value'=>'224'],
            ['label'=>'EQUATORIAL GUINEA','value'=>'240'],
            ['label'=>'GREECE','value'=>'30'],
            ['label'=>'GUATEMALA','value'=>'502'],
            ['label'=>'GUAM','value'=>'1671'],
            ['label'=>'GUINEA-BISSAU','value'=>'245'],
            ['label'=>'GUYANA','value'=>'592'],
            ['label'=>'HONG KONG','value'=>'852'],
            ['label'=>'HONDURAS','value'=>'504'],
            ['label'=>'CROATIA','value'=>'385'],
            ['label'=>'HAITI','value'=>'509'],
            ['label'=>'HUNGARY','value'=>'36'],
            ['label'=>'INDONESIA','value'=>'62'],
            ['label'=>'IRELAND','value'=>'353'],
            ['label'=>'ISRAEL','value'=>'972'],
            ['label'=>'ISLE OF MAN','value'=>'44'],
            ['label'=>'INDIA','value'=>'91'],
            ['label'=>'IRAQ','value'=>'964'],
            ['label'=>'IRAN, ISLAMIC REPUBLIC OF','value'=>'98'],
            ['label'=>'ICELAND','value'=>'354'],
            ['label'=>'ITALY','value'=>'39'],
            ['label'=>'JAMAICA','value'=>'1876'],
            ['label'=>'JORDAN','value'=>'962'],
            ['label'=>'JAPAN','value'=>'81'],
            ['label'=>'KENYA','value'=>'254'],
            ['label'=>'KYRGYZSTAN','value'=>'996'],
            ['label'=>'CAMBODIA','value'=>'855'],
            ['label'=>'KIRIBATI','value'=>'686'],
            ['label'=>'COMOROS','value'=>'269'],
            ['label'=>'SAINT KITTS AND NEVIS','value'=>'1869'],
            ['label'=>'KOREA DEMOCRATIC PEOPLES REPUBLIC OF','value'=>'850'],
            ['label'=>'KOREA REPUBLIC OF','value'=>'82'],
            ['label'=>'KUWAIT','value'=>'965'],
            ['label'=>'CAYMAN ISLANDS','value'=>'1345'],
            ['label'=>'KAZAKSTAN','value'=>'7'],
            ['label'=>'LAO PEOPLES DEMOCRATIC REPUBLIC','value'=>'856'],
            ['label'=>'LEBANON','value'=>'961'],
            ['label'=>'SAINT LUCIA','value'=>'1758'],
            ['label'=>'LIECHTENSTEIN','value'=>'423'],
            ['label'=>'SRI LANKA','value'=>'94'],
            ['label'=>'LIBERIA','value'=>'231'],
            ['label'=>'LESOTHO','value'=>'266'],
            ['label'=>'LITHUANIA','value'=>'370'],
            ['label'=>'LUXEMBOURG','value'=>'352'],
            ['label'=>'LATVIA','value'=>'371'],
            ['label'=>'LIBYAN ARAB JAMAHIRIYA','value'=>'218'],
            ['label'=>'MOROCCO','value'=>'212'],
            ['label'=>'MONACO','value'=>'377'],
            ['label'=>'MOLDOVA, REPUBLIC OF','value'=>'373'],
            ['label'=>'MONTENEGRO','value'=>'382'],
            ['label'=>'SAINT MARTIN','value'=>'1599'],
            ['label'=>'MADAGASCAR','value'=>'261'],
            ['label'=>'MARSHALL ISLANDS','value'=>'692'],
            ['label'=>'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','value'=>'389'],
            ['label'=>'MALI','value'=>'223'],
            ['label'=>'MYANMAR','value'=>'95'],
            ['label'=>'MONGOLIA','value'=>'976'],
            ['label'=>'MACAU','value'=>'853'],
            ['label'=>'NORTHERN MARIANA ISLANDS','value'=>'1670'],
            ['label'=>'MAURITANIA','value'=>'222'],
            ['label'=>'MONTSERRAT','value'=>'1664'],
            ['label'=>'MALTA','value'=>'356'],
            ['label'=>'MAURITIUS','value'=>'230'],
            ['label'=>'MALDIVES','value'=>'960'],
            ['label'=>'MALAWI','value'=>'265'],
            ['label'=>'MEXICO','value'=>'52'],
            ['label'=>'MALAYSIA','value'=>'60'],
            ['label'=>'MOZAMBIQUE','value'=>'258'],
            ['label'=>'NAMIBIA','value'=>'264'],
            ['label'=>'NEW CALEDONIA','value'=>'687'],
            ['label'=>'NIGER','value'=>'227'],
            ['label'=>'NIGERIA','value'=>'234'],
            ['label'=>'NICARAGUA','value'=>'505'],
            ['label'=>'NETHERLANDS','value'=>'31'],
            ['label'=>'NORWAY','value'=>'47'],
            ['label'=>'NEPAL','value'=>'977'],
            ['label'=>'NAURU','value'=>'674'],
            ['label'=>'NIUE','value'=>'683'],
            ['label'=>'NEW ZEALAND','value'=>'64'],
            ['label'=>'OMAN','value'=>'968'],
            ['label'=>'PANAMA','value'=>'507'],
            ['label'=>'PERU','value'=>'51'],
            ['label'=>'FRENCH POLYNESIA','value'=>'689'],
            ['label'=>'PAPUA NEW GUINEA','value'=>'675'],
            ['label'=>'PHILIPPINES','value'=>'63'],
            ['label'=>'PAKISTAN','value'=>'92'],
            ['label'=>'POLAND','value'=>'48'],
            ['label'=>'SAINT PIERRE AND MIQUELON','value'=>'508'],
            ['label'=>'PITCAIRN','value'=>'870'],
            ['label'=>'PUERTO RICO','value'=>'1'],
            ['label'=>'PORTUGAL','value'=>'351'],
            ['label'=>'PALAU','value'=>'680'],
            ['label'=>'PARAGUAY','value'=>'595'],
            ['label'=>'QATAR','value'=>'974'],
            ['label'=>'ROMANIA','value'=>'40'],
            ['label'=>'SERBIA','value'=>'381'],
            ['label'=>'RUSSIAN FEDERATION','value'=>'7'],
            ['label'=>'RWANDA','value'=>'250'],
            ['label'=>'SAUDI ARABIA','value'=>'966'],
            ['label'=>'SOLOMON ISLANDS','value'=>'677'],
            ['label'=>'SEYCHELLES','value'=>'248'],
            ['label'=>'SUDAN','value'=>'249'],
            ['label'=>'SWEDEN','value'=>'46'],
            ['label'=>'SINGAPORE','value'=>'65'],
            ['label'=>'SAINT HELENA','value'=>'290'],
            ['label'=>'SLOVENIA','value'=>'386'],
            ['label'=>'SLOVAKIA','value'=>'421'],
            ['label'=>'SIERRA LEONE','value'=>'232'],
            ['label'=>'SAN MARINO','value'=>'378'],
            ['label'=>'SENEGAL','value'=>'221'],
            ['label'=>'SOMALIA','value'=>'252'],
            ['label'=>'SURINAME','value'=>'597'],
            ['label'=>'SAO TOME AND PRINCIPE','value'=>'239'],
            ['label'=>'EL SALVADOR','value'=>'503'],
            ['label'=>'SYRIAN ARAB REPUBLIC','value'=>'963'],
            ['label'=>'SWAZILAND','value'=>'268'],
            ['label'=>'TURKS AND CAICOS ISLANDS','value'=>'1649'],
            ['label'=>'CHAD','value'=>'235'],
            ['label'=>'TOGO','value'=>'228'],
            ['label'=>'THAILAND','value'=>'66'],
            ['label'=>'TAJIKISTAN','value'=>'992'],
            ['label'=>'TOKELAU','value'=>'690'],
            ['label'=>'TIMOR-LESTE','value'=>'670'],
            ['label'=>'TURKMENISTAN','value'=>'993'],
            ['label'=>'TUNISIA','value'=>'216'],
            ['label'=>'TONGA','value'=>'676'],
            ['label'=>'TURKEY','value'=>'90'],
            ['label'=>'TRINIDAD AND TOBAGO','value'=>'1868'],
            ['label'=>'TUVALU','value'=>'688'],
            ['label'=>'TAIWAN, PROVINCE OF CHINA','value'=>'886'],
            ['label'=>'TANZANIA, UNITED REPUBLIC OF','value'=>'255'],
            ['label'=>'UKRAINE','value'=>'380'],
            ['label'=>'UGANDA','value'=>'256'],
            ['label'=>'UNITED STATES','value'=>'1'],
            ['label'=>'URUGUAY','value'=>'598'],
            ['label'=>'UZBEKISTAN','value'=>'998'],
            ['label'=>'HOLY SEE (VATICAN CITY STATE]','value'=>'39'],
            ['label'=>'SAINT VINCENT AND THE GRENADINES','value'=>'1784'],
            ['label'=>'VENEZUELA','value'=>'58'],
            ['label'=>'VIRGIN ISLANDS, BRITISH','value'=>'1284'],
            ['label'=>'VIRGIN ISLANDS, U.S.','value'=>'1340'],
            ['label'=>'VIET NAM','value'=>'84'],
            ['label'=>'VANUATU','value'=>'678'],
            ['label'=>'WALLIS AND FUTUNA','value'=>'681'],
            ['label'=>'SAMOA','value'=>'685'],
            ['label'=>'KOSOVO','value'=>'381'],
            ['label'=>'YEMEN','value'=>'967'],
            ['label'=>'MAYOTTE','value'=>'262'],
            ['label'=>'SOUTH AFRICA','value'=>'27'],
            ['label'=>'ZAMBIA','value'=>'260'],
            ['label'=>'ZIMBABWE','value'=>'263']

        ];

        return $options;
    }
}


