

    <div class="product attribute review">

            <strong class="type click_show review">Review</strong>

        <div class="value content_detail content_review" style="display: none">
            this is content
        </div>
    </div>


<script>
    require([
        'jquery'
    ],function ($) {
        $(".click_show.review").click(function(){
            $(this).toggleClass("active");
            $(".content_review").toggle('');
        });
    });
</script>
