

<div class="product attribute faq">

    <strong class="type click_show faq">FAQ</strong>

    <div class="value content_detail content_faq" style="display: none">
        this is content
    </div>
</div>


<script>
    require([
        'jquery'
    ],function ($) {
        $(".click_show.faq").click(function(){
            $(this).toggleClass("active");
            $(".content_faq").toggle('');
        });
    });
</script>
