<?php
/** @var \Amasty\AdvancedReview\Block\Images $block */
$collection = $block->getCollection();
?>

<?php if ($collection->getSize()): ?>
    <div id="amreview-id-<?= /* @noEscape */ $block->getReviewId() ?>"
         class="amreview-images <?= /* @noEscape */ $collection->getSize() >= 3 ? '-slider' : '' ?>"
         data-amreview-js="review-images">
        <?php foreach ($collection as $item): ?>
            <div class="amreview-slider-item" data-amreview-js="slider-item">
                <a href="<?= $block->escapeHtml($block->getFullImagePath($item)) ?>"
                   class="amreview-image-link fancybox"
                   data-fancybox="amreview-image-group-<?= /* @noEscape */ $block->getReviewId() ?>">
                    <img class="amreview-image"
                         src="<?= /* @noEscape */ $block->getFullImagePath($item);?>"
                         title="<?= $block->escapeHtml(__('Review image')); ?>"
                         alt="<?= $block->escapeHtml(__('Review image')); ?>"
                    />
                </a>
            </div>
        <?php endforeach; ?>
    </div>

    <script>
		require([
			"jquery",
			"Amasty_AdvancedReview/vendor/fancybox/jquery.fancybox.min"
		], function ($) {
			$('[data-amreview-js="review-images"]').find('a').fancybox({
				loop: true,
				toolbar: false,
				baseClass: 'amrev-fancybox-zoom'
			});
		});
    </script>
<?php endif;?>
