<?php
/**
 * @var \Amasty\AdvancedReview\Block\Summary $block
 * @var \Magento\Framework\Escaper $escaper
 */

// phpcs:ignoreFile
$rating = $block->getRatingSummary() ? $block->getRatingSummary() : 0;
$count = $block->getReviewsCount();
$ratingSummary = $block->getRatingSummaryValue() ? number_format($block->getRatingSummaryValue(),1) : 0;
?>

<div class="amreview-summary-info">
    <p class="amreview-summary"><?= $escaper->escapeHtml($ratingSummary) ?></p>
    <div class="amreview-rating-wrapper">
        <div class="amstars-rating-container"
            <?php $stars = $block->getRatingSummaryValue(); ?>
             title="<?= $escaper->escapeHtml($stars > 1 ? __('%1 stars', $stars) : __('%1 star', $stars)) ?>">
            <p class="amstars-stars" style="width:<?= $escaper->escapeHtml($rating); ?>%">
                <span class="hidden"><?= $escaper->escapeHtml($rating); ?>%</span>
            </p>
        </div>
    </div>
</div>
