<?php

/** @var \Satp\Event\Block\EventList $block */
$eventList = $block->getEventCollection();
$eventCount = $eventList->getTotalCount();
?>

<?php if ($eventList->getTotalCount() > 0): ?>
    <div class="block event-manager">
        <div class="block-title">
            <h3><?= __('New Events') ?></h3>
        </div>
        <div class="event-list-wrapper">
            <div class="event-list">
                <?php foreach ($eventList as $eventListItem):?>
                    <div class="event-list-item">
                        <div>
                            <a class="event-list-image-link"
                               href="<?= $block->escapeUrl($block->getEventManagerUrl($eventListItem->getEntityId()))?>">
                                <img src="<?= $block->escapeHtml($block->
                                getThumbnailImageURL($eventListItem->getThumbnailImage()));?>"
                                     alt="<?= $block->escapeHtml($eventListItem->getTitle());?>"/>
                            </a>
                            <div class="event-list-heading-date">
                                <div class="event-list-heading ellipsis">
                                    <a class="action view event-list-title"
                                       href="<?=$block->escapeUrl($block->getEventManagerUrl($eventListItem->getEntityId()))?>">
                                        <?=$block->escapeHtml($eventListItem->getTitle());?>
                                    </a>
                                </div>
                                <div class="event-list-period">
                            <span class="event-list-start-date">
                                <?= $block->escapeHtml($block->changeDateFormat($eventListItem->getStartDate()));?>
                            </span>
                                    <span>~</span>
                                    <span class="event-list-end-date">
                                <?= $block->escapeHtml($block->changeDateFormat($eventListItem->getEndDate()));?>
                            </span>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
    <script>
        require(['jquery', 'js/plugins/slick/slick'], function ($) {
            $('.event-list-wrapper .event-list').slick({
                dots:false,
                infinite: false,
                slidesToShow: 3,
                slidesToScroll: 3,
                prevArrow: false,
                nextArrow: false,
                responsive: [
                    {
                        breakpoint: 768,
                        settings: {
                            dots: false,
                            slidesToShow: 1.3,
                            slidesToScroll: 1,
                        }
                    },
                ]
            })
        });
    </script>
<?php else: ?>
    <div class="event-list-empty">
        <!--
        <?= $block->escapeHtml(__('No Event found!')); ?>
        -->
    </div>
<?php endif ?>
