<?php
/**
 * @author Eguana Team
 * @copyriht Copyright (c) 2020 Eguana {http://eguanacommerce.com}
 * Created by PhpStorm
 * User: raheel
 * Date: 09/11/20
 * Time: 08:00 PM
 */

/** @var \Magento\Framework\View\Element\Template $block */
?>
<div class="email-actions">
    <h5><?= $block->escapeHtml(__('Event Reservation')); ?></h5>
    <p><?= $block->escapeHtml(__('The event reservation is canceled.')); ?></p>
</div>
