<?php
/**
 * @author Eguana Team
 * @copyright Copyright (c) 2020 Eguana {http://eguanacommerce.com}
 * Created by PhpStorm
 * User: david
 * Date: 2020/08/12
 * Time: 10:46 AM
 */

/**
 * @var \Magento\Payment\Block\Info $block
 * @see \Magento\Payment\Block\Info
 */
?>
<dl class="payment-method">
    <?php if ($block->escapeHtml($block->getEcpayPaymentMethod())): ?>
    <dt class="title"><?= $block->escapeHtml($block->getEcpayPaymentMethod()) ?></dt>
    <?php else: ?>
    <dt class="title"><?= $block->escapeHtml($block->getMethod()->getTitle()) ?></dt>
    <?php endif; ?>
    <?php if ($block->getInstructions()): ?>
        <dd class="content"><?= /* @noEscape */ nl2br($block->escapeHtml($block->getInstructions())) ?></dd>
    <?php endif; ?>
</dl>
