<?php
/**
 * @author Eguana Team
 * @copyright Copyright (c) 2020 Eguana {http://eguanacommerce.com}
 * Created by PhpStorm
 * User: umer
 * Date: 10/8/20
 * Time: 5:25 PM
 */
/** @var \Eguana\SocialLogin\ViewModel\AddFriends $viewModel */

$viewModel = $block->getData('add_friend_view_model');
$helper = $this->helper('Eguana\SocialLogin\Helper\Data');
?>
<?php if (($viewModel->getEnabledInFrontend()) && ($viewModel->getStoreId() != '8')):?>
    <?php if ($viewModel->getEnabledLine()):?>
        <div class="line-add-friend">
            <p class="note">
                <?= $block->escapeHtml(__('Join the Laneige LINE official account')) ?><br />
                <?= $block->escapeHtml(__('You can enquire about your point information!')) ?>
            </p>
            <?php if ($viewModel->getLineBannerEnabled()): ?>
                <a href="<?= $block->escapeUrl($viewModel->lineAddFriendLink()) ?>" target="_blank" class="banner-desktop">
                    <div class="line-banner">
                        <div class="marketing-message">
                            <div class="content"><?= $block->escapeHtml($viewModel->getLineMarketingMessage()) ?></div>
                            <img class="line-logo" alt="line logo"
                                 src="<?= $block->escapeUrl($viewModel->getLineLogoUrl()) ?>"/>
                        </div>
                        <div class="qr-code">
                            <img class="line-qr-code" alt="line qr code"
                                 src="<?= $block->escapeUrl($viewModel->getLineQRCodeUrl()) ?>"/>
                        </div>
                    </div>
                </a>
                <div class="banner-mobile">
                    <?php
                    $lineBannerBlockId = $helper->getLineBannerCMSBlockId();
                    $lineBannerBlock = $this->getLayout()
                        ->createBlock('Magento\Cms\Block\Block')
                        ->setBlockId($lineBannerBlockId)
                        ->toHtml();
                    ?>
                    <?= $lineBannerBlock ?>
                </div>
            <?php else: ?>
                <a href="<?= $block->escapeUrl($viewModel->lineAddFriendLink()) ?>" target="_blank">
                    <img src="<?= $block->escapeUrl("https://scdn.line-apps.com/n/line_add_friends/btn/zh-Hant.png") ?>"
                         alt="<?= $block->escapeHtml(__('Add as friend')) ?>" height="36" border="0">
                </a>
            <?php endif; ?>
        </div>
    <?php endif; ?>
<?php elseif (($viewModel->getEnabledInFrontend()) && ($viewModel->getStoreId() == '8')): ?>
<?php if ($viewModel->getEnabledFacebook()):?>
        <div class="facebook-add-friend">
            <p class="note">
                <?= $block->escapeHtml(__('Join the VN Laneige FACEBOOK official account')) ?><br />
                <?= $block->escapeHtml(__('You can enquire about your point information!')) ?>
            </p>
            <a href="<?= $block->escapeUrl($viewModel->facebookAddFriendLink()) ?>" target="_blank">
                <img src="<?= $this->getViewFileUrl('Eguana_SocialLogin::images/fb-add-friends.jpg'); ?>" alt="<?= $block->escapeHtml(__('Add as friend')) ?>" height="36" border="0">
            </a>
        </div>
    <?php endif; ?>
<?php endif; ?>
