<?php
/**
 * @author Eguana Team
 * @copyriht Copyright (c) 2020 Eguana {http://eguanacommerce.com}
 * Created by PhpStorm
 * User: arslan
 * Date: 17/6/20
 * Time: 08:00 PM
 */

/**
 * @var \Eguana\Faq\Block\Faq $block
 */

$categoryData = $block->getCategoryOptionArray();
$faqData = $block->getFaqBindData();
$searchUrl = $block->getSearchUrl();
?>

<div class="faqs">
    <div class="search-block">
        <form class="form" action="<?= $block->escapeUrl($searchUrl)?>">
            <div class="field">
                <label class="label" for="faqSearchVal">
                    <span><?= /* @escapeNotVerified */ $block->escapeHtml(__('Search')) ?></span>
                </label>
                <div class="control">
                    <input type="text"
                           class="input-text required-entry faqSearchVal"
                           id="faqSearchVal"
                           name="faqSearchVal"
                           placeholder="<?= /* @escapeNotVerified */ $block->escapeHtmlAttr(__('Search')) ?>"
                           value="<?= $block->escapeHtmlAttr($block->getRequest()->getParam('faqSearchVal'))?>"/>
                    <button type="button" class="action links" onclick="var search_val = document.getElementById('faqSearchVal'); search_val.value='';"><span class="remove"><?=$block->escapeHtml(__('Remove'))?></span></button>
                </div>
                <div class="actions">
                    <button type="submit" class="button action search primary faqSearchBtn" title="search">
                        <span><?=$block->escapeHtml(__('Search'))?></span>
                    </button>
                </div>
            </div>
        </form>
    </div>
    <?php foreach ($categoryData as $key => $value):?>
        <?php if (isset($faqData[$key]) && count($faqData[$key]) > 0):?>
            <div class="block">
                <div class="item title" data-role="tab-collapsible">
                    <strong class="switch"
                            role="heading"
                            data-toggle="trigger"
                            data-role="tab-title"
                            aria-level="2">
                        <?= $block->escapeHtml($value) ?>
                    </strong>
                </div>
                <div class="item content" data-role="tab-content">
                    <div class="lists"
                         data-mage-init='{"accordion":{
                             "collapsible": true,
                             "animate": {"duration": 300},
                             "openedState": "_active",
                             "active": false,
                             "multipleCollapsible": true}}'>
                        <?php foreach ($faqData[$key] as $faq):?>
                            <div class="list">
                                <div data-role="collapsible">
                                    <div class="title" data-role="title">
                                        <span><?= $block->escapeHtml($faq->getTitle()) ?></span>
                                    </div>
                                </div>
                                <div class="content" data-role="content">
                                    <?= /* @noEscape */ $block->descriptionFilter($faq->getDescription()) ?>
                                </div>
                            </div>
                        <?php endforeach;?>
                    </div>
                </div>
            </div>
        <?php endif;?>
    <?php endforeach;?>
</div>
