<?php
/**
 * Created by Eguana Team.
 * User: sonia
 * Date: 7/21/20
 * Time: 10:41 AM
 */

/** @var \Amore\GaTagging\Block\GaTagging $block */
?>
<script>
    //회원가입
    var AP_JOIN_NAME = "<?= $block->escapeHtml($block->getJoinName()) ?>";
</script>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "<?= /* @noEscape */  $block->getComponentName()?>": {
                    "component": "Amasty_SalesRuleWizard/js/steps/apply_settings",
                    "formName": "<?= /* @noEscape */ $block->getData('config/formName') ?>"
                }
            }
        }
    }
}
</script>
