<?php
/**
 * Created by Eguana Team.
 * User: sonia
 * Date: 7/19/20
 * Time: 9:15 AM
 */
?>
<?php
/** @var \Amore\GaTagging\Block\GaTagging $block */
$currentProduct = $block->getCurrentProduct();
?>
<script>
    //상품상세
    var AP_PRD_NAME = "<?= $block->escapeHtml($currentProduct->getName())?>";
    var AP_PRD_CODE = "<?= $block->escapeHtml($currentProduct->getSku())?>";
    var AP_PRD_PRICE = "<?= $block->escapeHtml($currentProduct->getFinalPrice())?>";
    var AP_PRD_BRAND = "<?= $block->escapeHtml(__('Laneige'))?>";
    var AP_PRD_CATEGORY = "<?= $block->escapeHtml($block->getProductCategory($currentProduct))?>";
</script>
