<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
/** @var \Magento\Bundle\Pricing\Render\FinalPriceBox $block */

/** @var \Magento\Bundle\Pricing\Price\FinalPrice $finalPriceModel */
$finalPriceModel = $block->getPrice();
$minimalPrice = $finalPriceModel->getMinimalPrice();
$maximalPrice = $finalPriceModel->getMaximalPrice();
/** ex: \Magento\Bundle\Pricing\Price\BundleRegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $regularPriceModel */
$regularPriceModel = $block->getPriceType('regular_price');
$maximalRegularPrice = $regularPriceModel->getMaximalPrice();
$minimalRegularPrice = $regularPriceModel->getMinimalPrice();
$helper = $this->helper(\Eguana\CustomCatalog\Helper\Data::class);
$schema = ($block->getZone() == 'item_view') ? true : false;
?>
<?php if ($block->getSaleableItem()->getPriceView()): ?>
    <p class="minimal-price">
        <?php /* @escapeNotVerified */ echo $block->renderAmount($minimalPrice, [
            'display_label'     => $block->escapeHtml(__('As low as')),
            'price_id'          => $block->getPriceId('from-'),
            'include_container' => true
        ]); ?>
        <?php if ($minimalPrice < $minimalRegularPrice): ?>

            <?php if($discountedPrice = $helper->getDiscountPriceForSapt($minimalRegularPrice->getValue(), $minimalPrice->getValue())):?>
                <span class="discount-label">
                        <?= $discountedPrice ?>%
                </span>
            <?php endif;?>
            <span class="old-price">
                <?php /* @escapeNotVerified */ echo $block->renderAmount($minimalRegularPrice, [
                    'display_label'     => $block->escapeHtml(__('Regular Price')),
                    'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
                    'include_container' => true,
                    'skip_adjustments'  => true
                ]); ?>
            </span>
        <?php endif ?>
    </p>
<?php else: ?>
    <?php if ($block->showRangePrice()): ?>
        <p class="price-from">
            <?php if ($minimalPrice < $minimalRegularPrice): ?>
                <?php if($discountedPrice = $helper->getDiscountPriceForSapt($minimalRegularPrice->getValue(), $minimalPrice->getValue()) ):?>
                    <span class="discount-label">
                        <?= $discountedPrice?>%
                    </span>
                <?php endif;?>
                <span class="old-price">
                    <?php /* @escapeNotVerified */ echo $block->renderAmount($minimalRegularPrice, [
                        'display_label'     => $block->escapeHtml(__('Regular Price')),
                        'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
                        'price_type'        => 'oldPrice',
                        'include_container' => true,
                        'skip_adjustments'  => true
                    ]); ?>
                </span>
            <?php endif ?>
            <?php /* @escapeNotVerified */ echo $block->renderAmount($minimalPrice, [
                'price_id'          => $block->getPriceId('from-'),
                'price_type'        => 'minPrice',
                'include_container' => true
            ]); ?>
            <span class="final-price-bundle" style="display: none">
                <?php /* @escapeNotVerified */ echo $block->renderAmount($maximalPrice, [
                    'price_id'          => $block->getPriceId('to-'),
                    'price_type'        => 'finalPriceBundle',
                    'include_container' => true
                ]); ?>
            </span>
        </p>
        <p class="price-to">
	        <span class="price-space"></span>
            <?php if ($maximalPrice < $maximalRegularPrice): ?>
                <?php if($discountedPrice = $helper->getDiscountPriceForSapt($minimalRegularPrice->getValue(), $maximalRegularPrice->getValue())):?>
                    <span class="discount-label">
                        <?= $discountedPrice?>%
                    </span>
                <?php endif;?>
            <?php endif ?>
            <?php /* @escapeNotVerified */ echo $block->renderAmount($maximalPrice, [
                'price_id'          => $block->getPriceId('to-'),
                'price_type'        => 'maxPrice',
                'include_container' => true
            ]); ?>
        </p>
    <?php else: ?>
        <p class="bundle-regular-price">
        <?php if ($minimalPrice < $minimalRegularPrice): ?>
            <?php if($discountedPrice = $helper->getDiscountPriceForSapt($minimalRegularPrice->getValue(), $minimalPrice->getValue())):?>
                <span class="discount-label">
                    <?= $discountedPrice?>%
                </span>
            <?php endif;?>
            <?php /* @escapeNotVerified */ echo $block->renderAmount($minimalPrice, [
                'price_id'          => $block->getPriceId('product-price-'),
                'include_container' => true,
                'price_type'        => 'finalPrice',
                'schema' => $schema
            ]); ?>
            <span class="old-price">
                <?php /* @escapeNotVerified */ echo $block->renderAmount($minimalRegularPrice, [
                    'display_label'     => $block->escapeHtml(__('Regular Price')),
                    'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
                    'include_container' => true,
                    'skip_adjustments'  => true
                ]); ?>
            </span>
        <?php else: ?>
            <?php /* @escapeNotVerified */ echo $block->renderAmount($minimalPrice, [
                'price_id'          => $block->getPriceId('product-price-'),
                'include_container' => true
            ]); ?>
        <?php endif ?>
    <?php endif ?>
    </p>
<?php endif ?>
