<?php /** @var \Magento\Framework\View\Element\AbstractBlock $block */ ?>
<?php
/** @var \Amasty\ShopbyFilterAnalytics\ViewModel\FilterAnalytics $filterAnalytics */
$filterAnalytics = $block->getData('filter_analytics');
?>

<?php if ($filterAnalytics->isNeedCollectStatistics()): ?>
    <script type="text/x-magento-init">
            {
                "*": {
                    "Amasty_ShopbyFilterAnalytics/js/filterAnalytics": {
                        "filterData": <?= /** @noEscape */ $filterAnalytics->getJsonFilterOptions() ?>,
                        "requestUrl": "<?= /** @noEscape */ $filterAnalytics->getRequestUrl() ?>"
                    }
                }
            }
    </script>
<?php endif; ?>

