<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;
/** @var  $block \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer */
/** @var \Magento\Sales\Model\Order\Item $_item */
/** @var \Sapt\Sales\ViewModel\Product $viewModel */
/** @var \Magento\Framework\Pricing\Helper\Data $priceHelper */
$_item = $block->getItem();
$shippingMethod = $_item->getOrder()->getShippingDescription();
$product = $_item->getProduct();
$_order = $_item->getOrder();
$layoutHander = $block->getRequest()->getFullActionName();
$viewModel = $block->getData('view_model');
?>
<tr id="order-item-row-<?= (int) $_item->getId() ?>" class="item-info">
    <td class="col item" data-th="<?= $block->escapeHtmlAttr(__('Product Name')) ?>">
        <a href="<?= $block->escapeUrl($product->getUrlModel()->getUrl($product)) ?>"
           title="<?= $block->escapeHtmlAttr($product->getName()) ?>"
           tabindex="-1"
           class="product-item-photo">
            <?= $viewModel->getImage($product, 'cart_page_product_thumbnail')->toHtml() ?>
        </a>
        <div class="product-item-details">
            <strong class="product-item-name">
                <a href="<?= $block->escapeUrl($product->getUrlModel()->getUrl($product)) ?>"><?= $block->escapeHtml($product->getName()) ?></a>
            </strong>
            <?php if($product->getTypeId() != 'bundle'){ ?>
                <?php if ($_options = $block->getItemOptions()) :?>
                    <dl class="item-options">
                        <?php foreach ($_options as $_option) :?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <dd>
                                <span class="label"><?= $block->escapeHtml($_option['label']) ?>:</span>
                                <?php if (!$block->getPrintStatus()) : ?>
                                    <?php if (isset($_formatedOptionValue['full_view'])) :?>
                                        <?= $block->escapeHtml($_formatedOptionValue['full_view']) ?>
                                    <?php else :?>
                                        <?= $block->escapeHtml($_formatedOptionValue['value'], ['a', 'img']) ?>
                                    <?php endif; ?>
                                <?php else: ?>
                                    <?= $block->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value'])) ?>
                                <?php endif; ?>
                            </dd>
                        <?php endforeach; ?>
                    </dl>
                <?php endif;?>
            <?php } ?>
            <?php if ($_item->getRowTotal() == $_item->getDiscountAmount()): ?>
                <?php $priceHelper = $this->helper(\Magento\Framework\Pricing\Helper\Data::class); ?>
                <?= $priceHelper->currency(0) ?>
            <?php else: ?>
                <?= $block->getItemPriceHtml() ?><span class="product-qty-ordered">
                <?php if($layoutHander == 'sales_order_view'): ?>
                    <?= __(' / ') ?> <?= __("QTY %1", (int)$_item->getQtyOrdered()) ?></span>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    </td>
    <?php if (!$_item->getIsFreeGift()): ?>
    <td class="col actions" data-th="<?= $block->escapeHtmlAttr(__('Actions')) ?>">
        <?php if (!$block->getPrintStatus() && !$viewModel->getPrintStatus($block)) : ?>
            <a href="#" class="btn secondary review" data-order-item-id="<?= $_item->getId() ?>"><?= __('Review') ?></a>
            <?php $postParams = $viewModel->getPostData($product, $block); ?>
            <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($product->getSku()) ?>" action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
                <?php $optionsData = $viewModel->getOptionsData($product); ?>
                <?php foreach ($optionsData as $optionItem): ?>
                    <input type="hidden"
                           name="<?= $block->escapeHtml($optionItem['name']) ?>"
                           value="<?= $block->escapeHtml($optionItem['value']) ?>">
                <?php endforeach; ?>
                <input type="hidden" name="product" value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                <?= $block->getBlockHtml('formkey') ?>
                <button type="submit"
                        clicktext="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                        formtext="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                        title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                        class="action tocart primary">
                    <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                </button>
            </form>
            <?= /* @noEscape */ $viewModel->getAddReviewForm($_item, $block) ?>
        <?php endif; ?>
    </td>
    <?php endif; ?>
</tr>
