<div id="popup-modal" class="popup_cookie">
    <p>This is popup cookie</p>
</div>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
            };

            var popup = modal(options, $('#popup-modal'));
            if (!localStorage.getItem('popupShown')) {
                $('#popup-modal').modal('openModal');
                localStorage.setItem('popupShown', true);
            };
            if ($('.modal-inner-wrap').find('.popup_cookie')){
                $('.modal-inner-wrap').addClass('modal_cookie')
            }
        }
    );

</script>
