<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Sales\Block\Order\Info */ ?>
<?php /** @var $viewModel \Eguana\GWLogistics\ViewModel\CvsAddress */
    $viewModel = $block->getViewModel();
?>
<?php $_order = $block->getOrder() ?>
<div class="block block-order-details-view">
    <div class="block-title">
        <strong><?= $block->escapeHtml(__('Order Information')) ?></strong>
    </div>
    <div class="block-content">
        <?php if (!$_order->getIsVirtual()) : ?>
            <div class="box box-order-shipping-address">
                <strong class="box-title"><span><?= $block->escapeHtml(__('Shipping Address')) ?></span></strong>
                <?php if (!$viewModel->hasCvsLocation($_order)) : ?>
                <div class="box-content">
                    <address><?= /* @noEscape */ $block->getFormattedAddress($_order->getShippingAddress()) ?></address>
                </div>
                <?php else : ?>
                <div class="box-content">
                    <div><?= $block->escapeHtml($_order->getShippingAddress()->getLastname() . ' ' . $_order->getShippingAddress()->getFirstname()) ?></div>
                    <div><?= $block->escapeHtml($_order->getShippingAddress()->getTelephone()) ?></div>
                </div>
                <?php $cvsStoreData = $viewModel->getCvsStoreData($_order) ?>
                <div class="box-subtitle order-shipping-primary-address">
                    <?= $block->escapeHtml(__($cvsStoreData->getLogisticsSubType())) ?> <?= $block->escapeHtml($cvsStoreData->getCvsStoreName()) ?>
                </div>
                <div class="box-content">
                    <div>
                        <?= $block->escapeHtml($cvsStoreData->getCvsAddress()) ?>
                    </div>
                    <div><?= $block->escapeHtml($cvsStoreData->getCvsTelephone()) ?></div>
                </div>
                <?php endif; ?>
            </div>

            <div class="box box-order-shipping-method">
                <strong class="box-title">
                    <span><?= $block->escapeHtml(__('Shipping Method')) ?></span>
                </strong>
                <div class="box-content">
                <?php if ($_order->getShippingDescription()) : ?>
                    <?= $block->escapeHtml($_order->getShippingDescription()) ?>
                <?php else : ?>
                    <?= $block->escapeHtml(__('No shipping information available')) ?>
                <?php endif; ?>
                </div>
            </div>
        <?php endif; ?>

        <div class="box box-order-billing-address">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Billing Address')) ?></span>
            </strong>
            <div class="box-content">
                <address><?= /* @noEscape */ $block->getFormattedAddress($_order->getBillingAddress()) ?></address>
            </div>
        </div>
        <div class="box box-order-billing-method">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Payment Method')) ?></span>
            </strong>
            <div class="box-content">
                <?= $block->getPaymentInfoHtml() ?>
            </div>
        </div>
    </div>
</div>
