
<style>
    .navigation{
        position: fixed;
        top: 0; left: 0;
    }
</style>
<nav class="navigation" data-action="navigation" >
    <h2><b>디자인 시안 (Images)</b></h2>
    <ul id="menu" data-mage-init='{"menu":{"responsive":true, "expanded":true, "delay": 200, "position":{"my":"left top","at":"left+10 top+30"}}}'>
        <li class="level0 level-top parent ui-menu-item">카테고리
            <ul class="level0 submenu ui-menu ui-widget ui-widget-content ui-corner-all">
                <li class="ui-menu-item"><a href="#">메인</a></li>
                <li class="ui-menu-item"><a href="#">회사소개</a></li>
            </ul>
        </li>
        <li class="level0 level-top ui-menu-item">주문
            <ul class="level0 submenu ui-menu ui-widget ui-widget-content ui-corner-all">
                <li class="ui-menu-item">
                    <a href="#">결제</a>
                </li>
            </ul>
        </li>
    </ul>
</nav>
<hr style= "margin-bottom:100px;"></hr>
