<?php
/** @var \CJ\CouponCustomer\Block\Coupon\Index $block */
?>
<?php
$coupons = $block->getRuleCollection()->load();
$items = $coupons->getItems();
?>
<div class="block-title">
    <strong><?= $block->escapeHtml(__('Coupon List')); ?></strong>
</div>
<div class="table-wrapper table-coupon">
    <table class="data table table-coupon-child">
        <tbody>
        <tr>
            <th class="col-title"><?= __('Coupon name') ?></th>
            <th class="col-title"><?= __('The expiration date') ?></th>
            <th class="col-title"><?= __('Code') ?></th>
        </tr>
        <?php foreach ($items as $coupon) : ?>
            <tr>
                <td>
                    <?php echo $coupon['name']; ?>
                </td>
                <td>
                    <?php echo $coupon['to_date'] == null ? 'none' : $coupon['to_date']; ?>
                </td>
                <td>
                    <div class="coupon-button">
                        <button id="<?php echo $coupon['code'] ?>"> <?= $block->escapeHtml(__('Copy')) ?></button>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php if ($block->getPagerHtml()) : ?>
    <div class="ticket-toolbar toolbar bottom table-bottom"><?= $block->getPagerHtml(); ?></div>
<?php endif ?>
<script type="text/x-magento-init">
    {
        "*": {
            "copy-coupon-code":{}
        }
    }
</script>



