<?php
$helper = $this->helper(\CJ\SeoMetaData\Helper\Data::class);
if ($helper->getEnable()) :
    ?>
    <meta property="twitter:card" content="website" />
    <meta property="twitter:title"
          content="韓國草本護膚知名品牌最新推介 | 蘭芝(Laneige) 香港官方線上網站" />
    <meta property="twitter:image"
          content="<?= $block->escapeUrl($block->getViewFileUrl('Eguana_Theme::images/og.png')) ?>" />
    <meta property="twitter:description"
          content="韓國著名草本護膚天然成分化妝品品牌 | 點此確認蘭芝以創新秘方科學技術研發之新品，與您一同打造高雅肌膚內在美 | Laneige Hong Kong" />
    <meta property="twitter:url" content="<?= $block->escapeUrl($block->getCurrentUrl()) ?>" />
<?php
endif;
?>
