<?php
$helper = $this->helper(\CJ\SeoMetaData\Helper\Data::class);
if ($helper->getEnable()) :
    ?>
    <meta property="twitter:card" content="website" />
    <meta property="twitter:title"
          content="韓國草本護膚暢銷商品網頁 | 蘭芝(Laneige) 香港官方線上網站" />
    <meta property="twitter:image"
          content="<?= $block->escapeUrl($block->getViewFileUrl('Eguana_Theme::images/og.png')) ?>" />
    <meta property="twitter:description"
          content="韓國著名草本護膚天然成分化妝品品牌 | 點此查看蘭芝深受歡迎的暢銷排行榜—護膚品、美妝、經典奢華系列和男士產品 | Laneige Hong Kong" />
    <meta property="twitter:url" content="<?= $block->escapeUrl($block->getCurrentUrl()) ?>" />
<?php
endif;
?>
