<?php
$helper = $this->helper(\CJ\SeoMetaData\Helper\Data::class);
if ($helper->getEnable()) :
?>
<meta property="twitter:card" content="website" />
<meta property="twitter:title"
      content="蘭芝香港尊爵會員專屬購物車 | 蘭芝(Laneige) 香港官方線上網站" />
<meta property="twitter:image"
      content="<?= $block->escapeUrl($block->getViewFileUrl('Eguana_Theme::images/og.png')) ?>" />
<meta property="twitter:description"
      content="韓國著名草本護膚化妝品品牌 | 隨時隨地、無時無刻，網上購物輕鬆買，點選購物車確認您的商品品項及滿額禮遇吧！ | 蘭芝(Laneige) Hong Kong" />
<meta property="twitter:url" content="<?= $block->escapeUrl($block->getCurrentUrl()) ?>" />
<?php
    endif;
?>
