<?php
$helper = $this->helper(\CJ\SeoMetaData\Helper\Data::class);
if ($helper->getEnable()) :
    ?>
    <meta property="og:type" content="website" />
    <meta property="og:title"
          content="私人隱私政策及個資收集聲明 | 蘭芝(Laneige) 香港官方線上網站" />
    <meta property="og:image"
          content="<?= $block->escapeUrl($block->getViewFileUrl('Eguana_Theme::images/og.png')) ?>" />
    <meta property="og:description"
          content="韓國著名草本護膚化妝品品牌 | 由此確認消費者隱私權保護聲明，讓蘭芝香港幫您把關網上購物安全，與您一同安心購物 | Laneige Hong Kong" />
    <meta property="og:url" content="<?= $block->escapeUrl($block->getCurrentUrl()) ?>" />
<?php
endif;
?>
