<?php
$helper = $this->helper(\CJ\SeoMetaData\Helper\Data::class);
if ($helper->getEnable()) :
    ?>
    <meta property="twitter:card" content="website" />
    <meta property="twitter:title"
          content="蘭芝香港獨享尊爵會員計劃 | 蘭芝(Laneige) 香港官方線上網站" />
    <meta property="twitter:image"
          content="<?= $block->escapeUrl($block->getViewFileUrl('Eguana_Theme::images/og.png')) ?>" />
    <meta property="twitter:description"
          content="韓國著名草本護膚高雅化妝品品牌 | 多重會員權益，尊爵會員的專屬服務，加入會員讓蘭芝與您一同打造肌膚內在美 | Laneige Hong Kong" />
    <meta property="twitter:url" content="<?= $block->escapeUrl($block->getCurrentUrl()) ?>" />
<?php
endif;
?>
