<?php
$helper = $this->helper(\CJ\SeoMetaData\Helper\Data::class);
if ($helper->getEnable()) :
    ?>
    <meta property="og:type" content="website" />
    <meta property="og:title"
          content="蘭芝香港官方網站條款及細則 || Laneige Hong Kong Official" />
    <meta property="og:image"
          content="<?= $block->escapeUrl($block->getViewFileUrl('Eguana_Theme::images/og.png')) ?>" />
    <meta property="og:description"
          content="韓國著名草本護膚化妝品品牌 | 在此確認網站服務挑款及細則等相關說明，期望蘭芝香港能帶給您一趟美好的煥膚之旅 | Laneige Hong Kong" />
    <meta property="og:url" content="<?= $block->escapeUrl($block->getCurrentUrl()) ?>" />
<?php
endif;
?>
