<?php
$helper = $this->helper(\CJ\SeoMetaData\Helper\Data::class);
if ($helper->getEnable()) :
?>
<meta property="og:type" content="website" />
<meta property="og:title"
      content="會員登入﹡蘭芝香港尊爵會員您好！ | 蘭芝(Laneige) 香港官方線上網站" />
<meta property="og:image"
      content="<?= $block->escapeUrl($block->getViewFileUrl('Eguana_Theme::images/og.png')) ?>" />
<meta property="og:description"
      content="蘭芝 香港官方網站，護膚、美妝、男性保養 韓國著名草本護膚化妝品品牌，登入會員隨時查看您的訂購資訊和會員優惠 | Laneige Hong Kong" />
<meta property="og:url" content="<?= $block->escapeUrl($block->getCurrentUrl()) ?>" />
<?php
endif;
?>
