<?php
$helper = $this->helper(\CJ\SeoMetaData\Helper\Data::class);
if ($helper->getEnable()) :
?>
<meta property="twitter:card" content="website" />
<meta property="twitter:title"
      content="會員登入 | LANEIGE香港官方網上商店" />
<meta property="twitter:image"
      content="<?= $block->escapeUrl($block->getViewFileUrl('Eguana_Theme::images/og.png')) ?>" />
<meta property="twitter:description"
      content="歡迎來到蘭芝香港官方網站&線上購物！註冊會員，即可獨享尊爵會員優惠，與蘭芝一起打造專屬於你的美麗與自信 | Laneige Hong Kong" />
<meta property="twitter:url" content="<?= $block->escapeUrl($block->getCurrentUrl()) ?>" />
<?php
endif;
?>
