<?php
$helper = $this->helper(\CJ\SeoMetaData\Helper\Data::class);
if ($helper->getEnable()) :
?>
<meta property="og:type" content="website" />
<meta property="og:title"
      content="忘記密碼﹡簡單幾步驟 重啟與您的專屬連結 | 蘭芝(Laneige) 香港官方線上網站" />
<meta property="og:image"
      content="<?= $block->escapeUrl($block->getViewFileUrl('Eguana_Theme::images/og.png')) ?>" />
<meta property="og:description"
      content="韓國著名草本護膚化妝品品牌 | 忘記密碼了嗎？別擔心，輸入您的資料，讓蘭芝跟您一起找回密碼與所有變美的連結！ | 蘭芝(Laneige) Hong Kong" />
<meta property="og:url" content="<?= $block->escapeUrl($block->getCurrentUrl()) ?>" />
<?php
endif;
?>
