<?php
$helper = $this->helper(\CJ\SeoMetaData\Helper\Data::class);
if ($helper->getEnable()) :
?>
<meta property="og:type" content="website" />
<meta property="og:title"
      content="香港蘭芝現正最新熱門活動 | 蘭芝(Laneige) 香港官方線上網站" />
<meta property="og:image"
      content="<?= $block->escapeUrl($block->getViewFileUrl('Eguana_Theme::images/og.png')) ?>" />
<meta property="og:description"
      content="韓國著名草本護膚化妝品品牌 | 為蘭芝香港尊爵會員量身打造，一同查看絕不能錯過的線上官網獨享禮遇與蘭芝香港最新活動 | Laneige Hong Kong" />
<meta property="og:url" content="<?= $block->escapeUrl($block->getCurrentUrl()) ?>" />
<?php
endif;
?>
