<?php
$helper = $this->helper(\CJ\SeoMetaData\Helper\Data::class);
if ($helper->getEnable()) :
    ?>
    <meta property="twitter:card" content="website" />
    <meta property="twitter:title"
          content="蘭芝香港官方線上網站﹡全站導覽 | Laneige Hong Kong Official" />
    <meta property="twitter:image"
          content="<?= $block->escapeUrl($block->getViewFileUrl('Eguana_Theme::images/og.png')) ?>" />
    <meta property="twitter:description"
          content="韓國著名草本護膚天然成分化妝品品牌 | 想購物卻沒時間？我來幫您節省時間！輕鬆一點、快速瀏覽蘭芝香港官方線上網站 | Laneige Hong Kong" />
    <meta property="twitter:url" content="<?= $block->escapeUrl($block->getCurrentUrl()) ?>" />
<?php
endif;
?>
