<?php
$helper = $this->helper(\CJ\SeoMetaData\Helper\Data::class);
if ($helper->getEnable()) :
?>
<meta property="twitter:card" content="website" />
<meta property="twitter:title"
      content="香港島實體門市﹡服務專櫃查詢 | 蘭芝(Laneige) 香港官方線上網站" />
<meta property="twitter:image"
      content="<?= $block->escapeUrl($block->getViewFileUrl('Eguana_Theme::images/og.png')) ?>" />
<meta property="twitter:description"
      content="韓國著名草本護膚天然成分化妝品品牌 | 喜愛實體購物的樂趣？由此快速找尋位於您附近的實體據點，立即享受蘭芝高雅的護膚體驗 | Laneige Hong Kong" />
<meta property="twitter:url" content="<?= $block->escapeUrl($block->getCurrentUrl()) ?>" />
<?php
endif;
?>
