<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @var $block \Sapt\Catalog\Block\Freebies
 */
?>
<?php
$currentProduct = $block->getProduct();
if (!$currentProduct instanceof \Magento\Catalog\Model\Product) {
    return;
}
$freebies = $currentProduct->getFreebies();
if (empty($freebies)) {
    return;
}
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$products = $block->getFreebies($freebies);
$i = 0;
$imageDisplayArea = 'product_freebies';
?>

<?php if (!empty($products)): ?>
    <div class="product_freebies products wrapper grid products-grid" data-mage-init='{"listProducts":{}}'>
        <div class="block_title">
            <h3><?= $block->escapeHtml(__('FREEBIES')) ?></h3>
        </div>
        <div class="swiper-container slide_freebies">
            <div class="swiper-wrapper products list items product-items">
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($products as $_product): ?>
                    <div class="item swiper-slide product product-item" data-index="<?= $i ?>">
                        <?php /* @noEscape */ $productSku = $_product->getSku() ?>
                        <div class="product-item-info" data-container="product-grid">
                            <?php
                            $productImage = $block->getImage($_product, $imageDisplayArea);
                            ?>
                            <?php // Product Image ?>
                            <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                               class="product photo product-item-photo"
                               tabindex="-1"
                               ap-click-area="prds-<?= /* @noEscape */ $currentProduct->getName() ?>"
                               ap-click-name="prd click"
                               ap-click-data="<?= /* @noEscape */ $_product->getName() . '/' . $_product->getSku() ?>">
                                <?= $productImage->toHtml() ?>
                            </a>

                            <div class="product details product-item-details">
                                <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                ?>
                                <strong class="product name product-item-name">
                                    <a class="product-item-link"
                                       href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                                       ap-click-area="prds-<?= /* @noEscape */ $currentProduct->getName() ?>"
                                       ap-click-name="prd click"
                                       ap-click-data="<?= /* @noEscape */ $_product->getName() . '/' . $_product->getSku() ?>">
                                        <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                    </a>
                                </strong>
                            </div>
                        </div>

                    </div>
                    <?php $i++; ?>
                <?php endforeach; ?>

            </div>


        </div>
        <div class="swiper-button-prev swiper-button-prev"></div>
        <div class="swiper-button-next swiper-button-next"></div>
    </div>
<?php endif;?>

<script>
    require([
        'jquery',
        'swiper',
    ],function ($,Swiper) {
        if ($('.product_freebies .product-items .item').length > 3) {
            var swiper = new Swiper('.slide_freebies', {
                slidesPerView: 3,
                freeMode: false,
                autoHeight: true,
                direction: 'horizontal',
                loop: false,
                threshold: 30,
                breakpoints: {
                    768: {
                        slidesPerView: 1.3
                    }
                },
                navigation: {
                    nextEl: '.product_freebies .swiper-button-next',
                    prevEl: '.product_freebies .swiper-button-prev'
                }
            });
        }
    });
</script>
