<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @see \Magento\Catalog\Block\Product\View\Description
 */
?>
<?php
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$_product = $block->getProduct();
if (!$_product instanceof \Magento\Catalog\Model\Product) {
    return;
}
?>
<?php if ($_product->getProductLabels()): ?>
    <div class="product_labels">
        <?php echo $_helper->productAttribute($_product, $_product->getProductLabels(), 'product_labels') ?>
    </div>
<?php endif;?>
