<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
$_product = $block->getProduct();
$productImage = $_imagehelper->init($_product, 'category_page_grid')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(72);
$productImageUrl = $productImage->getUrl();
?>
<div class="sticky-product">
    <div class="sticky-product-images">
        <div class="sticky-image">
            <img class="default_image" src="<?php echo $productImageUrl; ?>" alt="<?php echo $productImage->getLabel(); ?>"/>
        </div>
        <div class="sticky-detail">
            <h2 class="product-name"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></h2>
        </div>
    </div>
</div>
<?php if ($_product->isSaleable()): ?>
    <script type="text/javascript">
        require([
            'jquery'
        ], function ($) {
            var p_scrolled = false;
            var offset = $('.box-tocart').offset().top + 400;
            $(window).scroll(function(){
                if(offset < $(window).scrollTop() && !p_scrolled){
                    p_scrolled = true;
                    $(".product-info-main").addClass("sticky");
                    if ($(window).width() < 768) {
                        var mWrapBundle = $('.product-info-main.sticky').find('.bundle-options-wrapper , .field-wrapper-qty');
                        if (!$(".product-info-main-wrapper").hasClass("is_popupcart")) {
                            mWrapBundle.hide();
                        }
                    }
                }
                if(offset >= $(window).scrollTop() && p_scrolled){
                    var mWrapBundle = $('.product-info-main.sticky').find('.bundle-options-wrapper , .field-wrapper-qty');
                    p_scrolled = false;
                    $(".product-info-main").removeClass("sticky");
                    $(".product-info-main-wrapper").removeClass("is_popupcart");
                    if ($(window).width() < 768) {
                        mWrapBundle.show();
                    }
                }

                var mWrapBundle = $('.product-info-main.sticky').find('.bundle-options-wrapper , .field-wrapper-qty');
                var hasSticky = $('.product-info-main').hasClass('sticky');
                if (mWrapBundle.is(":visible") && hasSticky) {
                    $('.product-info-main-wrapper').addClass('is_popupcart');
                }
            });

            if ($(window).width() < 768) {
                $(".product-info-main").prepend("<div class='btn_close_popcart'>Close</div>");
                $(".btn_close_popcart").click(function(){
                    var mWrapBundle = $('.product-info-main.sticky').find('.bundle-options-wrapper , .field-wrapper-qty');
                    if (mWrapBundle.is(":visible")) {
                        mWrapBundle.hide();
                        $('.product-info-main-wrapper').removeClass('is_popupcart');
                        return;
                    }
                });
            }

        });
    </script>
<?php else :?>
    <script type="text/javascript">
        require([
            'jquery'
        ], function ($) {
            $(".product-info-scroll").addClass("product-soldout");
        });
    </script>
<?php endif; ?>
