<?php
/**
 * Atome Payment Module for Magento 2
 *
 * @author Atome
 * @copyright 2020 Atome
 */
/** @var \Atome\MagentoPayment\Block\Cart\CheckoutCartBlock $block */
?>
<?php if ($block->canShow()) : ?>
    <div class='payment-method-note atome-checkout-note'>
        <?php echo __('Check out with') ?> <img class="atome-icon atome-logo" src="<?php echo $this->getViewFileUrl('Atome_MagentoPayment::image/logo.svg'); ?>"> <?php echo __('and enjoy 3 easy payments with 0% interest.') ?>
        <?php if ($block->supportNewUserOff()) : ?>
            <span class="atome-new-user-off-note"><?php echo __('New user %1 off.', $block->getFormatedNewUserOffAmount()) ?></span>
        <?php endif; ?>
    </div>
<?php endif; ?>
