<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \CJ\CustomCookie\Block\Html\Notices $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<?php
/** @var \Magento\Cookie\Helper\Cookie $cookieHelper */
$cookieHelper = $block->getData('cookieHelper');
$cookieIdentifier = $block->getCookieTemplateIdentifier();
$cmsContent = $block->getBlockCMSContent();
if ($cookieHelper->isCookieRestrictionModeEnabled()): ?>
    <?php if ($cookieIdentifier): ?>
        <?= $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId($cookieIdentifier)
            ->toHtml();
        ?>
    <?php else: ?>
<div id="modal">
    <div role="alertdialog"
         tabindex="-1"
         class="message global cookie"
         id="notice-cookie-block">
        <div role="document" class="content" tabindex="0">
            <p>
                <strong><?= $block->escapeHtml(__('We use cookies to make your experience better.')) ?></strong>
                <span><?= $block->escapeHtml(__(
                        'To comply with the new e-Privacy directive, we need to ask for your consent to set the cookies.'
                    )) ?>
                </span>
                <?= $block->escapeHtml(__('<a href="%1">Learn more</a>.', $block->getPrivacyPolicyLink()), ['a']) ?>
            </p>
            <div class="actions">
                <button id="btn-cookie-allow" class="action allow primary">
                    <span><?= $block->escapeHtml(__('Allow Cookies')) ?></span>
                </button>
            </div>
        </div>
    </div>
</div>
    <?= /* @noEscape */ $secureRenderer->renderStyleAsTag("display: none;", 'div#notice-cookie-block') ?>
    <script type="text/x-magento-init">
        {
            "#notice-cookie-block": {
                "cookieNotices": {
                    "cookieAllowButtonSelector": "#btn-cookie-allow",
                    "cookieName": "<?= /* @noEscape */ \Magento\Cookie\Helper\Cookie::IS_USER_ALLOWED_SAVE_COOKIE ?>",
                    "cookieValue": <?= /* @noEscape */ $cookieHelper->getAcceptedSaveCookiesWebsiteIds() ?>,
                    "cookieLifetime": <?= /* @noEscape */ $cookieHelper->getCookieRestrictionLifetime() ?>,
                    "noCookiesUrl": "<?= $block->escapeJs($block->getUrl('cookie/index/noCookies')) ?>"
                }
            }
        }
    </script>
        <script type="text/javascript">
            require([
                "jquery",
                "Magento_Ui/js/modal/modal"
            ],function($, modal) {

                var options = {
                    type: 'popup',
                    responsive: true,
                    title: 'Main title',
                    buttons: [{
                        text: $.mage.__('Ok'),
                        class: '',
                        click: function () {
                            this.closeModal();
                        }
                    }]
                };

                var popup = modal(options, $('#modal'));
                $("#button").click(function() {
                    $('#modal').modal('openModal');
                });
                $( document ).ready(function() {
                    $('#modal').modal('openModal');
                })
            });
        </script>
    <?php endif; ?>
<?php endif; ?>
