<?php
/** @var \CJ\CustomCookie\Block\Html\Notices $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<?php
$cookieIdentifier = $block->getCookieTemplateIdentifier();
$isEnabledCookiePopup = $block->isEnabledCookiePopup();
$cookieLifeTime = $block->getCookieLifeTime();
?>
<?php if($isEnabledCookiePopup): ?>
<div id="modal" style="display: none">
    <div role="alertdialog"
         tabindex="-1"
         class=""
         id="notice-cookie-block-popup">
        <div role="document" class="cookie-content" tabindex="0">
            <?= $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId($cookieIdentifier)
                ->toHtml();
            ?>
        </div>
        <div class="custom-allow-cookie">
            <button id="btn-cookie-close" class="custom-btn-cookie">
                <span><?= $block->escapeHtml(__('Close')) ?></span>
            </button>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
            {
                "*": {
                        "popupCookie":{
                            "cookieClosePopup": "#btn-cookie-close",
                            "cookieName": "<?= /* @noEscape */\CJ\CustomCookie\Helper\Data::USER_CLOSED_COOKIE_POPUP ?>",
                            "cookieValue": <?= /* @noEscape */$block->getWebsiteId() ?>,
                            "cookieLifetime": <?= /* @noEscape */$cookieLifeTime ?>,
                            "websiteId": <?= $block->getWebsiteId() ?>
                        }
                    }
            }
</script>
<?php endif; ?>
