<?php
/**
 * @author Eguana Team
 * @copyright Copyright (c) 2019 Eguana {http://eguanacommerce.com}
 * Created by PhpStorm
 * User: david
 * Date: 2020/06/26
 * Time: 4:39 PM
 */
?>
<?php
/**
 * @var $block \Eguana\EInvoice\Block\Ecpay\EInvoice
 * @see \Eguana\EInvoice\Block\Ecpay\EInvoice
 */
?>
<?php if ($block->hasEInvoices($block->getOrderId()) > 0) : ?>
    <div class="block order additional details e-invoices">
        <div class="block-title"><strong><?= $block->escapeHtml(__("E-Invoice Information")) ?></strong></div>
        <div class="block-content order e-invoice">
            <?php if ($block->hasEInvoiceTriplicateData($block->getOrderId()) > 0) : ?>
                <div class="box">
                    <strong class="box-title"><span><?= $block->escapeHtml(__("E-Invoice Title")) ?></span></strong>
                    <div class="box-content"><?= $block->escapeHtml(__($block->getEInvoiceTitle($block->getOrderId()))) ?></div>
                </div>
                <div class="box">
                    <strong class="box-title"><span><?= $block->escapeHtml(__("E-Invoice Tax ID Number")) ?></span></strong>
                    <div class="box-content"><?= $block->escapeHtml(__($block->getEInvoiceTaxIdNumber($block->getOrderId()))) ?></div>
                </div>
            <?php endif;?>
            <div class="box">
                <strong class="box-title"><span><?= $block->escapeHtml(__("E-Invoice Date")) ?></span></strong>
                <div class="box-content"><?= $block->escapeHtml(__($block->getEInvoiceDate($block->getOrderId()))) ?></div>
            </div>
            <div class="box">
                <strong class="box-title"><span><?= $block->escapeHtml(__("E-Invoice Number")) ?></span></strong>
                <div class="box-content"><?= $block->escapeHtml(__($block->getEInvoiceNumber($block->getOrderId()))) ?></div>
            </div>
            <?php if ($block->hasEInvoiceCellphoneBarCodeData($block->getOrderId()) > 0) : ?>
                <div class="box">
                    <strong class="box-title"><span><?= $block->escapeHtml(__("E-Invoice Cellphone BarCode")) ?></span></strong>
                    <div class="box-content"><?= $block->escapeHtml(__($block->getEInvoiceCellphoneBarCode($block->getOrderId()))) ?></div>
                </div>
            <?php endif;?>
        </div>
    </div>
<?php endif;?>
