<!--<title>雪花秀SPA，獨特的美容儀式 | 雪花秀</title>-->
<!--<meta name="description" content="雪花秀SPA用亞洲智慧體驗整體美。使用雪花秀產品體驗雪花秀的美容SPA | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="og:title" content="雪花秀SPA，獨特的美容儀式 | 雪花秀">-->
<!--<meta property="og:description" content="雪花秀SPA用亞洲智慧體驗整體美。使用雪花秀產品體驗雪花秀的美容SPA | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="twitter:title" content="雪花秀SPA，獨特的美容儀式 | 雪花秀">-->
<!--<meta property="twitter:description" content="雪花秀SPA用亞洲智慧體驗整體美。使用雪花秀產品體驗雪花秀的美容SPA | Sulwhasoo Hong Kong 中國香港">-->

<section class="content">
  <div class="blind">Introduction</div>
  <div class="l-wrap l-full">
      <div class="spa-intro">
          <div class="h1"><img src="/media/html/resource/img/spa/introduction/h_Spa-HK_Text-Content.png" alt="Sulwhasoo SPA’s Unique Beauty Rituals"></div>
          <img src="/media/html/resource/img/spa/introduction/image_1.jpg" alt="">
      </div>
  </div>
  <div class="l-wrap">
      <section class="spa-section">
          <div class="spa-section-guide">
              <h1 class="h">Sulwhasoo Spa為您呈獻 <br>：唯美之智，不為時間作動</h1>
              <p class="p">雪花秀護理療程以獨創的韓方護膚技術糅合傳統韓國草藥智慧，及專業美容師精心調理，讓您的肌<br> 膚回復平衡；療程中的傳統儀式亦有助尋回心靈平靜，通過內外調和，成就健康的恆久美。</p>
          </div>
          <div class="spa-guide">
              <div class="spa-guide-thumb">
                  <img src="/media/html/resource/img/spa/introduction/image_2.jpg" alt="">
              </div>
              <div class="spa-guide-cell">
                  <h2 class="h"><span>紅參足浴</span></h2>
                  <p class="p">以韓國紅參浸泡的暖水仔細沖洗乾淨，藉紅參能量與暖水的溫熱緩解雙足疲勞，讓身心靈徹底放鬆。
</p>
              </div>
          </div>
          <div class="spa-guide">
              <div class="spa-guide-thumb">
                  <img src="/media/html/resource/img/spa/introduction/image_3.jpg" alt="">
              </div>
              <div class="spa-guide-cell">
                  <h2 class="h"><span>雪花靜</span></h2>
                  <p class="p">進入Sulwhasoo SPA 護理房間後，整個護理療程將以一片棉布作序幕，這是參考了朝鮮時代的宮廷美容護理。你所選擇的韓方草藥香薰油將會加入棉布中，有助喚醒感官並提升護理療效。</p>
              </div>
          </div>
          <div class="spa-guide">
              <div class="spa-guide-thumb">
                  <img src="/media/html/resource/img/spa/introduction/image_4.jpg" alt="">
              </div>
              <div class="spa-guide-cell">
                  <h2 class="h"><span>Sulwhasoo獨有的美容工具</span></h2>
                  <p class="p">翡翠具降溫功效、琥珀有溫熱能量、白瓷具淨化作用，凡此種種精心挑選的按摩工具，均有助提升Sulwhasoo產品功效，發揮極致美療效果。</p>
              </div>
          </div>
      </section>
  </div>
</section>
