<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

?>
<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
?>
<?php if (!$_productCollection->count()) :?>
    <div class="message info empty"><div><?= $block->escapeHtml(__('We can\'t find products matching the selection.')) ?></div></div>
<?php else :?>
    <div class="bestseller-products swiper-container bestseller-slider">
        <div class="swiper-wrapper">
            <div class="swiper-slide bestseller-container intro"><div class="slide-bgimg"><?= /* @noEscape */ $block->getChildHtml('bestseller-intro');?></div></div>
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php $i = 1;?>
            <?php foreach ($_productCollection as $_product) :?>
                <div class="swiper-slide bestseller-container product-list">
                    <div class="slide-bgimg">
                        <div class="product-div">
                            <?php $productImage = $block->getImage($_product, 'category_page_list'); ?>
                            <div class="product-image" style="background-image: url(<?= $block->escapeUrl($productImage->getImageUrl())?>);"></div>
                            <div class="product-info">
                                <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                ?>
                                <label class="product-item-count"><?= $block->escapeHtml($i);?></label>
                                <h2 class="product name">
                                    <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                </h2>
                                <strong class="product-item-name-en">
                                    <?= $block->escapeHtml($_product->getResource()->getAttributeRawValue($_product->getId(),'name',0));?>
                                </strong>
                                <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                                <div class="product attribute overview">
                                    <div class="value" itemprop="<?=$block->escapeHtml(__('description'));?>">
                                        <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    </div>
                                </div>
                                <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                                   title="<?= /* @noEscape */ $_productNameStripped ?>"
                                   class="action more"><?= $block->escapeHtml(__('View Detail')) ?></a>
                                <?php
                                $helper = $this->helper(Pixlee\Pixlee\Helper\Data::class);
                                $websiteId = $helper->getWebsiteId();
                                $helper->initializePixleeAPI($websiteId);
                                ?>
                                <?php if ($helper->isActive() && $helper->getPDPWidgetId() != "") : ?>
                                    <div id="pixlee_container"></div>
                                    <div id="pixlee_widget_master_container"></div>
                                    <script id="pixlee_script" type="text/javascript">
                                        require(['https://assets.pxlecdn.com/assets/pixlee_widget_1_0_0.js'], function (pixlee) {
                                            Pixlee.init({apiKey: '<?= /* @noEscape */ $helper->getApiKey(); ?>'});
                                            Pixlee.addProductWidget({
                                                widgetId: <?= /* @noEscape */ $helper->getPDPWidgetId(); ?>,
                                                skuId: '<?= /* @noEscape */ $_product->getSku(); ?>',
                                                accountId:<?= /* @noEscape */ $helper->getAccountId(); ?>
                                            });
                                            Pixlee.resizeWidget();
                                        });
                                    </script>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </div>
                <?php $i++;?>
            <?php endforeach;?>
        </div>
        <!-- Add Pagination -->
        <div class="swiper-pagination"></div>
    </div>
<?php endif; ?>
