<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

?>
<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var $getDefault \Eguana\CustomCatalog\ViewModel\GetDefaultCategory
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
/** @var CJ\Catalog\Helper\Data $helper */
$helper = $this->helper(\CJ\Catalog\Helper\Data::class);
$currentCategory = $block->getLayer()->getCurrentCategory();
$categoryName = $currentCategory->getName();
$getDefault = $block->getData('view_model');
$gaEnhancedData = $block->getData('ga_enhanced');
$page = $gaEnhancedData->getCurrentPage();
$productPerPage = $gaEnhancedData->getProductPerPage();
$rootCategory = $gaEnhancedData->getRooCategory();
$isEnabledGAEnhanced = $gaEnhancedData->isEnabledGAEnhanced();

$apRecommendName = "";
$apProductName = "";
$apProductId = "";
$apProductPrice = "";
$apProductBrand = "";
$apProductPosition = "";
?>
<?php if (!$_productCollection->count()) :?>
    <div class="message info empty"><div><?= $block->escapeHtml(__('We can\'t find products matching the selection.')) ?></div></div>
<?php else :?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned() ?? 1;
    ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product) :?>
            <li class="item product product-item">
                <div class="product-item-info" data-container="product-<?= /* @noEscape */ $viewMode ?>">
                    <?php /* @noEscape */ $productName = $_helper->productAttribute($_product, $_product->getName(), 'name') ?>

                    <?php /* @noEscape */ $productSku = $_product->getSku() ?>
                    <?php
                    if ($isEnabledGAEnhanced) {
                        $apProductName = $_product->getName();
                        $apProductId = $_product->getId();
                        $apProductPrice = $_product->getPriceInfo()->getPrice('final_price')->getValue();
                        $apProductBrand = "laneige";
                        $apProductPosition = $_product->getCatIndexPosition() + ($page - 1) * $productPerPage + 1;
                    }
                    ?>
                    <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                       class="product photo product-item-photo"
                       tabindex="-1"
                       ap-click-area="prds-<?= /* @noEscape */ $getDefault->getDefaultCategory($currentCategory->getEntityId())->getName() ?>"
                       ap-click-name="prd click"
                       ap-click-data="<?= /* @noEscape */ $getDefault->getProductByDefault($productSku)->getName() . '/' . $productSku ?>"
                        <?php if($isEnabledGAEnhanced): ?>
                            ap-prd-name="<?= $apProductName ?>"
                            ap-prd-id="<?= $apProductId ?>"
                            ap-prd-price="<?= $apProductPrice ?>"
                            ap-prd-cate="<?= $rootCategory ?>"
                            ap-prd-brand="<?= $apProductBrand ?>"
                            ap-prd-position="<?= $apProductPosition ?>"
                            ap-prd-list="<?= $categoryName ?>"
                        <?php endif; ?>
                    >
                        <span class="flags">
                        <?php if($_product->getData('new')):?>
                            <span class="flag new"><?= $block->escapeHtml($_product->getResource()->getAttribute('new')->getStoreLabel());?></span>
                        <?php endif;?>
                        <?php if($_product->getData('best')):?>
                            <span class="flag best"><?= $block->escapeHtml($_product->getResource()->getAttribute('best')->getStoreLabel()); ?></span>
                        <?php endif;?>
                        </span>
                        <?= $productImage->toHtml() ?>
                        <?php
                        // Product Hover Image
                         $block->getChildBlock("product_image_hover")->setData(['product'=>$_product]);
                         ?>
                         <?= $block->getChildHtml('product_image_hover',false); ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                               ap-click-area="prds-<?= /* @noEscape */ $getDefault->getDefaultCategory($currentCategory->getEntityId())->getName() ?>"
                               ap-click-name="prd click"
                               ap-click-data="<?= /* @noEscape */ $getDefault->getProductByDefault($productSku)->getName() . '/' . $productSku ?>"
                                <?php if($isEnabledGAEnhanced): ?>
                                    ap-prd-name="<?= $apProductName ?>"
                                    ap-prd-id="<?= $apProductId ?>"
                                    ap-prd-price="<?= $apProductPrice ?>"
                                    ap-prd-cate="<?= $rootCategory ?>"
                                    ap-prd-brand="<?= $apProductBrand ?>"
                                    ap-prd-position="<?= $apProductPosition ?>"
                                    ap-prd-list="<?= $categoryName ?>"
                                <?php endif; ?>
                            >
                                <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </strong>
                        <div class="product description product-item-description">
                            <?php if ($rawDescription = $_product->getProductExtraDescription()): ?>
                                <?php $chunks = $helper->mb_chunk_split($rawDescription); ?>
                                <?php foreach ($chunks as $chunk): ?>
                                    <p><?= $chunk ?></p>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </div>
                        <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                        <?php if ($_product->isAvailable()) :?>
                            <?= $block->getProductDetailsHtml($_product) ?>
                        <?php endif; ?>

                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $block->escapeHtmlAttr($position) : '' ?>>
                                <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $block->escapeHtmlAttr($position) : '' ?>>
                                    <?php if ($_product->isSaleable()) :?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form"
                                              data-product-sku="<?= $block->escapeHtmlAttr($_product->getSku()) ?>"
                                              action="<?= $block->escapeUrl($postParams['action']) ?>"
                                              method="post">
                                            <input type="hidden"
                                                   name="product"
                                                   value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                            <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                   value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    ClickText="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                    FormText="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                    title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                    class="action tocart primary">
                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                            </button>
                                        </form>
                                    <?php endif; ?>
                                </div>
                                <?php if(!$_product->getData('offline')):?>
                                <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $block->escapeHtmlAttr($position) : '' ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')) :?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                                <?php endif;?>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) :?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= $block->escapeJs($_product->getSku()) ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
