<script>
    require([
        'jquery',
        'domReady!'
    ], function ($) {
        $(function () {
           const resize_ob = new ResizeObserver(function(entries) {
               let rect = entries[0].contentRect;
               let height = rect.height;
               if (height > 0) {
                   $('.breadcrumbs ~ .category-view .category-description').addClass('category-margin');
                   $('.breadcrumbs').addClass('reduce-margin-bottom');
               }
           });

           resize_ob.observe(document.querySelector('.page.messages'));
        });
    });
</script>
