<?php
/**
 * Created by Eguana.
 * User: Brian
 * Date: 2020-11-19
 * Time: 오후 4:49
 */
/** @var $block \Magento\Framework\View\Element\Template */
/** @var \Amore\PointsIntegration\ViewModel\PointsIntegration $pointsViewModel */
$pointsViewModel = $block->getData('points_view_model');

$blockId = $pointsViewModel->getRewardsBlock() ?: 'point_policy_block';
$membershipProgramCmsBlock = $block->getLayout()
    ->createBlock(Magento\Cms\Block\Block::class)
    ->setBlockId($blockId)
    ->toHtml();
?>
<div class="item title" data-role="collapsible">
    <a class="switch" data-toggle="trigger" href="#tab-1"><?= $block->escapeHtml(__('Introduction of Membership Program'))?></a>
</div>
<div id="tab-1" class="item content" data-role="content">
    <?php if ($membershipProgramCmsBlock): ?>
        <div class="block point-membership-program">
            <div class="block-content">
                <?= /* @noEscape */ $membershipProgramCmsBlock; ?>
            </div>
        </div>
    <?php endif;?>
</div>
