<?php
/**
 * Created by Eguana.
 * User: Brian
 * Date: 2020-11-19
 * Time: 오후 4:49
 */
/** @var $block \Magento\Framework\View\Element\Template */

$membershipProgramCmsBlock = $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('point_policy_block')->toHtml();
?>
<div class="item title" data-role="collapsible">
    <a class="switch" data-toggle="trigger" href="#tab-1"><?= $block->escapeHtml(__('Introduction of Membership Program'))?></a>
</div>
<div id="tab-1" class="item content" data-role="content">
    <?php if ($membershipProgramCmsBlock): ?>
        <div class="block point-membership-program">
            <div class="block-content">
                <?= $membershipProgramCmsBlock; ?>
            </div>
        </div>
    <?php endif;?>
</div>
