<?php
/**
 * @author Eguana Team
 * @copyright Copyright (c) 2020 Eguana {http://eguanacommerce.com}
 * Created by PhpStorm
 * User: david
 * Date: 2020/12/16
 * Time: 2:56 PM
 */
/** @var $block \Magento\Framework\View\Element\Template */

$pointsModalCmsBlock = $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('point_policy_modal_block')->toHtml();
?>
<a id="points-modal-info" type="button" class="action" data-trigger="trigger">
    <span data-bind="i18n: 'Point Guideline'"></span>
</a>
<div data-bind="mageInit: {
'Magento_Ui/js/modal/modal':{
    'type': 'popup',
    'title': jQuery.mage.__('Points Policy'),
    'trigger': '[data-trigger=trigger]',
    'responsive': true,
    'buttons': [{
        text: jQuery.mage.__('Confirm'),
        class: 'agree button action primary'
    }]
}}">
    <div id="points-modal" class="content">
        <?php
        $pointsModalCmsBlock = $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('point_policy_modal_block')->toHtml();
        ?>
        <?php if ($pointsModalCmsBlock): ?>
            <div class="modal-block">
                <div class="modal-block-content">
                    <?= $pointsModalCmsBlock; ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
