<?php
/**
 * Created by Eguana.
 * User: Brian
 * Date: 2020-11-10
 * Time: 오전 11:01
 */
/** @var $block \Amore\PointsIntegration\Block\Points\Index */
$pointSearchResult = $block->getPointsSearchResult();
?>
<div class="block block-points-integration">
    <div class="block-title">
        <strong><?= __('Integration Points'); ?></strong>
    </div>
    <div class="block-content content">
        <?php if (count($pointSearchResult) > 0) : ?>
            <div class="pos-customer-info">
                <div class="pos-customer-name">
                    <strong><?= $block->escapeHtml(__('Name')) . ' : '; ?><?= $pointSearchResult['lastName'] . $pointSearchResult['firstName']; ?></strong>
                </div>
                <div class="pos-customer-integration-code">
                    <span><?= $block->escapeHtml(__('Customer Code')) . ' : '; ?><?= $pointSearchResult['cstmIntgSeq']; ?></span>
                </div>
                <div class="pos-customer-grade-code">
                    <?= $block->escapeHtml(__('Customer Grade Code')) . ' : '; ?>
                    <?= $pointSearchResult['cstmGradeCD']; ?>
                </div>
                <div class="pos-customer-grade-name">
                    <?= $block->escapeHtml(__('Customer Grade')) . ' : '; ?>
                    <?= $pointSearchResult['cstmGradeNM']; ?>
                </div>
                <div class="pos-customer-available-points">
                    <?= $block->escapeHtml(__('Available Points')) . ' : '; ?>
                    <?= $pointSearchResult['availablePoint']; ?>
                    <?= $block->getChildHtml('member.points.modal.info'); ?>
                </div>
                <div class="pos-customer-expire-points">
                    <?= $block->escapeHtml(__('Expire Points')) . ' : '; ?>
                    <?= $pointSearchResult['expirePoint']; ?>
                </div>
                <div class="pos-customer-expireDate">
                    <?= $block->escapeHtml(__('Expiry Date')) . ' : '; ?>
                    <?= $block->dateFormat($pointSearchResult['expireDate']); ?>
                </div>
            </div>
        <?php else : ?>
            <div class="message info empty">
                <span><?= $block->escapeHtml(__('Customer Points Info is not Exist.')) ?></span>
            </div>
        <?php endif ?>
    </div>
</div>
