<?php
/**
 * Created by Eguana.
 * User: Brian
 * Date: 2020-11-11
 * Time: 오후 5:36
 */
/** @var $block \Amore\PointsIntegration\Block\Points\RedeemPointsSearch */
$pointSearchResult = $block->getPointsRedeemSearchResult();
$membershipProgramCmsBlock = $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('point_policy_block')->toHtml();
?>
<div class="item title" data-role="collapsible">
    <a class="switch" data-toggle="trigger" href="#history-of-redemption-tab"><?= $block->escapeHtml(__('History of Redemption'))?></a>
</div>
<div id="history-of-redemption-tab" class="item content" data-role="content">
    <?php if (count($pointSearchResult) > 0) : ?>
        <div class="table-wrapper point-redeem">
            <table class="data table table-point history" id="point-redeem-table">
                <thead>
                <tr>
                    <th scope="col" class="col product-name"><?= $block->escapeHtml(__('Product Name')) ?></th>
                    <th scope="col" class="col redeem-points"><?= $block->escapeHtml(__('Redeemed Points')) ?></th>
                    <th scope="col" class="col redeem-date"><?= $block->escapeHtml(__('Redeemed Date')) ?></th>
                    <th scope="col" class="col redeem-location"><?= $block->escapeHtml(__('Redeemed Location')) ?></th>
                    <th scope="col" class="col redeem-qty"><?= $block->escapeHtml(__('Redeemed Quantity')) ?></th>
                </tr>
                </thead>
                <tbody class="redeem-points-list">
                <?php foreach ($pointSearchResult as $redeemSearch) :?>
                    <tr>
                        <td data-th="<?=$block->escapeHtmlAttr(__('Product Name')) ?>" class="col product-name"><?=$redeemSearch['prdNM'] ?></td>
                        <td data-th="<?=$block->escapeHtmlAttr(__('Redeemed Points')) ?>" class="col redeem-points"><?=$redeemSearch['usePoint'] ?></td>
                        <td data-th="<?=$block->escapeHtmlAttr(__('Redeemed Date')) ?>" class="col redeem-date"><?=$redeemSearch['redeemDate'] ?></td>
                        <td data-th="<?=$block->escapeHtmlAttr(__('Redeemed Location')) ?>" class="col redeem-location"><?=$redeemSearch['redeemStoreNM'] ?></td>
                        <td data-th="<?=$block->escapeHtmlAttr(__('Redeemed Quantity')) ?>" class="col redeem-qty"><?=$redeemSearch['redeemQty'] ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <div class="toolbar">
            <div class="pages" id="redeem-points-pager">
                <ul class="items pages-items pagination">
                    <?php if ($pointSearchResult[0]['totPage'] > 1): ?>
                        <?php if ($pointSearchResult[0]['prev']): ?>
                            <li class="item pages-item-previous points-integration-redeem-pager active" data-page="<?=$pointSearchResult[0]['prevPage']; ?>"><a class="action previous"><span><?=$block->escapeHtml(__('previous')); ?></span></a></li>
                        <?php endif; ?>
                        <?php for ($i = $pointSearchResult[0]['startPage']; $i <= $pointSearchResult[0]['endPage']; $i++) : ?>
                            <?php if ($i == $pointSearchResult[0]['page']): ?>
                                <li class="item points-integration-redeem-pager active" data-page="<?=$i; ?>"><strong class="page"><?=$i; ?></strong></li>
                            <?php else: ?>
                                <li class="item points-integration-redeem-pager active" data-page="<?=$i; ?>"><a class="page"><?=$i; ?></a></li>
                            <?php endif; ?>
                        <?php endfor; ?>
                        <?php if ($pointSearchResult[0]['next']): ?>
                            <li class="item pages-item-next points-integration-redeem-pager active" data-page="<?=$pointSearchResult[0]['nextPage']; ?>"><a class="action next"><span><?=$block->escapeHtml(__('next')); ?></span></a></li>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php if ($pointSearchResult[0]['totPage'] == 1): ?>
                        <li class="item points-integration-redeem-pager" data-page="<?$pointSearchResult[0]['totPage']; ?>">
                            <?=$pointSearchResult[0]['totPage']?>
                        </li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    <?php else : ?>
        <div class="table-wrapper point-redeem">
            <table class="data table table-point history" id="point-redeem-table">
                <thead>
                <tr>
                    <th scope="col" class="col product-name"><?= $block->escapeHtml(__('Product Name')) ?></th>
                    <th scope="col" class="col redeem-points"><?= $block->escapeHtml(__('Redeemed Points')) ?></th>
                    <th scope="col" class="col redeem-date"><?= $block->escapeHtml(__('Redeemed Date')) ?></th>
                    <th scope="col" class="col redeem-location"><?= $block->escapeHtml(__('Redeemed Location')) ?></th>
                    <th scope="col" class="col redeem-qty"><?= $block->escapeHtml(__('Redeemed Quantity')) ?></th>
                </tr>
                </thead>
                <tbody class="redeem-points-list">
                    <tr>
                        <td class="empty" colspan="5">
                            <span><?= $block->escapeHtml(__('Points Redemption History Does not Exist.')) ?></span>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    <?php endif ?>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "redeemSearch": {}
        }
    }
</script>
