<?php
/** @var $viewModel \Eguana\Magazine\ViewModel\Index\MagazineList */
$viewModel = $block->getData('view_model_list');
$magazineCollection = $viewModel->getMonthWiseMagazineCollection();
?>
<div class="block magazine-image">
    <?php if (!empty($magazineCollection->getData())):?>
        <ul class="list-image-box" id="slick">
            <?php foreach ($magazineCollection as $magazineItem): ?>
                <li class="magazine-item-box">
                    <div class="magazine-item">
                        <a
                            href="<?= $block->escapeHtml($block->
                            getUrl($viewModel->
                            getItemDetailsUrl($magazineItem['entity_id'])));?>">
                <span>
                    <img src="<?= $block->escapeHtml($viewModel->getThumbnailSrc($magazineItem['thumbnail_image']));?>"
                         alt="<?= $block->escapeHtml($magazineItem['thumbnail_alt']);?>" />
                </span>
                        </a>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
    <?php endif;?>

</div>
