<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
/* @var $getDefault \Eguana\CustomCatalog\ViewModel\GetDefaultCategory */

$getDefault = $block->getData('view_model_get_default_name');
?>

<?php

$exist = null;
if ($block->getItems() && $block->getItems()->getSize()) {
    $exist = $block->getItems()->getSize();
    $type = 'history';
    $class = $type;
    $image = 'related_products_list';
    $items = $block->getItems();
    $limit = 4;
    $count = 0;
    $canItemsAddToCart = $block->canItemsAddToCart();

    $showAddTo = true;
    $showCart = true;
    $templateType = $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
}
?>

<?php if ($exist):?>
<div class="block <?= $block->escapeHtmlAttr($class) ?>">
    <div class="block-title title">
        <strong id="block-<?= $block->escapeHtmlAttr($class) ?>-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('My History')) ?></strong>
        <a class="action view" href="<?= $block->escapeUrl($block->getUrl('customer/account/history')) ?>">
            <span><?= $block->escapeHtml(__('View more')) ?></span>
        </a>
    </div>
    <div class="block-content content" aria-labelledby="block-<?= $block->escapeHtmlAttr($class) ?>-heading">
        <div class="swiper-container products wrapper grid products-grid products-<?= $block->escapeHtmlAttr($type) ?>">
            <ol class="swiper-wrapper products list items product-items">
                <?php foreach ($items as $_item): ?>
                    <?php 
                        $count++;
                        if ($count > $limit) break;
                        /* @noEscape */ $productSku = $_item->getSku(); 
                    ?>
                    <li class="swiper-slide item product product-item">
                    <div class="product-item-info">
                        <?= /* @escapeNotVerified */ '<!-- ' . $image . '-->' ?>
                        <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                            class="product photo product-item-photo"
                            ap-click-area="product"
                            ap-click-name="prd click"
                            ap-click-data="<?= /* @noEscape */ $getDefault->getProductByDefault($productSku)->getName() . '/' . $productSku ?>">
                            <?= $block->getImage($_item, $image)->toHtml() ?>
                        </a>
                        <div class="product-item-inner">
                            <div class="product actions product-item-actions">
                                <?php if ($showAddTo || $showCart): ?>
                                    <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                        <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                            <?= $addToBlock->setProduct($_item)->getChildHtml() ?>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <div class="product details product-item-details">
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                    title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                    href="<?= /* @escapeNotVerified */ $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                    ap-click-area="product"
                                    ap-click-name="prd click"
                                    ap-click-data="<?= /* @noEscape */ $getDefault->getProductByDefault($productSku)->getName() . '/' . $productSku ?>">
                                    <?= $block->escapeHtml($_item->getName()) ?></a>
                            </strong>

                            <?= /* @noEscape */ $block->getProductPrice($_item) ?>

                            <?php if ($templateType): ?>
                                <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                            <?php endif; ?>

                            <div class="product-item-inner">
                                <div class="product actions product-item-actions">
                                    <?php if ($showAddTo || $showCart): ?>
                                        <div class="actions-primary">
                                            <?php if ($_item->isSaleable()): ?>
                                                <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                    <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}' type="button" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                        <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                    </button>
                                                <?php else: ?>
                                                    <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                    $postData = $postDataHelper->getPostData($block->escapeUrl($block->getAddToCartUrl($_item)), ['product' => $_item->getEntityId()])
                                                    ?>
                                                    <button class="action tocart primary"
                                                            data-post='<?= /* @escapeNotVerified */ $postData ?>'
                                                            type="button" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                        <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                    </button>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    </li>
                <?php endforeach ?>
            </ol>
        </div>
    </div>
</div>

<script>
    require([
        'jquery',
        'swiper'
    ],function ($,Swiper) {

            var swiper = new Swiper(".products-grid.products-history", {
                slidesPerView: 4,
                freeMode: false,
                autoHeight: true,
                direction: 'horizontal',
                loop: false,
                threshold: 30,
                spaceBetween: 48,
                breakpoints: {
                    768: {
                        slidesPerView: 2.1,
                        spaceBetween: 11.5,
                    }
                }
            });
    });
</script>
<?php endif;?>
