<!--<title>설화수 라운지 - 설화수 스타일 - 인터뷰 전체 목록 | 설화수 한국</title>-->
<!--<meta name="description" content="설화수 스타일 from Korea - 인터뷰 전체 보기 | Sulwhasoo">-->
<!--<meta property="og:title" content="설화수 라운지 - 설화수 스타일 - 인터뷰 전체 목록 | 설화수 한국">-->
<!--<meta property="og:description" content="설화수 스타일 from Korea - 인터뷰 전체 보기 | Sulwhasoo">-->
<!--<meta property="twitter:title" content="설화수 라운지 - 설화수 스타일 - 인터뷰 전체 목록 | 설화수 한국">-->
<!--<meta property="twitter:description" content="설화수 스타일 from Korea - 인터뷰 전체 보기 | Sulwhasoo">-->

<section class="content">
    <h1 class="blind">설화수 스타일</h1>
    <div class="l-wrap l-full">
        <div class="experience">
            
            <div class="experience-box">
                <div class="experience-cell">
                    <img src="/media/html/experience/sulhwasoo_style/__icsFiles/afieldfile/2021/12/30/20211221_final_sulwhasoo_style_banner_pc.jpg" alt="유나 양">
                </div>
                <div class="experience-cell desc">
                    <div class="h">Yuna Yang, <br>The new category</div>
                    <h2 class="h-sub">디자이너<b>유나 양</b></h2>
                    <h2>유나 양이라는 <br>새로운 카테고리</h2>
                    <a href="/kr/ko/experience/sulhwasoo_style/yuna-yang.html" class="btn btn-l">인터뷰 상세</a>
                </div>
            </div>
            
            <div class="experience-box">
                <div class="experience-cell desc">
                    <div class="h">Leenalchi takes us<br>to a whole new world </div>
                    <h2 class="h-sub">밴드<b>이날치 밴드</b></h2>
                    <h2>이날치가 열어젖힌<br>새로운 세상이 내려온다 </h2>
                    <a href="/kr/ko/experience/sulhwasoo_style/band-leenalchi.html" class="btn btn-l">인터뷰 상세</a>
                </div>
                <div class="experience-cell">
                    <img src="/media/html/experience/sulhwasoo_style/__icsFiles/afieldfile/2021/05/13/20210513_final_sulwhasoo_style_banner_pc.jpg" alt="이날치 밴드">
                </div>
            </div>
            
        </div>
    </div>
    <div class="l-wrap">
        <div class="experience-list">
            <div class="blind">Sulwhasoo style list</div>
            <ul>
                
                <li class="experience-item">
                    <a href="/kr/ko/experience/sulhwasoo_style/yuna-yang.html" class="thumb">
                        <img src="/media/html/experience/sulhwasoo_style/__icsFiles/afieldfile/2021/12/30/20211221_final_sulwhasoo_style_detail-thumb_pc.jpg" alt="유나 양">
                        <div class="cover">
                            <span class="title">디자이너</span>
                            <b class="name">유나 양</b>
                        </div>
                    </a>
                </li>
                
                <li class="experience-item">
                    <a href="/kr/ko/experience/sulhwasoo_style/band-leenalchi.html" class="thumb">
                        <img src="/media/html/experience/sulhwasoo_style/__icsFiles/afieldfile/2021/05/13/20210513_final_sulwhasoo_style_thumb_pc.jpg" alt="이날치 밴드">
                        <div class="cover">
                            <span class="title">밴드</span>
                            <b class="name">이날치 밴드</b>
                        </div>
                    </a>
                </li>
                
                <li class="experience-item">
                    <a href="/kr/ko/experience/sulhwasoo_style/1288547_2814.html" class="thumb">
                        <img src="/media/html/experience/sulhwasoo_style/__icsFiles/afieldfile/2020/09/11/0911_02_02.jpg" alt="바이올리니스트 정경화">
                        <div class="cover">
                            <span class="title">바이올리니스트</span>
                            <b class="name">정경화</b>
                        </div>
                    </a>
                </li>
                
                <li class="experience-item">
                    <a href="/kr/ko/experience/sulhwasoo_style/1288546_2814.html" class="thumb">
                        <img src="/media/html/experience/sulhwasoo_style/__icsFiles/afieldfile/2020/09/11/0911_01_01.jpg" alt="배우 이정은">
                        <div class="cover">
                            <span class="title">배우</span>
                            <b class="name">이정은</b>
                        </div>
                    </a>
                </li>
                
                <li class="experience-item">
                    <a href="/kr/ko/experience/sulhwasoo_style/1280413_2814.html" class="thumb">
                        <img src="/media/html/experience/sulhwasoo_style/__icsFiles/afieldfile/2020/04/07/Style-List_Thumbnails_1.jpg" alt="김소연 에스팀 대표">
                        <div class="cover">
                            <span class="title">에스팀 대표</span>
                            <b class="name">김소연</b>
                        </div>
                    </a>
                </li>
                
                <li class="experience-item">
                    <a href="/kr/ko/experience/sulhwasoo_style/jun-soo-kyung.html" class="thumb">
                        <img src="/media/html/experience/sulhwasoo_style/__icsFiles/afieldfile/2020/01/14/thumb.jpg" alt="음악감독 전수경">
                        <div class="cover">
                            <span class="title">음악감독</span>
                            <b class="name">전수경</b>
                        </div>
                    </a>
                </li>
                
                <li class="experience-item">
                    <a href="/kr/ko/experience/sulhwasoo_style/jeong-yoo-jung.html" class="thumb">
                        <img src="/media/html/experience/sulhwasoo_style/__icsFiles/afieldfile/2019/10/21/191021_final_sulwhasoo_style_detail-thumb_PC.jpg" alt="작가 정유정">
                        <div class="cover">
                            <span class="title">작가</span>
                            <b class="name">정유정</b>
                        </div>
                    </a>
                </li>
                
                <li class="experience-item">
                    <a href="/kr/ko/experience/sulhwasoo_style/kim-ji-yoon.html" class="thumb">
                        <img src="/media/html/experience/sulhwasoo_style/__icsFiles/afieldfile/2019/07/16/thumb.jpg" alt="박사 김지윤">
                        <div class="cover">
                            <span class="title">정치학 박사</span>
                            <b class="name">김지윤</b>
                        </div>
                    </a>
                </li>
                
                <li class="experience-item">
                    <a href="/kr/ko/experience/sulhwasoo_style/hong-jee-hui.html" class="thumb">
                        <img src="/media/html/experience/sulhwasoo_style/__icsFiles/afieldfile/2019/07/01/thumb.jpg" alt="화가 홍지희">
                        <div class="cover">
                            <span class="title">화가</span>
                            <b class="name">홍지희</b>
                        </div>
                    </a>
                </li>
                
                <li class="experience-item">
                    <a href="/kr/ko/experience/sulhwasoo_style/kim-young-jin.html" class="thumb">
                        <img src="/media/html/experience/sulhwasoo_style/__icsFiles/afieldfile/2019/04/12/1552647776723_l.jpg" alt="한복 디자이너 김영진">
                        <div class="cover">
                            <span class="title">한복 디자이너</span>
                            <b class="name">김영진</b>
                        </div>
                    </a>
                </li>
                
                <li class="experience-item">
                    <a href="/kr/ko/experience/sulhwasoo_style/cho-sang-kyung.html" class="thumb">
                        <img src="/media/html/experience/sulhwasoo_style/__icsFiles/afieldfile/2019/02/07/15421034050921.jpg" alt="의상 디렉터 조상경 ">
                        <div class="cover">
                            <span class="title">의상 디렉터</span>
                            <b class="name">조상경</b>
                        </div>
                    </a>
                </li>
                
                <li class="experience-item">
                    <a href="/kr/ko/experience/sulhwasoo_style/goh-sang-ji.html" class="thumb">
                        <img src="/media/html/experience/sulhwasoo_style/__icsFiles/afieldfile/2019/02/07/15385496872242.jpg" alt="뮤지션 고상지">
                        <div class="cover">
                            <span class="title">뮤지션</span>
                            <b class="name">고상지</b>
                        </div>
                    </a>
                </li>
                
                <li class="experience-item">
                    <a href="/kr/ko/experience/sulhwasoo_style/kim-yoona.html" class="thumb">
                        <img src="/media/html/experience/sulhwasoo_style/__icsFiles/afieldfile/2019/02/07/1534905539124.jpg" alt="가수 김윤아">
                        <div class="cover">
                            <span class="title">가수</span>
                            <b class="name">김윤아</b>
                        </div>
                    </a>
                </li>
                
                <li class="experience-item">
                    <a href="/kr/ko/experience/sulhwasoo_style/lee-ji-sun.html" class="thumb">
                        <img src="/media/html/experience/sulhwasoo_style/__icsFiles/afieldfile/2019/02/07/1528437138195.jpg" alt="디자이너 이지선">
                        <div class="cover">
                            <span class="title">디자이너</span>
                            <b class="name">이지선</b>
                        </div>
                    </a>
                </li>
                
                <li class="experience-item">
                    <a href="/kr/ko/experience/sulhwasoo_style/song-hye-kyo.html" class="thumb">
                        <img src="/media/html/experience/sulhwasoo_style/__icsFiles/afieldfile/2019/02/07/1522724573371.jpg" alt="배우 송혜교">
                        <div class="cover">
                            <span class="title">배우</span>
                            <b class="name">송혜교</b>
                        </div>
                    </a>
                </li>
                
            </ul>
        </div>
        <div class="experience-more">
            <div class="h"><img src="/media/html/resource/img/experience/txt-style-list-1.png" alt="설화수 스타일 from Korea"></div>
            <button type="button" id="experience-btn" class="btn btn-l" >더보기</button>
        </div>
    </div>
</section>

<script>
	require([
	'jquery',
	], function ($) {
	   if ($(".experience-list").length > 0) {
            var l = $(".experience-list"),
                h = l.find(".experience-item:gt(3)"),
                g = $("#experience-btn");
            h.hide();
            g.on("click", function () {
                h.show();
                $(this).hide();
                $(this).prev(".h").hide();
                $("html, body").animate({ scrollTop: l.offset().top }, 800);
            });
        }
	});
</script>