<!--<title>金潤雅 - 雪花秀風格 Sulwhasoo Style | 雪花秀</title>-->
<!--<meta name="description" content="雪花秀風格 Sulwhasoo Style 專訪 歌手 金潤雅 面試詳情 | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="og:title" content="金潤雅 - 雪花秀風格 Sulwhasoo Style | 雪花秀">-->
<!--<meta property="og:description" content="雪花秀風格 Sulwhasoo Style 專訪 歌手 金潤雅 面試詳情 | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="twitter:title" content="金潤雅 - 雪花秀風格 Sulwhasoo Style | 雪花秀">-->
<!--<meta property="twitter:description" content="雪花秀風格 Sulwhasoo Style 專訪 歌手 金潤雅 面試詳情 | Sulwhasoo Hong Kong 中國香港">-->

<section class="content">
    <div class="blind">Sulwhasoo Style</div>
    <article class="sws-style">
		<div class="l-wrap l-full">
			<div class="basic style_basic">
				<div class="sws-style-visual">
				<h1 class="h1"><span class="title">歌手</span> <b class="name">金潤雅</b></h1>
				<img src="/media/html/resource/img/experience/sulwhasoo_style/1534905539124.jpg" class="only-desktop" alt="">
				<img src="/media/html/resource/img/experience/sulwhasoo_style/1534905539124m.jpg" class="only-mobile" alt="">
				</div>
			</div>

		</div>

		<div class="l-wrap">
			<div class="sws-style-body">
				<div class="content static parbase">
					<style>
					.sws-style .q.style_1 {margin:2em 0 1.8em;}
					</style>
					<div class="sws-style-section">
						<blockquote class="blockquote">
						    <p class="quote break-word">金潤雅創作藝術的方式</p>
						</blockquote>
						<div class="sws-style-sticky">
						    <img src="/media/html/resource/img/experience/sulwhasoo_style/15349053544401.jpg" alt="가수 김윤아">
						</div>
						<div class="sws-style-desc">
					    	<p class="q">就如森林和人之間的關係一樣，金潤雅和大眾總是有著渾然天成的連繫。</p>
						    <p class="p">
						        金潤雅長期以來都是大眾的安慰與激勵。她有什麼魅力令眾人的傾慕？<br>「現代人的生活給了我很多不同的靈感。我對人們的渴望、想得到怎樣的快樂和他們如何過自己的生活感到興趣。我會細心觀察別人的生活。我在SNS很活躍，看別人的生活點滴，比分享我自己的生活更加有趣。知道他們活得快樂，我也感到快樂。<br>生活的目的就是，無論你住在哪裡、在做什麼，下一刻都要活得比當下快樂，否則，生活就會變得很沒趣，只會留下悲傷。因此，我會唱一些關於日常生活的歌，包括如何走向快樂，相信這就是大眾能對我的歌曲產生同嗚的原因。」
						<br>我們能走近金潤雅，源於她樂於傾聽的態度。她可能看起來像個與世隔絕而敏感的藝術家，但實情並非如是，她會開放聆聽別人的故事，這就是她創作藝術的方式。<br>「在最初的兩三年我過得比較辛苦。我並不喜歡那些我不認識的人，像很熟悉我般跟我說話，這讓人感到困惑。後來我學會了享受它。我將自己分成兩部分：一個音樂人和一個普通人。我覺得既然我選擇以這種方式生活，我必須對我的決定負責。因此，音樂成為生活的一部分，我沒有模糊或放輕任何部分的自己，每一部分的我都在平衡地建構著我的生活。」<br><br>
						    </p>
						    <p class="q">金潤雅很率直。音樂就是她生命的一部分。</p>
						    <p class="p">
						        她吸收世界上一切美麗的東西，就像樹林每天吸收大量水份一樣。在音樂方面，這更為真實，她想要盡情吸收。就像路上會自然引起別人注意的花朵一樣，她想要製作不知不覺間安慰著人、繞樑三日的動人音樂。<br>「音樂不是超然的東西。簡單來說，音樂就只是音樂，但能被音樂包圍的感覺很好。就正如我使用雪花秀來潔膚一樣。我那問題多多又敏感的皮膚，實在很難找到對的產品，幸而有人介紹我用雪花秀，自此我就一直在使用它。我很高興能找到一種完全不用擔心有副作用的產品，它的存在讓我感到安慰。音樂也是如此。即使世界沒有音樂，也不會對人類造成任何嚴重的不便；就像人不能找到一個好的潔面乳，也不會是世界末日一樣。但是當你一旦發現它並把它帶入你的生活，你的生活就會變得美好一點。所以，雖然音樂只是音樂，但其實你需要它。」<br>來自生活的音樂融入生活。 金潤雅的音樂能長留聽眾的心坎之中，就是因為它並非超凡脫俗。
						    </p>
						</div>
					</div>

					<div class="sws-style-section">
						<div class="sws-style-sticky">
						    <img src="/media/html/resource/img/experience/sulwhasoo_style/15349053544402.jpg" alt="가수 김윤아">
						</div>
						<div class="sws-style-desc">
						    <!--<p class="q"></p>

						    <p class="p"></p>-->

						    <blockquote class="blockquote">
						        <p class="quote break-word">二十一歲，年青的紫雨林樂隊</p>
						    </blockquote>

						    <p class="q">二十一年前成立的紫雨林樂隊，新發的專輯充滿了關於青春的歌曲。</p>
						    <p class="p">
						       金潤雅說：「樂隊由人組成，所以樂隊的表演、聲音和哲學，都會隨著時間的推移而發展和變化。」<br>紫雨林仍是歌頌著相同的青春，但是整個意念已經變得成熟。「我們首演已經是二十一年前的事了。樂隊首次亮相是在夏季，所以去年夏天，我們舉辦了一場特別的音樂會，來慶祝成立廿十週年。但因為當中有些美中不足，今年我們將會舉辦另一場音樂會。我們新一張新專輯亦已經完成，主題是《青春禮讚》。雖然我們所有的成員都長大了成熟了，但紫雨林是個無論年齡變得多大，都會談論著青春的團隊。我們音樂的基礎是源於孤獨和人們的渴望，這是年輕人的象徵。我們經常歌頌青春，其實紫雨林都只是二十一歲，仍很年輕。」<br>自1997年第一張專輯發行至今，紫雨林已經成軍二十一年，先後發行了十張專輯。大多數樂隊都如雲霧一樣，在韓國音樂界中神奇地出現了，然後不知不覺間地消失了。但是紫雨林選擇成為一片森林，而不是一片雲霧。樂隊的名字都告訴我們，他們就是一片下著紫雨的森林。美麗的森林一直是我們情感的庇護所， 二十一年後的今天，這片森林已變得更加華麗和清新。
						    </p>
						</div>
					</div>
				</div>

			</div>
		</div>
	</article>
    <div class="l-wrap">
        <div class="experience-list">
            <div class="blind">Sulwhasoo style list</div>
            <ul>
                
                <li class="experience-item">
                    <a href="/hk/zh/experience/sulwhasoo_style/cho-sang-kyung.html" class="thumb">
                        <img src="/media/html/experience/sulwhasoo_style/__icsFiles/afieldfile/2019/02/07/15421034050921.jpg" alt="服裝指導  Cho Sang Kyung">
                        <div class="cover">
                            <span class="title">服裝指導</span>
                            <b class="name">Cho Sang Kyung</b>
                        </div>
                    </a>
                </li>
                
                <li class="experience-item">
                    <a href="/hk/zh/experience/sulwhasoo_style/goh-sang-ji.html" class="thumb">
                        <img src="/media/html/experience/sulwhasoo_style/__icsFiles/afieldfile/2019/02/07/15385496872242.jpg" alt="音樂家  Goh Sang Ji">
                        <div class="cover">
                            <span class="title">音樂家</span>
                            <b class="name">Goh Sang Ji</b>
                        </div>
                    </a>
                </li>
                
                <li class="experience-item">
                    <a href="/hk/zh/experience/sulwhasoo_style/kim-yoona.html" class="thumb">
                        <img src="/media/html/experience/sulwhasoo_style/__icsFiles/afieldfile/2019/02/07/1534905539124.jpg" alt="歌手  金潤雅">
                        <div class="cover">
                            <span class="title">歌手</span>
                            <b class="name">金潤雅</b>
                        </div>
                    </a>
                </li>
                
                <li class="experience-item">
                    <a href="/hk/zh/experience/sulwhasoo_style/lee-ji-sun.html" class="thumb">
                        <img src="/media/html/experience/sulwhasoo_style/__icsFiles/afieldfile/2019/02/07/1528437138195.jpg" alt="設計師  李智善">
                        <div class="cover">
                            <span class="title">設計師</span>
                            <b class="name">李智善</b>
                        </div>
                    </a>
                </li>
                
            </ul>
        </div>
    </div>
</section>
<script>
	require([
	'jquery',
	], function ($) {
	    $(".sws-style-sticky").each(function (u, v) {
	    	console.log("sdkh");
	        var t = $(v),
	            s = t.parent();
	        $(window).on("scroll", function () {
	        	console.log(t.css("position"));
                if (t.css("position") !== "absolute") {
                    return;
                }
                console.log("ajs");
                t.css("top", n(t, s));
            }).scroll();
	        $(window).on("resize", function () {
	            var w = n(t, s);
	            if (t.css("position") !== "absolute") {
	                return;
	            }
	            t.css("top", w);
	        });
	        $('body').on("mousewheel", function () {
	            var x = event.wheelDelta / 8;
	            var w = window.pageYOffset;
	            window.scrollTo(0, w - x);
	        });
	    });
	    function n(w, v) {
	        var x = 0,
	            t = w.outerHeight(),
	            s = v.offset().top,
	            u = v.outerHeight();
	        if ($(window).scrollTop() > s) {
	            x = $(window).scrollTop() - s;
	            if (u - t + s < $(window).scrollTop()) {
	                x = u - t;
	            }
	        } else {
	            x = 0;
	        }
	        return x;
	    }
	});
</script>