<!--<title>Goh Sang Ji - 雪花秀風格 Sulwhasoo Style | 雪花秀</title>-->
<!--<meta name="description" content="雪花秀風格 Sulwhasoo Style 專訪 音樂家 Goh Sang Ji 面試詳情 | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="og:title" content="Goh Sang Ji - 雪花秀風格 Sulwhasoo Style | 雪花秀">-->
<!--<meta property="og:description" content="雪花秀風格 Sulwhasoo Style 專訪 音樂家 Goh Sang Ji 面試詳情 | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="twitter:title" content="Goh Sang Ji - 雪花秀風格 Sulwhasoo Style | 雪花秀">-->
<!--<meta property="twitter:description" content="雪花秀風格 Sulwhasoo Style 專訪 音樂家 Goh Sang Ji 面試詳情 | Sulwhasoo Hong Kong 中國香港">-->

<section class="content">
    <div class="blind">Sulwhasoo Style</div>
    
    <article class="sws-style">
		<div class="l-wrap l-full">
			<div class="basic style_basic"><div class="sws-style-visual">
				<h1 class="h1"><span class="title">音樂家</span> <b class="name">Goh Sang Ji</b></h1>
				<img src="/media/html/resource/img/experience/sulwhasoo_style/1538549687224.jpg" class="only-desktop" alt="">
				<img src="/media/html/resource/img/experience/sulwhasoo_style/1538549687224m.jpg" class="only-mobile" alt="">
				</div>

			</div>

		</div>

		<div class="l-wrap">
			<div class="sws-style-body">
				<div class="content static parbase">
					<style>
					.sws-style .q.style_1 {margin:2em 0 1.8em;}
					</style>
					<div class="sws-style-section">
						<blockquote class="blockquote">
						    <p class="quote break-word">當探戈遇上巴洛克</p>
						</blockquote>
						<div class="sws-style-sticky">
						    <img src="/media/html/resource/img/experience/sulwhasoo_style/15385499133641.jpg" alt="Musician Koh Sang Ji">
						</div>
						<div class="sws-style-desc">
						    <p class="q">在Goh Sang Ji（고상지）創作及重新編曲的專輯中，可聽到港口樂器班多鈕手風琴奏出的自由之聲。</p>
						    <p class="p">
						        班多鈕手風琴是音樂家Goh Sang Ji策劃演奏會、創作及重新編寫樂章不可或缺的夥伴，她以班多鈕手風琴拓寬音樂國度。<br>「我以前覺得錄音室更自在，現在卻懂得享受站在舞台上的時光。我從前一上台就很緊張，錄音時才能沉靜下來，細膩演奏我的樂曲。不過，最近在台上演奏變得很有意思。」<br>近日，Goh Sang Ji不僅演奏樂器，更親自策劃演奏會，她表示這個過程令她渾身是勁。一如演奏其他樂器，班多鈕手風琴手亦跟運動員一樣持續訓練自己。為了一次演出，練習不容鬆懈。Goh Sang Ji在演奏會前每天練習高達六小時，平日每天平均練習三小時，就像運動員每天練跑，她亦要每天練習以保持手感。不過，她最近愛上了巴洛克音樂，練琴時間都不夠了。<br>「學音樂永不令人厭倦，你總有新的發現。我機緣巧合下愛上了巴洛克音樂。我的音樂深受日本動畫影響，我自小是日本動畫的忠實粉絲，畫面配上對的音樂實在太美好。我迷上探戈是因為這令我想起《勇者鬥惡龍》的配樂。我上一張專輯向我所有摯愛的動畫角色致敬，而我尊敬的音樂總監都身兼動畫配樂總監。不過，我從古典音樂中亦有一些新奇發現。」<br>她聽巴哈的雙小提琴協奏曲時，竟發現班多紐手風琴演奏家皮亞佐拉常用的旋律。巴哈是皮亞佐拉創作音樂的靈感泉源，這是個有趣的新發現，亦是她開始研究巴洛克音樂的原因。<br>「我著聽巴洛克音樂，竟發現我敬佩的音樂總監的音樂，原來深受巴洛克音樂的影響。我是流行音樂家，雖然有基本音樂根底，始終不太留意古典音樂，所以直到現在才有此發現。這驅使我深入學習巴洛克音樂，畢竟這是古典音樂的根基。」<br><br>
						    </p>
						</div>
					</div>

					<div class="sws-style-section">
						<div class="sws-style-sticky">
						    <img src="/media/html/resource/img/experience/sulwhasoo_style/15385499133642.jpg" alt="Musician Koh Sang Ji">
						</div>
						<div class="sws-style-desc">
						    <!--<p class="q"></p>

						    <p class="p"></p>-->

						    <blockquote class="blockquote">
						        <p class="quote break-word">Sang Ji Goh無限擴展的音樂觀</p>
						    </blockquote>

						    <p class="q">自從發現自己著迷的音樂源於巴洛克，她便決定學習巴洛克音樂。</p>
						    <p class="p">
						       能在巴哈、泰勒曼 及韋瓦第的古典音樂中找到現代魅力，使她大為驚嘆。「我作曲時亦曾陷入『矯飾主義』。因為人們通常期望我以探戈節奏為創作基礎，在重新編曲時往往發現自己傾向重複相似的旋律。那時我正尋找新突破，最後竟在古老音樂中找到。我相信愈深入學習古典音樂基礎，愈能拓展我的音樂觀。」<br>Goh Sang Ji對自己的過去感到「羞愧」，她敢於承認自己的羞愧實在值得欣賞。她之所以感到羞愧，是她現在才打開古典音樂的大門，以前從沒學過任何古典音樂便作曲。因此她下定決心要用心學習。當小編說期待她日後的作品時，她笑著回道︰「我也很期待，這一定很有趣。我正與敬佩的幾位音樂人合作，包括鋼琴家Moon Suk Choi及Hyun Jin Lee、小提琴家Jong Soo Yoon及Yi Chae Kang、以及鋼片琴家Mother Vibe。我有信心大家經過磨合，日後合作一定事半功倍。我們尊重對方、互相依賴，將各自的音樂世界合而為一。」<br>她曾在訪問中提及自己遇過一連串「時機恰到好處」的巧合。她讀的大學恰好有樂隊；她的母親恰好送她購自阿根廷的班多鈕手風琴；恰好有人電郵世界級的班多鈕手風琴手小松亮太，而他他恰好應允；因為沒有其他演出者，所以她恰好在金東律的演唱會演奏；她亦恰好出演了《無限挑戰》。所有巧合似乎只是一椿椿幸運事件，卻像班多鈕手風琴的折疊風箱般連接起來。每件巧合事件之間，Goh Sang Ji迎接過不少挑戰，嘗試過無數次，正如每次為風箱注入空氣，她都需要靠自己的一雙手。往後，大家將見證她如何與班多鈕手風琴一起抓緊更多「巧合」的機會。
						    </p>
						</div>
					</div>
				</div>

			</div>
		</div>
	</article>
    
     <div class="l-wrap">
        <div class="experience-list">
            <div class="blind">Sulwhasoo style list</div>
            <ul>
                
                <li class="experience-item">
                    <a href="/hk/zh/experience/sulwhasoo_style/cho-sang-kyung.html" class="thumb">
                        <img src="/media/html/experience/sulwhasoo_style/__icsFiles/afieldfile/2019/02/07/15421034050921.jpg" alt="服裝指導  Cho Sang Kyung">
                        <div class="cover">
                            <span class="title">服裝指導</span>
                            <b class="name">Cho Sang Kyung</b>
                        </div>
                    </a>
                </li>
                
                <li class="experience-item">
                    <a href="/hk/zh/experience/sulwhasoo_style/goh-sang-ji.html" class="thumb">
                        <img src="/media/html/experience/sulwhasoo_style/__icsFiles/afieldfile/2019/02/07/15385496872242.jpg" alt="音樂家  Goh Sang Ji">
                        <div class="cover">
                            <span class="title">音樂家</span>
                            <b class="name">Goh Sang Ji</b>
                        </div>
                    </a>
                </li>
                
                <li class="experience-item">
                    <a href="/hk/zh/experience/sulwhasoo_style/kim-yoona.html" class="thumb">
                        <img src="/media/html/experience/sulwhasoo_style/__icsFiles/afieldfile/2019/02/07/1534905539124.jpg" alt="歌手  金潤雅">
                        <div class="cover">
                            <span class="title">歌手</span>
                            <b class="name">金潤雅</b>
                        </div>
                    </a>
                </li>
                
                <li class="experience-item">
                    <a href="/hk/zh/experience/sulwhasoo_style/lee-ji-sun.html" class="thumb">
                        <img src="/media/html/experience/sulwhasoo_style/__icsFiles/afieldfile/2019/02/07/1528437138195.jpg" alt="設計師  李智善">
                        <div class="cover">
                            <span class="title">設計師</span>
                            <b class="name">李智善</b>
                        </div>
                    </a>
                </li>
                
            </ul>
        </div>
    </div>
</section>

<script>
	require([
	'jquery',
	], function ($) {
	    $(".sws-style-sticky").each(function (u, v) {
	    	console.log("sdkh");
	        var t = $(v),
	            s = t.parent();
	        $(window).on("scroll", function () {
	        	console.log(t.css("position"));
                if (t.css("position") !== "absolute") {
                    return;
                }
                console.log("ajs");
                t.css("top", n(t, s));
            }).scroll();
	        $(window).on("resize", function () {
	            var w = n(t, s);
	            if (t.css("position") !== "absolute") {
	                return;
	            }
	            t.css("top", w);
	        });
	        $('body').on("mousewheel", function () {
	            var x = event.wheelDelta / 8;
	            var w = window.pageYOffset;
	            window.scrollTo(0, w - x);
	        });
	    });
	    function n(w, v) {
	        var x = 0,
	            t = w.outerHeight(),
	            s = v.offset().top,
	            u = v.outerHeight();
	        if ($(window).scrollTop() > s) {
	            x = $(window).scrollTop() - s;
	            if (u - t + s < $(window).scrollTop()) {
	                x = u - t;
	            }
	        } else {
	            x = 0;
	        }
	        return x;
	    }
	});
</script>