<!--<title>宋慧喬 - 雪花秀風格 Sulwhasoo Style | 雪花秀</title>-->
<!--<meta name="description" content="雪花秀風格 Sulwhasoo Style 專訪 Actress 宋慧喬 面試詳情 | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="og:title" content="宋慧喬 - 雪花秀風格 Sulwhasoo Style | 雪花秀">-->
<!--<meta property="og:description" content="雪花秀風格 Sulwhasoo Style 專訪 Actress 宋慧喬 面試詳情 | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="twitter:title" content="宋慧喬 - 雪花秀風格 Sulwhasoo Style | 雪花秀">-->
<!--<meta property="twitter:description" content="雪花秀風格 Sulwhasoo Style 專訪 Actress 宋慧喬 面試詳情 | Sulwhasoo Hong Kong 中國香港">-->

<section class="content">
    <div class="blind">Sulwhasoo Style</div>
    
    <article class="sws-style">
		<div class="l-wrap l-full">
			<div class="basic style_basic"><div class="sws-style-visual">
				<h1 class="h1"><span class="title">Actress</span> <b class="name">宋慧喬</b></h1>
				<img src="/media/html/resource/img/experience/sulwhasoo_style/1522724573371.jpg" class="only-desktop" alt="">
				<img src="/media/html/resource/img/experience/sulwhasoo_style/1522724573371m.jpg" class="only-mobile" alt="">
				</div>

			</div>

		</div>

		<div class="l-wrap">
			<div class="sws-style-body">
				<div class="content static parbase">
					<div class="sws-style-section">
						<blockquote class="blockquote">
						<p class="quote break-word">最好遇上最好的極致演譯</p>
						</blockquote>
						<div class="sws-style-sticky">
							<img src="/media/html/resource/img/experience/sulwhasoo_style/15227244421621.jpg" alt="Actor Song Hye Kyo">
						</div>
						<div class="sws-style-desc">
							<p class="q">這是宋慧喬長期被擁戴的原因嗎？她為人所熟悉，但不會讓人看膩。她看起來總是充滿新鮮感的，而她總是恰到好處，從不突兀。</p>
							<p class="p">
							  電視編劇盧熙京這裡形容宋慧喬：「她很好地扮演了兩個不同性格之間的平衡，這是言語難以形容的。她是會讓人產生好奇的女演員。」她實至名歸成為雪花秀的新繆斯女神。<br>
							  「作為一個女演員，我不斷嘗試為人帶來新鮮感，但我更努力做好『女演員』的本份。每當我想到雪花秀時，我就會將她想像成為一位『女演員』。雪花秀總是讓人喜愛，不僅因爲一系列的產品，而是這品牌本身帶著一份原始魅力，親身接觸更覺其旖旎，這就是它一直被視為是最好品牌的原因。」<br>
							  她說很高興能與雪花秀合作，因為它是一個有堅定信念和意念的品牌。她一直認為信念是最重要的，而雪花秀代表了她作為女演員的信念。「那些堅持信念的人或品牌，能貫徹始終從不動搖，我一直想成為那些人中的一員，這樣我就能贏得別人的信任。」<br>
							  宋慧喬表示，雪花秀會在四月份才正式發佈有關合作，所以遺憾地未能在三月份這一期中和大家分享更多幕後消息。但幸運的是，我們可在對話中看到端倪。我們正準備再次向世界傳遞對美的定義。因為有著宋慧喬這位伙伴，一切將變得更有意義。 「這就是我喜歡的，不僅要堅持過去，而且要與現在相融。這並不像你想像的那麼容易，因為不是你所想的東西都能一一實現。隨著年日過去，你必須對原有的信念堅定不移，才能融入現在。我認為這是一個重要的關鍵。」
							</p>
							<p class="q">回望過去，這就是她的演戲方法。她從不固步自封。</p>
							<p class="p">
							  「我知道這是陳腔濫調，但我真的嘗試每一刻都竭盡所能。我一直認為『現在就是最重要的時刻』。我曾經認為傳統太沉重了，因為我們很多人對傳統的觀念有偏見，認為它很形式化和永遠不會改變的。但我在想，為什麼傳統就是這樣呢？保持不變並不是唯一的答案。傳統存在於我們這個時代，它不就應該與我們一同呼吸和理解我們的處境嗎？演戲也是如此。昨天的我只屬於昨天，今天必須成為全新的我。我與今天一起生活的人一同呼吸，所以我不就應該向他們展示今天的我嗎？這就是今天的宋慧喬，個性自然地融和於所演的角色之中。當然每次都很難，但我總是試著這樣做。」

							</p>
						</div>
					</div>

					<div class="sws-style-section">
						<div class="sws-style-sticky">
							<img src="/media/html/resource/img/experience/sulwhasoo_style/15227244421622.jpg" alt="Actor Song Hye Kyo">
						</div>
						<div class="sws-style-desc">
						<!--<p class="q"></p>

						<p class="p"></p>-->

						<blockquote class="blockquote">
						  <p class="quote break-word">「當你找到使你舒適的平衡時，生活的和諧或美麗自然會來到。」</p>
						</blockquote>

						<p class="q">她在生活中尋求平衡已有一段時間。她一直長時間工作著，自然希望平衡工作和私人生活。</p>
						<p class="p">
						  作為一個與大眾一同呼吸的人，她明白不能投放太多時間於自己的私人生活上，但同時也感到不應因為工作而失去自己的身份。她不時搖動，失去平衡，就好像站在平衡木上。但現在，尋找平衡對她來說，就如同坐在鞦韆上一樣愜意。<br>
						「我想答案很遙遠，但又近在眼前。當我遵循別人的標準時，我可能失去平衡，但這不適合我，我應該有自己的標準。平衡是按我個人的標準的。我認為每個人都應該找到自己的平衡點。即使你經歷了許多試驗和錯誤，但當你找到使你感到舒適的平衡時，生活的和諧或美麗自然會來到。我可以笑多一點，更積極地思考，來讓自己感覺更舒適。這些情緒都會自然地反映在我的面部表情和姿勢上。」 <br>
						她的回答使她看起來更加美麗，這就是她的標準，再沒有追問下去的必要。今天的宋慧喬，按照她的原則和標準保持生活平衡。她的美麗由內而外，完全發自內心。<br>
						嚴冬下的梅花更顯美麗。全球認可的最好與最好——宋慧喬與雪花秀，相互合作，從極致綻放出極致。縱然梅花將落，但新的美麗高潮卻即將展開。
						</p>
						</div>
					</div>
				</div>

			</div>
		</div>
	</article>
    
    
<div class="l-wrap">
    <div class="experience-list">
        <div class="blind">Sulwhasoo style list</div>
        	<ul>
            
	            <li class="experience-item">
	                <a href="/hk/zh/experience/sulwhasoo_style/cho-sang-kyung.html" class="thumb">
	                    <img src="/media/html/experience/sulwhasoo_style/__icsFiles/afieldfile/2019/02/07/15421034050921.jpg" alt="服裝指導  Cho Sang Kyung">
	                    <div class="cover">
	                        <span class="title">服裝指導</span>
	                        <b class="name">Cho Sang Kyung</b>
	                    </div>
	                </a>
	            </li>
	            
	            <li class="experience-item">
	                <a href="/hk/zh/experience/sulwhasoo_style/goh-sang-ji.html" class="thumb">
	                    <img src="/media/html/experience/sulwhasoo_style/__icsFiles/afieldfile/2019/02/07/15385496872242.jpg" alt="音樂家  Goh Sang Ji">
	                    <div class="cover">
	                        <span class="title">音樂家</span>
	                        <b class="name">Goh Sang Ji</b>
	                    </div>
	                </a>
	            </li>
	            
	            <li class="experience-item">
	                <a href="/hk/zh/experience/sulwhasoo_style/kim-yoona.html" class="thumb">
	                    <img src="/media/html/experience/sulwhasoo_style/__icsFiles/afieldfile/2019/02/07/1534905539124.jpg" alt="歌手  金潤雅">
	                    <div class="cover">
	                        <span class="title">歌手</span>
	                        <b class="name">金潤雅</b>
	                    </div>
	                </a>
	            </li>
	            
	            <li class="experience-item">
	                <a href="/hk/zh/experience/sulwhasoo_style/lee-ji-sun.html" class="thumb">
	                    <img src="/media/html/experience/sulwhasoo_style/__icsFiles/afieldfile/2019/02/07/1528437138195.jpg" alt="設計師  李智善">
	                    <div class="cover">
	                        <span class="title">設計師</span>
	                        <b class="name">李智善</b>
	                    </div>
	                </a>
	            </li>
                
            </ul>
        </div>
    </div>
</section>

<script>
	require([
	'jquery',
	], function ($) {
	    $(".sws-style-sticky").each(function (u, v) {
	    	console.log("sdkh");
	        var t = $(v),
	            s = t.parent();
	        $(window).on("scroll", function () {
	        	console.log(t.css("position"));
                if (t.css("position") !== "absolute") {
                    return;
                }
                console.log("ajs");
                t.css("top", n(t, s));
            }).scroll();
	        $(window).on("resize", function () {
	            var w = n(t, s);
	            if (t.css("position") !== "absolute") {
	                return;
	            }
	            t.css("top", w);
	        });
	        $('body').on("mousewheel", function () {
	            var x = event.wheelDelta / 8;
	            var w = window.pageYOffset;
	            window.scrollTo(0, w - x);
	        });
	    });
	    function n(w, v) {
	        var x = 0,
	            t = w.outerHeight(),
	            s = v.offset().top,
	            u = v.outerHeight();
	        if ($(window).scrollTop() > s) {
	            x = $(window).scrollTop() - s;
	            if (u - t + s < $(window).scrollTop()) {
	                x = u - t;
	            }
	        } else {
	            x = 0;
	        }
	        return x;
	    }
	});
</script>