<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Review\Block\Customer\View $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

$product = $block->getProductData();
?>
<?php if ($product->getId()): ?>
    <div class="customer-review view">
        <div class="customer-review-heading"><h2><?= __('Review') ?></h2></div>
        <div class="product-details">
            <div class="product-media">
                <a class="product-photo" href="<?= $block->escapeUrl($product->getProductUrl()) ?>">
                    <?php /* customer_account_product_review_page */ ?>
                    <?= $block->getImage($block->getProductData(), 'customer_account_product_review_page')->toHtml() ?>
                </a>
            </div>
            <div class="product-info">
                <h2 class="product-name"><?= $block->escapeHtml($product->getName()) ?></h2>
            </div>
        </div>

        <div class="review-details">
            <?php if ($block->getRating() && $block->getRating()->getSize()): ?>
                <div class="title">
                    <strong><?= $block->escapeHtml(__('Your Review')) ?></strong>
                </div>
                <div class="customer-review-rating">
                    <div class="sub-title">
                        <strong><?= $block->escapeHtml(__('Rating')) ?></strong>
                    </div>
                    <?php foreach ($block->getRating() as $_rating): ?>
                        <?php if ($_rating->getPercent()): ?>
                            <?php $rating = ceil($_rating->getPercent()) ?>
                            <?php $ratingId = $_rating->getRatingId() ?>
                            <div class="rating-summary item">
                            <span class="rating-label">
                                <span><?= $block->escapeHtml($_rating->getRatingCode()) ?></span>
                            </span>
                                <div class="rating-result <?= $block->escapeHtml($_rating->getRatingCode()) ?>"
                                     id="rating-div-<?= $block->escapeHtml($ratingId) ?>"
                                     title="<?= /* @noEscape */ $rating ?>%">
                                <span>
                                    <span><?= /* @noEscape */ $rating ?>%</span>
                                </span>
                                </div>
                                <?= /* @noEscape */
                                $secureRenderer->renderStyleAsTag(
                                    "width:" . /* @noEscape */ $rating . "%",
                                    'div#rating-div-'.$_rating->getRatingId().
                                    '>span:first-child'
                                ) ?>
                            </div>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>

            <div class="review-title"><?= $block->escapeHtml($block->getReviewData()->getTitle()) ?></div>
            <div class="review-content">
                <?= /* @noEscape */ nl2br($block->escapeHtml($block->getReviewData()->getDetail())) ?>
            </div>
            <div class="review-date">
                <?= $block->escapeHtml(__('Submitted on %1', '<time class="date">' .
                    $block->dateFormat($block->getReviewData()->getCreatedAt()) . '</time>'), ['time']) ?>
            </div>

            <?= $this->getLayout()->createBlock("Amasty\AdvancedReview\Block\Images")->setReviewId($block->getReviewData()->getId())->setTemplate("Amasty_AdvancedReview::images_detail.phtml")->toHtml() ?>

        </div>
    </div>
    <div class="actions-toolbar">
        <a class="btn-default-dark btn-default-big" href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
            <span><?= $block->escapeHtml(__('Back to the list')) ?></span>
        </a>
    </div>
<?php endif; ?>
