<?php if ($block->getItems()): ?>
<div class="giftset_home_content giftset_tab_content">
    <div class="giftset_tab main-recommendation-slider">
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <h2 class="ex-title">專屬推薦</h2>
            <hr/>
            <div class="data item content giftset-contents-slider">
                <?php
                /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
                ?>
                    <?php
                    $_helper = $this->helper(Magento\Catalog\Helper\Output::class);
                    $optionDataHelper = $this->helper(Sapt\Catalog\Helper\OptionData::class);
                    $sliderId = $block->getData('id') ?: 'products-slider';
                    $showProgress = $block->getData('progress') ?: false;
                    $type = 'widget-product-grid';
                    $mode = 'grid';
                    $image = 'new_products_content_widget_grid';
                    $items = $block->getItems();

                    $showWishlist = true;
                    $showCompare = false;
                    $showCart = true;
                    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
                    $description = false;
                    ?>
                    <div class="block widget block-products-slider block-products-list <?= /* @noEscape */ $mode ?>">
                        <?php if ($block->getTitle()): ?>
                            <div class="block-title">
                                <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
                            </div>
                        <?php endif ?>
                        <div class="block-content">
                            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
                            <div id="<?= $sliderId ?>" class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
                                <ol class="product-items products list items <?= /* @noEscape */ $type ?>">
                                    <?php $iterator = 1; ?>
                                    <?php foreach ($items as $_item) : ?>
                                        <?php /* @noEscape */ $productSku = $_item->getSku() ?>
                                        <?= /* @noEscape */ ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                                        <div class="product-item-wrapper">
                                            <div class="product-item-info">
                                                <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                                   class="product-item-photo"
                                                   ap-click-area="product"
                                                   ap-click-name="prd click"
                                                   ap-click-data="<?= /* @noEscape */ $block->getProductDefaultName($productSku) . '/' . $productSku; ?>">
                                                    <?= $block->getImage($_item, $image)->toHtml() ?>
                                                </a>
                                                <?php if ($_item->getProductLabels()): ?>
                                                    <div class="product_labels">
                                                        <?php echo $_helper->productAttribute($_item, $_item->getProductLabels(), 'product_labels') ?>
                                                    </div>
                                                <?php endif;?>
                                                <div class="product-item-details">
                                                    <div class="product_tags">
                                                        <?php if ($_item->getProductTags()): ?>
                                                            <?php echo $_helper->productAttribute($_item, $_item->getProductTags(), 'product_tags') ?>
                                                        <?php endif;?>
                                                    </div>
                                                    <?php if($_item->getData('new')):?>
                                                        <span class="product-item-flag"><?= $block->escapeHtml($_item->getResource()->getAttribute('new')->getStoreLabel());?></span>
                                                    <?php endif;?>
                                                    <?php if($_item->getData('best')):?>
                                                        <span class="product-item-flag"><?= $block->escapeHtml($_item->getResource()->getAttribute('best')->getStoreLabel()); ?></span>
                                                    <?php endif;?>
                                                    <strong class="product-item-name">
                                                        <a title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                                           href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                                           class="product-item-link"
                                                           ap-click-area="product"
                                                           ap-click-name="prd click"
                                                           ap-click-data="<?= /* @noEscape */ $block->getProductDefaultName($productSku) . '/' . $productSku; ?>">
                                                            <?= $block->escapeHtml($_item->getName()) ?>
                                                        </a>
                                                    </strong>
                                                    <div class="product-item-short-description">
                                                        <?= $this->helper(Magento\Catalog\Helper\Output::class)->productAttribute($_item, $_item->getShortDescription(), 'short_description') ?>
                                                    </div>

                                                    <?= $block->getProductPrice($_item) ?>

                                                    <div class="product-item-inner">
                                                        <div class="product-item-actions">
                                                            <div class="actions-primary">
                                                                <?php if ($showCart): ?>
                                                                    <?php if ($_item->isSaleable()): ?>
                                                                        <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                                        $postData = $postDataHelper->getPostData($block->escapeUrl($block->getAddToCartUrl($_item)), ['product' => $_item->getEntityId()])
                                                                        ?>
                                                                        <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                                            <?php if ($_item->getTypeId() == 'bundle'):?>
                                                                                <?php $bundleOptions = []; ?>
                                                                                <?php $selectionCollection = $_item->getTypeInstance(true)->getSelectionsCollection($_item->getTypeInstance(true)->getOptionsIds($_item),$_item);
                                                                                foreach ($selectionCollection as $selection) {
                                                                                    $valueSelect = '';
                                                                                    if ($selection->getIsDefault() && $selection->isSaleable()) {
                                                                                        $valueSelect = $selection->getSelectionId();
                                                                                    }
                                                                                    $bundleOptions[$selection->getOptionId()] = $valueSelect;
                                                                                    ?>
                                                                                <?php }
                                                                                $postData = $postDataHelper->getPostData($block->escapeUrl($block->getAddToCartUrl($_item)), ['product' => $_item->getEntityId(), 'bundle_option' => $bundleOptions])
                                                                                ?>
                                                                                <?php
                                                                                ?>
                                                                            <?php endif;?>
                                                                            <button class="action tocart primary"
                                                                                    clicktext="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                                    formtext="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                                    data-post='<?= /* @escapeNotVerified */ $postData ?>'
                                                                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                                            </button>
                                                                        <?php else: ?>
                                                                            <button class="action tocart primary"
                                                                                    clicktext="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                                    formtext="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                                    data-post='<?= /* @escapeNotVerified */ $postData ?>'
                                                                                    type="button" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                                            </button>
                                                                        <?php endif; ?>
                                                                    <?php else: ?>
                                                                        <button class="action tocart primary disabled"
                                                                                type="button" disabled
                                                                                title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                                            <span><?= $block->escapeHtml(__('Sold out')) ?></span>
                                                                        </button>
                                                                    <?php endif; ?>
                                                                <?php endif?>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                        <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
                                    <?php endforeach ?>
                                </ol>
                                <?php if ($showProgress): ?>
                                    <div class="progress"><span class="progress_ing"></span></div>
                                <?php endif; ?>
                            </div>
                            <?= $block->getPagerHtml() ?>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</div>
<?php endif;?>
<script type="text/javascript">
    require(['jquery', 'slick'], function($, slick) {
        $(document).ready(function() {
            $('.giftset-contents-slider').each(function(index, element) {
                var $prdRecomm =  $(this).find('.product-items'),
                    $prdRecommProgressBar = $(this).find('.progress .progress_ing'),
                    $prdRecommSlidesToShow = 4;
                
                $prdRecomm.on('init', function(event, slick){
                    (window.innerWidth > 768) ? $prdRecommSlidesToShow = 4 : $prdRecommSlidesToShow = 1.56;
                    var calc = (100 / (slick.slideCount / $prdRecommSlidesToShow));

                    $prdRecommProgressBar.css({
                        'width': calc + '%',
                    });
                });

                $prdRecomm.slick({
                    dots:false,
                    slidesToShow: $prdRecommSlidesToShow,
                    slidesToScroll: $prdRecommSlidesToShow,
                    infinite: false,
                    responsive: [
                        {
                            breakpoint: 768,
                            settings: {
                                dots: true,
                                autoplay: true,
                                slidesToShow: 1.56,
                                slidesToScroll: 1,
                                prevArrow: false,
                                nextArrow: false
                            }
                        },
                    ]
                }).on('beforeChange', function(event, slick, currentSlide, nextSlide){
                    (window.innerWidth > 768) ? $prdRecommSlidesToShow = 4 : $prdRecommSlidesToShow = 1.56;
                    var calc = (100 / (slick.slideCount / $prdRecommSlidesToShow)) * ((nextSlide / $prdRecommSlidesToShow) + 1);

                    $prdRecommProgressBar.css({
                        'width': calc + '%',
                    });
                });
            });
        })
    });
</script>
<style>
    .cart-discount .product-item-info {
        display: flex;
        padding: 16px;
        margin-bottom: 0 !important;
    }

    .cart-discount .product-item-photo {
        width: 28%;
    }

    .cart-discount .product-item-details {
        width: 50%;
        padding: 5px !important;
        text-align: left;
        align-items: flex-start !important;
        display: block !important;
    }

    .cart-discount .slick-slide {
        width: 50% !important;
        background: #d2d7f91a;
    }

    .cart-discount .slick-track {
        opacity: 1;
        transform: translate3d(0px, 0px, 0px);
        display: flex;
    }

    .cart-discount .block-static-block {
        width: 100%;
        padding: 0;
    }

    .cart-discount .product-reviews-summary {
        display: none !important;
    }

    .cart-discount .actions-secondary {
        display: none !important;
    }

    .cart-discount .product-image-container {
        padding: 0px !important;
        background: none !important;
    }

    .cart-discount .tocart {
        background: none !important;
        border: 0px solid #333 !important;
        margin-top: 0px !important;
        padding: 0 !important;
        color: #333 !important;
    }

    .cart-discount .product_tags {
        display: none !important;
    }

    .cart-discount .tocart::after {
        content: '\e905';
        font-family: 'icons';
        font-size: 11px;
        margin-left: 2px;
    }

    .cart-discount .block {
        border: 0px solid #333 !important;
        padding: 0px !important;
    }

    .cart-discount .ex-title {
        text-align: left;
        font-size: 20px;
        font-weight: bolder;
    }

    .cart-discount .tocart:hover {
        background: none !important;
    }

    .cart-discount .giftset-contents-slider {
        margin-top: 18px !important;
    }

    .cart-discount .product-item-name {
        margin: -9px 0 0 !important;
    }

    .cart-discount .product-item-link {
        font-weight: bold;
    }

    .cart-discount .product-item .price-box {
        margin: 0px 0 6px !important;
    }

    @media only screen and (max-width: 768px) {
        .cart-discount .giftset-contents-slider {
            padding: 0 !important;
        }

        .cart-discount .tocart span {
            color: #333 !important;
            font-size: 12px !important;
        }

        .cart-discount {
            width: 100% !important;
        }

        .cart-discount .block {
            padding: 0 !important;
        }

        .main-recommendation-slider {
            margin-left: 0px !important;
        }

        .cart-discount .product-item-info {
            padding: 5px !important;
        }
    }

    .cart-discount .tocart:hover {
        background: none !important;
    }

    .cart-discount .tocart:active {
        background: none !important;
    }

    .products-grid .product-item .product-item-details .actions-primary .tocart:hover {
        background: none !important;
        background-color: #ffffff !important;
        border-color: #ffffff !important;
    }

    .products-grid .product-item .product-item-details .actions-primary .tocart:focus {
        background: none !important;
        background-color: #fff !important;
    }
</style>