<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 * @var $catalogHelper \CJ\CatalogProduct\Helper\Data
 */
?>
<?php if ($block->getCollection()->getSize()) :?>
    <?php $widget = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonDecode($block->getWidgetOptionsJson());
    $widgetOptions = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($widget['productListToolbarForm']);
    $catalogHelper = $this->helper(\CJ\CatalogProduct\Helper\Data::class);
    $onsale = $block->getRequest()->getParam('on_sale') ?? 0;

    ?>
    <div class="toolbar toolbar-products" data-mage-init='{"productListToolbarForm":<?= /* @noEscape */ $widgetOptions ?>}'>
        <?php if($catalogHelper->getEnableFilterOnSale($block->getStoreId())): ?>
            <div id="on-sale-box" class="field choice sale_filter">
                <input type="checkbox" name="on_sale" class="checkbox" id="on_sale" title="On Sale" <?= $onsale ? 'checked':'' ?>
                       onclick="javascript:location.href='<?= $block->getPagerUrl(['on_sale' => $onsale ? 0 : 1 ]) ?>'">
                <label for="on_sale" class="label"><span><?= __('On Sale') ?></span></label>
            </div>
        <?php endif; ?>
        <?php if ($block->getIsBottom()): ?>
            <?= $block->getPagerHtml() ?>
            <?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/limiter.phtml')) ?>
        <?php else: ?>
            <?php if ($block->isExpanded()): ?>
                <?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/viewmode.phtml')) ?>
            <?php endif ?>
            <?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/amount.phtml')) ?>
            <?php if ($block->isExpanded()): ?>
                <?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/sorter.phtml')) ?>
            <?php endif ?>
        <?php endif ?>
    </div>
<?php endif ?>
