<?php

/**
 * @var \Eguana\Faq\Block\Faq $block
 */

$categoryData = $block->getCategoryOptionArray();
$faqData = $block->getFaqBindData();
?>
<?php if ($block->isShowFaqInPDP()):?>
    <div class="faqs-page">
    <?php foreach ($categoryData as $key => $value):?>
        <?php if (!empty($faqData[$key])):?>
            <div class="block">
                <div class="item title" data-role="tab-collapsible">
                    <strong class="switch"
                            role="heading"
                            data-toggle="trigger"
                            data-role="tab-title"
                            aria-level="2">
                        <?= $block->escapeHtml($value) ?>
                    </strong>
                </div>
                <div class="item content" data-role="tab-content">
                    <div class="lists"
                         data-mage-init='{"accordion":{
                             "collapsible": true,
                             "animate": {"duration": 300},
                             "openedState": "_active",
                             "active": false,
                             "multipleCollapsible": true}}'>
                        <?php foreach ($faqData[$key] as $faq):?>
                            <div class="list">
                                <div data-role="collapsible">
                                    <div class="title" data-role="title">
                                        <span><?= $block->escapeHtml($faq->getTitle()) ?></span>
                                    </div>
                                </div>
                                <div class="content" data-role="content">
                                    <?= /* @noEscape */ $block->descriptionFilter($faq->getDescription()) ?>
                                </div>
                            </div>
                        <?php endforeach;?>
                    </div>
                </div>
            </div>
        <?php endif;?>
    <?php endforeach;?>
</div>
<?php endif;?>
