<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php
$isSalable = $block->getProduct()->getIsSalable();
if ($isSalable) {
    $availability = 'InStock';
} else {
    $availability = 'OutOfStock';
}
?>
<script type="application/ld+json">
    {
        "@context": "https://schema.org/",
        "@type": "Product",
        "name": "<?= /* @noEscape */ $block->escapeHtml($block->getProduct()->getName()) ?>",
        "productID": "<?= /* @noEscape */ $block->escapeHtml($block->getProduct()->getSku()) ?>",
        "image": "<?= $block->escapeUrl($block->getImage($block->getProduct(), 'product_base_image')->getImageUrl()) ?>",
        "description": "<?= /* @noEscape */ $block->escapeHtml($block->getProduct()->getShortDescription()) ?>",
        "offers": {
            "price": "<?= /* @noEscape */ $block->escapeHtml($block->getProduct()->getFinalPrice()) ?>",
            "priceCurrency": "TWD",
            "availability": "<?= $availability ?>"
        }
    }
</script>
