<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
/** @var \Magento\ConfigurableProduct\Pricing\Render\FinalPriceBox$block */

/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
$oldPrice = $priceModel->getAmount()->getValue();
$discountedPrice = $finalPriceModel->getAmount()->getValue();
$discountPercent = $oldPrice ? ($oldPrice - $discountedPrice) * 100 / $oldPrice : false;
?>
<p class="price-title configurable-price-title"><?= $block->escapeHtml(__('Price')) ?></p>
<div>
    <?php if (!$block->isProductList() && $block->hasSpecialPrice()): ?>
        <?php if ($discountPercent): ?>
            <span class="discount-label"><?= $discountPercent ?>%</span>
        <?php endif; ?>
        <span class="old-price sly-old-price no-display">
            <?php /* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [
                'display_label'     => __('Price'),
                'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
                'price_type'        => 'oldPrice',
                'include_container' => true,
                'skip_adjustments'  => true
            ]); ?>
        </span>
        <span class="special-price config-special-price">
            <?php
            $arguments = [
                'display_label' => __('As low as'),
                'price_id' => $block->getPriceId('product-price-' . $idSuffix),
                'price_type' => 'finalPrice',
                'include_container' => true,
                'schema' => $schema
            ];

            /* @noEscape */ echo $block->renderAmount($finalPriceModel->getAmount(), $arguments);
            ?>
        </span>
    <?php elseif ($block->isProductList() && $block->hasSpecialPrice()): ?>
        <?php if ($discountPercent): ?>
            <span class="discount-label"><?= $discountPercent ?>%</span>
        <?php endif; ?>
        <span class="old-price">
            <?php /* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [
                'display_label'     => __('Regular Price'),
                'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
                'price_type'        => 'oldPrice',
                'include_container' => true,
                'skip_adjustments'  => true
            ]); ?>
        </span>
        <span class="special-price">
            <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
                'display_label'     => __('Special Price'),
                'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                'price_type'        => 'finalPrice',
                'include_container' => true,
                'schema' => $schema
            ]); ?>
        </span>
    <?php elseif (!$block->isProductList()):?>
        <span class="normal-price">
            <?php
            $arguments = [
                'display_label' => __('As low as'),
                'price_id' => $block->getPriceId('product-price-' . $idSuffix),
                'price_type' => 'finalPrice',
                'include_container' => true,
                'schema' => $schema
            ];

            /* @noEscape */ echo $block->renderAmount($finalPriceModel->getAmount(), $arguments);
            ?>
        </span>
    <?php elseif ($block->isProductList()): ?>
        <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
            'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
            'price_type'        => 'finalPrice',
            'include_container' => true,
            'schema' => $schema
        ]); ?>
    <?php endif; ?>
    <?php if ($block->showMinimalPrice()): ?>
        <?php if ($block->getUseLinkForAsLowAs()):?>
            <a href="<?= /* @escapeNotVerified */ $block->getSaleableItem()->getProductUrl() ?>" class="minimal-price-link">
                <?= /* @escapeNotVerified */ $block->renderAmountMinimal() ?>
            </a>
        <?php else:?>
            <span class="minimal-price-link">
                <?= /* @escapeNotVerified */ $block->renderAmountMinimal() ?>
            </span>
        <?php endif?>
    <?php endif; ?>
</div>
