<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Sales\Block\Order\History $block */

?>
<?php $_orders = $block->getOrders(); ?>
<?= $block->getChildHtml('info') ?>
<div class="order-history-tabs">
    <ul class="items order-links">
        <li class="nav item current"><strong><?= __('Order') ?></strong></li>
        <li class="nav item"><a href="<?= $block->getUrl('rma/returns/history') ?>"><?= __('Refund') ?></a></li>
    </ul>
    <div id="order_history" class="item content" data-role="content">
        <div class="orders-history">
            <?php if ($_orders && count($_orders)): ?>
                <script>
                    var AP_REVIE_PRD = '';
                    var AP_REVIE_PRDCODE = '';
                    var AP_REVIE_RATING = '';
                    var AP_REVIE_PICTURE = '';
                    var AP_REVIE_CONTENT = '';
                </script>
                <?php /** @var \Magento\Sales\Model\Order $_order */ ?>
                <?php foreach ($_orders as $_order): ?>
                    <div class="order-wrapper">
                        <a href="<?= $block->getUrl('sales/order/view', ['order_id' => $_order->getId()]) ?>"><?= $block->formatDate($_order->getCreatedAt()) ?></a>
                        <?php $itemBlock = $block->getChildBlock('order_items')->setOrder($_order) ?>
                        <?= $itemBlock->toHtml() ?>
                    </div>
                <?php endforeach; ?>

                <script type="text/javascript">
                    require([
                        "jquery",
                        "Magento_Ui/js/modal/modal",
                        'mage/url',
                    ],function($, modal, urlBuilder) {
                        var options = {
                            type: 'popup',
                            responsive: true,
                            innerScroll: true,
                            modalClass: "add-review-modal",
                            title: "<?= __('Write a review')?>",
                            buttons: []
                        };

                        $(".actions a.btn.review").click(function() {
                            var orderItemId = $(this).data('order-item-id');
                            modal(options, $('.block.review-add.review-product-'+orderItemId));
                            $('.block.review-add.review-product-'+orderItemId).show();
                            $('.block.review-add.review-product-'+orderItemId).modal('openModal');
                            return true;
                        });
                    })
                </script>
            <?php else: ?>
                <p class="no-order">
                    <?= $block->escapeHtml(__('You have placed no orders.')) ?>
                </p>
            <?php endif ?>
        </div>
        <?php if ($block->getPagerHtml()): ?>
            <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
        <?php endif ?>
    </div>
</div>

