<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 * @var $catalogHelper \CJ\CatalogProduct\Helper\Data
 */
?>
<?php if ($block->getCollection()->getSize()) :?>
    <?php $widget = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonDecode($block->getWidgetOptionsJson());
    $widgetOptions = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($widget['productListToolbarForm']);
    //$catalogHelper = $this->helper(\CJ\CatalogProduct\Helper\Data::class);
    $onsale = $block->getRequest()->getParam('on_sale') ?? 0;

    ?>
    <?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');//get current category
    ?>
    <div class="toolbar toolbar-products" data-mage-init='{"productListToolbarForm":<?= /* @noEscape */ $widgetOptions ?>}'>

        <?php if ($block->getIsBottom()): ?>
        <?php else: ?>
            <div class="category-filter-items">
                <p><?= $category->getName(); ?></p><?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/amount.phtml')) ?>
            </div>
        <?php endif ?>

        <?php //if($catalogHelper->getEnableFilterOnSale($block->getStoreId())): ?>
            <!-- <div id="on-sale-box" class="field choice sale_filter">
                <input type="checkbox" name="on_sale" class="checkbox" id="on_sale" title="On Sale" <?php //$onsale ? 'checked':'' ?>
                       onclick="javascript:location.href='<?php //$block->getPagerUrl(['on_sale' => $onsale ? 0 : 1 ]) ?>'">
                <label for="on_sale" class="label"><span><?php //__('On Sale') ?></span></label>
            </div> -->
        <?php //endif; ?>
        <?php if ($block->getIsBottom()): ?>
            <?= $block->getPagerHtml() ?>
            <?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/limiter.phtml')) ?>
        <?php else: ?>
            <?php if ($block->isExpanded()): ?>
                <?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/viewmode.phtml')) ?>
            <?php endif ?>
            <?php if ($block->isExpanded()): ?>
                <?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/sorter.phtml')) ?>
            <?php endif ?>
        <?php endif ?>
    </div>
<?php endif ?>
