<?php
/**
 * Created by Eguana Team.
 * User: sonia
 * Date: 6/21/20
 * Time: 8:36 AM
 */

namespace Eguana\GWLogistics\Test\Unit\Controller\Test;

use Eguana\GWLogistics\Controller\Test\Index;
use PHPUnit\Framework\TestCase;

class IndexTest extends TestCase
{
    private $test;

    protected function setUp()
    {
        $objectManager = new \Magento\Framework\TestFramework\Unit\Helper\ObjectManager($this);
        $this->test = $objectManager->getObject(Index::class);
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testExecute()
    {
        $this->expectOutputString('');
        $this->test->execute();

    }
}
