<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Wishlist\Block\Customer\Wishlist $block */
/** @var \Magento\Wishlist\Helper\Data $helper */
/** @var \Magento\Framework\Data\Helper\PostHelper $postDataHelper */

use Magento\Framework\App\ActionInterface;

$helper = $this->helper(\Magento\Wishlist\Helper\Data::class);
$postDataHelper = $this->helper(\Magento\Framework\Data\Helper\PostHelper::class);
$wishlist = $block->getWishlistInstance();
$removeAllParams = $postDataHelper->getPostData(
    $this->getUrl('wishlist/index/removeall'),
    ['wishlist_id' => $wishlist->getId(), ActionInterface::PARAM_NAME_URL_ENCODED => '']
);
?>

<?php if ($helper->isAllow()) : ?>
    <?= ($block->getChildHtml('wishlist.rss.link')) ?>
    <form class="form-wishlist-items" id="wishlist-view-form"
          data-mage-init='{"wishlist":{
          "addToCartUrl":<?= /* @noEscape */ $block->getItemAddToCartParams("%item%") ?>,
          "addAllToCartUrl":<?= /* @noEscape */ $block->getAddAllToCartParams() ?>,
          "removeAllItemUrl":<?= /* @noEscape */ $removeAllParams ?>,
          "commentString":""},
          "validation": {}}' action="<?= $block->escapeUrl($block->getUrl('wishlist/index/update', ['wishlist_id' => $block->getWishlistInstance()->getId()])) ?>" method="post">
        <?= $block->getChildHtml('top') ?>
        <?php if ($block->hasWishlistItems()): ?>
            <div class="top-wishlist">
                <div class="total"><?= __('Total %1', $helper->getItemCount()) ?></div>
                <div class="actions-toolbar">
                    <div class="primary">
                        <?= $block->getChildHtml('control_buttons') ?>
                    </div>
                </div>
            </div>
            <input type="hidden" name="wishlist_id" value="<?= $wishlist->getId() ?>"/>
            <?= $block->getBlockHtml('formkey') ?>
            <?php $block->getChildBlock('items')->setItems($block->getWishlistItems()); ?>
            <?= $block->getChildHtml('items') ?>
        <?php else: ?>
            <div class="empty"><span><?= $block->escapeHtml(__('Your Wishilist Is Empty.')) ?></span></div>
        <?php endif ?>
        <?= $block->getChildHtml('bottom') ?>
    </form>
    <script id="form-tmpl" type="text/x-magento-template">
        <form id="wishlist-hidden-form" method="post" action="<%- data.url %>" class="no-display">
            <% if (data.qty) { %>
            <input name="qty" value="<%- data.qty %>">
            <% } %>

            <% if (data.item) { %>
            <input name="item" value="<%- data.item %>">
            <% } %>

            <% if (data.entity) { %>
            <input name="entity" value="<%- data.entity %>">
            <% } %>
        </form>
    </script>
    <div class="toolbar wishlist-toolbar"><?= $block->getChildHtml('wishlist_item_pager'); ?></div>
<?php endif ?>
