<?php
/** @var \Magento\Wishlist\Block\Catalog\Product\View\AddTo\Wishlist $block */
/** @var \Sapt\AjaxWishlist\ViewModel\AjaxWishlistStatus $viewModel */
?>
<?php if ($block->isWishListAllowed()): ?>
    <?php $viewModel = $block->getData('moduleStatusViewModel'); ?>
    <?php if ($viewModel->moduleStatus()): ?>
        <!-- ko scope: 'ajaxwishlist' -->
        <a
            class="action towishlist"
            clicktext="<?= $block->escapeHtml(__('Add to Wishlist')) ?>"
            formtext="<?= $block->escapeHtml(__('Add to Wishlist')) ?>"
            data-bind="css:{wishlisticon : wishlistitem().all_wishlist_items ?
       typeof wishlistitem().all_wishlist_items[<?=/* @noEscape */$block->getProduct()->getId()?>] !='undefined':false}"
            data-product-id='<?= /* @noEscape */$block->getProduct()->getId() ?>'
            data-action="wishlist-actions"><span><?= $block->escapeHtml(__('Add to Wish List')) ?></span></a>
        <!-- /ko -->
    <?php else: ?>
        <a href="#"
           clicktext="<?= $block->escapeHtml(__('Add to Wishlist')) ?>"
           formtext="<?= $block->escapeHtml(__('Add to Wishlist')) ?>"
           class="action towishlist"
           data-post='<?= /* @noEscape */ $block->getWishlistParams() ?>'
           data-action="add-to-wishlist"><span><?= $block->escapeHtml(__('Add to Wish List')) ?></span></a>
    <?php endif; ?>
<?php endif; ?>


