<?php
/**
 * Created by Eguana Team.
 * User: sonia
 * Date: 9/4/20
 * Time: 10:23 AM
 */

/** @var \Magento\Framework\View\Element\Template $block */
?>
<?php if ($block->getEventName()) : ?>
<script type="text/x-magento-init">
    {
        "*": {
            "Amore_GaTagging/js/add-to-cart": {
                "eventName": "<?= /* @noEscape */$block->getEventName() ?>"
            }
        }
    }
</script>
<?php endif ?>
