<?php
/**
 * Created by Eguana Team.
 * User: sonia
 * Date: 7/19/20
 * Time: 9:15 AM
 */
?>
<?php
/** @var \Amore\GaTagging\Block\GaTagging $block */
$currentProduct = $block->getCurrentProduct();
$productHelper = $this->helper("Magento\Catalog\Helper\Product");
$gaTaggingHelper = $this->helper("Amore\GaTagging\Helper\Data");
$productInfo = $block->getProductInfo($currentProduct);
// Get original price
$originalPrice = $block->getProductOriginalPrice($currentProduct);
// Get Discounted price
$price = $block->getProductDiscountedPrice($currentProduct);
$productImageUrl = $productHelper->getThumbnailUrl($currentProduct);
$qty = ($currentProduct->isSaleable()) ? $block->getProductDefaultQty($currentProduct) * 1 : 0;
?>
<script>
    var AP_DATA_PAGETYPE = "<?= $block->getPageType()?>";
    //상품상세 todo additional AP
    var AP_ECOMM_CURRENCY = "<?=$block->getCurrentCurrencyCode()?>";
    var AP_PRD_NAME = "<?= $block->escapeHtml($currentProduct->getName())?>";
    var AP_PRD_CODE = "<?= $block->escapeHtml($currentProduct->getSku())?>";
    var AP_PRD_PRDPRICE = "<?= $block->escapeHtml($originalPrice) ?>";
    var AP_PRD_PRICE = "<?= $block->escapeHtml($price)?>";
    var AP_PRD_BRAND = "<?= $block->escapeHtml($gaTaggingHelper->getSiteName() ?? '')?>";
    var AP_PRD_URL = "<?= $block->escapeHtml($currentProduct->getProductUrl()) ?>";
    var AP_PRD_CATEGORY = "<?= $block->escapeHtml($block->getProductCategory($currentProduct))?>";
    var AP_PRD_APGBRCODE = "<?= substr($currentProduct->getSku(), 0, 5)?>"
    var AP_PRD_IMG_URL = "<?= $block->escapeUrl($productImageUrl)  ?>";
    var AP_PRD_QTY = <?= $block->escapeHtml($qty) ?>;
    var AP_PRD_ISTOCK = <?=$currentProduct->getIsSalable()?>;
    var AP_PRD_DISCOUNT = <?=$originalPrice - $price?>;
    var PRD_DATA = [
        <?php foreach($productInfo as $info) : ?>
        <?= $info ?>,
        <?php endforeach; ?>
    ];
</script>

