<!--<title>雪花秀2020限量版彩妝系列<br>Spring Into Happiness<br>韓式粉嫩春妝氣色 綻放春日迷人氣息 | 雪花秀</title>-->
<!--<meta name="description" content="雪花秀資訊 - 雪花秀2020限量版彩妝系列<br>Spring Into Happiness<br>韓式粉嫩春妝氣色 綻放春日迷人氣息 | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="og:title" content="雪花秀2020限量版彩妝系列<br>Spring Into Happiness<br>韓式粉嫩春妝氣色 綻放春日迷人氣息 | 雪花秀">-->
<!--<meta property="og:description" content="雪花秀資訊 - 雪花秀2020限量版彩妝系列<br>Spring Into Happiness<br>韓式粉嫩春妝氣色 綻放春日迷人氣息 | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="twitter:title" content="雪花秀2020限量版彩妝系列<br>Spring Into Happiness<br>韓式粉嫩春妝氣色 綻放春日迷人氣息 | 雪花秀">-->
<!--<meta property="twitter:description" content="雪花秀資訊 - 雪花秀2020限量版彩妝系列<br>Spring Into Happiness<br>韓式粉嫩春妝氣色 綻放春日迷人氣息 | Sulwhasoo Hong Kong 中國香港">-->
<section class="content renewal-archive-detail">
		
	<!-- S : ICS + 부분 HTML 영역으로 사용하는 경우 (Beauty Ritual, News, Print, film) -->
    
	<div class="archive-section">
        <div class="archive-header">
            <div class="header-inner">
                <h1 class="h">雪花秀2020限量版彩妝系列<br>Spring Into Happiness<br>韓式粉嫩春妝氣色 綻放春日迷人氣息</h1>
				<span class="type">News</span>
				<span class="date">2020.02.24</span>
			</div>
		</div>
		<!-- S : 이미지인 경우 Beauty Ritual, News, Print-->
        
		<!-- Beauty Ritual은 video 존재 유무에 따라 타입이 나눠짐-->
		
		
		<div class="archive-content">
			
			<figure class="archive-image">
				<img src="/media/html/experience/archive/__icsFiles/afieldfile/2021/08/23/spring_collection_thumbnail_new_hk_1.jpg" alt="Sulwhasoo launches its new “2020 Spring Limited Collection”">
			</figure>
			
			<div class="archive-static-body">
				<!-- HTML or text 삽입 -->
				<div class="print-copy">
					<div class="content static parbase about-view-content">
						<style>
						.l-about .tit-list, 
						.l-about h3, 
						.product-line h4, 
						.prod-text .prod-sub-tit {color:#555;}
						.product-line:after {display:block;content:"";clear:both;}
						.news-view-content .product-line .prod-desc {width:100%;}
						.news-view-content .l-about h3 {margin-top:20px;margin-bottom:10px;}
						.product-line h4 {display:inline-block;margin-bottom:10px;font-weight:bold;border-bottom:1px solid #555;line-height:1.5;}
						.product-line .prod-text .prod-price {display:block;margin-top:10px;font-weight:bold;}
						.news-view-content .product-line .prod-text {padding-top:0;}
						.news-view-content .product-line .prod-text .prod-sub-txt-list li {padding-top:10px;}
						.rel-date {color:#555;text-align:right;}
						.l-about .tit-list {text-align:center;}
						.l-about .tit-list li {margin-bottom:10px;font-size:1.17em;font-weight:bold;}
						.l-about .sub-list li {margin-bottom:10px;}
						.l-about .sub-list li:last-child {margin-bottom:0;}
						@media only all and (max-width: 767px) {
						.news-view-content .product-line .prod-img {float:none;}
						}
						</style>
						<div class="l-about">
							<ul class="tit-list">
							    <li>再度與法國知名藝術工作室合作 傳承傳統美學</li>
							    <li>獨特豐富刺繡圖騰 包裝極具匠心傳遞美滿祝願</li>
							    <li>三大皇牌護膚化妝品 打造春日韓式妝容</li>
							</ul>    
							<br>
							<p>韓國尊貴護膚品牌雪花秀致力鑽研韓方傳統藥理，結合劃時代先進科技一拼加入化妝品，讓女士們化妝同時護膚，體驗水潤無瑕妝品。今年雪花秀特別推出極具收藏價值的春季限量版彩妝系列，再度誠邀法國藝術工作室Antoinette Poisson設計，以刺繡方式呈現盛放的梅花及蝴蝶，點綴活力喜悅的春日氣息，同時展現融和之美。</p>
							<h3>清新刺繡洋溢韓式傳統風采 送上誠摯祝福</h3>
							<ul class="sub-list">
							    <li>以綻放梅花為主體，梅花五瓣象徵五福，即快樂、幸福、長壽、順利與和平，祝願事事順利，和美幸福。</li>
							    <li>配以翩翩起舞的蝴蝶，把幸福、財富、人緣等美好祝願送到全世界。</li>
							    <li>米白色背景配以粉色刺繡，高雅脫俗。</li>
							</ul>
							<h3>與法國藝術工作室再次合作 聯手弘揚傳統手藝之美</h3>
							<ul class="sub-list">
							    <li>Antoinette Poisson是法國著名藝術工作室，透過現代手法傳承法國18世紀裝潢藝術而聞名。</li>
							    <li>工作室十分注重傳統工藝及文化遺產的傳承，並致力於以傳統方法打造藝術品，與雪花秀的「傳承」理念不謀而合。</li>
							</ul>
						</div>
						<div class="product-line">    
							<h4>2020春日限量系列</h4>
							<div class="prod-desc">
							    <div>
							        <img class="prod-img" src="/media/html/resource/img/news/perfecting_cushion_spring_collection_news_hk.jpg" alt="">
							    </div>
							    <div class="prod-text">
							        <strong class="prod-sub-tit">Perfecting Cushion EX Spring Limited Edition緻美無瑕氣墊粉底液限量版</strong>
							        <span class="prod-price">HKD $450/15g x 2</span>
							        <ul class="prod-sub-txt-list">
							            <li>萃取自<b>裂褶菌的精華成分，高效補濕</b>上妝後肌膚感覺水盈舒適，由內而外煥發細緻光采。</li>
							            <li>獨創 <b>Slim Fit High Coverage Formula</b> 粉底極致貼薄，輕盈融入每吋肌膚，細緻修飾斑印細紋，妝效持久清新如初。</li>
							            <li>極致輕盈貼薄，高度遮瑕補濕，肌膚散發水嫩光采。</li>
							        </ul>
							    </div>
							</div>
							<div class="prod-desc">
							    <div>
							        <img class="prod-img" src="/media/html/resource/img/news/snowise_brightening_cushion_spring_collection_news_hk.jpg" alt="">
							    </div>
							    <div class="prod-text">
							        <strong class="prod-sub-tit">Snowise Brightening Cushion Spring Limited Edition滋晶雪瀅煥白氣墊粉底液限量版</strong>
							        <span class="prod-price">HKD $460/14g x 2</span>
							        <ul class="prod-sub-txt-list">
							            <li>蘊含<b>珍珠貝母複合物<sup>™</sup>，提升肌膚的自然光澤，</b> 即時提亮肌膚，如鍍上珠光亮彩，綻現輕透亮白肌。</li>
							            <li><b>白參多醣釋放肌膚水光，</b> 令肌膚豐盈滋養，顯著水漾勻淨，剔透亮白。</li>
							            <li>極致輕盈貼薄，高度遮瑕補濕，肌膚散發水嫩光采。</li>
							            <li>專利Air Glow Formula及Slim Fit Applicator，自然遮瑕，締造自然持久無瑕妝效。</li>
							        </ul>
							    </div>
							</div>
							<div class="prod-desc">
							    <div>
							        <img class="prod-img" src="/media/html/resource/img/news/essential_lip_serum_stick_spring_collection_news_hk.jpg" alt="">
							    </div>
							    <div class="prod-text">
							        <strong class="prod-sub-tit">Essential Lip Serum Stick Spring Limited Edition肌本柔潤護唇膏限量版</strong>
							        <span class="prod-price">HKD $290/3g （4號 Rose Red / 5號 Blossom Coral)</span>
							        <ul class="prod-sub-txt-list">
							            <li>萃取自<b>山茶花籽的山茶花油，配合紅花精華，</b>形成高親膚性油質保護屏障層，具極強補濕功效，為雙唇<b>建立雙重鎖水屏障。</b></li>
							            <li><b>白參多醣釋放肌膚水光，</b> 令肌膚豐盈滋養，顯著水漾勻淨，剔透亮白。</li>
							            <li>蘊含杏核油及專利成份<b> Elastane Complex，</b> 有效撫平唇紋，<b>增強唇部彈性，</b> 讓雙唇更豐潤立體。</li>
							            <li>活力光感色彩的<b>桃紅</b>與<b>橙紅</b>，呈現如梅花瓣般的醉人色調，為櫻唇賦予活力，煥發亮麗光澤。</li>
							        </ul>
							    </div>
							</div>
						</div>
					</div>
				</div>
				<!-- //HTML or text 삽입 -->
			</div>
		</div>
			
		<!-- E : 이미지인 경우 -->
		
		<!-- S : 영상인 경우 -->
        
		<!-- E : 영상인 경우 -->
		<!-- S : HTML 영역으로 사용하는 경우-->
        
		<!-- E : HTML 영역으로 사용하는 경우 -->
	</div>
	<!-- E : ICS + 부분 HTML 영역으로 사용하는 경우 (Beauty Ritual, News, Print, film) -->
	

	<!-- E : 전체 HTML 영역으로 사용하는 경우 (event, cover, etc) -->
	<!-- S : 아카이브 컨텐츠 목록 -->
	<div class="others-archive-list-wrap">
		<div class="others-archive-list">
			<button class="sul-slide-btn-prev"><span class="blind">이전</span></button>
			<div class="sul-slide-list others-list">
				<div class="sul-slide-item others-item">
					<a href="/hk/zh/experience/archive/1314968_3836.html" class="thumb" ap-click-area="Contents" ap-click-name="Click - Contents" ap-click-data="Sulwhasoo Post Others_雪花秀全新推出UV Wise Brightening Multi Protector<br>溫和親膚零負擔 亮肌防曬抗污染 打造健康自信美肌" tabindex="0">
						<div class="thumb-frame">
							<div class="cover"><span class="category">NEWS</span></div>
							<img src="/media/html/experience/archive/__icsFiles/afieldfile/2021/07/14/thumbnail_article_1.jpg" alt="Sulwhasoo releases upgraded anti-pollution, sun-care cream, UV Wise Brightening Multi Protector">
						</div>
					</a>
				</div>
				<div class="sul-slide-item others-item">
					<a href="/hk/zh/experience/archive/1314969_3836.html" class="thumb" ap-click-area="Contents" ap-click-name="Click - Contents" ap-click-data="Sulwhasoo Post Others_雪花秀2020限量版彩妝系列<br>Spring Into Happiness<br>韓式粉嫩春妝氣色 綻放春日迷人氣息" tabindex="0">
						<div class="thumb-frame">
							<div class="cover"><span class="category">NEWS</span></div>
							<img src="/media/html/experience/archive/__icsFiles/afieldfile/2021/08/23/KakaoTalk_20210823_163311146.jpg" alt="Sulwhasoo launches its new “2020 Spring Limited Collection”">
						</div>
					</a>
				</div>
				<div class="sul-slide-item others-item">
					<a href="/hk/zh/experience/archive/1314966_3836.html" class="thumb" ap-click-area="Contents" ap-click-name="Click - Contents" ap-click-data="Sulwhasoo Post Others_雪花秀至臻巨獻 – Timetreasure Honorstige<br> 珍雪芊萃琉金霜及精華 <br>內外強化修護肌膚 臻極尊貴韓方 譜寫恆久美顏傳奇" tabindex="0">
						<div class="thumb-frame">
							<div class="cover"><span class="category">NEWS</span></div>
							<img src="/media/html/experience/archive/__icsFiles/afieldfile/2021/07/14/timetreasure_1.jpg" alt="Sulwhasoo launches the new Timetreasure Honorstige">
						</div>
					</a>
				</div>
			</div>
			<button class="sul-slide-btn-next"><span class="blind">다음</span></button>
		</div>
	</div>
	<!-- E : 아카이브 컨텐츠 목록 -->
</section>

<script>
	require([
	'jquery',
	'js/plugins/slick/slick'
	], function ($) {
	    $('.others-list').slick({
	        slidesToShow: 3,
	        slidesToScroll: 1,
	        arrows: true,
	        fade: false,
	        dots: false,
	        infinite : false,
	        draggable : true,
	        prevArrow: $('.others-archive-list').find('.sul-slide-btn-prev'),
	        nextArrow: $('.others-archive-list').find('.sul-slide-btn-next'),
	        responsive: [{
	            breakpoint: 768,
	            settings: {
	                slidesToShow: 1.5,
	                slidesToScroll: 1
	            }
	        }]
	    });
	});

</script>