<!--<title>雪花秀至臻巨獻 – Timetreasure Honorstige<br> 珍雪芊萃琉金霜及精華 <br>內外強化修護肌膚 臻極尊貴韓方 譜寫恆久美顏傳奇 | 雪花秀</title>-->
<!--<meta name="description" content="雪花秀資訊 - 雪花秀至臻巨獻 – Timetreasure Honorstige<br> 珍雪芊萃琉金霜及精華 <br>內外強化修護肌膚 臻極尊貴韓方 譜寫恆久美顏傳奇 | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="og:title" content="雪花秀至臻巨獻 – Timetreasure Honorstige<br> 珍雪芊萃琉金霜及精華 <br>內外強化修護肌膚 臻極尊貴韓方 譜寫恆久美顏傳奇 | 雪花秀">-->
<!--<meta property="og:description" content="雪花秀資訊 - 雪花秀至臻巨獻 – Timetreasure Honorstige<br> 珍雪芊萃琉金霜及精華 <br>內外強化修護肌膚 臻極尊貴韓方 譜寫恆久美顏傳奇 | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="twitter:title" content="雪花秀至臻巨獻 – Timetreasure Honorstige<br> 珍雪芊萃琉金霜及精華 <br>內外強化修護肌膚 臻極尊貴韓方 譜寫恆久美顏傳奇 | 雪花秀">-->
<!--<meta property="twitter:description" content="雪花秀資訊 - 雪花秀至臻巨獻 – Timetreasure Honorstige<br> 珍雪芊萃琉金霜及精華 <br>內外強化修護肌膚 臻極尊貴韓方 譜寫恆久美顏傳奇 | Sulwhasoo Hong Kong 中國香港">-->

<section class="content renewal-archive-detail">
	
	<!-- S : ICS + 부분 HTML 영역으로 사용하는 경우 (Beauty Ritual, News, Print, film) -->
    
	<div class="archive-section">
        <div class="archive-header">
            <div class="header-inner">
                <h1 class="h">雪花秀至臻巨獻 – Timetreasure Honorstige<br> 珍雪芊萃琉金霜及精華 <br>內外強化修護肌膚 臻極尊貴韓方 譜寫恆久美顏傳奇</h1>
				<span class="type">News</span>
				<span class="date">2020.01.01</span>
			</div>
		</div>
		<!-- S : 이미지인 경우 Beauty Ritual, News, Print-->
        
			<!-- Beauty Ritual은 video 존재 유무에 따라 타입이 나눠짐-->
			
			
			<div class="archive-content">
				
				<figure class="archive-image">
					<img src="/media/html/experience/archive/__icsFiles/afieldfile/2021/08/23/sulwhasoo-launches-the-new-timetreasure-honorstige_1.jpg" alt="Sulwhasoo launches the new Timetreasure Honorstige">
				</figure>
				
				
				<div class="archive-static-body">
					<!-- HTML or text 삽입 -->
					<div class="print-copy">
						<div class="content static parbase about-view-content">
							<style>
							.l-about .tit-list, 
							.l-about h3, 
							.product-line h4, 
							.prod-text .prod-sub-tit,
							.prod-text .prod-price {color:#555;}
							.news-view-content .l-about h3 {margin-top:20px;margin-bottom:10px;}
							.news-view-content .product-line .prod-text {padding-top:0;}
							.l-about .tit-list {text-align:center;}
							.l-about .tit-list li {margin-bottom:10px;font-size:1.17em;font-weight:bold;}
							.l-about .sub-list li {margin-bottom:10px;}
							.l-about .sub-list li:last-child {margin-bottom:0;}
							.product-line h4 {display:inline-block;margin-bottom:10px;border-bottom:1px solid #555;line-height:1.5;}
							.product-line .prod-desc {width:100%;}
							.product-line .prod-text .prod-price {display:block;margin-top:10px;font-weight:bold;}
							.product-line .prod-text .prod-sub-txt-list li {padding-top:10px;}
							.product-line .prod-text .prod-sub-txt-list li .list-desc {font-size:12px;}
							.product-line:after {display:block;content:"";clear:both;}
							.rel-date {color:#555;text-align:right;}
							@media only all and (max-width: 767px) {
							    .news-view-content .product-line .prod-img {float:none;}
							}
							</style>
							<div class="l-about">
							    <ul class="tit-list">
							        <li>新成分靈芝精華及人參細胞原生質<sup>™</sup>促進細胞修復再生　緩和肌膚衰老症狀</li>
							        <li>獨有專利成分赤松逆齡活膚精萃  持續活膚煥顏　刺激肌膚自我產生膠原蛋白</li>
							        <li>金色外型靈感源自古代帝王所用器皿 融合現代化設計 更顯珍貴</li>
							    </ul>    
							    <br>
							    <p>韓國尊貴護膚品牌雪花秀，匯聚超過半世紀對人參及韓方草藥深入研究，精心鑽研護膚精髓，將奢華美顏傳奇融入護膚品，由內而外實現調和之美。2020年，品牌呈獻極致尊貴的抗衰老面霜及精華——Timetreasure Honorstige 珍雪芊萃琉金霜及精華，珍罕成份有效抗衰老，逆轉肌齡重拾活力，御守肌膚年輕之美。</p>
							    <h3>4大珍罕草本成分 活化衰老肌膚細胞 激活皮膚再生力</h3>
							    <ul class="sub-list">
							        <li>靈芝精華︰《東醫寶鑑》指出靈芝有助延年益壽、調節膚色，雪花秀根據國外及韓國評分標準，從靈芝的大小、厚度及水分，嚴選最優越等級的靈芝，並以獨有環保技術，萃取出高含量的靈芝精華，從而轉化成卓越護膚成分。靈芝有效增加細胞緊密度，加強肌膚表面保護屏障，強效修補及刺激膠原蛋白增生，重建肌膚彈性，高效修復因衰老導致的歲月痕跡。</li>
							        <li>人參細胞原生質<sup>™</sup>︰首次以人參細胞作護膚成分，以完整破壁技術，完整地吸收人參原始活力成分的人參細胞，提昇肌膚吸收效果及速度，密集地增強肌膚活力，鞏固真皮層再生能力，持久保持肌膚水分、彈性於良好狀態，達至高效抗衰老效果。</li>
							        <li>赤松逆齡活膚精萃︰蘊含 2 倍 DAA 逆齡活膚精萃，阻截衰老連鎖反應，強化肌膚屏障，有效減少老化細胞達 55%，回復年輕健康肌膚。</li>
							    </ul>
							    <h3>金色外型突顯瑰麗奢華</h3>
							    <ul class="sub-list">
							        <li>採用全金屬金色瓶身，以古代帝王專用的護膚品包裝作藍本，改良成優越的現代化設計。</li>
							        <li>金色及黑色的包裝極致奢華，其中金色更突顯靈芝的珍貴。</li>
							        <li>圓拱形頂蓋印有梅花綻放的圖案以及雪花秀的中文標誌，代表著品牌顯赫的形象，突顯品牌的尊貴，更顯韓國美學的傳承。</li>
							        <li>獨具全新香味，東方草藥清香直接於肌膚發揮功效，紓緩內、外壓力，並提升肌膚防禦機能。</li>
							    </ul>
							</div>
							<div class="product-line">    
							    <div class="prod-desc">
							        <div>
							            <img class="prod-img" src="/media/html/resource/img/news/timetreasure_honorstige_cream_news_hk.jpg" alt="">
							        </div>
							        <div class="prod-text">
							            <strong class="prod-sub-tit">Timetreasure Honorstige 珍雪芊萃琉金霜</strong>
							            <span class="prod-price">HKD $5,400/60ml</span>
							            <ul class="prod-sub-txt-list">
							                <li>蘊含靈芝精華及人參細胞原生質<sup>™</sup>，促進肌膚細胞再生，改善肌膚衰老情況，讓肌膚更緊緻、更富彈性。</li>
							                <li>滋養潤膚的面霜，以手指的溫度軟融即可賦予高貼服度的質感，於肌膚表層形成滋潤保護膜，抵禦環境污染及內在壓力造成的肌膚衰老症狀。</li>
							                <li>臨床實驗證明，使用 Timetreasure Honorstige 珍雪芊萃琉金霜 8 星期，肌膚緊緻度提升 13.8%，皺紋減少 16.8%，提升肌膚緊緻度，撫平肌膚紋理，煥發年輕光彩。<p class="list-desc">*31 位 43-56 歲女士使用 8 星期的臨床測試結果</p>
							                </li>
							            </ul>
							        </div>
							    </div>
							    <div class="prod-desc">
							        <div>
							            <img class="prod-img" src="/media/html/resource/img/news/timetreasure_honorstige_serum_news_hk.jpg" alt="">
							        </div>
							        <div class="prod-text">
							            <strong class="prod-sub-tit">Timetreasure Honorstige 珍雪芊萃琉金精華</strong>
							            <span class="prod-price">HKD $5,400/40ml</span>
							            <ul class="prod-sub-txt-list">
							                <li>蘊含靈芝精華及人參細胞原生質<sup>™</sup> ，促進肌膚細胞再生，改善肌膚衰老情況，提升肌膚光澤感並撫平細紋，讓肌膚更有活力，更顯年輕。</li>
							                <li>質地透薄，容易被肌膚吸收，留下絲滑補濕保護層。臨床實驗證明，使用 Timetreasure Honorstige 珍雪芊萃琉金精華 8 星期，肌膚透析度提升 7.9%，肌膚光澤度提昇 3.2%，皺紋大大減少 9%，整體肌膚獲得深層修復，從底層煥發年輕活力。
							                    <p class="list-desc">*31 位 43-56 歲女士使用 8 星期的臨床測試結果</p></li>
							            </ul>
							        </div>
							    </div>
							</div>
						</div>
					</div>
					<!-- //HTML or text 삽입 -->
				</div>
			</div>
			
		<!-- E : 이미지인 경우 -->
		
		<!-- S : 영상인 경우 -->
        
		<!-- E : 영상인 경우 -->
		<!-- S : HTML 영역으로 사용하는 경우-->
        
		<!-- E : HTML 영역으로 사용하는 경우 -->
	</div>
	<!-- E : ICS + 부분 HTML 영역으로 사용하는 경우 (Beauty Ritual, News, Print, film) -->
	

	<!-- E : 전체 HTML 영역으로 사용하는 경우 (event, cover, etc) -->
	<!-- S : 아카이브 컨텐츠 목록 -->
	<div class="others-archive-list-wrap">
		<div class="others-archive-list">
			<button class="sul-slide-btn-prev"><span class="blind">이전</span></button>
			<div class="sul-slide-list others-list">
				<div class="sul-slide-item others-item">
					<a href="/hk/zh/experience/archive/1314968_3836.html" class="thumb" ap-click-area="Contents" ap-click-name="Click - Contents" ap-click-data="Sulwhasoo Post Others_雪花秀全新推出UV Wise Brightening Multi Protector<br>溫和親膚零負擔 亮肌防曬抗污染 打造健康自信美肌" tabindex="0">
						<div class="thumb-frame">
							<div class="cover"><span class="category">NEWS</span></div>
							<img src="/media/html/experience/archive/__icsFiles/afieldfile/2021/07/14/thumbnail_article_1.jpg" alt="Sulwhasoo releases upgraded anti-pollution, sun-care cream, UV Wise Brightening Multi Protector">
						</div>
					</a>
				</div>
				<div class="sul-slide-item others-item">
					<a href="/hk/zh/experience/archive/1314969_3836.html" class="thumb" ap-click-area="Contents" ap-click-name="Click - Contents" ap-click-data="Sulwhasoo Post Others_雪花秀2020限量版彩妝系列<br>Spring Into Happiness<br>韓式粉嫩春妝氣色 綻放春日迷人氣息" tabindex="0">
						<div class="thumb-frame">
							<div class="cover"><span class="category">NEWS</span></div>
							<img src="/media/html/experience/archive/__icsFiles/afieldfile/2021/08/23/KakaoTalk_20210823_163311146.jpg" alt="Sulwhasoo launches its new “2020 Spring Limited Collection”">
						</div>
					</a>
				</div>
				<div class="sul-slide-item others-item">
					<a href="/hk/zh/experience/archive/1314966_3836.html" class="thumb" ap-click-area="Contents" ap-click-name="Click - Contents" ap-click-data="Sulwhasoo Post Others_雪花秀至臻巨獻 – Timetreasure Honorstige<br> 珍雪芊萃琉金霜及精華 <br>內外強化修護肌膚 臻極尊貴韓方 譜寫恆久美顏傳奇" tabindex="0">
						<div class="thumb-frame">
							<div class="cover"><span class="category">NEWS</span></div>
							<img src="/media/html/experience/archive/__icsFiles/afieldfile/2021/07/14/timetreasure_1.jpg" alt="Sulwhasoo launches the new Timetreasure Honorstige">
						</div>
					</a>
				</div>
			</div>
			<button class="sul-slide-btn-next"><span class="blind">다음</span></button>
		</div>
	</div>
	<!-- E : 아카이브 컨텐츠 목록 -->
</section>

<script>
	require([
	'jquery',
	'js/plugins/slick/slick'
	], function ($) {
	    $('.others-list').slick({
	        slidesToShow: 3,
	        slidesToScroll: 1,
	        arrows: true,
	        fade: false,
	        dots: false,
	        infinite : false,
	        draggable : true,
	        prevArrow: $('.others-archive-list').find('.sul-slide-btn-prev'),
	        nextArrow: $('.others-archive-list').find('.sul-slide-btn-next'),
	        responsive: [{
	            breakpoint: 768,
	            settings: {
	                slidesToShow: 1.5,
	                slidesToScroll: 1
	            }
	        }]
	    });
	});

</script>