<!--<title>[NEW] Concentrated Ginseng Renewing Serum EX | 雪花秀</title>-->
<!--<meta name="description" content="雪花秀資訊 - [NEW] Concentrated Ginseng Renewing Serum EX | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="og:title" content="[NEW] Concentrated Ginseng Renewing Serum EX | 雪花秀">-->
<!--<meta property="og:description" content="雪花秀資訊 - [NEW] Concentrated Ginseng Renewing Serum EX | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="twitter:title" content="[NEW] Concentrated Ginseng Renewing Serum EX | 雪花秀">-->
<!--<meta property="twitter:description" content="雪花秀資訊 - [NEW] Concentrated Ginseng Renewing Serum EX | Sulwhasoo Hong Kong 中國香港">-->

<section class="content renewal-archive-detail">
    <div class="archive-static-body">
        <article class="post post--jaeumsang">
            <h1 class="blind">禦時緊顏參養精華</h1>
            <section class="post-section post-section--visual">
                <h2 class="blind">禦時緊顏參養精華 visual image</h2>
                <span class="visual-new"><img src="/media/html/resource/img/cover/jaeumsaengSerum/jaeumsaengSerum_new.png" alt="NEW"></span>
                <div class="visual-text">
                    <h3 class="visual-title">
                        <picture class="img-box">
                            <source srcset="/media/html/resource/img/cover/jaeumsaengSerum/jaeumsaengSerum_visual_title_mo.png" media="(max-width: 766px)">
                            <img src="/media/html/resource/img/cover/jaeumsaengSerum/jaeumsaengSerum_visual_title_pc.png" alt="禦時緊顏參養精華">
                        </picture>
                    </h3>
                    <p class="visual-desc">
                        <picture class="img-box">
                            <source srcset="/media/html/resource/img/cover/jaeumsaengSerum/jaeumsaengSerum_visual_desc_mo.png" media="(max-width: 766px)">
                            <img src="/media/html/resource/img/cover/jaeumsaengSerum/jaeumsaengSerum_visual_desc_pc.png" alt="一瓶瞬間回復緊緻年輕肌">
                        </picture>
                    </p>
                </div>
            </section>

            <section class="post-section post-section--video">
                <h2 class="blind">Concentrated Ginseng Renewing Serum EX video</h2>
                <div class="section__inner">
                    <div class="video-container aos-init" data-aos="fade-up">
                        <article class="wrap-cover-202108-vdo aos-init" data-aos="fade-up">
                            <div class="inner-cover-202108-vdo">
                                <div class="cover-202108-vdo">
                                    <button ap-click-area="Contents" ap-click-name="Click - Video" ap-click-data="Cover_CGRC 2021" data-role-video="youtube" style="display: block">
                                        <span class="hidden">Concentrated Ginseng Renewing Serum EX youtube video</span>
                                    </button>
                                    <div class="iframe-cover-202108-vdo" style="display: none">
                                        <iframe id="cover202108Vdo1" src="https://www.youtube.com/embed/AtP9VPSE2OI?showinfo=0&amp;color=white&amp;theme=dark&amp;enablejsapi=1&amp;rel=0&amp;playsinline=1" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen="" title="play Concentrated Ginseng Renewing Serum EX video" class="video-iframe"></iframe>
                                    </div>
                                </div>
                            </div>
                        </article>
                    </div>
                    <div class="video-text aos-init" data-aos="fade-up">
                        <p class="desc">
                            <strong>結合創新微囊技術 1瓶逾*190,000&nbsp;&nbsp;顆抗炎人參精萃Ginsenomics™微囊<br>
                                短短7天即見三層式肌底「提·拉·緊」
                            </strong>
                        </p>
                        <span class="tags">
                          <em>#ReplenishSupportStrengthen #TripleResilienceEffect</em>
                          <em>#GINSENOMICS™&nbsp; #CapsuleSerum</em>
                        </span>
                    </div>
                </div>
            </section>

            <section class="post-section post-section--serums aos-init" data-aos="fade-up">
                <div class="section__inner">
                    <div class="serum-images">
                        <div class="serum-images__item aos-init" data-aos="zoom-out" data-aos-delay="0" data-aos-duration="1500">
                            <img src="/media/html/resource/img/cover/jaeumsaengSerum/jaeumsaengSerum_serum-visual01_pc.jpg" class="images">
                        </div>
                        <div class="serum-images__item aos-init" data-aos="zoom-out" data-aos-delay="200" data-aos-duration="1500">
                            <img src="/media/html/resource/img/cover/jaeumsaengSerum/jaeumsaengSerum_serum-visual02_pc.jpg" class="images display-pc">
                            <img src="/media/html/resource/img/cover/jaeumsaengSerum/jaeumsaengSerum_serum-visual02_mo.png" class="images display-mo">
                        </div>
                        <div class="serum-images__item aos-init" data-aos="zoom-out" data-aos-delay="100" data-aos-duration="1500">
                            <img src="/media/html/resource/img/cover/jaeumsaengSerum/jaeumsaengSerum_serum-visual03_pc.jpg" class="images display-pc">
                            <img src="/media/html/resource/img/cover/jaeumsaengSerum/jaeumsaengSerum_serum-visual03_mo.jpg" class="images display-mo">
                        </div>
                    </div>
                </div>
            </section>

            <section class="post-section post-section--info aos-init" data-aos="fade-up">
                <h2 class="blind">Concentrated Ginseng Renewing Serum EX product info</h2>
                <div class="section__inner">
                    <div class="info__column info__column--image">
                        <img src="/media/html/resource/img/cover/jaeumsaengSerum/jaeumsaengSerum_info_thumbnail_pc.jpg" data-aos="zoom-out" class="aos-init">
                    </div>
                    <div class="info__column info__column--left">
                        <dl class="prd-info-wrapper">
                            <dt class="blind">badge:</dt>
                            <dd data-aos="fade-up" class="aos-init">
                                <span class="badge"> NEW </span>
                            </dd>
                            <dt class="blind">product name:</dt>
                            <dd class="prd-name aos-init" data-aos="fade-up">禦時緊顏參養精華</dd>
                            <dt class="blind">product description:</dt>
                            <dd class="prd-desc aos-init" data-aos="fade-up">
                                結合創新微囊技術 1瓶逾*190,000&nbsp;&nbsp;顆抗炎人
                                <br>
                                參精萃Ginsenomics™微囊，激活肌底細胞
                                <br>
                                自生力，進行三層式肌底「提·拉·緊」

                                <p class="desc-label">
                                    *50ml 禦時緊顏參養精華含有190,000顆Ginsenomics™微囊
                                </p>
                            </dd>
                            <dd>
                                <div class="prd-buttons aos-init" data-aos="fade-up">
                                    <a href="/hk/zh/products/concentrated-ginseng-renewing-serum.html" class="button" ap-click-area="Contents" ap-click-name="Click - Product Detail Link" ap-click-data="Cover_Concentrated Ginseng Renewing Serum EX">
                                        了解更多
                                    </a>
                                </div>
                            </dd>
                        </dl>
                    </div>
                </div>
            </section>

            <section class="post-section post-section--benefit aos-init" data-aos="fade-up">
                <h2 class="blind">Concentrated Ginseng Renewing Serum EX Benefit</h2>
                <div class="effect-banner">
                    <div class="effect-banner__inner">
                        <p class="effect-text">
                            <em>短短7天</em>
                            <br>
                            即見三層式肌底「提·拉·緊」
                            <br>
                            <em>打造完美健康肌膚</em>
                        </p>
                    </div>
                </div>
                <div class="section__inner">
                    <div class="video-container aos-init" data-aos="fade-up">
                        <article class="wrap-cover-202108-vdo aos-init" data-aos="fade-up">
                            <div class="inner-cover-202108-vdo">
                                <h3 class="hidden">Concentrated Ginseng Renewing Serum EX Video</h3>
                                <div class="cover-202108-vdo">
                                    <button ap-click-area="Contents" ap-click-name="Click - Video" ap-click-data="Cover_CGRC 2021" data-role-video="youtube" style="display: block">
                                        <span class="hidden">youtube video of Concentrated Ginseng Renewing Serum EX</span>
                                    </button>
                                    <div class="iframe-cover-202108-vdo" style="display: none">
                                        <iframe id="cover202108Vdo2" src="https://www.youtube.com/embed/0dfM3HXsnPw?showinfo=0&amp;color=white&amp;theme=dark&amp;enablejsapi=1&amp;rel=0&amp;playsinline=1" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen="" title="play youtube video of Concentrated Ginseng Renewing Serum EX " class="video-iframe"></iframe>
                                    </div>
                                </div>
                            </div>
                        </article>
                    </div>
                    <ul class="benefit-list">
                        <li data-aos="fade-up" class="aos-init">
                            <div class="benefit-thumbnail">
                                <img src="/media/html/resource/img/cover/jaeumsaengSerum/jaeumsaengSerum_benefit-thumb01_pc.jpg">
                            </div>
                            <div class="benefit-info">
                                <em class="benefit-word">提升彈性</em>
                                <div class="benefit-desc">
                                    肌膚底層細胞密度增加
                                    <br>
                                    由內而外改善肌底彈性
                                    <span class="benefit-percent">
                                        <span class="number">
                                            10.26
                                            <span class="unit">%</span>
                                        </span>
                                    </span>
                                </div>
                            </div>
                        </li>
                        <li data-aos="fade-up" class="aos-init">
                            <div class="benefit-thumbnail">
                                <img src="/media/html/resource/img/cover/jaeumsaengSerum/jaeumsaengSerum_benefit-thumb02_pc.jpg">
                            </div>
                            <div class="benefit-info">
                                <em class="benefit-word">緊緻肌膚</em>
                                <div class="benefit-desc">
                                    抑制膠原分解
                                    <br>
                                    激活膠原自生力
                                    <span class="benefit-percent">
                <span class="number">
                  1.92
                  <span class="unit">%</span>
                </span>
            </span></div>
                            </div>
                        </li>
                        <li data-aos="fade-up" class="aos-init">
                            <div class="benefit-thumbnail">
                                <img src="/media/html/resource/img/cover/jaeumsaengSerum/jaeumsaengSerum_benefit-thumb03_pc.jpg">
                            </div>
                            <div class="benefit-info">
                                <em class="benefit-word">拉平紋理</em>
                                <div class="benefit-desc">
                                    改善可見皺紋
                                    <br>
                                    加強皮膚防禦力
                                    <span class="benefit-percent">
                <span class="number">
                  18.67
                  <span class="unit">%</span>
                </span>
            </span></div>
                            </div>
                        </li>
                    </ul>
                    <div class="benefit-reference aos-init" data-aos="fade-up">
                        <h4 class="reference-title">
                            *御時緊顏參養精華測試結果（ 1 周 使用結果）
                        </h4>
                        <dl class="reference-info">
                            <dt>測試對象：</dt>
                            <dd>32名30-40多歲的女性</dd>
                            <dt>測試時間：</dt>
                            <dd>2021.05.31 - 7.30</dd>
                            <dt>測試機構：</dt>
                            <dd>Dermapro Co., Ltd.</dd>
                        </dl>
                    </div>
                </div>
            </section>

            <section class="post-section post-section--effect aos-init" data-aos="fade-up">
                <h2 class="blind">Concentrated Ginseng Renewing Serum EX effect</h2>
                <div class="section__inner">
                    <div class="effect-list">
                        <div class="effect-list__item aos-init" data-aos="fade-down" data-aos-delay="100">
                            <img src="/media/html/resource/img/cover/jaeumsaengSerum/jaeumsaengSerum_effect-section_thumb01_pc.jpg">
                            <div class="effect-info">
                                <h3 class="effect-title">
                                    專利成分Ginsenomics™6000倍*高濃度抗炎人參精萃48小時**激活膠原蛋白自生&nbsp;&nbsp;&nbsp;
                                </h3>
                                <ol class="effect-desc">
                                    <li>
                                        *與Compound K複合物(即珍貴的人參皂苷ginsenoside)的成分比較
                                    </li>
                                    <li>**經紫外線處理後 48 小時，確認膠原蛋白活化的體外測試結果</li>
                                </ol>
                            </div>
                        </div>
                        <div class="effect-list__item aos-init" data-aos="fade-down" data-aos-delay="200">
                            <img src="/media/html/resource/img/cover/jaeumsaengSerum/jaeumsaengSerum_effect-section_thumb02_pc.jpg">
                            <div class="effect-info">
                                <h3 class="effect-title">
                                    1瓶逾*190,000 顆抗炎人參精萃 Ginsenomics™ 微囊 8倍加快
                                    **滲透三層肌底緊緻肌膚
                                </h3>
                                <ol class="effect-desc">
                                    <li>
                                        *30ml 禦時緊顏參養精華含有100,000 顆Ginsenomics™微囊，而50ml
                                        禦時緊顏參養精華含有190,000顆Ginsenomics™微囊。
                                    </li>
                                    <li>**與本品牌舊有系列產品比較</li>
                                </ol>
                            </div>
                        </div>
                        <div class="effect-list__item aos-init" data-aos="fade-down" data-aos-delay="300">
                            <img src="/media/html/resource/img/cover/jaeumsaengSerum/jaeumsaengSerum_effect-section_thumb03_pc.jpg">
                            <div class="effect-info">
                                <h3 class="effect-title">
                                    創新微囊技術確保 Ginsenomics™ 最佳狀態 及功效
                                </h3>
                                <ol class="effect-desc">
                                    <li>
                                        *30ml 禦時緊顏參養精華含有100,000 顆Ginsenomics™微囊， 而50ml
                                        禦時緊顏參養精華含有190,000顆Ginsenomics™微囊。
                                    </li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </article>
    </div>

    <div class="others-archive-list-wrap">
        <div class="others-archive-list">
            <button class="sul-slide-btn-prev"><span class="blind">이전</span></button>
            <div class="sul-slide-list others-list">
                <div class="sul-slide-item others-item">
                    <a href="/hk/zh/experience/archive/etc_concentrated_ginseng_renewing_serum_2022.html" class="thumb" ap-click-area="Contents" ap-click-name="Click - Contents" ap-click-data="Sulwhasoo Post Others_[NEW] Concentrated Ginseng Renewing Serum EX" tabindex="0">
                        <div class="thumb-frame">
                            <div class="cover">
                                <span class="category">ETC</span>
                            </div>
                            <img src="/media/html/experience/archive/__icsFiles/afieldfile/2022/02/22/FCAS_coverpage_tumb_355x205.jpg" alt="FCAS_coverpage_tumb alt">
                        </div>
                    </a>
                </div>
                <div class="sul-slide-item others-item">
                    <a href="/hk/zh/experience/archive/etc_holiday_collection_2021.html" class="thumb" ap-click-area="Contents" ap-click-name="Click - Contents" ap-click-data="Sulwhasoo Post Others_UNLOCK THE SECRET CHAMBER" tabindex="0">
                        <div class="thumb-frame">
                            <div class="cover">
                                <span class="category">ETC</span>
                            </div>
                            <img src="/media/html/experience/archive/__icsFiles/afieldfile/2021/10/25/THE_SECRET_CHAMBER_list_1.jpg" alt="UNLOCK THE SECRET CHAMBER">
                        </div>
                    </a>
                </div>
            </div>
            <button class="sul-slide-btn-next"><span class="blind">다음</span></button>
        </div>
    </div>
</section>
<script>

    require([
        'jquery',
        'js/plugins/aos/aos',
        'js/plugins/swiper/swiper.min',
        'js/plugins/slick/slick'
    ], function ($,AOS,Swiper) {

        /* 2020.03.11 Youtube 영상 재생 로직 :: S */
        /**
         * Youtube iFrame API 세팅
         * @type {HTMLScriptElement}
         */
        var tag = document.createElement("script");
        tag.src = "https://www.youtube.com/iframe_api";
        var firstScriptTag = document.getElementsByTagName("script")[0];
        firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
        var players = [];
        window.onYouTubeIframeAPIReady = function () {
            var i = 0;

            $(".iframe-cover-202108-vdo").each(function (index) {
                var id = $(this).find("iframe").attr("id");
                players.push(
                    new YT.Player(id, {
                        events: {
                            onReady: onPlayerReady,
                            onStateChange: onPlayerStateChange,
                        },
                    })
                );
            });
        };
        function onPlayerReady(event) {}
        function onPlayerStateChange(event) {}

        $(function () {
            var $videoArea = $(".wrap-cover-202108-vdo");
            $videoArea.each(function (index) {
                var _this = $(this);
                _this.find("button").on("click", function () {
                    $(this).css("display", "none");
                    $(this).siblings(".iframe-cover-202108-vdo").css("display", "block");
                    $(this).siblings(".desc-script").addClass("script-open");
                    players[index].playVideo();
                });
            });
        });
        /* 2020.03.11 Youtube 영상 재생 로직 :: E */

        function CoverCommFunc() {
            var _$this = this,
                // 슬라이드 고유 클래스명
                slideClassName = ["cover-slide1", "cover-slide2"],
                slidesOption = {},
                kvElement = document.querySelector(".post-section--visual"),
                scrollInit = window.pageYOffset,
                kvOffset,
                isMobile = false,
                filter = "win16|win32|win64|mac",
                macOS = "Mac OS";
            swiper = {};

            // library event
            _$this.library = {
                init: function () {
                    _$this.library.aos();
                },
                // aos
                aos: function () {
                    AOS.init({
                        duration: 500,
                        offset: 250,
                    });
                    $("[data-aos-id]").each(function (idx) {
                        var aosIn = "aos:in:slide-slide" + (idx + 1);
                        var slideName = "slide" + (idx + 1);
                        document.addEventListener(aosIn, function (detail) {
                            swiper[slideName].slideTo(1, 0);
                            swiper[slideName].autoplay.start();
                        });
                    });
                },
            };

            // swiper
            _$this.swiperEvent = {
                // swiper slide 실행
                init: function () {
                    for (var i = 0; i < slideClassName.length; i++) {
                        var slideName = "slide" + (i + 1);
                        swiper[slideName] = new Swiper(
                            _$this.swiperEvent.containerClassName(slideClassName[i]),
                            slidesOption[i]
                        );
                    }
                },
                // 각 슬라이드 요소 찾기
                containerClassName: function (className, type) {
                    if (type === "pagination") {
                        return $(
                            ".wrap-cover-202108-swiper." +
                            className +
                            " .cover-202108-swiper .swiper-pagination"
                        );
                    } else {
                        return $(
                            ".wrap-cover-202108-swiper." + className + " .swiper-container"
                        );
                    }
                },
                // 슬라이드 공통 옵션 매칭
                addSlideOption: function () {
                    $(".swiper-container").each(function (idx) {
                        slidesOption[idx] = {
                            slidesPerView: 1,
                            pagination: {
                                el: _$this.swiperEvent.containerClassName(
                                    slideClassName[idx],
                                    "pagination"
                                ),
                                type: "progressbar",
                            },
                            noSwiping: true,
                            loop: true,
                            speed: 1000,
                            autoplay: {
                                delay: 3000,
                            },
                            on: {
                                init: function () {
                                    this.autoplay.stop();
                                    var thisSlide = this;
                                    var ctlBtn = $("." + slideClassName[idx]).find(".btn-control");
                                    ctlBtn.on("click", function () {
                                        var isSts = $(this).hasClass("stop");
                                        if (isSts) {
                                            thisSlide.autoplay.stop();
                                            $(this).removeClass("stop").addClass("play").text("재생");
                                        } else {
                                            thisSlide.autoplay.start();
                                            $(this).removeClass("play").addClass("stop").text("정지");
                                        }
                                    });
                                },
                            },
                        };
                    });
                },
            };
            // kv animation
            _$this.kvAnimation = {
                getKvbRect: function () {
                    kvOffset = kvElement.getBoundingClientRect();
                },
                kvAnimation: function (scroll) {
                    if (window.pageYOffset < kvOffset.top + scrollInit + kvOffset.height) {
                        kvElement.classList.add("ani-start");
                    } else if (window.pageYOffset === 0) {
                        kvElement.classList.add("ani-start");
                    } else {
                        kvElement.classList.remove("ani-start");
                    }
                },
            };
            return {
                init: function () {
                    // 모바일 접속 구분 (notosans font mobile line-height 적용 위해 필요)
                    if (navigator.platform) {
                        if (navigator.userAgent.indexOf(macOS) > 0) $("body").addClass("mac");
                        isMobile = filter.indexOf(navigator.platform.toLowerCase()) < 0;
                    }
                    if (isMobile) $("body").addClass("mobile");
                    _$this.library.init();
                    _$this.swiperEvent.addSlideOption();
                    _$this.swiperEvent.init();
                    _$this.kvAnimation.getKvbRect();
                    _$this.kvAnimation.kvAnimation();
                },
                scrollEvent: function (scroll) {
                    _$this.kvAnimation.kvAnimation(scroll);
                },
                getKvbRect: function () {
                    _$this.kvAnimation.getKvbRect();
                },
            };
        }

        var coverCommFunc = new CoverCommFunc();

        $(document).ready(function () {
            coverCommFunc.init();
        });

        window.addEventListener("scroll", function () {
            coverCommFunc.scrollEvent(window.pageYOffset);
        });

        window.addEventListener("resize", function () {
            coverCommFunc.getKvbRect();
        });

        $('.others-list').slick({
            slidesToShow: 3,
            slidesToScroll: 1,
            arrows: true,
            fade: false,
            dots: false,
            infinite : false,
            draggable : true,
            prevArrow: $('.others-archive-list').find('.sul-slide-btn-prev'),
            nextArrow: $('.others-archive-list').find('.sul-slide-btn-next'),
            responsive: [{
                breakpoint: 768,
                settings: {
                    slidesToShow: 1.5,
                    slidesToScroll: 1
                }
            }]
        });

    });


</script>

