<!--<title>Changing the framework of facial serums for healthy radiance,<br>NEW First Care Activating Serum | 雪花秀</title>-->
<!--<meta name="description" content="雪花秀資訊 - Changing the framework of facial serums for healthy radiance,<br>NEW First Care Activating Serum | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="og:title" content="Changing the framework of facial serums for healthy radiance,<br>NEW First Care Activating Serum | 雪花秀">-->
<!--<meta property="og:description" content="雪花秀資訊 - Changing the framework of facial serums for healthy radiance,<br>NEW First Care Activating Serum | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="twitter:title" content="Changing the framework of facial serums for healthy radiance,<br>NEW First Care Activating Serum | 雪花秀">-->
<!--<meta property="twitter:description" content="雪花秀資訊 - Changing the framework of facial serums for healthy radiance,<br>NEW First Care Activating Serum | Sulwhasoo Hong Kong 中國香港">-->

<section class="content renewal-archive-detail">
		<!-- S : ICS + 부분 HTML 영역으로 사용하는 경우 (Beauty Ritual, News, Print, film) -->
		<div class="archive-section">
            <div class="archive-header">
                <div class="header-inner">
                    <h1 class="h">Changing the framework of facial serums for healthy radiance,<br>NEW First Care Activating Serum</h1>
					<span class="type">Film</span>
					<span class="date">2020.04.03</span>
				</div>
			</div>
			<!-- S : 이미지인 경우 Beauty Ritual, News, Print-->
            
			<!-- S : 영상인 경우 -->
            
			<div class="archive-content">
				<a href="https://youtu.be/093Ram83T70" class="archive-player yt-player media" data-track-name="movie">
					<img src="/media/html/experience/archive/__icsFiles/afieldfile/2020/04/03/03_940.png" alt="Changing the framework of facial serums for healthy radiance, NEW First Care Activating Serum">
					<i class="icon-play icon-expend"></i>
				</a>
				
				<div class="film-desc">
					<!-- HTML or text 삽입 -->
					<!-- <div class="desc" tabindex="0"> -->
					<div class="desc" tabindex="0"> 
						(Subtitles)<br>
						Changing the framework of facial serums for healthy radiance<br>
						JAUM Activator™ the first step of anti-aging<br>
						Healthy nutrients are best absorbed on an empty stomach<br>
						Sulwhasoo's new idea conceived from Asian wisdom<br><br>

						(Narration) <br>
						For healthier and more radiant skin, <br>
						Sulwhasoo announced a new idea for anti-aging. <br><br>

						(Subtitles) <br>
						The first step after cleansing, <br>
						delivering nutrients deep at first, right into clean skin<br><br>

						(Narration) <br>
						The first anti-aging step, applied right after washing<br>
						To deliver nutrients deep at first, right into clean skin<br><br>

						(Subtitles) <br>
						Sulwhasoo FCAS, your first step for anti-aging <br>
						1 bottle sold every 10 seconds, FCAS captures the hearts of women worldwide<br><br>

						(Narration) <br>
						Sulwhasoo First Care Activating Serum<br>
						Has become a global bestseller loved by women all over the world<br><br>

						(Subtitles) <br>
						NEW FCAS's even more powerful<br>
						JAUM Activator™<br>

						(Narration) <br>
						Now with the NEW FCAS’s even more powerful JAUM Activator™<br><br>

						(Subtitles) <br>
						Healthy and radiant skin that improves every day<br><br>

						(Narration) <br>
						Experience healthier and more radiant skin every day. <br><br>

						(Narration/Subtitles) <br>
						Sulwhasoo First Care Activating Serum
					</div>
					<!-- </div> -->
					<!-- //HTML or text 삽입 -->
				</div>
			</div>
            
			<!-- E : 영상인 경우 -->
			<!-- S : HTML 영역으로 사용하는 경우-->
            
			<!-- E : HTML 영역으로 사용하는 경우 -->
		</div>
		<!-- E : ICS + 부분 HTML 영역으로 사용하는 경우 (Beauty Ritual, News, Print, film) -->

		<!-- E : 전체 HTML 영역으로 사용하는 경우 (event, cover, etc) -->
		<!-- S : 아카이브 컨텐츠 목록 -->
		<div class="others-archive-list-wrap">
			<div class="others-archive-list">
				<button class="sul-slide-btn-prev"><span class="blind">이전</span></button>
				<div class="sul-slide-list others-list">
					<div class="sul-slide-item others-item">
						<a href="/hk/zh/experience/archive/1314965_3836.html" class="thumb media" ap-click-area="Contents" ap-click-name="Click - Contents" ap-click-data="Sulwhasoo Post Others_First Care Activating Serum" tabindex="0">
							<div class="thumb-frame">
								<div class="cover"><span class="category">FILM</span></div>
								<img src="/media/html/experience/archive/__icsFiles/afieldfile/2021/07/15/20210402_final_archive_thumb_355_pc_01.jpg" alt="First Care Activating Serum">
								<i class="icon-play"><span class="blind">영상보기</span></i>
							</div>
						</a>
					</div>
					<div class="sul-slide-item others-item">
						<a href="/hk/zh/experience/archive/1314929_3836.html" class="thumb media" ap-click-area="Contents" ap-click-name="Click - Contents" ap-click-data="Sulwhasoo Post Others_Concentrated Ginseng Renewing Serum&amp;Rescue Ampoule_GINSENOMICS™" tabindex="0">
							<div class="thumb-frame">
								<div class="cover"><span class="category">FILM</span></div>
								<img src="/media/html/experience/archive/__icsFiles/afieldfile/2021/01/15/20210115_final_concentrated-ginseng-rescue-ampoule-texture_archive-list_pc_1.jpg" alt="Concentrated Ginseng Renewing Serum&amp;Rescue Ampoule_GINSENOMICS™">
								<i class="icon-play"><span class="blind">영상보기</span></i>
							</div>
						</a>
					</div>
					<div class="sul-slide-item others-item">
						<a href="/hk/zh/experience/archive/1314932_3836.html" class="thumb media" ap-click-area="Contents" ap-click-name="Click - Contents" ap-click-data="Sulwhasoo Post Others_HOW TO : F/W MAKEUP LOOK" tabindex="0">
							<div class="thumb-frame">
								<div class="cover"><span class="category">FILM</span></div>
								<img src="/media/html/experience/archive/__icsFiles/afieldfile/2020/09/21/20200921_final_perfecting-foundation_archive-main_350_1.jpg" alt="HOW TO : F/W MAKEUP LOOK">
								<i class="icon-play"><span class="blind">영상보기</span></i>
							</div>
						</a>
					</div>
				</div>
				<button class="sul-slide-btn-next"><span class="blind">다음</span></button>
			</div>
		</div>
		<!-- E : 아카이브 컨텐츠 목록 -->
	</section>
<script>
	require([
	'jquery',
	'js/plugins/slick/slick'
	], function ($) {
	    $('.others-list').slick({
	        slidesToShow: 3,
	        slidesToScroll: 1,
	        arrows: true,
	        fade: false,
	        dots: false,
	        infinite : false,
	        draggable : true,
	        prevArrow: $('.others-archive-list').find('.sul-slide-btn-prev'),
	        nextArrow: $('.others-archive-list').find('.sul-slide-btn-next'),
	        responsive: [{
	            breakpoint: 768,
	            settings: {
	                slidesToShow: 1.5,
	                slidesToScroll: 1
	            }
	        }]
	    });
	});

</script>