<!--<title>Brighter Eyes, Full of Vitality.<br>Sulwhasoo Bloomstay Vitalizing Eye Cream | 雪花秀</title>-->
<!--<meta name="description" content="雪花秀資訊 - Brighter Eyes, Full of Vitality.<br>Sulwhasoo Bloomstay Vitalizing Eye Cream | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="og:title" content="Brighter Eyes, Full of Vitality.<br>Sulwhasoo Bloomstay Vitalizing Eye Cream | 雪花秀">-->
<!--<meta property="og:description" content="雪花秀資訊 - Brighter Eyes, Full of Vitality.<br>Sulwhasoo Bloomstay Vitalizing Eye Cream | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="twitter:title" content="Brighter Eyes, Full of Vitality.<br>Sulwhasoo Bloomstay Vitalizing Eye Cream | 雪花秀">-->
<!--<meta property="twitter:description" content="雪花秀資訊 - Brighter Eyes, Full of Vitality.<br>Sulwhasoo Bloomstay Vitalizing Eye Cream | Sulwhasoo Hong Kong 中國香港">-->

<section class="content renewal-archive-detail">

    <!-- S : ICS + 부분 HTML 영역으로 사용하는 경우 (Beauty Ritual, News, Print, film) -->

    <div class="archive-section">
        <div class="archive-header">
            <div class="header-inner">
                <h1 class="h"><span style="white-space: nowrap;">Brighter</span> <span style="white-space: nowrap;">Eyes,</span> <span style="white-space: nowrap;">Full</span> <span style="white-space: nowrap;">of</span> <span style="white-space: nowrap;">Vitality.<br>Sulwhasoo</span> <span style="white-space: nowrap;">Bloomstay</span> <span style="white-space: nowrap;">Vitalizing</span> <span style="white-space: nowrap;">Eye</span> <span style="white-space: nowrap;">Cream</span></h1>
                <span class="type">Film</span>
                <span class="date">2020.02.04</span>
            </div>
        </div>
        <!-- S : 이미지인 경우 Beauty Ritual, News, Print-->

        <!-- S : 영상인 경우 -->

        <div class="archive-content">
            <a href="https://www.youtube.com/watch?v=2EDC1CMM-W0&amp;feature=youtu.be" class="archive-player yt-player media" data-track-name="movie">
                <img src="/media/html/experience/archive/__icsFiles/afieldfile/2020/02/03/bloomstay_vitalizing_eye_cream_940.jpg" alt="Brighter Eyes, Full of Vitality. Sulwhasoo Bloomstay Vitalizing Eye Cream">
                <i class="icon-play icon-expend"></i>
            </a>

            <div class="film-desc">
                <!-- HTML or text 삽입 -->
                <!-- <div class="desc" tabindex="0"> -->
                <div class="desc" tabindex="0">
                    (Narration)<br>
                    The powerful resilience and energy of plum blossoms<br>
                    blooming in the snow deliver revitalizing energy<br>
                    to bring a sparkle in your eyes.<br><br>

                    (Subtitles)<br>
                    -7.15% reduction of pigmentation in the eye area<br>
                    +130% improved resilience in the eye area<br><br>

                    (Subtitles)<br>
                    Test results of 32 Asian women between the ages of 29 and 42 for six weeks<br>
                    Increased moisture in the outer edges of the eyes: 108%, Increased moisture in the skin: 139%, Reduced wrinkles around the eye area: 14%<br><br>

                    (Narration)<br>
                    The Sulwhasoo Bloomstay Vitalizing Eye Cream<br><br>

                    (Subtitles)<br>
                    NEW Sulwhasoo Bloomstay Vitalizing Eye Cream<br>
                    Sulwhasoo</div>
                <!-- </div> -->
                <!-- //HTML or text 삽입 -->
            </div>
        </div>

        <!-- E : 영상인 경우 -->
        <!-- S : HTML 영역으로 사용하는 경우-->

        <!-- E : HTML 영역으로 사용하는 경우 -->
    </div>
    <!-- E : ICS + 부분 HTML 영역으로 사용하는 경우 (Beauty Ritual, News, Print, film) -->


    <!-- E : 전체 HTML 영역으로 사용하는 경우 (event, cover, etc) -->
    <!-- S : 아카이브 컨텐츠 목록 -->
    <div class="others-archive-list-wrap">
        <div class="others-archive-list">
            <button class="sul-slide-btn-prev"><span class="blind">이전</span></button>
            <div class="sul-slide-item sul-slide-list others-list">

                <div class="sul-slide-item others-item">
                    <a href="/hk/zh/experience/archive/1314965_3836.html" class="thumb media" ap-click-area="Contents" ap-click-name="Click - Contents" ap-click-data="Sulwhasoo Post Others_First Care Activating Serum" tabindex="0">
                        <div class="thumb-frame">
                            <div class="cover"><span class="category">FILM</span></div>
                            <img src="/media/html/experience/archive/__icsFiles/afieldfile/2021/07/15/20210402_final_archive_thumb_355_pc_01.jpg" alt="First Care Activating Serum">
                            <i class="icon-play"><span class="blind">영상보기</span></i>
                        </div>
                    </a>
                </div>

                <div class="sul-slide-item others-item">
                    <a href="/hk/zh/experience/archive/1314929_3836.html" class="thumb media" ap-click-area="Contents" ap-click-name="Click - Contents" ap-click-data="Sulwhasoo Post Others_Concentrated Ginseng Renewing Serum&amp;Rescue Ampoule_GINSENOMICS™" tabindex="0">
                        <div class="thumb-frame">
                            <div class="cover"><span class="category">FILM</span> </div>
                            <img src="/media/html/experience/archive/__icsFiles/afieldfile/2021/01/15/20210115_final_concentrated-ginseng-rescue-ampoule-texture_archive-list_pc_1.jpg" alt="Concentrated Ginseng Renewing Serum&amp;Rescue Ampoule_GINSENOMICS™">
                            <i class="icon-play"><span class="blind">영상보기</span></i>
                        </div>
                    </a>
                </div>

                <div class="sul-slide-item others-item">
                    <a href="/hk/zh/experience/archive/1314932_3836.html" class="thumb media" ap-click-area="Contents" ap-click-name="Click - Contents" ap-click-data="Sulwhasoo Post Others_HOW TO : F/W MAKEUP LOOK" tabindex="0">
                        <div class="thumb-frame">
                            <div class="cover"><span class="category">FILM</span></div>
                            <img src="/media/html/experience/archive/__icsFiles/afieldfile/2020/09/21/20200921_final_perfecting-foundation_archive-main_350_1.jpg" alt="HOW TO : F/W MAKEUP LOOK">
                            <i class="icon-play"><span class="blind">영상보기</span></i>
                        </div>
                    </a>
                </div>

            </div>
            <button class="sul-slide-btn-next"><span class="blind">다음</span></button>
        </div>
    </div>
    <!-- E : 아카이브 컨텐츠 목록 -->
</section>
<script>
    require([
        'jquery',
        'js/plugins/slick/slick'
    ], function ($) {
        $('.others-list').slick({
            slidesToShow: 3,
            slidesToScroll: 1,
            arrows: true,
            fade: false,
            dots: false,
            infinite : false,
            draggable : true,
            prevArrow: $('.others-archive-list').find('.sul-slide-btn-prev'),
            nextArrow: $('.others-archive-list').find('.sul-slide-btn-next'),
            responsive: [{
                breakpoint: 768,
                settings: {
                    slidesToShow: 1.5,
                    slidesToScroll: 1
                }
            }]
        });
    });

</script>
