<!--<title>Timetreasure Renovating Eye Serum | 雪花秀</title>-->
<!--<meta name="description" content="雪花秀資訊 - Timetreasure Renovating Eye Serum | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="og:title" content="Timetreasure Renovating Eye Serum | 雪花秀">-->
<!--<meta property="og:description" content="雪花秀資訊 - Timetreasure Renovating Eye Serum | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="twitter:title" content="Timetreasure Renovating Eye Serum | 雪花秀">-->
<!--<meta property="twitter:description" content="雪花秀資訊 - Timetreasure Renovating Eye Serum | Sulwhasoo Hong Kong 中國香港">-->
<section class="content renewal-archive-detail">
		
		<!-- S : ICS + 부분 HTML 영역으로 사용하는 경우 (Beauty Ritual, News, Print, film) -->
        
		<div class="archive-section">
            <div class="archive-header">
                <div class="header-inner">
                    <h1 class="h">Timetreasure Renovating Eye Serum</h1>
					<span class="type">Beauty Ritual</span>
					<span class="date">2019.06.03</span>
				</div>
			</div>
			<!-- S : 이미지인 경우 Beauty Ritual, News, Print-->
            
				<!-- Beauty Ritual은 video 존재 유무에 따라 타입이 나눠짐-->
				
					
					<div class="archive-content">
						<a href="https://www.youtube.com/watch?v=YcAoPRyg9Qo&list=PL5f6KV3Fngy4sy6Ssyol1dgZZfLT_I0Ca&index=7&t=0s" class="archive-player yt-player media" data-track-name="movie">
							<img src="/media/html/experience/archive/__icsFiles/afieldfile/2021/07/14/1559115276411_1_2.jpg" alt="Timetreasure Renovating Eye Serum">
							<i class="icon-play icon-expend"></i>
						</a>
						
						<div class="film-desc">
							<!-- HTML or text 삽입 -->
							<!-- <div class="desc" tabindex="0"> -->
							<div class="h">Beauty Ritual - 珍雪臻金煥生眼部精華</div><br>


								尊貴的全效抗衰老眼部精華蘊含韓國珍罕赤松，輔以臻金<br>
								明眸按摩棒，煥活眼部肌膚的緊緻力量。<br><br>

								舒緩按摩 – 重覆3次<br>
								均勻地由內至外於眼窩及眼下按壓，再以相同方向輕掃。<br><br>

								彈性按摩 – 重覆3次<br>
								輕柔地以打圈方式由內至外按壓眼眉及眼底，再以相同方<br>
								向輕掃。<br><br>

								重點修護 – 重覆 3 次<br>
								以向上打圈方式按壓眼頭至眼尾，再以相同方向輕掃。<br>
							<!-- </div> -->
							<!-- //HTML or text 삽입 -->
						</div>
					</div>
					
					
				
				
			<!-- E : 이미지인 경우 -->
			
			<!-- S : 영상인 경우 -->
            
			<!-- E : 영상인 경우 -->
			<!-- S : HTML 영역으로 사용하는 경우-->
            
			<!-- E : HTML 영역으로 사용하는 경우 -->
		</div>
		<!-- E : ICS + 부분 HTML 영역으로 사용하는 경우 (Beauty Ritual, News, Print, film) -->
		

		<!-- E : 전체 HTML 영역으로 사용하는 경우 (event, cover, etc) -->
		<!-- S : 아카이브 컨텐츠 목록 -->
	<div class="others-archive-list-wrap">
		<div class="others-archive-list">
			<button class="sul-slide-btn-prev"><span class="blind">이전</span></button>
			<div class="sul-slide-list others-list">
				<div class="sul-slide-item others-item">
					<a href="/hk/zh/experience/archive/1314967_3836.html" class="thumb" ap-click-area="Contents" ap-click-name="Click - Contents" ap-click-data="Sulwhasoo Post Others_Timetreasure Renovating Eye Serum" tabindex="0">
						<div class="thumb-frame">
							<div class="cover"><span class="category">BEAUTY RITUAL</span></div>
							<img src="/media/html/experience/archive/__icsFiles/afieldfile/2021/07/14/Timetreasure_BeautyRitual_1.jpg" alt="Timetreasure Renovating Eye Serum">
						</div>
					</a>
				</div>
			</div>
			<button class="sul-slide-btn-next"><span class="blind">다음</span></button>
		</div>
	</div>
	<!-- E : 아카이브 컨텐츠 목록 -->
</section>
<script>
	require([
	'jquery',
	'js/plugins/slick/slick'
	], function ($) {
	    $('.others-list').slick({
	        slidesToShow: 3,
	        slidesToScroll: 1,
	        arrows: true,
	        fade: false,
	        dots: false,
	        infinite : false,
	        draggable : true,
	        prevArrow: $('.others-archive-list').find('.sul-slide-btn-prev'),
	        nextArrow: $('.others-archive-list').find('.sul-slide-btn-next'),
	        responsive: [{
	            breakpoint: 768,
	            settings: {
	                slidesToShow: 1.5,
	                slidesToScroll: 1
	            }
	        }]
	    });
	});

</script>