<!--<title>Innovation of Concentrated Ginseng Renewing Serum | 雪花秀</title>-->
<!--<meta name="description" content="雪花秀資訊 - Innovation of Concentrated Ginseng Renewing Serum | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="og:title" content="Innovation of Concentrated Ginseng Renewing Serum | 雪花秀">-->
<!--<meta property="og:description" content="雪花秀資訊 - Innovation of Concentrated Ginseng Renewing Serum | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="twitter:title" content="Innovation of Concentrated Ginseng Renewing Serum | 雪花秀">-->
<!--<meta property="twitter:description" content="雪花秀資訊 - Innovation of Concentrated Ginseng Renewing Serum | Sulwhasoo Hong Kong 中國香港港">-->

<section class="content renewal-archive-detail">
		
	<!-- S : ICS + 부분 HTML 영역으로 사용하는 경우 (Beauty Ritual, News, Print, film) -->
    
	<div class="archive-section">
        <div class="archive-header">
            <div class="header-inner">
                <h1 class="h">Innovation of Concentrated Ginseng Renewing Serum</h1>
				<span class="type">Film</span>
				<span class="date">2020.03.24</span>
			</div>
		</div>
		<!-- S : 이미지인 경우 Beauty Ritual, News, Print-->
        
		<!-- S : 영상인 경우 -->
        
		<div class="archive-content">
			<a href="https://youtu.be/Rod7Oh1mRqA" class="archive-player yt-player media" data-track-name="movie">
				<img src="/media/html/experience/archive/__icsFiles/afieldfile/2020/03/24/Renewing_940.jpg" alt="Innovation of Concentrated Ginseng Renewing Serum">
				<i class="icon-play icon-expend"></i>
			</a>
			
			<div class="film-desc">
				<!-- HTML or text 삽입 -->
				<!-- <div class="desc" tabindex="0"> -->
				<div class="desc" tabindex="0">
					(Subtitles)<br>
					Concentrated Ginseng Renewing Serum<br><br>
					Innovation of Concentrated Ginseng Renewing Serum<br>
					3 Layered anti-aging<br><br>

					(Subtitles)<br>
					Cultivation for 3 Layered anti-aging<br><br>

					(Subtitles)<br>
					Aeroponic Ginseng<br>
					Scientific cultivation of ginseng specialized for skin<br><br>

					(Subtitles)<br>
					Nutrition CO2 Concentration Light Intensity Temperature Humidity<br>
					Environment where ginseng specialized for skin grow best<br><br>

					(Subtitles)<br>
					Maximizes effects of ginseng just for skin<br><br>

					(Subtitles)<br>
					Stem/Compound K<br>
					In-depth skin resilience improvement<br>
					Stems, Leaves/Ginsenoside Rd<br>
					Reinforcement skin's resilience<br>
					Seeds/Ginseng Seed Oil<br>
					epidermal strengthening<br><br>


					(Subtitles)<br>
					Technology for 3 Layered anti-aging<br><br>

					(Subtitles)<br>
					Only 0.0074L comes from a ginseng seed<br><br>

					(Subtitles)<br>
					Oil Blending<br>
					Combined with lipids at the optimal ratio<br><br>

					(Subtitles)<br>
					Dropping<br>
					Stabilized drop by drop into a moisturized base<br><br>

					(Subtitles)<br>
					Dispersing<br>
					Microcapsules formed through dispersion and mixing<br><br>

					(Subtitles)<br>
					Ginsenisphere™<br>
					Patented microencapsulation technology delivers increased efficacy to skin<br><br>

					(Subtitles)<br>
					Layered anti-aging in 3 different layers<br>
					3 layer resilience care solution<br><br>

					(Subtitles)<br>
					Surface Layer Shapes the apperance<br>
					Core Layer Resilience, Upward tension<br>
					Deep layer Plumps skin, Adds volume<br><br>
					Concentrated Ginseng Renewing Serum
				</div>
				<!-- </div> -->
				<!-- //HTML or text 삽입 -->
			</div>
		</div>
        
		<!-- E : 영상인 경우 -->
		<!-- S : HTML 영역으로 사용하는 경우-->
        
		<!-- E : HTML 영역으로 사용하는 경우 -->
	</div>
	<!-- E : ICS + 부분 HTML 영역으로 사용하는 경우 (Beauty Ritual, News, Print, film) -->
	

	<!-- E : 전체 HTML 영역으로 사용하는 경우 (event, cover, etc) -->
	<!-- S : 아카이브 컨텐츠 목록 -->
	<div class="others-archive-list-wrap">
		<div class="others-archive-list">
			<button class="sul-slide-btn-prev"><span class="blind">이전</span></button>
			<div class="sul-slide-list others-list">
				<div class="sul-slide-item others-item">
						<a href="/hk/zh/experience/archive/1314965_3836.html" class="thumb media" ap-click-area="Contents" ap-click-name="Click - Contents" ap-click-data="Sulwhasoo Post Others_First Care Activating Serum" tabindex="0">
							<div class="thumb-frame">
								<div class="cover"><span class="category">FILM</span></div>
								<img src="/media/html/experience/archive/__icsFiles/afieldfile/2021/07/15/20210402_final_archive_thumb_355_pc_01.jpg" alt="First Care Activating Serum">
								<i class="icon-play"><span class="blind">영상보기</span></i>
							</div>
						</a>
					</div>
					<div class="sul-slide-item others-item">
						<a href="/hk/zh/experience/archive/1314929_3836.html" class="thumb media" ap-click-area="Contents" ap-click-name="Click - Contents" ap-click-data="Sulwhasoo Post Others_Concentrated Ginseng Renewing Serum&amp;Rescue Ampoule_GINSENOMICS™" tabindex="0">
							<div class="thumb-frame">
								<div class="cover"><span class="category">FILM</span></div>
								<img src="/media/html/experience/archive/__icsFiles/afieldfile/2021/01/15/20210115_final_concentrated-ginseng-rescue-ampoule-texture_archive-list_pc_1.jpg" alt="Concentrated Ginseng Renewing Serum&amp;Rescue Ampoule_GINSENOMICS™">
								<i class="icon-play"><span class="blind">영상보기</span></i>
							</div>
						</a>
					</div>
					<div class="sul-slide-item others-item">
						<a href="/hk/zh/experience/archive/1314932_3836.html" class="thumb media" ap-click-area="Contents" ap-click-name="Click - Contents" ap-click-data="Sulwhasoo Post Others_HOW TO : F/W MAKEUP LOOK" tabindex="0">
							<div class="thumb-frame">
								<div class="cover"><span class="category">FILM</span></div>
								<img src="/media/html/experience/archive/__icsFiles/afieldfile/2020/09/21/20200921_final_perfecting-foundation_archive-main_350_1.jpg" alt="HOW TO : F/W MAKEUP LOOK">
								<i class="icon-play"><span class="blind">영상보기</span></i>
							</div>
						</a>
					</div>
			</div>
			<button class="sul-slide-btn-next"><span class="blind">다음</span></button>
		</div>
	</div>
	<!-- E : 아카이브 컨텐츠 목록 -->
</section>

<script>
	require([
	'jquery',
	'js/plugins/slick/slick'
	], function ($) {
	    $('.others-list').slick({
	        slidesToShow: 3,
	        slidesToScroll: 1,
	        arrows: true,
	        fade: false,
	        dots: false,
	        infinite : false,
	        draggable : true,
	        prevArrow: $('.others-archive-list').find('.sul-slide-btn-prev'),
	        nextArrow: $('.others-archive-list').find('.sul-slide-btn-next'),
	        responsive: [{
	            breakpoint: 768,
	            settings: {
	                slidesToShow: 1.5,
	                slidesToScroll: 1
	            }
	        }]
	    });
	});

</script>