<?php
/**
 * @author Eguana Team
 * @copyright Copyright (c) 2020 Eguana {http://eguanacommerce.com}
 * Created by PhpStorm
 * User: umer
 * Date: 12/6/20
 * Time: 10:59 PM
 */
/**
 * @var $block \Eguana\SocialLogin\Block\SocialLogin\Login
 */
$helper = $block->getHelper();
$block->unSetSession();
?>
<?php if ($helper->isEnabledInFrontend()):?>
    <?php
    $lineUrl = $block->getUrl('sociallogin/linelogin/connect');
    $googleUrl = $block->getUrl('sociallogin/googlelogin/connect');
    $facebookUrl = $block->getUrl('sociallogin/facebooklogin/connect'); ?>
    <div class="socialloginlogin-login">
        <p><?= $block->escapeHtml(__('Quick login binding')) ?></p>
        <?php if ($helper->isEnabledLine()):?>
            <a class="line-button-link"
               href="javascript:void(0);"
               rel="nofollow"
               data-role="eguana_sociallogin"
               data-href="<?= $block->escapeUrl($lineUrl) ?>"
               ClickText="<?= $block->escapeHtml(__('Login with LINE')) ?>"
               FormClasses="line-button-link"
               FormText="<?= $block->escapeHtml(__('Login with LINE')) ?>"
               ap-click-area="<?= $block->escapeHtmlAttr('Login') ?>"
               ap-click-name="<?= $block->escapeHtmlAttr('Login Click') ?>"
               ap-click-data="<?= $block->escapeHtmlAttr('Login with LINE') ?>">
                <?= $block->escapeHtml(__('Login with LINE')) ?>
            </a>
        <?php endif; ?>
        <?php if ($helper->isEnabledFacebook()):?>
            <a class="facebook-button-link"
               href="javascript:void(0);" rel="nofollow"
               data-role="eguana_sociallogin"
               data-href="<?= $block->escapeUrl($facebookUrl) ?>"
               ClickText="<?= $block->escapeHtml(__('Login with Facebook')) ?>"
               FormClasses="facebook-button-link"
               FormText="<?= $block->escapeHtml(__('Login with Facebook')) ?>"
               ap-click-area="<?= $block->escapeHtmlAttr('Login') ?>"
               ap-click-name="<?= $block->escapeHtmlAttr('Login Click') ?>"
               ap-click-data="<?= $block->escapeHtmlAttr('Login with Facebook') ?>">
                <?= $block->escapeHtml(__('Login with Facebook')) ?>
            </a>
        <?php endif; ?>
        <?php if ($helper->isEnabledGoogle()):?>
            <a class="google-button-link"
               href="javascript:void(0);"
               rel="nofollow"
               data-role="eguana_sociallogin"
               data-href="<?= $block->escapeUrl($googleUrl) ?>"
               ClickText="<?= $block->escapeHtml(__('Login with Google')) ?>"
               FormClasses="google-button-link"
               FormText="<?= $block->escapeHtml(__('Login with Google')) ?>"
               ap-click-area="<?= $block->escapeHtmlAttr('Login') ?>"
               ap-click-name="<?= $block->escapeHtmlAttr('Login Click') ?>"
               ap-click-data="<?= $block->escapeHtmlAttr('Login with Google') ?>">
                <?= $block->escapeHtml(__('Login with Google')) ?>
            </a>
        <?php endif; ?>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "*": {
            "socialLoginJs": {}
        }
    }
</script>
