<?php
/** @var \Magento\Theme\Block\Html\Breadcrumbs $block */
/** @var \Magento\Catalog\ViewModel\Product\Breadcrumbs $viewModel */
$viewModel = $block->getData('viewModel');
$ProductBreadcrumbs = $this->getLayout()->createBlock('Sapt\CommonSapt\Block\Catalog\Product\Breadcrumbs');
$breadcrumbs = $ProductBreadcrumbs->getBreadcrumbs();
?>

<div class="breadcrumbs">
    <?php if (!empty($breadcrumbs)) : ?>
    <ul class="items">
        <?php
            foreach ($breadcrumbs as $crumbName => $crumbInfo) :
                $crumbInfo['title'] = (isset($crumbInfo['title']))? $crumbInfo['title']: '';
                $crumbInfo['label'] = (isset($crumbInfo['label']))? $crumbInfo['label']: '';
        ?>
        <li class="item <?= $block->escapeHtmlAttr($crumbName===0 ? 'home' : $crumbName) ?>">
            <?php if (isset($crumbInfo['link'])) : ?>
                <a href="<?= $block->escapeUrl($crumbInfo['link']) ?>"
                   title="<?= $block->escapeHtml($crumbInfo['title']) ?>"><?= $block->escapeHtml(__($crumbInfo['label'])) ?></a>
            <?php elseif ($crumbName === "product") : ?>
                <a href="<?= $block->getRequest()->getUriString(); ?>"
                   title="<?= $block->escapeHtml($crumbInfo['label']) ?>"><strong><?= $block->escapeHtml(__($crumbInfo['label'])) ?></strong></a>
            <?php else : ?>
                <?= $block->escapeHtml(__($crumbInfo['label'])) ?>
            <?php endif; ?>
        </li>
        <?php endforeach; ?>
    </ul>
    <?php endif; ?>
</div>

<?php
$widget = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonDecode($viewModel->getJsonConfigurationHtmlEscaped());
$widgetOptions = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($widget['breadcrumbs']);
?>
<?php if (empty($breadcrumbs)) : ?>
<script type="text/x-magento-init">
{
    ".breadcrumbs": {
        "breadcrumbs": <?= /* @noEscape */ $widgetOptions ?>
    }
}
<?php endif; ?>
</script>
