<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php
$isSalable = $block->getProduct()->getIsSalable();
if ($isSalable) {
    $availability = 'InStock';
} else {
    $availability = 'OutOfStock';
}
if ($block->getProduct()->getTypeId() == 'bundle') {
    $price = $block->getProduct()->getPriceInfo()->getPrice('final_price')->getMinimalPrice()->getValue();
} else {
    $price = $block->getProduct()->getFinalPrice();
}
?>
<?php
$sortDescription = $this->helper(Magento\Catalog\Helper\Output::class)->productAttribute(
    $block->getProduct(),
    $block->getProduct()->getShortDescription(),
    'short_description'
);

$additionalData = $block->getModelAdditionalData();
$code = $additionalData->getCurrencyCode();
?>
<script type="application/ld+json">
    {
        "@context": "https://schema.org/",
        "@type": "Product",
        "name": "<?= /* @noEscape */ $block->escapeHtml($block->getProduct()->getName()) ?>",
        "productID": "<?= /* @noEscape */ $block->escapeHtml($block->getProduct()->getSku()) ?>",
        "image": "<?= $block->escapeUrl($block->getImage($block->getProduct(), 'product_base_image')->getImageUrl()) ?>",
        "description": "<?= /* @noEscape */ $block->getProduct()->getShortDescription() ? $sortDescription : $block->escapeHtml($block->getProduct()->getName()) ?>",
        "brand": {
            "@type": "Thing",
            "name": "Laneige"
        },
        "offers": {
            "price": "<?= /* @noEscape */ $block->escapeHtml(round($price)) ?>",
            "priceCurrency": "<?= $code ?>",
            "availability": "<?= $availability ?>"
        }
    }
</script>
