<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var Magento\Wishlist\Block\Catalog\Product\ProductList\Item\AddTo\Wishlist $block */
?>
<?php
$productType = $block->getProduct()->getTypeId();
if ($productType == 'bundle')
{
    $product = $block->getProduct();
    $optionsCollection = $product->getTypeInstance(true)
        ->getSelectionsCollection(
            $product->getTypeInstance(true)->getOptionsIds($product),
            $product
        );
    $requestData = [];
    foreach ($optionsCollection as $options) {
        $requestData['bundle_option['.$options->getOptionId().']'] = (int) $options->getSelectionId();
        $requestData['bundle_option_qty['.$options->getOptionId().']'] = (int) $options->getSelectionQty();
    }
    $requestData['qty'] = 1;
} else {
    $requestData = [];
}
?>
<?php if ($block->getWishlistHelper()->isAllow()) : ?>
	<!-- ko scope: 'ajaxwishlist' -->
    <a
       clicktext="<?= $block->escapeHtml(__('Add to Wish List')) ?>"
       formtext="<?= $block->escapeHtml(__('Add to Wish List')) ?>"
       class="action towishlist"
       title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
       aria-label="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
       data-action="wishlist-actions"
       data-product-id='<?= $block->getProduct()->getId() ?>'
       data-bind="css:{wishlisticon : wishlistitem().all_wishlist_items ?
       typeof wishlistitem().all_wishlist_items[<?=/* @noEscape */$block->getProduct()->getId()?>] !='undefined':false}"
       role="button">
        <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
    </a>
	<!-- /ko -->
<?php endif; ?>
