<div id="pdp-final-price-ajax"></div>
<?php
/**
 * @var $block \CJ\PointRedemption\Block\FinalPriceAjax
 */
$url = $block->getAjaxUrl();
$productId = $block->getCurrentProductId();
?>
<script type="text/javascript">
    require(['jquery'], function ($) {
            $.ajax({
                url: "<?=$url?>",
                type: "POST",
                data: {product_id: <?=$productId?>},
                dataType: "json",
            }).done(function (data) {
                $('#pdp-final-price-ajax').html(data.output);
            });
    });
</script>
