<?php
/**
 * Top menu for store
 *
 * @see \Satp\Megamenu\Block\Topmenu
 */
?>
<?php
    $_helper = $this->helper('Satp\Megamenu\Helper\Data');
    $_config = $_helper->getConfig('satp_megamenu');
    $columnsLimit = 0;
    if($_config['general']['enable']) {
?>
<?php $_menu = $block->getMegamenuHtml(); ?>

<nav class="navigation satp-megamenu side-megamenu" role="navigation">
    <ul>
        <?php echo $_menu; ?>
    </ul>
</nav>

<script type="text/javascript">
    require([
        'jquery',
        'Satp_Megamenu/js/satp_megamenu'
    ], function ($) {
        $(".satp-megamenu").satpMegamenu();
    });
</script>
<?php
    }
?>
