<?php
/**
 * Created by Eguana Team.
 * User: sonia
 * Date: 6/20/20
 * Time: 10:02 PM
 */

namespace Eguana\GWLogistics\Test\Unit\Model\Request;

use Eguana\GWLogistics\Model\Request\CvsCreateShipmentOrder;
use PHPUnit\Framework\TestCase;

class CvsCreateShipmentOrderTest extends TestCase
{
    /**
     * @var CvsCreateShipmentOrder
     */
    private $cvsCreateShipmentOrder;

    protected function setUp()
    {
        $objectManager = new \Magento\Framework\TestFramework\Unit\Helper\ObjectManager($this);
        $this->cvsCreateShipmentOrder = $objectManager->getObject(CvsCreateShipmentOrder::class);
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function tearDown()
    {
        $this->cvsCreateShipmentOrder = null;
    }

    public function testExecute()
    {
        $this->expectOutputString(''); // tell PHPUnit to expect '' as output
//        print_r("Hello World");
//        print "Ping";
//        echo "Pong";
        $out = "Foo";
        var_dump($out);
    }

    public function testGetCheckSum()
    {
        $result = 'eguana';
        $this->assertEquals(
            $result,
            $this->cvsCreateShipmentOrder->getCheckSum()
        );
    }

}
