<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
$_product = $block->getProduct();
$productImage = $_imagehelper->init($_product, 'category_page_grid')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(72);
$productImageUrl = $productImage->getUrl();
?>
<div class="sticky-product">
    <div class="sticky-product-images">
        <div class="sticky-image">
            <img class="default_image" src="<?php echo $productImageUrl; ?>" alt="<?php echo $productImage->getLabel(); ?>"/>
        </div>
        <div class="sticky-detail">
            <h2 class="product-name"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></h2>
            <div class="sticky-selected-detail not-show" data-empty="<?= __('Choose a color') ?>"></div>
        </div>
    </div>
</div>

<?php if ($_product->isSaleable()): ?>
    <script type="text/javascript">
        require([
            'jquery',
            'underscore'
        ], function ($, _) {
            var p_scrolled = false;
            var offsetPrepare = $('.box-tocart').offset().top + $('.box-tocart').outerHeight();
            var offset = $('.box-tocart').offset().top + $('.box-tocart').outerHeight() ;

            var devent = _.debounce(function () {

                if(offsetPrepare < $(window).scrollTop()){
                    $(".product-info-main").addClass("sticky");
                }

                if(offset < $(window).scrollTop() && !p_scrolled){
                    p_scrolled = true;
                    $(".product-info-main").addClass("stickyshow");
                    if ($(window).width() < 768) {
                        var mWrapBundle = $('.product-info-main.sticky').find('.bundle-options-wrapper , .field-wrapper-qty');
                        if (!$(".product-info-main-wrapper").hasClass("is_popupcart")) {
                            mWrapBundle.hide();
                        }
                    }
                }
                if(offsetPrepare >= $(window).scrollTop()){
                    $(".product-info-main").removeClass("sticky");
                }
                if(offset >= $(window).scrollTop() && p_scrolled){
                    var mWrapBundle = $('.product-info-main').find('.bundle-options-wrapper , .field-wrapper-qty');
                    p_scrolled = false;
                    $(".product-info-main").removeClass("stickyshow");
                    $(".product-info-main-wrapper").removeClass("is_popupcart");
                    var formHeight = $('.product-info-main-wrapper').height();
                    // $('.product-info-main-wrapper').css('min-height', formHeight + 'px');
                    if ($(window).width() < 768) {
                        mWrapBundle.show();
                    }
                }

                var mWrapBundle = $('.product-info-main.sticky').find('.bundle-options-wrapper , .field-wrapper-qty');
                var hasSticky = $('.product-info-main').hasClass('sticky');
                if (mWrapBundle.is(":visible") && hasSticky) {
                    $('.product-info-main-wrapper').addClass('is_popupcart');
                }
            }, 100);

            $(window).scroll(function(){
                devent();
            });

            if ($(window).width() < 768) {
                $(".product-info-main").prepend("<div class='btn_close_popcart'>Close</div>");
                $(".btn_close_popcart").click(function(){
                    var mWrapBundle = $('.product-info-main.sticky').find('.bundle-options-wrapper , .field-wrapper-qty');
                    if (mWrapBundle.is(":visible")) {
                        mWrapBundle.hide();
                        $('.product-info-main-wrapper').removeClass('is_popupcart');
                        return;
                    }
                });

                $(document).click(function(e)  {
                    var container = $(".product-add-form");
                    var stickyProduct = $(".product-info-main");
                    var popupCart = $('.product-info-main-wrapper');

                    // if the target of the click isn't the container nor a descendant of the container
                    if (!container.is(e.target) && container.has(e.target).length === 0) {
                        if(stickyProduct.hasClass('sticky') && popupCart.hasClass('is_popupcart')) {
                            var mWrapBundle = $('.product-info-main.sticky').find('.bundle-options-wrapper , .field-wrapper-qty');
                            if (mWrapBundle.is(":visible")) {
                                mWrapBundle.hide();
                                $('.product-info-main-wrapper').removeClass('is_popupcart');
                                return;
                            }
                        }
                    }
                });
            }

        });
    </script>
<?php else :?>
    <script type="text/javascript">
        require([
            'jquery'
        ], function ($) {
            $(".product-info-scroll").addClass("product-soldout");
        });
    </script>
<?php endif; ?>

<script type="text/javascript">
    require([
        'jquery'
    ], function ($) {
        $(document).ready(function(){
            var formHeight = $('.product-info-main-wrapper').height();
            // $('.product-info-main-wrapper').css('min-height', formHeight + 'px');
        });

        $('.product.oneline-review .review-rating-wrapper a').click(function(e){
            e.preventDefault();
            $('#tab-label-reviews').click();

            $([document.documentElement, document.body]).animate({
                scrollTop: $("#review-form").offset().top - 55
            }, 300);

            setTimeout(function(){
                $([document.documentElement, document.body]).animate({
                    scrollTop: $("#review-form").offset().top - 55
                }, 300);
            }, 300);
        });
    });
</script>
