<!--<title>旗艦店和水療項目 | 雪花秀</title>-->
<!--<meta name="description" content="享受奢華的SPA，包括高級抗衰老、面部護理和身體護理，可在首爾Balance SPA旗艦店、Balance SPA旗艦店和水療樂天享受 | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="og:title" content="旗艦店和水療項目 | 雪花秀">-->
<!--<meta property="og:description" content="享受奢華的SPA，包括高級抗衰老、面部護理和身體護理，可在首爾Balance SPA旗艦店、Balance SPA旗艦店和水療樂天享受 | Sulwhasoo Hong Kong 中國香港">-->
<!--<meta property="twitter:title" content="旗艦店和水療項目 | 雪花秀">-->
<!--<meta property="twitter:description" content="享受奢華的SPA，包括高級抗衰老、面部護理和身體護理，可在首爾Balance SPA旗艦店、Balance SPA旗艦店和水療樂天享受 | Sulwhasoo Hong Kong 中國香港">-->

<section class="content">
    <h1 class="blind">SPA PROGRAMS</h1>
    <div class="l-wrap">
        <div class="programs-container">
            <section class="programs-section">
                <div class="programs">
                    <div class="programs-thumb">
                        <img src="/media/html/resource/img/spa/img_programs_01.jpg" class="thumb-l" alt="">
                        <img src="/media/html/resource/img/spa/img_programs_01_m.jpg" class="thumb-m" alt="">
                    </div>
                    <div class="programs-desc">
                        <div class="h">尊貴特色療程</div>
                        <p class="p">Sulwhasoo SPA的皇牌療程，運用尊貴產品及特別的工具作全身整全護理。</p>
                    </div>
                    <div class="more"><i class="icon-more"></i></div>
                </div>
                <div class="programs-reserve">
                    <div class="parsys signature">
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">人參傳承活顏之旅</h2>
                                <div class="desc">
                                    承傳雪花秀52年人參精研成果，透過韓式經絡及全新韓方手法由面部、肩頸及至背部作激活按摩護理，享受全方位滋養修護體驗。 配合極致珍貴人參全效護理系列，以99.9純金箔及8倍人參活性皂苷等尊貴成份，將活顏抗氧能量灌注至肌底，活化肌膚細胞循環，讓肌膚緊緻柔滑，回復透亮彈性。
                                    <span class="price"><i>140 分鐘</i> HKD 3,600</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_a80d" class="btn" data-track-name="人參全效滋補之旅 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">珍雪臻金煥生之旅</h2>
                                <div class="desc">
                                    選用珍貴琥珀配上紅松樹精華油從頭部到腿部進行身體深層按摩。面部護理亦會配以全面功能提升的珍雪臻金煥生系列，締造年輕緊緻輪廓，能有效即時淡化紋理及改善浮腫，能使肌膚剔透明亮及幼嫩柔滑。
                                    <span class="price"><i>140 分鐘</i> HKD 4,200</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_92fc" class="btn" data-track-name="極致珍雪全效煥活之旅 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">珍雪芊萃琉金三重臻極護理</h2>
                                <div class="desc">
                                    以白玉胸肩淋巴按摩，促進人體代謝，加強肌膚吸收產品功效；透過珍雪芊萃琉金系列作三重式重整修護，為肌膚注入源源不絕的年輕活力，激活肌膚超卓再生力，為細胞對抗衰老問題，提升肌膚彈性，使肌膚重拾活力及光采。<br/>
                                    <br/>
                                    • 重煥肌膚逆齡因子<br/>
                                    • 重生年輕細胞<br/>
                                    • 重拾肌膚彈性<br/>
                                    <span class="price"><i>135 分鐘</i> HKD 5,600</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_92fc" class="btn" data-track-name="極致珍雪全效煥活之旅 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <section class="programs-section">
                <div class="programs">
                    <div class="programs-thumb">
                        <img src="/media/html/resource/img/spa/img_programs_02.jpg" class="thumb-l" alt="">
                        <img src="/media/html/resource/img/spa/img_programs_02_m.jpg" class="thumb-m" alt="">
                    </div>
                    <div class="programs-desc">
                        <div class="h">面部護理</div>
                        <p class="p">採用Sulwhasoo護膚產品作深層的面部療程。</p>
                    </div>
                    <div class="more"><i class="icon-more"></i></div>
                </div>
                <div class="programs-reserve">
                    <div class="parsys facial">
                        <!-- <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">白樺白瓷水律舒膚護理</h2>
                                <div class="desc">
                                    專為缺水過敏肌膚而設的舒緩護理，配合冰涼白瓷作按摩，即時舒緩降紅 ，令肌膚回復水漾細緻。
                                    <span class="price"><i>90 分鐘</i> HKD 1,400</span>
                                </div>
                                <div class="func">
                                </div>
                            </div>
                        </div> -->
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">白參白瓷水漾美肌護理</h2>
                                <div class="desc">
                                    以人參籽油配合冰涼白瓷按摩，為細胞注入水份；再以明褘草固本精華液及高濃度美白精華有效地加強肌膚吸收能力，使肌膚水凝、透亮。
                                    <span class="price"><i>90 分鐘</i> HKD 1,700</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_89b8" class="btn" data-track-name="白參白瓷水漾美肌護理 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">白參白玉滋晶煥白護理</h2>
                                <div class="desc">
                                    以珍貴白參對抗乾燥、膚色不均的亮白護理，配合滋陰清熱的白玉按摩肌膚，全效勻淨膚色並提升彈性，瞬間重現飽滿亮白狀態。
                                    <span class="price"><i>100分鐘</i> HKD 1,900</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_6cc3" class="btn" data-track-name="白參白玉滋晶煥白護理 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">梅花煥活緊緻護理</h2>
                                <div class="desc">
                                    針對因經睡眠不足、工作緊張等引致肌膚疲倦灰暗、深增層缺水，失卻彈性等輕熟肌膚問題。以強效抗氧化的雪御梅花系列為肌膚細胞作防護，配以儀器及韓方細胞激活按摩，使肌膚高效抗氧及回復彈性。
                                    <span class="price"><i>110 分鐘</i> HKD 2,100</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_d3e1" class="btn" data-track-name="白參無瑕亮肌護理 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">白參無瑕亮肌護理</h2>
                                <div class="desc">
                                    適合受到光害或因年齡變改變所致的色斑肌膚，以滋晶雪瀅煥白系列作深層護理，令色斑瞬間減退，展現顯著美白效果，還原肌膚白晳晶瑩及柔潤彈性。
                                    <span class="price"><i>110 分鐘</i> HKD 2,500</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_d3e1" class="btn" data-track-name="白參無瑕亮肌護理 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">人參翡翠滋陰煥顏護理</h2>
                                <div class="desc">
                                    以滋陰生人參面霜配合翡翠玉石作按摩，深層灌注人參滋養，全效賦活元氣淡化紋理，煥發緊緻嫩顏光采。
                                    <span class="price"><i>100分鐘</i> HKD 2,100</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_b7e" class="btn" data-track-name="人參翡翠滋陰煥顏護理 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">赤松琥珀珍雪活顏護理</h2>
                                <div class="desc">
                                    選用極致尊貴的珍雪系列產品，讓肌膚深層盡享珍罕赤松的長青生機，配合蘊藏陽能量的琥珀作按摩，預防色斑及促進修復受損細胞，肌膚瞬間回春再生。
                                    <span class="price"><i>100 分鐘</i> HKD 2,400</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_2511" class="btn" data-track-name="赤松琥珀珍雪活顏護理 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">赤松黑矅石排毒緊緻護理</h2>
                                <div class="desc">
                                    以尊貴珍雪系列配合黑曜石作按摩，有效吸收皮膚表層雜質，加速改善肌膚代謝功能，提升面部輪廓，回復皮膚青春緊緻狀態。
                                    <span class="price"><i>110 分鐘</i> HKD 2,800</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_5dba" class="btn" data-track-name="赤松黑矅石排毒緊緻護理 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">赤松珍雪輪廓重塑緊緻護理</h2>
                                <div class="desc">
                                    利用尊貴全效珍雪系列作深層細胞激活按摩，即時拉緊肌膚彈性纖維，阻截肌膚老化的連鎖效應，撫平紋理，塑造完美緊緻輪廓；逶過琥珀能量石按摩，帶動氣血運行，使肌膚迅速吸收珍罕赤松及野生人參的精萃，令肌膚瞬間回復彈性和活力。
                                    <span class="price"><i>110 分鐘</i> HKD 3,200</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_3c34" class="btn" data-track-name="赤松珍雪細胞更生護理 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <section class="programs-section">
                <div class="programs">
                    <div class="programs-thumb">
                        <img src="/media/html/resource/img/spa/img_programs_03.jpg" class="thumb-l" alt="">
                        <img src="/media/html/resource/img/spa/img_programs_03_m.jpg" class="thumb-m" alt="">
                    </div>
                    <div class="programs-desc">
                        <div class="h">身體護理</div>
                        <p class="p">運用Sulwhasoo特別調配的身體按摩油作深層的身體護理。</p>
                    </div>
                    <div class="more"><i class="icon-more"></i></div>
                </div>
                <div class="programs-reserve">
                    <div class="body parsys">
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">寧神舒肌按摩</h2>
                                <div class="desc">
                                    以全新的韓方平衡按摩手法，有效舒緩繃緊肌肉，為疲憊的身體肌膚傳遞活力和生機。
                                    <span class="price"><i>70 分鐘 / 100 分鐘</i> HKD 1,100 / HKD 1,500</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_2005" class="btn" data-track-name="忘憂舒緩按摩護理 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">艾鹽深層肌肉按摩</h2>
                                <div class="desc"> 以獨特手法舒張筋膜再以配合深層經絡穴位按摩，將繃緊肌肉放鬆，然後加上艾鹽熱包透過熱力加速背部的氣血循環，將體内濕氣、寒氣排走，使肌肉放鬆，減輕因運動及工作勞損、肌肉酸痛疲勞、婦女週期腹背痛不適等疼痛問題。
                                    <span class="price"><i>70 分鐘 / 100 分鐘</i> HKD 1,350 / HKD 1,850</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_565d" class="btn" data-track-name="深層肌肉舒解按摩 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">滋陰丹舒壓按摩</h2>
                                <div class="desc">
                                    使用滋陰丹草球為背部及後腿作按摩，利用熱力將韓方草藥滲透至肌理，能改善身體機能， 特別針對痠痛肌肉，有效減輕關節痛楚及腳部水腫，同時加速血液循環，為繃緊肌肉帶來鬆弛效果。
                                    <span class="price"><i>90 分鐘</i> HKD 1,700</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_31a0" class="btn" data-track-name="滋陰丹草球熱療 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">琥珀能量石排毒按摩</h2>
                                <div class="desc">以琥珀能量寶石於肩、背、腰及前腿作按摩，帶走負能量，排毒淨化，特別針對因過度疲倦，引致血氣及淋巴循環不佳的狀況，使身體能量提升，同時加速血液循環， 去除水腫情況，為疲倦狀態注入能量。
                                    <span class="price"><i>100 分鐘</i> HKD 2,200</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_31a0" class="btn" data-track-name="滋陰丹草球熱療 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">腹腔調和養生護理</h2>
                                <div class="desc">
                                    以擁有「醫草」美譽的艾草於腹部進行韓式溫熱療法，利用磁療捧拍按腹部以煥醒深層經絡，配合腹部按摩及緊膚體膜，有效調和五臟六腑，提升身體自癒機能，回復肌膚彈性。
                                    <span class="price"><i>90 分鐘</i> HKD 1,400</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_b71a" class="btn" data-track-name="腹腔調和養生護理 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">胸部腺體順行護理</h2>
                                <div class="desc">
                                    以擁有「醫草」美譽的艾草於胸部進行韓式溫熱療法，利用磁療捧拍按腹部以煥醒胸部腺體活躍性，配合胸部按摩及緊膚體膜，有效疏通乳腺，緊緻及提升胸部線條。
                                    <span class="price"><i>90 分鐘</i> HKD 1,500</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_99bd" class="btn" data-track-name="胸部腺體順行護理 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">胸腹整全護理</h2>
                                <div class="desc">
                                    以擁有「醫草」美譽的艾草於胸腹位置進行韓式溫熱療法，利用磁療捧拍按胸腹部以煥醒腺體活躍性，配合胸腹按摩及緊膚體膜，提升全身血氣循環，加強代謝功能，回復肌膚緊緻亮滑。
                                    <span class="price"><i>120 分鐘</i> HKD 2,300</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_5e7c" class="btn" data-track-name="胸腹整全護理 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <section class="programs-section">
                <div class="programs">
                    <div class="programs-thumb">
                        <img src="/media/html/resource/img/spa/img_programs_04.jpg" class="thumb-l" alt="">
                        <img src="/media/html/resource/img/spa/img_programs_04_m.jpg" class="thumb-m" alt="">
                    </div>
                    <div class="programs-desc">
                        <div class="h">重點護理</div>
                        <p class="p">可搭配面部護理或身體護理，達至更佳效果。</p>
                    </div>
                    <div class="more"><i class="icon-more"></i></div>
                </div>
                <div class="programs-reserve">
                    <div class="parsys addon">
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">明眸眼部護理</h2>
                                <div class="desc">
                                    以獨特的眼部穴位按壓,，刺激眼部穴位，促進眼部血液運行，放鬆眼周肌肉，改善眼部浮腫，淡化黑眼圈。
                                    <span class="price"><i>15 分鐘</i> HKD 350</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_b256" class="btn" data-track-name="明眸眼部護理 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">再生眼部護理</h2>
                                <div class="desc">
                                    以RF緊膚美肌儀緊緻眼部肌膚，淡化眼部皺紋、魚尾紋，改善眼袋及黑眼圈等眼部問題。
                                    <span class="price"><i>30 分鐘</i> HKD 750</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_6037" class="btn" data-track-name="再生眼部護理 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">琥珀明亮眼部護理</h2>
                                <div class="desc">
                                    利用松樹脂經千年石化而成的珍貴寶石琥珀作按摩眼部，舒緩眼部疲憊，提升眼部循環，改善黑眼圈，眼袋及眼部疲倦等問題。
                                    <span class="price"><i>35 分鐘</i> HKD 800</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_9941" class="btn" data-track-name="琥珀明亮眼部護理 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">白玉煥顏眼部護理</h2>
                                <div class="desc">
                                    以具有冰涼感覺的白玉為眼周肌膚作按摩，再配合珍雪眼部產品以及人參煥顏眼膜，有效改善眼周浮腫，紋理，彈性等問題，重煥眼部年輕活力。
                                    <span class="price"><i>35 分鐘</i> HKD 950</span>
                                </div>
                                <div class="func">
                                </div>
                            </div>
                        </div>
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">頸部滋養護理</h2>
                                <div class="desc">
                                    以獨特的按摩手法，促進頸部循環功能。配合以草藥調製的頸膜，深層滋潤頸部肌膚，改善頸部細紋。
                                    <span class="price"><i>30 分鐘</i> HKD 600</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_8c32" class="btn" data-track-name="頸部滋養護理 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">RF 頸部緊緻活肌護理</h2>
                                <div class="desc">
                                    以RF緊膚美肌儀器緊緻提升頸部肌膚，再配合經絡舒緩按摩，暢通淋巴循環，深層賦活細胞，全面改善頸部肌膚紋理並提升彈性，令幼嫩頸部肌膚如絲細緻。
                                    <span class="price"><i>30 分鐘</i> HKD 750</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_6b36" class="btn" data-track-name="RF 頸部緊緻活肌護理 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">頸部理紋療法</h2>
                                <div class="desc">
                                    以獨特的按摩手法，促進頸部循環功能。配合膠原頸膜，深層滋潤頸部肌膚，達至提升、緊膚、去皺等功效。
                                    <span class="price"><i>35 分鐘</i> HKD 800</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_cb1e" class="btn" data-track-name="頸部理紋療法 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">滋養活肌護理</h2>
                                <div class="desc">
                                    以重點式高效修復肌膚問題的高濃度精華液，配合獨特的「無間高脈衝電子牽引科技」，加強滲透效果，瞬間為細胞灌注所需養分，於任何季節皆可滿足不同膚質需要，讓肌膚盡享針對性之滋補呵護。
                                    <span class="price"><i>30 分鐘</i> HKD 800</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_53fb" class="btn" data-track-name="滋養活肌護理 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">滋陰丹草球背肌舒緩護理</h2>
                                <div class="desc">
                                    以雪花秀獨有的滋陰丹及滋陰保衛丹草球經溫熱後，於肩背按壓，促進血氣運行，消除肩背疲勞。
                                    <span class="price"><i>30 分鐘</i> HKD 600</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_e948" class="btn" data-track-name="滋陰丹草球背肌舒緩護理 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">腹腔養生熱敷護理</h2>
                                <div class="desc">
                                    以素有「醫草」美譽之艾草於腹部作熱敷護理，發揮溫炙療效，有助暢通腰腹部位的血氣循環，調和五臟六腑。
                                    <span class="price"><i>20 分鐘</i> HKD 500</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_29a0" class="btn" data-track-name="腹腔養生熱敷護理 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">淋巴排毒腿部護理</h2>
                                <div class="desc">
                                    以獨有的精華油按摩，配合白泥軟膜中和毒素，舒緩腿部僵硬肌肉，促進血氣運行。
                                    <span class="price"><i>30 分鐘</i> HKD 500</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_ca1e" class="btn" data-track-name="淋巴排毒腿部護理 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">金箔人參手部滋養護理</h2>
                                <div class="desc">
                                    以特製的人參籽精華配合高效抗氧化的99.9%純金金箔進行手部按壓，配合珍貴的人參籽精華，賦予深層手部肌膚活力滋養。
                                    <span class="price"><i>45 分鐘</i> HKD 400</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_4f3" class="btn" data-track-name="金箔人參手部滋養護理 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">重點深層舒緩按摩</h2>
                                <div class="desc">
                                    針對局部肌肉蹦緊部位作深層按摩，消除肌肉緊張，即時舒緩蹦緊肌肉，減輕肌肉痛症。
                                    <span class="price"><i>30 分鐘</i> HKD 600</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_d4fd" class="btn" data-track-name="重點深層舒緩按摩 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">清瑩淨肌背部護理</h2>
                                <div class="desc">
                                    利用蘊含桑樹精華及玉竹粉的美白粉糰進行背部護理，即時收斂過多的油脂分泌，淨化背部肌膚，締造柔滑亮白美肌。
                                    <span class="price"><i>35 分鐘</i> HKD 800</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_fac0" class="btn" data-track-name="清瑩淨肌背部護理 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">腹腔調和養生按摩</h2>
                                <div class="desc">
                                    以擁有「醫草」美譽的艾草進行韓式溫熱療法，促進血氣運行。配合獨特的磁療捧以煥醒深層經絡，再於腹部按摩，有效調和五臟六腑，提升身體免疫和自癒機能。
                                    <span class="price"><i>40 分鐘</i> HKD 900</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_e524" class="btn" data-track-name="腹腔調和養生按摩 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">人參舒膚護理</h2>
                                <div class="desc">
                                    以細滑天然晶體及珍貴的紅參精華作全身磨砂，深層去除老化角質，促進細胞吸收力。配合紅參精華體膜，為肌膚灌注無窮活力， 回復自然光采。
                                    <span class="price"><i>40 分鐘</i> HKD 1,200</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_c14f" class="btn" data-track-name="人參舒膚護理 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>

                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">白玉淋巴排毒煥活護理</h2>
                                <div class="desc">
                                    以香薰油及白玉作胸肩乳腺淋巴排毒按摩，促進人體代謝廢物排出，加強血液和淋巴液的循環，舒緩肩頸背痛及胸部脹痛問題。
                                    <span class="price"><i>20 分鐘</i> HKD 900</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_e524" class="btn" data-track-name="腹腔調和養生按摩 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">琥珀頭部按摩</h2>
                                <div class="desc">
                                    以香薰精油及琥珀玉石，為崩緊頭皮作疏通經絡按摩，加強氣血循環，放鬆肌肉，紓緩頭痛，改善睡眠質素。
                                    <span class="price"><i>20 分鐘</i> HKD 700</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_e524" class="btn" data-track-name="腹腔調和養生按摩 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">白玉腿部排毒按摩</h2>
                                <div class="desc">
                                    以香薰精油及白玉玉石，針對腰腿酸痛，以穴位刺激，激活腿部動脈氣血循環，紓緩腿部崩緊肌肉；疏通經絡，改善氣血淋巴循環促進肝膽排毒，提升身體免疫力。
                                    <span class="price"><i>30 分鐘</i> HKD 900</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_e524" class="btn" data-track-name="腹腔調和養生按摩 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>
                        <div class="parbase program section">
                            <div class="programs-item">
                                <h2 class="h">紅參白玉足底護理</h2>
                                <div class="desc">
                                    以珍貴的紅參精華作腿部磨砂，深層去除老化角質，促進細胞吸收力；以香薰精油及白玉玉石，針對腿部氣血循環不佳，深層帶動體內津液流動，改善氣血淋巴循環，加速新陳代謝。
                                    <span class="price"><i>35 分鐘</i> HKD 900 <br /><br /> * 重點護理須同時享用60分鐘或以上的護理服務。 <br />* 尚有更多限定美療禮遇，歡迎致電2314 3288查詢。</span>
                                </div>
                                <div class="func">
                                    <!--<a href="/hk/zh/spa/reservation.html#program_e524" class="btn" data-track-name="腹腔調和養生按摩 Reservations">預約</a>-->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</section>

