<?php
/** @var \CJ\DataLayer\Block\DataLayer $block */
$currentProduct = $block->getCurrentProduct();
/** @var \CJ\DataLayer\ViewModel\Data $viewModel */
$viewModel = $block->getData('view_model');
?>
<script type="text/x-magento-init">
    {
        "*": {
            "CJ_DataLayer/js/actions/product-detail": {
                "currency": "<?= $viewModel->getCurrencyCode() ?>",
                "products": {
                    "name": "<?= $block->escapeHtml($currentProduct->getName()) ?>",
                    "id": "<?= $block->escapeHtml($currentProduct->getSku()) ?>",
                    "price": <?= (int)$currentProduct->getFinalPrice() ?>,
                    "category": "<?= $block->escapeHtml($block->getProductCategory($currentProduct)) ?>",
                    "quantity": <?= $viewModel->getMinQtyAllow() ?>
                }
            }
        }
    }
</script>
