<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
/** @var \Sapt\AjaxWishlist\ViewModel\AjaxWishlistStatus $viewModel */

$viewModel = $block->getData('wishlistStatusViewModel');
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) : ?>
    <?php
    $type = 'widget-product-carousel';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    ?>
    <ol class="products list items product-items <?= /* @noEscape */ $type ?>">
        <?php $iterator = 1; ?>
        <?php foreach ($items as $_item) : ?>
            <?= /* @noEscape */ ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
            <div class="product-item-info">
                <div class="product_box_photo">
                    <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
                        <?= $block->getImage($_item, $image)->toHtml() ?>
                    </a>
                    <div class="product-item-inner">
                        <div class="product-item-actions">
                            <div class="actions-secondary" data-role="add-to-links">
                                <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist) : ?>
                                    <?php //if ($viewModel->moduleStatus()): ?>
                                    <?php if (true): ?>
                                        <!-- ko scope: 'ajaxwishlist' -->
                                        <a data-bind="css:{wishlisticon : wishlistitem().all_wishlist_items?typeof wishlistitem().all_wishlist_items['<?= $block->escapeHtmlAttr($_item->getId()) ?>'] != 'undefined':false}"
                                           data-wishlist-action='<?= /* @noEscape */ $block ->getAddToWishlistParams($_item) ?>'
                                           data-action="wishlist-actions"
                                           data-product-id='<?= /* @noEscape */ $_item->getId() ?>'
                                           class="action towishlist"
                                           title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                            <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                        </a>
                                        <!-- /ko  -->
                                    <?php else: ?>
                                        <a href="#"
                                           data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                            <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                        </a>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="product-item-details">
                    <strong class="product-item-name">
                        <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                           href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                           class="product-item-link">
                            <?= $block->escapeHtml($_item->getName()) ?>
                        </a>
                    </strong>

                    <?= $block->getProductPriceHtml($_item, $type) ?>

                    <?php if ($templateType) : ?>
                        <?= $block->getReviewsSummaryHtml($_item, $templateType, true) ?>
                    <?php endif; ?>

                    <?php if ($showCart) : ?>
                        <div class="product-item-inner">
                            <div class="product-item-actions">
                                <?php if ($showCart) : ?>
                                    <div class="actions-primary">
                                        <?php if ($_item->isSaleable()) : ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                            <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_item->getSku()) ?>" action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
                                                <input type="hidden" name="product" value="<?= $block->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                <?= $block->getBlockHtml('formkey') ?>
                                                <button type="submit"
                                                        title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                        class="action tocart primary">
                                                    <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                </button>
                                            </form>
                                        <?php else : ?>
                                            <button class="action tocart primary disabled"
                                                    type="button" disabled
                                                    title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                <span><?= $block->escapeHtml(__('Sold out')) ?></span>
                                            </button>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
            <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
        <?php endforeach ?>
    </ol>
<?php endif;?>
