<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\NegotiableQuote\Block\Quote\Totals
 */
?>
<?php foreach ($block->getTotals() as $code => $total): ?>
    <?php if ($total->getBlockName()): ?>
        <?= $block->getChildHtml($total->getBlockName(), false) ?>
    <?php else:?>
        <?php $style = ($total->getStyle() ? ' ' . $total->getStyle() : '' ); ?>
        <tr class="<?= $block->escapeHtml($code . $style) ?>">
            <th <?= $block->escapeHtml($block->getLabelProperties()) ?> scope="row" class="mark">
                <?php if ($total->getStrong()):?>
                    <strong><?= $block->escapeHtml($total->getLabel()) ?></strong>
                <?php else:?>
                    <?= $block->escapeHtml($total->getLabel()) ?>
                <?php endif; ?>
            </th>
            <td <?= $block->escapeHtml($block->getValueProperties()) ?>
                data-th="<?= $block->escapeHtml($total->getLabel()) ?>"
                class="amount">
                <?php if ($total->getStrong()):?>
                    <strong>
                        <?= /* @noEscape */ $block->formatPrice(
                            $total->getValue(),
                            $total->getCurrency() ? $total->getCurrency() : $block->getQuote()->getQuoteCurrencyCode()
                        ) ?>
                    </strong>
                <?php else:?>
                    <?= /* @noEscape */ $block->formatPrice(
                        $total->getValue(),
                        $total->getCurrency() ? $total->getCurrency() : $block->getQuote()->getQuoteCurrencyCode())
                    ?>
                <?php endif; ?>
            </td>
        </tr>
    <?php endif; ?>
<?php endforeach?>
