<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
/* @var $getDefault \Eguana\CustomCatalog\ViewModel\GetDefaultCategory */

$getDefault = $block->getData('view_model_get_default_name');
?>

<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Customers Also Love');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = true;
            $templateType = null;
            $description = false;
        }
        break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Customers Also Love');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = true;
            $templateType = null;
            $description = false;
        }
        break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showAddTo = false;
            $showCart = true;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showAddTo = false;
            $showCart = true;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = count($block->getItems())) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
        break;

    default:
        $exist = null;
}
$_item = null;
?>


<?php if ($exist):?>

<?php if ($type == 'related' || $type == 'upsell'): ?>
<?php if ($type == 'related'): ?>
<div class="block <?= $block->escapeHtmlAttr($class) ?>"
     data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}'
     data-limit="<?= $block->escapeHtmlAttr($limit) ?>" data-shuffle="<?= /* @noEscape */ $shuffle ?>">
    <?php else: ?>
    <div class="block <?= $block->escapeHtmlAttr($class) ?>" data-mage-init='{"upsellProducts":{}}'
         data-limit="<?= $block->escapeHtmlAttr($limit) ?>" data-shuffle="<?= /* @noEscape */ $shuffle ?>">
        <?php endif; ?>
        <?php else: ?>
        <div class="block <?= $block->escapeHtmlAttr($class) ?>">
            <?php endif; ?>
            <div class="block-title title">
                <strong id="block-<?= $block->escapeHtmlAttr($class) ?>-heading" role="heading"
                        aria-level="2"><?= $block->escapeHtml($title) ?></strong>
            </div>
            <div class="block-content content" aria-labelledby="block-<?= $block->escapeHtmlAttr($class) ?>-heading">
                <?php if ($type == 'related' || $type == 'upsell'): ?>
                <div class="swiper-container products wrapper grid products-grid products-<?= $block->escapeHtmlAttr($type) ?>">
                    <ol class="swiper-wrapper products list items product-items">
                        <?php else: ?>
                        <div class="products wrapper grid products-grid products-<?= $block->escapeHtmlAttr($type) ?>">
                            <ol class="products list items product-items">
                                <?php endif; ?>
                                <?php foreach ($items as $_item): ?>
                                    <?php $available = ''; ?>
                                    <?php $productSku = $_item->getSku(); ?>
                                    <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                        <?php if (!$_item->getRequiredOptions()): ?>
                                            <?php $available = 'related-available'; ?>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    <?php if ($type == 'related' || $type == 'upsell'): ?>
                                        <li class="swiper-slide item product product-item">
                                    <?php else: ?>
                                        <li class="item product product-item">
                                    <?php endif; ?>
                                    <div class="product-item-info <?= /* @noEscape */ $available ?>">
                                        <?= /* @escapeNotVerified */ '<!-- ' . $image . '-->' ?>
                                        <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                           class="product photo product-item-photo"
                                           ap-click-area="product"
                                           ap-click-name="prd click"
                                           ap-click-data="<?= $getDefault->getProductByDefault($productSku)->getName() . '/' . $productSku ?>">
                                            <?= $block->getImage($_item, $image)->toHtml() ?>
                                        </a>
                                        <div class="product details product-item-details">
                                            <strong class="product name product-item-name">
                                                <a class="product-item-link"
                                                   title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                                   href="<?= /* @escapeNotVerified */ $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                                   ap-click-area="product"
                                                   ap-click-name="prd click"
                                                   ap-click-data="<?= $getDefault->getProductByDefault($productSku)->getName() . '/' . $productSku ?>">
                                                    <?= $block->escapeHtml($_item->getName()) ?></a>
                                            </strong>

                                            <?= /* @noEscape */ $block->getProductPrice($_item) ?>

                                            <?php if ($templateType): ?>
                                                <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                            <?php endif; ?>

                                            <div class="product-item-inner">
                                                <div class="product actions product-item-actions">
                                                    <?php if ($showAddTo || $showCart): ?>
                                                        <div class="actions-primary">
                                                            <?php if ($_item->isSaleable()): ?>
                                                                <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                                    <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}' type="button" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                                        <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                                    </button>
                                                                <?php else: ?>
                                                                    <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                                    $postData = $postDataHelper->getPostData($block->escapeUrl($block->getAddToCartUrl($_item)), ['product' => $_item->getEntityId()])
                                                                    ?>
                                                                    <button class="action tocart primary"
                                                                            data-post='<?= /* @escapeNotVerified */ $postData ?>'
                                                                            type="button" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                                        <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                                    </button>
                                                                <?php endif; ?>
                                                            <?php endif; ?>
                                                        </div>
                                                        <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                                            <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                                <?= $addToBlock->setProduct($_item)->getChildHtml() ?>
                                                            <?php endif; ?>
                                                        </div>
                                                    <?php endif; ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    </li>
                                <?php endforeach ?>
                            </ol>
                        </div>
                        <?php if ($type == 'related' || $type == 'upsell'): ?>
                            <div class="swiper-button-prev swiper-button-prev"></div>
                            <div class="swiper-button-next swiper-button-next"></div>
                        <?php endif; ?>
                </div>
            </div>
            <?php endif;?>
