<?php
/**
 * @author Eguana Team
 * @copyright Copyright (c) 2020 Eguana {http://eguanacommerce.com}
 * Created by PhpStorm
 * User: umer
 * Date: 22/6/20
 * Time: 6:29 PM
 */

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<div class="block block-customer-login">
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login">
                <div class="field email required">
                    <label class="label" for="email">
                        <span><?= $block->escapeHtml(__('Email / Phone number')) ?></span>
                    </label>
                    <div class="control">
                        <input
                            placeholder="<?= $block->escapeHtml(__('Email / Phone number')) ?>"
                            name="login[username]"
                            value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> id="email" type="text" class="input-text" placeholder="Enter email or mobile number" title="<?= $block->escapeHtmlAttr(__('Email / Phone number')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'mobileloginvalidationrule':true}">
                    </div>
                </div>
                <div class="field password required">
                    <label for="pass" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                    <div class="control">
                        <input placeholder="<?= $block->escapeHtml(__('Password')) ?>" name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}">
                    </div>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="submit"
                                class="action login primary"
                                name="send"
                                id="send2"
                                ap-click-area="<?= $block->escapeHtmlAttr(__('Login')) ?>"
                                ap-click-name="<?= $block->escapeHtmlAttr(__('Login Click')) ?>"
                                ap-click-data="<?= $block->escapeHtmlAttr(__('General Login')) ?>">
                            <span>
                                <?= $block->escapeHtml(__('Login')) ?>
                            </span>
                        </button>
                    </div>
                    <div class="secondary">
                        <a class="action remind"
                           href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"
                           ap-click-data="<?= $block->escapeHtmlAttr(__('Forgot Your Password?')) ?>">
                            <span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span>
                        </a>
                        <?= $block->getChildHtml('customer.new') ?>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
<script type="text/x-magento-init">
   {
       "*": {
           "mobileLoginRule": {}
       }
   }
</script>
