<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\Compare\ListCompare */
try {
    $ecommerceStatus = $this->helper('Eguana\EcommerceStatus\Helper\Data::class')->getECommerceStatus();
}catch (\Exception $e){
    $ecommerceStatus = 1;
}
?>
<?php $total = $block->getItems()->getSize() ?>
<?php if ($total): ?>
    <div class="table-wrapper comparison">
        <table class="data table table-comparison" id="product-comparison"
               data-mage-init='{"compareList":{
                    "windowPrintSelector":".action.print",
                    "productsInRow":"5",
                    "selectors":{
                        "productAddToCartSelector":"button.action.tocart"}
                }}'>
            <tbody>
            <tr>
                <?php $index = 0; ?>
                <?php $helper = $this->helper(Magento\Catalog\Helper\Output::class); ?>
                <?php /** @var $item \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($block->getItems() as $item): ?>
                    <?php if ($index++ == 0): ?>
                        <th scope="row" class="cell label print">

                        </th>
                    <?php endif; ?>
                    <td data-th="<?= $block->escapeHtmlAttr(__('Product')) ?>" class="cell product info product-item">
                        <div class="product-item-info">
                        <?php $compareHelper = $this->helper(Magento\Catalog\Helper\Product\Compare::class);?>
                            <a href="#" data-post='<?= /* @noEscape */ $compareHelper->getPostDataRemove($item) ?>'
                            class="action delete" title="<?= $block->escapeHtmlAttr(__('Remove Product')) ?>">
                                <span><?= $block->escapeHtml(__('Remove Product')) ?></span>
                            </a>
                            <a class="product-item-photo" href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>"
                               title="<?= /* @noEscape */ $block->stripTags($item->getName(), null, true) ?>">
                                <?= $block->getImage($item, 'product_comparison_list')->toHtml() ?>
                            </a>
                        </div>
                        <div class="product-item-detais">
                            <strong class="product-item-name">
                                <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>"
                                   title="<?= /* @noEscape */ $block->stripTags($item->getName(), null, true) ?>">
                                    <?= /* @noEscape */ $helper->productAttribute($item, $item->getName(), 'name') ?>
                                </a>
                            </strong>
                            <?= /* @noEscape */ $block->getProductPrice($item, '-compare-list-top') ?>
                            <div class="product-item-inner">
                                <div class="product actions product-item-actions">
                                    <div class="product-item-table-cell">
                                        <div class="actions-primary">
                                            <?php if ($item->isSaleable() && $ecommerceStatus): ?>
                                                <form data-role="tocart-form" action="<?= $block->escapeUrl($this->helper(Magento\Catalog\Helper\Product\Compare::class)->getAddToCartUrl($item)) ?>" method="post">
                                                    <?= $block->getBlockHtml('formkey') ?>
                                                    <button type="submit" class="action tocart primary">
                                                        <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                    </button>
                                                </form>
                                            <?php endif; ?>
                                        </div>
                                        <?php if ($this->helper(Magento\Wishlist\Helper\Data::class)->isAllow()) : ?>
                                            <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                                <!-- ko scope: 'ajaxwishlist' -->
                                                <a
                                                    class="action towishlist"
                                                    data-bind="css:{wishlisticon : wishlistitem().all_wishlist_items
?typeof wishlistitem().all_wishlist_items[<?=
                                                    /* @noEscape */
                                                    $item->getId() ?>]!='undefined':false}"
                                                    title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
                                                    aria-label="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
                                                    data-action="wishlist-actions"
                                                    data-product-id='<?= /* @noEscape */
                                                    $item->getId() ?>'
                                                    role="button">
                                                    <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>

                                                </a>
                                                <!-- /ko -->
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                <?php endforeach; ?>
            </tr>
            </tbody>
            <tbody>
            <?php foreach ($block->getAttributes() as $attribute): ?>
                <?php $index = 0; ?>
                <?php if ($block->hasAttributeValueForProducts($attribute)): ?>
                    <tr>
                        <?php foreach ($block->getItems() as $item): ?>
                            <?php if ($index++ == 0): ?>
                                <th scope="row" class="cell label  <?= $attribute->getAttributeCode() ?>">
                                        <span class="attribute label">
                                            <?= $block->escapeHtml($attribute->getStoreLabel() ? $attribute->getStoreLabel() : __($attribute->getFrontendLabel())) ?>
                                        </span>
                                </th>
                            <?php endif; ?>
                            <td class="cell product attribute <?= $attribute->getAttributeCode() ?>">
                                <div class="attribute value">
                                    <?php switch ($attribute->getAttributeCode()) {
                                        case "price": ?>
                                            <?= /* @noEscape */ $block->getProductPrice(
                                                $item,
                                                '-compare-list-' . $attribute->getCode()
                                            )
                                            ?>
                                            <?php break;
                                        case "small_image": ?>
                                            <?php $block->getImage($item, 'product_small_image')->toHtml(); ?>
                                            <?php break;
                                        default: ?>
                                            <?php if (is_string($block->getProductAttributeValue($item, $attribute))): ?>
                                                <?= /* @noEscape */  $helper->productAttribute($item, $block->getProductAttributeValue($item, $attribute), $attribute->getAttributeCode()) ?>
                                            <?php endif; ?>
                                            <?php break;
                                    } ?>
                                </div>
                            </td>
                        <?php endforeach; ?>
                    </tr>
                <?php endif; ?>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
            {
                "[data-role=tocart-form]": {
                    "catalogAddToCart": {}
                }
            }
            </script>
    <?php endif; ?>
<?php else: ?>
    <div class="message info empty"><div><?= $block->escapeHtml(__('You have no items to compare.')) ?></div></div>
<?php endif; ?>
