<?php
/**
 * Created by Eguana Team.
 * User: sonia
 * Date: 6/28/20
 * Time: 7:40 AM
 */

namespace Eguana\GWLogistics\Model;

use Eguana\GWLogistics\Api\Data\QuoteCvsLocationInterface;
use Magento\Framework\Model\AbstractModel;

/**
 * Class QuoteCvsLocation
 * @package Eguana\GWLogistics\Model
 */
class QuoteCvsLocation extends AbstractModel implements QuoteCvsLocationInterface
{
    protected function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init(\Eguana\GWLogistics\Model\ResourceModel\QuoteCvsLocation::class);
    }

    /**
     * @return int
     */
    public function getQuoteAddressId(): int
    {
        return $this->getData('quote_address_id');
    }

    /**
     * @return string
     */
    public function getMerchantTradeNo()
    {
        return $this->getData('merchant_trade_no');
    }

    /**
     * @return string
     */
    public function getLogisticsSubType()
    {
        return $this->getData('logistics_sub_type');
    }

    /**
     * @return string
     */
    public function getCvsStoreId()
    {
        return $this->getData('cvs_store_id');
    }

    /**
     * @return string
     */
    public function getCvsStoreName()
    {
        return $this->getData('cvs_store_name');
    }

    /**
     * @return string
     */
    public function getCvsAddress()
    {
        return $this->getData('cvs_address');
    }

    /**
     * @return string|null
     */
    public function getCvsTelephone()
    {
        return $this->getData('cvs_telephone');
    }

    /**
     * @return string|null
     */
    public function getCvsOutside()
    {
        return $this->getData('cvs_outside');
    }

    /**
     * @return string|null
     */
    public function getExtraData()
    {
        return $this->getData('extra_data');
    }

    /**
     * @return int
     */
    public function getIsSelected(): int
    {
        return $this->getData('is_selected');
    }
}
