<!-- title="Sulwhasoo Brand Belief - Brand Belief | Sulwhasoo Hong Kong" -->
<!-- <meta name="description" content="Sulwhasoo - BRAND BELIEF - 唯美之智，不為時間所動 | Sulwhasoo Hong Kong 中國香港"> -->
<div class="sulwhainside">
    <section class="sulwhainside-banner__wrapper">
        <img src="/media/html/resource/img/about/brand_belief/mob_img_sulwhainside_banner01.png" alt="TIMELESS
        WISDOM
        AGELESS BEAUTY" class="visible--mob">
        <img src="/media/html/resource/img/about/brand_belief/img_sulwhainside_banner01.png" alt="TIMELESS WISDOM AGELESS BEAUTY" class="visible--pc">
        <div class="sulwhainside-banner__item">
            <!-- Start DNDLAB Edit 2021-01-29 -->
            <h2 class="sulwhainside-banner__title">
                唯美之智，不為時間所動
            </h2><!-- End DNDLAB Edit 2021-01-29 -->
            <div class="sulwhainside-banner__content">
                雪花秀深信，真正的美，不會隨時間流逝而褪色，只會隨歲月蛻變而昇華。<br>
                在每個人生里程碑中，每位女士都可以煥發出獨一無二的動人光采。<br>
                雪花秀不斷重新詮釋美的定義，跨越時空界限，永續完美光芒的健康肌膚傳奇。
            </div>
        </div>
    </section>
    <div class="sulwhainside__img-wrapper">
        <!-- Start DNDLAB edit 2020-12-04 -->
        <img class="sulwhainside__img visible--mob" src="/media/html/resource/img/about/brand_belief/mob_img_sulwhainside_image_group.png" alt="">
        <img class="sulwhainside__img-pc visible--pc" src="/media/html/resource/img/about/brand_belief/pc_img_sulwhainside_image_group.png" alt="">
        <!-- End DNDLAB edit 2020-12-04 -->
    </div>
    <section class="science-top__wrapper">
        <div class="science-top__contents">
            <h2 class="science-top__head">
                科研
            </h2>
            <div class="science-top__banner">
                <!-- Start DNDLAB edit 2020-12-04 -->
                <img src="/media/html/resource/img/about/brand_belief/mob_img_sulwhainside_science_top.png" alt="" class="visible--mob">
                <img src="/media/html/resource/img/about/brand_belief/pc_img_sulwhainside_science_top.png" alt="" class="visible--pc"> <!-- End DNDLAB edit 2020-12-04 -->
            </div>
            <div class="science-top__title">
                無琅智慧之源
            </div><!-- Start DNDLAB edit 2020-11-20 -->
            <div class="science-top__content cont-plus-wrap">
                <div class="basic-content">
                    雪花秀科學研究中心是品牌的智慧之源，透過融和傳統韓方智慧與現代尖端科技，令雪花秀不斷創新。
                </div>
                <div class="more-content">
                    <br>
                    雪花秀從1960年代起，五十多年來一直開始研究人參，致力以天然材料及韓方草藥，打造出獨一無二的美肌產品，過去五十多年來持續研究韓方化妝保養品材料。經過多年的發展，目前雪花秀韓方科學研究中心已有超過500位專家。
                    <br><br>
                    雪花秀科學研究中心結合韓方和科技用於美肌，乃世界首創，對高麗人參、草藥效能研究、抗衰老科研﹑韓方理論現代化等都有深入研究。
                    <br><br>
                    雪花秀科學研究中心可以以「結合」一詞來闡述。研究團隊從韓國的古書中發掘智慧，將其轉化為現代理論。此外，研究團隊亦透過韓國植物萃取成分，研發出高效能美肌產品。將過去與現在、傳統與科學、韓方材料以及化妝保養品相結合，透過不斷融和，成就雪花秀的品牌智慧。這就是雪花秀科學研究中心標誌——無珢智慧(Infinite Wisdom)的源由。
                </div>
                <div class="btn-more-wrap">
                    <button type="button" class="btn-more-content">
                        <span class="btn-text">查看更多</span>
                    </button>
                </div>
            </div><!-- End DNDLAB edit 2020-11-20 -->
        </div>
    </section>
    <!-- Start DNDLAB Edit 2021-01-29 -->
    <div class="science-middle__wrapper">
        <figure class="science-middle__imgs">
            <div class="science-middle__items">
                <!-- Start DNDLAB edit 2020-12-04 -->
                <img src="/media/html/resource/img/about/brand_belief/mob_img_sulwhainside_middle_image_group.png" alt="" class="visible--mob">
                <img src="/media/html/resource/img/about/brand_belief/pc_img_sulwhainside_middle_image_group.png" alt="" class="visible--pc"> <!-- End DNDLAB edit 2020-12-04 -->
            </div>
        </figure>
        <div class="science-middle__text"></div>
        <div class="science-middle__text science-middle__text--second"></div>
    </div><!-- End DNDLAB Edit 2021-01-29 -->
    <section class="science-bottom__wrapper">
        <div class="science-bottom__banner">
            <!-- Start DNDLAB edit 2020-12-04 -->
            <img src="/media/html/resource/img/about/brand_belief/mob_img_sulwhainside_bottom.png" alt="" class="visible--mob">
            <img src="/media/html/resource/img/about/brand_belief/pc_img_sulwhainside_bottom.png" alt="" class="visible--pc"> <!-- End DNDLAB edit 2020-12-04 -->
        </div>
        <div class="science-bottom__container slick-default__wrapper">
            <div class="science-bottom__list slick-default__list">




                <div class="science-bottom__item slick-default__item" style="" tabindex="-1">
                    <figure>
                        <!-- Start DNDLAB edit 2020-12-04 -->
                        <img class="science-bottom__img visible--mob" src="/media/html/resource/img/about/brand_belief/mob_img_sulwhainside_bottom_content_01.png" alt="">
                        <img class="science-bottom__img visible--pc" src="/media/html/resource/img/about/brand_belief/pc_img_sulwhainside_bottom_content_01.png" alt=""> <!-- End DNDLAB edit 2020-12-04 -->
                        <figcaption class="science-bottom__text-wrapper">
                            <!-- Start DNDLAB Edit 2021-01-29 -->
                            <h2 class="science-bottom__title">
                                高麗人參深度研究
                            </h2><!-- End DNDLAB Edit 2021-01-29 -->
                            <p class="science-bottom__content">
                                在世界眾多人參中，高麗人參營養成分豐富，是廣受認可的優質植物，研究中心的專業專注試驗麗人參。除了研究其植物學外，也嘗試以水耕栽種、生物轉化等技術進行培植。
                            </p>
                        </figcaption>
                    </figure>
                </div><div class="science-bottom__item slick-default__item" style="" tabindex="0">
                    <figure>
                        <!-- Start DNDLAB edit 2020-12-04 -->
                        <img class="science-bottom__img visible--mob" src="/media/html/resource/img/about/brand_belief/mob_img_sulwhainside_bottom_content_02.png" alt="">
                        <img class="science-bottom__img visible--pc" src="/media/html/resource/img/about/brand_belief/pc_img_sulwhainside_bottom_content_02.png" alt=""> <!-- End DNDLAB edit 2020-12-04 -->
                        <figcaption class="science-bottom__text-wrapper">
                            <!-- Start DNDLAB Edit 2021-01-29 -->
                            <h2 class="science-bottom__title">
                                韓方材料效能研究
                            </h2><!-- End DNDLAB Edit 2021-01-29 -->
                            <p class="science-bottom__content">
                                東洋古籍中除了人參以外，還記載了諸多不同植物材料，研究中心仔細鑽研後，探索了3,912種植物組合、選出效能最佳的一組，並找出萃取方法。經過多年科研，終煉成雪花秀的核心成份活性美顏人參皂苷，而這成份為高麗參獨有。
                            </p>
                        </figcaption>
                    </figure>
                </div><div class="science-bottom__item slick-default__item" style="" tabindex="0">
                    <figure>
                        <!-- Start DNDLAB edit 2020-12-04 -->
                        <img class="science-bottom__img visible--mob" src="/media/html/resource/img/about/brand_belief/mob_img_sulwhainside_bottom_content_03.png" alt="">
                        <img class="science-bottom__img visible--pc" src="/media/html/resource/img/about/brand_belief/pc_img_sulwhainside_bottom_content_03.png" alt=""> <!-- End DNDLAB edit 2020-12-04 -->
                        <figcaption class="science-bottom__text-wrapper">
                            <!-- Start DNDLAB Edit 2021-01-29 -->
                            <h2 class="science-bottom__title">
                                科學的皮膚效能驗證與最新抗衰老研究
                            </h2><!-- End DNDLAB Edit 2021-01-29 -->
                            <p class="science-bottom__content">
                                雪花秀科學研究中心多年來積累大量抗衰老科學研究數據，根據這些數據，並針對現代肌膚需要，提供適切的解決方案，再以臨床試驗驗證實際效能。
                            </p>
                        </figcaption>
                    </figure>
                </div><div class="science-bottom__item slick-default__item" style="" tabindex="-1">
                    <figure>
                        <!-- Start DNDLAB edit 2020-12-04 -->
                        <img class="science-bottom__img visible--mob" src="/media/html/resource/img/about/brand_belief/mob_img_sulwhainside_bottom_content_04.png" alt="">
                        <img class="science-bottom__img visible--pc" src="/media/html/resource/img/about/brand_belief/pc_img_sulwhainside_bottom_content_04.png" alt=""> <!-- End DNDLAB edit 2020-12-04 -->
                        <figcaption class="science-bottom__text-wrapper">
                            <!-- Start DNDLAB Edit 2021-01-29 -->
                            <h2 class="science-bottom__title">
                                韓方理論現代化研究
                            </h2><!-- End DNDLAB Edit 2021-01-29 -->
                            <p class="science-bottom__content">
                                傳統智慧與現代科技融合，研究中心將過去積累對數萬種材料與古籍秘方的知識，轉化為數據，經分析過後，以現代科研改良後成為現今美肌良方。
                            </p>
                        </figcaption>
                    </figure>
                </div></div>
        </div>
    </section>
    <section class="sulwhainside-banner__wrapper sulwhainside-banner__wrapper--ginsenomics">
        <img src="/media/html/resource/img/about/brand_belief/mob_img_sulwhainside_banner02.png" alt="Ginsenomics™" class="visible--mob">
        <img src="/media/html/resource/img/about/brand_belief/img_sulwhainside_banner02.png" alt="Ginsenomics™" class="visible--pc">
        <div class="sulwhainside-banner__item sulwhainside-banner__item--ginsenomics">
            <!-- Start DNDLAB Edit 2021-01-29 -->
            <h2 class="sulwhainside-banner__title sulwhainside-banner__title--ginsenomics">
                Ginsenomics™
            </h2><!-- End DNDLAB Edit 2021-01-29 -->
            <div class="sulwhainside-banner__content sulwhainside-banner__content--ginsenomics">
                <div class="cont-plus-wrap">
                    <div class="basic-content">
                        Ginsenomics™是雪花秀人參研究的精髓。高麗人參中具有三十多種人參皂苷成分，其中含量極少的人參皂苷對於肌膚抗衰老具有相當卓越的功效，雪花秀不僅萃取了這種珍貴的人參皂苷，還更進一步將其製成6,000倍濃縮的活性美顏人參皂苷——Ginsenomics™，用獨有技術將人參能量傳遞給肌膚。
                    </div>
                    <div class="more-content">
                        <br>
                        Ginsenomics™亦是抗衰老研究成果，能提升肌膚生命力，，即使年月增長，肌膚也可以自我修復﹑變得健康。
                    </div>
                    <div class="btn-more-wrap">
                        <button type="button" class="btn-more-content">
                            <span class="btn-text">查看更多</span>
                        </button>
                    </div>

                </div>
            </div>
        </div>
    </section>
    <div class="story-ginseng">
        <div class="story-ginseng__contents">
            <div class="story-ginseng__top">
                <div class="visible--mob">
                    <figure class="story-ginseng__top-img-wrap">
                        <img src="/media/html/resource/img/about/brand_belief/mob_sulwhainside_story_ginseng.png" alt="" class="story-ginseng__top-img">
                    </figure>
                </div>
                <div class="visible--pc">
                    <figure class="story-ginseng__top-img-wrap">
                        <img src="/media/html/resource/img/about/brand_belief/pc_sulwhainside_story_ginseng.png" alt="" class="story-ginseng__top-img">
                    </figure>
                </div>
                <div class="story-ginseng__top-info">
                    <p class="story-ginseng__top-title">
                        人參的故事
                    </p>
                    <div class="story-ginseng__top-description cont-plus-wrap">
                        <div class="basic-content">1711年，法國耶穌會的杜德美神父在寫給母國的信中如此說道：「有種材料對於一般人而言太過昂貴，但會用於呈給皇帝的物品中」，這種材料就是高麗人參。此外，人參在幾世紀以前早已名揚西方國家，英國東印度公司的查德 · 考克斯也曾留下如下的紀錄：「(人參) 太珍貴了，一般人完全沒有機會接觸，可說是世上最珍貴的植物」，世界各地皆有許多人參的珍貴之處與其效能的相關記錄。
                        </div>
                        <div class="more-content">
                            <br>
                            東亞地區在更早之前就知道人參的存在與效能，最早在西元三世紀時，中國的《傷寒論》中就有人參處方的紀錄，人參可說是東亞文化圈中歷史相當悠久的寶物。「高麗人參」的歷史亦非常悠久，西元六世紀就開始進行人參交易，早在十四世紀時，也就是高麗末期開始就有栽種人參的紀錄。1687年的《承政院日記》中也曾提及人參的栽種方法，朝鮮時代國土約34%的地區皆產人參，可見高麗人參在過去亦為人盡皆知的珍貴植物。此外，古書中還留下了朝鮮時代的君王英祖因服用人參而得以延年益壽的紀錄。
                            <br><br>
                            高麗人參是代表韓國的高級植物，非常具歷史色彩，在許多國家都能看到它的相關紀錄。另外，高麗人參的優越效能已得到植物學、生物學、化學等近代科學的驗證。如今，雪花秀仍然努力不懈研究人參，不斷尋找人參的新效能。
                        </div>
                        <div class="btn-more-wrap">
                            <button type="button" class="btn-more-content">
                                <span class="btn-text">查看更多</span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="story-ginseng__bottom">
                <figure class="story-ginseng__bottom-banner">
                    <div class="visible--mob">
                        <!-- Start DNDLAB edit 2020-12-04 -->
                        <img src="/media/html/resource/img/about/brand_belief/mob_img_story_ginseng_bottom_banner.png" alt="" class="story-ginseng__bottom-banner-img">
                        <!-- End DNDLAB edit 2020-12-04 -->
                    </div>
                    <div class="visible--pc">
                        <!-- Start DNDLAB edit 2020-12-04 -->
                        <img src="/media/html/resource/img/about/brand_belief/pc_img_story_ginseng_bottom_banner.png" alt="" class="story-ginseng__bottom-banner-img">
                        <!-- End DNDLAB edit 2020-12-04 -->
                    </div>
                </figure>
                <div class="story-ginseng__bottom-info">
                    <div class="story-ginseng__title">
                        人參的科學
                    </div>
                    <p class="story-ginseng__bottom-description story-ginseng__bottom-description--first"></p>
                    <p class="story-ginseng__bottom-description story-ginseng__bottom-description--second">
                        科學方法研究人參，是雪花秀引以為傲的傳統，歷史已非常悠久。卓越的技術造就優秀的產品，而優秀的產業建立了雪花秀的名聲。
                    </p>
                </div>
            </div>
        </div>
    </div>
    <section class="sulwhainside-heritage__wrapper">
        <h2 class="sulwhainside-heritage__head">
            歷史傳承
        </h2>
        <div class="sulwhainside-heritage__container slick-default__wrapper">
            <div class="sulwhainside-heritage__list slick-default__list">


                <div class="sulwhainside-heritage__item slick-default__item" style="" tabindex="0">
                    <figure>
                        <!-- Start DNDLAB Edit 2020-12-18 -->
                        <img class="sulwhainside-heritage__img visible--mob" src="/media/html/resource/img/about/brand_belief/mob_img_sulwhainside_heritage01.png" alt="">
                        <img class="sulwhainside-heritage__img visible--pc" src="/media/html/resource/img/about/brand_belief/img_sulwhainside_heritage01.png" alt=""> <!-- End DNDLAB Edit 2020-12-18 -->
                    </figure>
                </div><div class="sulwhainside-heritage__item slick-default__item" style="" tabindex="0">
                    <figure>
                        <img class="sulwhainside-heritage__img visible--mob" src="/media/html/resource/img/about/brand_belief/mob_img_sulwhainside_heritage02.png" alt="초창기 연구원들의 모습">
                        <img class="sulwhainside-heritage__img visible--pc" src="/media/html/resource/img/about/brand_belief/img_sulwhainside_heritage02.png" alt="초창기 연구원들의 모습">
                    </figure>
                </div></div>
        </div>
        <div class="sulwhainside-heritage__text-wrap">
            <p class="sulwhainside-heritage__title">
                始於1966年
            </p>
            <div class="sulwhainside-heritage__content cont-plus-wrap">
                <div class="basic-content">雪花秀是歷經五十多年挑戰與創新的品牌，起始可回溯至1960年代。1966年，雪花秀的產品始祖問世——首創人參保養品「ABC人參面霜」。1997年，品牌對人參處方有更進一步的了解，品牌名稱進化為「雪花秀」。雪花秀的歷史可說是韓國化妝保養品的歷史。</div>
                <div class="more-content">
                    <br>
                    Amorepacific於1954年成立化妝保養品研究室，當時韓國尚無研究化妝保養品的概念。研究團隊憑著對於代表韓國的珍貴植物人參的熱情，開始進行研究，後來於1966年推出雪花秀產品的始祖「ABC人參面霜」，1973年推出含有人參皂苷成分萃取物的「韓國珍生參美」，1987年將品牌重新定名為「雪花」，1997年定名為「雪花秀」。雪花秀的獨有哲學，正正就是歷經五十多年堅持夢想﹑創新過程沈澱而成。
                </div>
                <div class="btn-more-wrap">
                    <button type="button" class="btn-more-content">
                        <span class="btn-text">查看更多</span>
                    </button>
                </div>
            </div>
        </div>
    </section>
</div>
<script type="text/javascript">
    require([
        'jquery',
        'js/plugins/slick/slick'
    ], function ($) {
        $(document).ready(function(){
            var belief = (function(){

                function init(){
                    initSulwhaInsideSlick();
                    sulwhainsideBannerInit();
                    initSulwhaInsideHeritageSlick();
                    initSulwhaInsideIngredientsSlick();
                    moreContent();
                }

                /* science-bottom.js */
                function initSulwhaInsideSlick() {
                    /* Start DNDLAB edit 2020-12-04 */
                    $('.science-bottom__list').slick({
                        dots: false,
                        infinite: false,
                        mobileFirst: true,
                        arrows: false,
                        slidesToShow: 1.24,
                        slidesToScroll: 1,
                        prevArrow: $('.science-bottom__prev-slide'),
                        nextArrow: $('.science-bottom__next-slide'),
                        dotsClass: 'slick-default__dots',
                        slide: '.slick-default__item',
                        responsive: [
                            {
                                breakpoint: 1023,
                                settings: 'unslick',
                            },
                        ],
                    })
                    /* End DNDLAB edit 2020-12-04 */

                    /* Start DNDLAB edit 2020-12-04 */
                    $(window).resize(function () {
                        if (
                            window.innerWidth < 1024 &&
                            $('.science-bottom__list').hasClass('slick-initialized') === false
                        ) {
                            $('.science-bottom__list').slick({
                                dots: false,
                                infinite: false,
                                mobileFirst: true,
                                arrows: false,
                                slidesToShow: 1.24,
                                slidesToScroll: 1,
                                prevArrow: $('.science-bottom__prev-slide'),
                                nextArrow: $('.science-bottom__next-slide'),
                                dotsClass: 'slick-default__dots',
                                slide: '.slick-default__item',
                                responsive: [
                                    {
                                        breakpoint: 1023,
                                        settings: 'unslick',
                                    },
                                ],
                            })
                        }
                    })
                    /* End DNDLAB edit 2020-12-04 */
                }
                /* //science-bottom.js */


                /* sulwhainside-banner.js */
                function sulwhainsideBannerInit() {
                    $(document)
                        .on('click', '.sulwhainside-banner__btn--more', function () {
                            $('.sulwhainside-banner__btn--more').addClass(
                                'sulwhainside-banner__btn--none'
                            )
                            $('.sulwhainside-banner__btn--close').removeClass(
                                'sulwhainside-banner__btn--none'
                            )
                            $('.sulwhainside-banner__content--second').removeClass(
                                'sulwhainside-banner__content--none'
                            )
                        })
                        .on('click', '.sulwhainside-banner__btn--close', function () {
                            $('.sulwhainside-banner__btn--more').removeClass(
                                'sulwhainside-banner__btn--none'
                            )
                            $('.sulwhainside-banner__btn--close').addClass(
                                'sulwhainside-banner__btn--none'
                            )
                            $('.sulwhainside-banner__content--second').addClass(
                                'sulwhainside-banner__content--none'
                            )
                        })
                }
                /* //sulwhainside-banner.js */

                /* sulwhainside-heritage.js */
                function initSulwhaInsideHeritageSlick() {
                    $('.sulwhainside-heritage__list').slick({
                        dots: false,
                        infinite: false,
                        mobileFirst: true,
                        arrows: false,
                        slidesToShow: 1.37,
                        slidesToScroll: 1,
                        prevArrow: $('.sulwhainside-heritage__prev-slide'),
                        nextArrow: $('.sulwhainside-heritage__next-slide'),
                        dotsClass: 'slick-default__dots',
                        slide: '.slick-default__item',
                        responsive: [
                            {
                                breakpoint: 1023,
                                settings: 'unslick',
                            },
                        ],
                    })

                    $(window).resize(function () {
                        if (
                            window.innerWidth < 1024 &&
                            $('.sulwhainside-heritage__list').hasClass('slick-initialized') === false
                        ) {
                            $('.sulwhainside-heritage__list').slick({
                                dots: false,
                                infinite: false,
                                mobileFirst: true,
                                arrows: false,
                                slidesToShow: 1.37,
                                slidesToScroll: 1,
                                prevArrow: $('.sulwhainside-heritage__prev-slide'),
                                nextArrow: $('.sulwhainside-heritage__next-slide'),
                                dotsClass: 'slick-default__dots',
                                slide: '.slick-default__item',
                                responsive: [
                                    {
                                        breakpoint: 1023,
                                        settings: 'unslick',
                                    },
                                ],
                            })
                        }
                    })
                }
                /* //sulwhainside-heritage.js */

                /* sulwhainside-ingredients.js */
                function initSulwhaInsideIngredientsSlick() {
                    /* Start DNDLAB edit 2020-12-04 */
                    $('.sulwhainside-ingredients__list').slick({
                        dots: false,
                        infinite: false,
                        mobileFirst: true,
                        arrows: false,
                        slidesToShow: 1.37,
                        slidesToScroll: 1,
                        prevArrow: $('.sulwhainside-ingredients__prev-slide'),
                        nextArrow: $('.sulwhainside-ingredients__next-slide'),
                        dotsClass: 'slick-default__dots',
                        slide: '.slick-default__item',
                        responsive: [
                            {
                                breakpoint: 1023,
                                settings: {
                                    dots: false,
                                    arrows: true,
                                    slidesToShow: 3,
                                    slidesToScroll: 3,
                                },
                            },
                        ],
                    })
                    /* End DNDLAB edit 2020-12-04 */
                }


                function moreContent(){
                    $('.btn-more-content').on('click',function(){
                        var $contWrap = $(this).parents('.cont-plus-wrap');
                        var isOpen = $contWrap.hasClass('open');

                        if(!isOpen) {
                            $contWrap.addClass('open')
                            $(this).children('.btn-text').text('查看更少')
                        } else{
                            $contWrap.removeClass('open')
                            $(this).children('.btn-text').text('查看更多')
                        }
                    });
                }

                /* sulwhainside-ingredients.js */

                return {
                    init: init
                }
            })();

            // init

            belief.init();
        });
    });
</script>
