<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**  @var $block \Magento\Checkout\Block\Cart */
?>
<div class="cart-empty">
    <div class="cart-container">
        <div class="form-cart">
            <div class="cart-empty-content">
                <p class="message-cart-empty"><?= $block->escapeHtml(__('There are no items in your cart')) ?></p>
            <?= $block->getChildHtml('checkout_cart_empty_widget') ?>
            <?= $block->getChildHtml('shopping.cart.table.after') ?>
            </div>
        </div>
        <?= $block->getChildHtml('checkout.cart.noitems.summary') ?>
    </div>
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Checkout/js/empty-cart": {}
    }
}
</script>
