<?php
/** @var \Amasty\Coupons\Block\Coupon $block */
/** @var \CJ\Coupons\ViewModel\CouponList $couponListViewModel */
$couponListViewModel = $block->getData('couponListViewModel');
?>
<div class="block discount"
     id="block-discount"
     data-mage-init='{"collapsible":{"openedState": "active", "saveState": true}}'>
    <div class="title" data-role="title">
        <strong id="block-discount-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Apply Discount Code')) ?></strong>
    </div>
    <div class="content" data-role="content" aria-labelledby="block-discount-heading">

        <form onsubmit="javascript:amCouponsSubmit(this);return false;" id="discount-coupon-form"
              action="<?= /* @noEscape */ $block->getUrl('checkout/cart/couponPost') ?>"
              method="post"
              data-mage-init='{"discountCode":{"couponCodeSelector": "#coupon_code_fake",
                                               "removeCouponSelector": "#remove-coupon",
                                               "applyButton": "button.action.apply",
                                               "cancelButton": "button.action.cancel"}}'>
            <input name="form_key" type="hidden" value="<?= $block->escapeHtml($block->getFormKey()) ?>" />
            <div class="fieldset coupon">

                <div class="field">
                    <label for="coupon_code" class="label"><span><?= $block->escapeHtml(__('Enter promo code')) ?></span></label>
                    <div class="control">
                        <input type="text" class="input-text" id="coupon_code_fake" name="coupon_code_fake"  placeholder="<?= $block->escapeHtml(__('Enter promo code'));?>" />
                        <input type="hidden" class="input-text" id="coupon_code" name="coupon_code"   />
                        <input type="hidden" class="input-text" id="last_code" name="last_code"   />
                        <input type="hidden" class="input-text" id="remove_coupon" name="remove_coupon"   />
                        <?= /* @escapeNotVerified */ $block->getBlockHtml('formkey'); ?>
                    </div>
                </div>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button class="action coupon-wallet primary" type="button" value="<?= $block->escapeHtml(__('view my coupon')) ?>">
                            <span><?= /* @escapeNotVerified */  $block->escapeHtml(__('view my coupon')) ?></span>
                        </button>
                    </div>
                    <div class="primary">
                        <button class="action apply primary" type="button" value="<?= $block->escapeHtml(__('Apply')) ?>">
                            <span><?= $block->escapeHtml(__('Apply')) ?></span>
                        </button>
                    </div>
                </div>
            </div>
            <div>
                <?php
                $couponCodes = $block->getCouponsCode();
                $couponString = '';
                if ($couponCodes) :
                    $couponString = implode(',', $couponCodes);
                    ?>
                    <div class="title">
                        <?= $block->escapeHtml(__('APPLIED COUPONS'))?>
                    </div>
                    <?php
                    foreach ($couponCodes as $couponCode) :
                        ?>
                        <div class="amCoupons">
                            <input type="hidden"  class="amCouponsCode" value="<?= $block->escapeHtml($couponCode);?>"/>
                            <?= $block->escapeHtml($couponCode);?>
                            <a href="#" onclick="javascript: amCancelCoupon('<?= $block->escapeHtml($couponCode);?>'); return false;"><?= $block->escapeHtml(__('Cancel'));?></a>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
        </form>
    </div>
</div>
<div class="popup-container">
    <div id="popup-modal">
        <div class="modal-body-content">
            <div class="coupon-popup coupon-container">
                <div class="coupon-wrap">
                    <div class="other-promo">
                        <div class="coupon-content">
                            <?php if ($couponListViewModel): ?>
                                <?php
                                try {
                                    $coupons = $couponListViewModel->getRuleCollection()->load();
                                } catch (\Magento\Framework\Exception\LocalizedException $e) {
                                    $coupons = [];
                                }
                                ?>
                                <div class="coupon-applied">
                                    <?php foreach ($coupons as $coupon) : ?>
                                        <?php /** @var \Magento\SalesRule\Model\Rule $coupon */?>
                                        <!-- start card -->
                                        <div class="discount-card">
                                            <div class="discount-bar lng-coupon-popup-color"></div>
                                            <div class="discount-card-content">
                                                <div class="discount-label">
                                                    <div class="discount-title">
                                                        <div class="landscape">
                                                            <img src="<?= $block->escapeHtml($couponListViewModel->getLogo()) ?>">
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="discount-border-center"></div>
                                                <div class="discount-content">
                                                    <div class="discount-title-percent"><?=$block->escapeHtml($coupon['name']);?></div>
                                                    <div class="discount-percent">
                                                        <span><?= $block->escapeHtml(__('Total discount for activities:')) ?></span>
                                                        <span class="highlight">
                                                            <?php if ($coupon->getSimpleAction() == 'by_percent'): ?>
                                                                <?= floatval($coupon['discount_amount']) ?>%
                                                            <?php else: ?>
                                                                <?= $couponListViewModel->getCurrencyCode() . floatval($coupon['discount_amount']) ?>
                                                            <?php endif; ?>
                                                        </span>
                                                    </div>
                                                    <div class="discount-percent">
                                                        <span><?=$block->escapeHtml(__('Expiration date:'))?></span> <span style="color: red"><?= $coupon['to_date'] == null ? '' : $coupon['to_date']; ?></span>
                                                    </div>
                                                    <div class="discount-description"><?=$block->escapeHtml($coupon['description'])?></div>
                                                </div>
                                            </div>
                                            <div class="discount-border-right lng-discount-border-right"></div>
                                            <?php
                                            $beenUsed = in_array($coupon['code'], $block->getCouponsCode());
                                            ?>
                                            <div data-beenused="<?= $beenUsed ? 1 : 0 ?>"
                                                 class="discount-card-button lng-discount-card-button"
                                                 id="<?= $coupon['code'] ?>">
                                                <?= $beenUsed ? $block->escapeHtml(__('Cancel')) : $block->escapeHtml(__('Apply')) ?>
                                            </div>
                                        </div>
                                        <!-- and card -->
                                    <?php endforeach; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    require([
        'ko',
        'jquery',
        'mage/translate',
        'Magento_Checkout/js/model/quote',
        'Magento_Ui/js/modal/modal'
    ], function (ko,$,$t, quote, modal) {
        $(function () {
            'use strict';
            //define coupon popup
            let options = {
                type: 'popup',
                responsive: true,
                title: $t('Coupon List'),
                innerScroll: true,
                buttons: [
                    {
                        text: $.mage.__('Ok'),
                        class: '',
                        click: function () {
                            this.closeModal();
                        }
                    }
                ]
            };
            let popup = null;
            $('.coupon-wallet').on('click', function() {
                popup = modal(options, $('#popup-modal'));
                $('#popup-modal').modal(options).modal('openModal');
            });

            $('.discount-card-button').on('click', function () {
                let action = $(this).data('beenused');
                if (action) {
                    // this is cancel action
                    amCancelCoupon(this.id); return false;
                } else {
                    // resubmit form coupon
                    $('#coupon_code_fake').val(this.id);
                    $('#discount-coupon-form').submit();
                }

            });
        });
    });
</script>
<script type="application/javascript">
    function amCouponsSubmit(form){
        var elements = document.getElementsByClassName("amCouponsCode");
        var names = [];
        for(var i=0; i<elements.length; i++) {
            names.push(elements[i].value);
        }
        var newCode = document.getElementById('coupon_code_fake').value;
        if(!newCode) {
            return false;
        }
        document.getElementById('last_code').value = document.getElementById('coupon_code_fake').value;
        names.push(newCode);
        names = amGetUnique(names, newCode);
        document.getElementById('coupon_code').value = names.join(',');
        form.submit();
    }

    function amGetUnique(arr){
        var u = {}, a = [];
        for(var i = 0, l = arr.length; i < l; ++i){
            if(u.hasOwnProperty(arr[i])) {
                continue;
            }
            a.push(arr[i]);
            u[arr[i]] = 1;
        }
        return a;
    };

    function amRemove(arr) {
        var what, a = arguments, L = a.length, ax;
        while (L && arr.length) {
            what = a[--L];
            while ((ax = arr.indexOf(what)) !== -1) {
                arr.splice(ax, 1);
            }
        }
        return arr;
    };


    function amCancelCoupon(code){
        var elements = document.getElementsByClassName("amCouponsCode");
        var names = [];
        for(var i=0; i<elements.length; i++) {
            names.push(elements[i].value);
        }
        document.getElementById('last_code').value = code;
        document.getElementById('remove_coupon').value = code;
        names = amRemove(names, code);
        document.getElementById('coupon_code').value = names.join(',');
        document.getElementById('discount-coupon-form').submit();
    }
</script>
