<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\NegotiableQuote\Block\Quote\Totals\Original */ ?>
<?php $total = $block->getTotal() ?>
<?php foreach ($total->getSubtotals() as $key => $option): ?>
    <tr class="<?= /* @noEscape */ $block->escapeHtml($key . ' ' . $option['class']) ?>">
        <th scope="row" class="mark">
            <?= $block->escapeHtml($option['label']) ?>
        </th>
        <td data-th="<?= $block->escapeHtml($option['label']) ?>" class="amount">
            <?= /* @noEscape */ $block->displayPrices($option['value'], $total->getCurrency()) ?>
        </td>
    </tr>
<?php endforeach ?>
<tr class="<?= $block->escapeHtml($total->getCode()) ?>">
    <th scope="row" class="mark">
        <?= $block->escapeHtml($total->getLabel()) ?>
    </th>
    <td data-th="<?= $block->escapeHtml($total->getLabel()) ?>" class="amount">
        <?= /* @noEscape */ $block->displayPrices($total->getValue(), $total->getCurrency()) ?>
    </td>
</tr>
