<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Onepage\Failure */
?>
<?php if ($block->getRealOrderId()) :?>
    <p class="text_info"><?= $block->escapeHtml(__('Order #') . $block->getRealOrderId()) ?></p>
<?php endif ?>
<?php if ($error = $block->getErrorMessage()) :?>
    <p class="text_info"><?= $block->escapeHtml($error) ?></p>
<?php endif ?>
<p class="text_info">
    <?= $block->escapeHtml(__("We couldn't process your order. Please place an order again later, or contact our service center.")) ?>

</p>
<div class="action try_again">
    <?= $block->escapeHtml(
    __('<a class="btn secondary" href="%1">Try Again</a>', $block->escapeUrl($block->getContinueShoppingUrl())),
    ['a']
) ?>
</div>
