<?php
/**
 * @author Eguana Team
 * @copyriht Copyright (c) 2020 Eguana {http://eguanacommerce.com}
 * Created by PhpStorm
 * User: arslan
 * Date: 17/6/20
 * Time: 08:00 PM
 */

/**
 * @var \Eguana\Faq\Block\Faq $block
 */

$categoryData = $block->getCategoryOptionArray();
$faqData = $block->getFaqBindData();
$searchUrl = $block->getSearchUrl();
?>
<div class="cms-2columns-left-container">
    <div class="page-row">
        <div class="pagebuilder-column cms-2columns-sidebar">
            <h2><?= __('Service Center') ?></h2>
            <ul>
                <li>
                    <span><?= __('FAQ') ?></span>
                </li>
            </ul>
            <style>
            @media only all and (max-width:767px) {
                .cms-2columns-sidebar > ul {
                    display:none;
                }
            }
            </style>
        </div>
        <div class="pagebuilder-column faqs">
            <h1><?= __('Frequently Asked Questions') ?></h1>
            <?php foreach ($categoryData as $key => $value):?>
                <?php if (isset($faqData[$key]) && count($faqData[$key]) > 0):?>
                    <div class="block">
                        <div class="item title" data-role="tab-collapsible">
                            <strong class="switch"
                                    role="heading"
                                    data-toggle="trigger"
                                    data-role="tab-title"
                                    aria-level="2">
                                <?= $block->escapeHtml($value) ?>
                            </strong>
                        </div>
                        <div class="faq-actions">
                            <a class="open-all" href="javascript:void(0)">
                                <span class="open-all-label"><?= __('OPEN ALL QUESTIONS') ?></span>
                                <span class="close-all-label"><?= __('CLOSE ALL QUESTIONS') ?></span>
                            </a>
                        </div>
                        <div class="item content" data-role="tab-content">
                            <div class="lists"
                                data-mage-init='{"accordion":{
                                    "collapsible": true,
                                    "animate": {"duration": 300},
                                    "openedState": "_active",
                                    "active": false,
                                    "multipleCollapsible": true}}'>
                                <?php foreach ($faqData[$key] as $faq):?>
                                    <div class="list">
                                        <div data-role="collapsible">
                                            <div class="title" data-role="title">
                                                <span><?= $block->escapeHtml($faq->getTitle()) ?></span>
                                            </div>
                                        </div>
                                        <div class="content" data-role="content" style="display: none;">
                                            <?= /* @noEscape */ $block->descriptionFilter($faq->getDescription()) ?>
                                        </div>
                                    </div>
                                <?php endforeach;?>
                            </div>
                        </div>
                    </div>
                <?php endif;?>
            <?php endforeach;?>
        </div>
    </div>
</div>
<script>
    require(['jquery'], function($){
        $('.open-all').click(function(){
            if($('.open-all').hasClass('active')) {
                $('.faqs .lists').accordion("deactivate");
                $('.open-all').removeClass('active');
            } else {
                $('.faqs .lists').accordion("activate");
                $('.open-all').addClass('active');
            }
        })
    });
</script>
