<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var $getDefault \Eguana\CustomCatalog\ViewModel\GetDefaultCategory
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$amoreHelper = $this->helper(Amore\GaTagging\Helper\Data::class);
$getDefault = $block->getData('view_model');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= $block->escapeHtml(__('We can\'t find products matching the selection.')) ?></div></div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned() ?? 1;
    ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php $index = 1;?>
            <?php /** @var $_product \Magento\Catalog\Model\Product */?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php
                    $productSku = $_product->getSku();
                    $originalPrice = $amoreHelper->getProductOriginalPrice($_product);
                    $finalPrice = $amoreHelper->getProductDiscountedPrice($_product);
                    $discountPrice = $originalPrice - $finalPrice;
                ?>
                <li class="item product product-item"
                    data-ap-cate="<?= $amoreHelper->getProductCategory($_product);?>"
                    data-ap-index="<?= $index ?>"
                    data-ap-code="<?= $productSku ?>"
                    data-ap-apg-code="<?= $block->escapeHtmlAttr($amoreHelper->getApgBrandCode($productSku)) ?>"
                    data-ap-name="<?= $block->escapeHtmlAttr($_product->getName()) ?>"
                    data-ap-site-name="<?= $block->escapeHtmlAttr($amoreHelper->getSiteName()) ?>"
                    data-ap-org-price="<?= $block->escapeHtmlAttr($originalPrice) ?>"
                    data-ap-discount="<?= $block->escapeHtmlAttr($discountPrice) ?>"
                    data-ap-final-price="<?= $block->escapeHtmlAttr($finalPrice) ?>">
                    <?php if( $viewMode == 'list' ):?>
                        <strong class="product name product-item-name">
                            <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                        </strong>
                        <strong class="product-item-name-en">
                            <?= $block->escapeHtml($_product->getResource()->getAttributeRawValue($_product->getId(),'name',0));?>
                        </strong>
                        <div class="product-item-contents-wrapper">
                    <?php endif;?>
                        <div class="product-item-info" data-container="product-<?= /* @noEscape */ $viewMode ?>">
                            <?php
                            $productImage = $block->getImage($_product, $imageDisplayArea);
                            if ($pos != null) {
                                $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;"';
                            }
                            ?>
                            <?php // Product Image ?>
                            <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                               class="product photo product-item-photo"
                               tabindex="-1"
                               ap-click-area="product"
                               ap-click-name="prd click"
                               ap-click-data="<?= /* @noEscape */ $getDefault->getProductByDefault($productSku)->getName() . '/' . $productSku ?>"
                               data-cate="<?= /* @noEscape */ $amoreHelper->getProductCategory($getDefault->getProductByDefault($productSku));?>"
                               data-index="<?=$index?>"
                               data-org-price="<?=$originalPrice?>"
                               data-final-price="<?=$finalPrice?>"
                            >
                                <?= $productImage->toHtml() ?>
                            </a>
                            <div class="product details product-item-details">
                                <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                ?>
                                <strong class="product name product-item-name">
                                    <a class="product-item-link"
                                       href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                                       ap-click-area="product"
                                       ap-click-name="prd click"
                                       ap-click-data="<?= /* @noEscape */ $getDefault->getProductByDefault($productSku)->getName() . '/' . $productSku ?>"
                                       data-cate="<?= /* @noEscape */ $amoreHelper->getProductCategory($getDefault->getProductByDefault($productSku));?>"
                                       data-index="<?=$index?>"
                                       data-org-price="<?=$originalPrice?>"
                                       data-final-price="<?=$finalPrice?>"
                                    >
                                        <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                    </a>
                                </strong>

                                <?php if( $viewMode == 'list' ):?>
                                    <div class="product-item-short-description">
                                        <?= $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    </div>
                                <?php endif;?>

                                <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>

                                <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>

                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $block->escapeHtmlAttr($position) : '' ?>>
                                        <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $block->escapeHtmlAttr($position) : '' ?>>
                                            <?php if( $viewMode == 'list' ):?>
                                                <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                                                   class="action todetail primary"
                                                   type="button"
                                                   ap-click-area="product"
                                                   ap-click-name="prd click"
                                                   ap-click-data="<?= /* @noEscape */ $getDefault->getProductByDefault($productSku)->getName() . '/' . $productSku ?>"
                                                   data-cate="<?= /* @noEscape */ $amoreHelper->getProductCategory($getDefault->getProductByDefault($productSku));?>"
                                                   data-index="<?=$index?>"
                                                   data-org-price="<?=$originalPrice?>"
                                                   data-final-price="<?=$finalPrice?>"
                                                >
                                                    <span><?= $block->escapeHtml(__('View')) ?></span>
                                                </a>
                                            <?php endif;?>
                                            <?php if ($_product->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
                                                    <input type="hidden" name="product" value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                                    <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                    <?= $block->getBlockHtml('formkey') ?>
                                                    <button type="submit"
                                                            title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                            class="action tocart primary">
                                                        <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                    </button>
                                                </form>
                                            <?php endif; ?>
                                        </div>
                                        <?php if(!$_product->getData('offline')):?>
                                        <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $block->escapeHtmlAttr($position) : '' ?>>
                                            <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                            <?php endif; ?>
                                        </div>
                                        <?php endif;?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php if( $viewMode == 'list' ):?>
                    </div>
                    <?php endif;?>
                </li>
                <?php $index++;?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= $block->escapeJs($_product->getSku()) ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
    <script type="text/x-magento-init">
        {
            ".products.wrapper": {
                "Amore_GaTagging/js/ap-select-item": {
                    "searchItemElement": ".product-item",
                    "listItemName": "<?= $block->escapeJs(\Amore\GaTagging\Model\CommonVariable::SEARCH_ITEM_LIST_NAME) ?>"
                }
            }
        }
    </script>
<?php endif; ?>

