<?php
/**
 * @author Eguana Team
 * @copyriht Copyright (c) 2020 Eguana {http://eguanacommerce.com}
 * Created by PhpStorm
 * User: raheel
 * Date: 9/2/21
 * Time: 5:12 AM
 */
?>
<div data-role="bss-fbpixel-atc" style="display:none;">

</div>
<script type="text/x-magento-init">
    {
        "[data-role='bss-fbpixel-atc']":
            {
                "Magento_Ui/js/core/app": <?= $block->getJsLayout();?>
            }
    }
</script>
