<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Rma\Block\Returns\History */
/** @var $viewModel Eguana\CustomRMA\ViewModel\CustomName */
?>
<?php $_returns = $block->getReturns(); ?>
<?php 
    $viewModel = $block->getData('custom_name_view_model'); 
    $orderViewModel = $block->getData('order_item_model');
    $priceHelper = $this->helper(\Magento\Framework\Pricing\Helper\Data::class);
?>

<?= $block->getChildHtml('info') ?>
<div class="order-history-tabs">
    <ul class="items order-links">
        <li class="nav item"><a href="<?= $block->getUrl('sales/order/history') ?>"><?= __('Order') ?></a></li>
        <li class="nav item current"><strong><?= __('Refund') ?></strong></li>
    </ul>
    <div id="order_history" class="item content" data-role="content">
        <div class="orders-history">
            <?php if ($_returns->getSize()): ?>
                <?php foreach ($_returns as $_return): ?>
                    <?php $_order = $_return->getOrder(); ?>
                    <div class="order-wrapper">
                        <a class="created-at" href="<?= $block->escapeUrl($block->getViewUrl($_return)) ?>"><?= $block->escapeHtml($this->helper(Magento\Rma\Helper\Data::class)->getFormatedDate($_return->getDateRequested())) ?></a>
	                    <a href="<?= $block->getUrl('sales/order/view', ['order_id' => $_return->getOrder()->getId()]) ?>">
                            <?= $_order->getIncrementId() ?>
	                    </a>
                        <div class="table-wrapper cart">
                            <?php $items = $_return->getItems(); ?>
                            <table class="cart data table items">
                                <tbody>
                                    <?php foreach($items as $_item): ?>
                                        <?php $_orderItem = $orderViewModel->getOrderItem($_item->getData('order_item_id')); ?>
                                        <?php $product = $_orderItem->getProduct(); ?>
                                        <tr class="item-info">
                                            <td class="col item">
                                                <span class="product-item-photo"><?= $orderViewModel->getImage($product, 'cart_page_product_thumbnail')->toHtml() ?></span>
                                                <div class="product-item-details">
                                                    <div class="shipping">
                                                        <span class="in-delivery"><?= __('In Delivery') ?></span>
                                                        <span class="method"><?= $_order->getShippingDescription() ?></span>
                                                    </div>
                                                    <strong class="product-item-name">
                                                        <?= $block->escapeHtml($_item->getProductName()) ?>
                                                    </strong>
                                                    <?php $_options = json_decode($_item->getData('product_options')); ?>
                                                    <?php if (!empty($_options->attributes_info)) : ?>
                                                        <dl class="item-options">
                                                            <?php foreach ($_options->attributes_info as $_option) : ?>
                                                                <dt><?= $block->escapeHtml($_option->label); ?></dt>
                                                                <dd><?= $block->escapeHtml($_option->value); ?></dd>
                                                            <?php endforeach; ?>
                                                        </dl>
                                                    <?php endif; ?>

                                                    <span class="cart-price"><?= $priceHelper->currency($_orderItem->getPrice()); ?></span>

                                                    <div class="return-status">
                                                        <?php if($_return->getStatus() == 'pending'):?>
                                                            <?= $block->escapeHtml(__('Waiting for a refund')); ?>
                                                        <?php else :?>
                                                            <?= $block->escapeHtml($_return->getStatusLabel()) ?>
                                                        <?php endif ?>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    <?php endforeach ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                <?php endforeach; ?>
            <?php else: ?>
                <p class="no-order">
                    <?= $block->escapeHtml(__('You have placed no returns.')) ?>
                </p>
            <?php endif ?>
        </div>
        <?php if ($block->getPagerHtml()): ?>
            <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
        <?php endif ?>
    </div>
</div>
